### ISSUE TITLE
pkgconfig files not installed with `--enable-script-wrapper-compilers`

### ISSUE THREAD

**Issue by minrk** [open-mpi/ompi#12609] opened 2024-06-10 13:47 UTC
## Background information

I'm exploring the consequences of enabling `--enable-script-wrapper-compilers`, and noticed that enabling the script wrappers prevents installation of pkg-config files.

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

v5.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

From source, with [this script](https://github.com/conda-forge/openmpi-feedstock/blob/cbb86edcddd5ffc58659ab23fbf80f5bdea05365/recipe/build-mpi.sh#L59-L76) (_for_ conda-forge, but currently running by hand for testing)

```bash
./configure --prefix=$PREFIX \
            --disable-dependency-tracking \
            --enable-mpi-fortran \
            --enable-script-wrapper-compilers \
            --disable-wrapper-rpath \
            --disable-wrapper-runpath \
            --with-wrapper-cflags="-I$PREFIX/include" \
            --with-wrapper-cxxflags="-I$PREFIX/include" \
            --with-wrapper-fcflags="-I$PREFIX/include" \
            --with-wrapper-ldflags="${wrapper_ldflags}" \
            --with-sge \
            --with-hwloc=$PREFIX \
            --with-libevent=$PREFIX \
            --with-zlib=$PREFIX \
            --enable-mca-dso
```

I think the only relevant argument there is `--enable-script-wrapper-compilers `, the rest should probably be ignored.

### Please describe the system on which you are running

* Operating system/version: macOS 14.5
* Computer hardware: M1 macbook
* Network type: N/A

-----------------------------

## Details of the problem

The openmpi pkg-config files are [conditionally installed](https://github.com/open-mpi/ompi/blob/9bb695e3b71a22d1e776a2eb5afe8781e1f52c9f/ompi/tools/wrappers/Makefile.am#L77-L82), and the condition is:

```
if (not OPAL_WANT_SCRIPT_WRAPPER_COMPILERS) and OPAL_INSTALL_BINARIES 
```

when presumably it should be:

```
if OPAL_WANT_SCRIPT_WRAPPER_COMPILERS  or OPAL_INSTALL_BINARIES
```

Which means they don't get installed if `--enable-script-wrapper-compilers` is given. The files are generated correctly, they just get left out of installation, so I imagine this is not deliberate. Adding `cp -v ompi/tools/wrappers/*.pc $PREFIX/lib/pkgconfig/` after installation produces the desired result.

Perhaps relevant to https://github.com/open-mpi/ompi/issues/10572 where `--enable-script-wrapper-compilers` is discussed in reference to pkg-config, but it is not mentioned that enabling it removes all pkg-config files.

**Comment by janjust** [comment] 2024-06-13 17:28
@jsquyres Hey, is this intended behavior? Regarding the condition on when to install pkg-config files?

@minrk just fyi - but your link seems to point to some unknown fork to me.

**Comment by jsquyres** [comment] 2024-06-17 20:59
Many thanks for the report, @minrk.

Does https://github.com/open-mpi/ompi/pull/12627 fix your issue?  (that PR is against main, but it should probably apply pretty easily to the v5.0.x branch)

**Comment by minrk** [comment] 2024-06-18 12:43
@jsquyres yes, that fixes it. Thank you!

Sorry for the weird link, that fork keeps coming up first in my searches. Fixed it.

**Comment by wenduwan** [comment] 2024-07-11 16:23
Changes merged. Closing.

**Closed** 2024-07-11 16:23 UTC
Labels: Target: main, Target: v5.0.x
