### ISSUE TITLE
3.0.0 error: 'FILE' was not declared

### ISSUE THREAD

**Issue by PABourdin** [open-mpi/ompi#4761] opened 2018-01-28 15:14 UTC
Hello,
I have successfully installed OpenMPI 1.10.7 and 3.0.0 tarballs, together with pHDF5 on CentOS 7.

When I compile my code, with 1.10.7 all is fine.
When I use 3.0.0 instead, I get this error:

```
In file included from include/TimeTasks.h:24:0,
                 from utility/TimeTasks.cpp:24:
include/errors.h:27:23: error: variable or field ‘eprintf_fileLine’ declared void
 void eprintf_fileLine(FILE * fptr, const char *type,
                       ^
include/errors.h:27:23: error: ‘FILE’ was not declared in this scope
```

Why is this error triggered with 3.0.0 and not with 1.10.7? What shall I do?
Thanks and best greetings.

**Comment by PABourdin** [comment] 2018-01-28 17:53
Looks like I have to `include <stdio.h>` explicitly.

I guess this was included before automatically from "mpi.h". No idea if this is a bug or a feature...?

**Comment by ggouaillardet** [comment] 2018-01-29 02:46
I do not think the MPI standards states `stdio.h` should be `#include`'d from `mpi.h`, so you should not expect this. imho, clearly not a bug, but an implementation choice (not sure that qualifies as a feature though)

**Comment by PABourdin** [comment] 2018-01-29 12:37
Well, it is just very surprising (and irritating) if a well-tested years-old code suddenly does not compile any longer due to a version change in MPI. Therefore, I hope you understand my reaction to report here.

If such "implementation choices" are made that require developers to change their code, it would actually be useful to write this in a prominent place, like `ompi/NEWS`.

I therefore leave this open for one of the developers to check and close this issue. Thanks!

**Comment by ggouaillardet** [comment] 2018-01-29 13:06
I fully understand you reported this issue (e.g. something that has been working for ever does not work any more).

In this case, I believe it worked because "you were lucky", and I cannot blame you for that.
That being said, this is not something that should have been taken for granted, and I do not think this under the hood changes between major versions deserves to be documented.

I will also not close this issue until a fellow developer volunteers to be the tie breaker.

**Comment by jsquyres** [comment] 2018-01-29 16:33
I believe the change is due to the fact that Open MPI stopped compiling / installing the C++ MPI bindings by default in v2.0.0 (because the MPI v3.0 spec deleted them).

When the C++ bindings were installed by default, then `mpi.h`, when compiled with a C++ compiler, would have to include a bunch of other head files -- including `<stdio.h>`.  When Open MPI stopped compiling/installing the C++ bindings by default, the `mpi.h`, when compiled with a C++ compiler, stopped including files like `<stdio.h>` (because, although it may not seem that way from this conversation, `mpi.h` actually tries to include as few additional header files as possible).

Meaning:

* If you enable the C++ bindings in Open MPI 3.0, I suspect your code will compile again without any changes (because `mpi.h` will include the C++ MPI bindings, which will therefore include `<stdio.h>`).
* @ggouaillardet is right that the MPI spec doesn't say anything about including `<stdio.h>`, and you were "getting lucky" that some other package -- Open MPI, in this case -- was including it for you.  The correct behavior for user applications is to `#include` whatever files they need -- even if they happen to get `#included` by other files.
* You're not wrong that we should announce changes that affect user's source code like this.  While we did announce that the C++ bindings were no longer built/installed by default, we did miss this implication (that a variety of system header files -- including `<stdio.h>` -- are no longer included by `mpi.h`).  Honestly, this is kind of a second-level / indirect implication to user applications, and I'm not surprised that we missed it.  ☹️

**Closed** 2018-01-29 17:42 UTC
Labels: question
