### ISSUE TITLE
ibv_exp_query_device error when runing mpi program using roce v2

### ISSUE THREAD

**Issue by thzhao** [open-mpi/ompi#5807] opened 2018-09-29 02:11 UTC
When I ran mpi program using roce v2, I got ibv_exp_query_device error. It seems that something is wrong when ib device is initiated. However, the program still run , and I can get correct results.

here is information about my system.

OS : CentOS Linux release 7.2.1511 (Core) 

Linux version:  3.10.0-327.el7.x86_64

Open MPI: 3.1.3a1

ofed version: MLNX_OFED_LINUX-4.4-1.0.0.0 (OFED-4.4-1.0.0)

network adaptor: Mellanox Technologies MT27520 Family [ConnectX-3 Pro]

mlx4_0	1	0	fe80:0000:0000:0000:ee0d:9aff:fe01:36f0			v2	enp2s0

**command**: 
mpirun -n 2 --allow-run-as-root --bind-to none  --mca btl_tcp_if_include enp2s0 -H cu01,cu02  ./cpi

**output:**

```
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x26b00000002 valid_mask = 0x1)
[cu01][[12691,1],1][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Invalid argument
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   cu01
  Local device: mlx4_0
--------------------------------------------------------------------------
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x26900000002 valid_mask = 0x1)
[cu02][[12691,1],0][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Invalid argument
Process 0 of 2 is on cu02
Process 1 of 2 is on cu01
pi is approximately 3.1415926544231318, Error is 0.0000000008333387
wall clock time = 0.020466
[cu02:29920] 1 more process has sent help message help-mpi-btl-openib.txt / error in device init
[cu02:29920] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by abeltre1** [comment] 2018-09-29 19:04
I have a similar question with extra results: #5810

**Comment by gongjingcs** [comment] 2019-09-05 11:52
I also have this question

**Comment by jsquyres** [comment] 2019-09-05 14:38
This issue was related to the `openib` BTL plugin, and was fixed in both Open MPI v3.0.4 and v3.1.4.

The issue is also made moot in the v4.0.x release with the addition of the UCX PML plugin (which, for many reasons, effectively replaces the `openib` BTL plugin).  The `openib` BTL is still present in the v4.0.x release, but it is no longer the default for IB and RoCE networks (assuming you have compiled Open MPI with UCX support).

**Closed** 2019-09-05 14:39 UTC
Labels: question

**Comment by gongjingcs** [comment] 2019-09-06 06:31
thanks alot. One thing I want to check is that whether this kind of error info will affect the RDMA network I use. How can I check RDMA network is really used in openmpi. openmpi version is 3.1.2.

**Comment by jsquyres** [comment] 2019-09-06 13:49
You can run with `mpirun --mca pml ucx ...` to force the UCX PML to be used in Open MPI (vs. falling back to an Open MPI TCP mechanism if UCX isn't available), but I have a dim recollection that there's a TCP mode in UCX, too.  You'll have to check the UCX documentation to see how to force things there.

The easiest way is to check the performance using microbenchmarks, such as the OSU MPI benchmarks.  

The difference in point-to-point latency should be large for RDMA networks vs. TCP.  Latency for RDMA 0-byte MPI messages should be single-digit microseconds.  For TCP, it will be tens of microseconds (anywhere from 10-100 microseconds, depending on your software stack/hardware/etc.).
