### ISSUE TITLE
build fails with both --enable-mpi-java --with-devel-headers

### ISSUE THREAD

**Issue by g-raffy** [open-mpi/ompi#6383] opened 2019-02-14 10:26 UTC
Hi there,

The latest version of openmpi 2.x (2.1.6) fails to build when options `--enable-java-mpi` and `--with-devel-headers` are both active.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

openmpi v2.1.6 (latest 2.x)

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
from the source/distribution tarball [https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.6.tar.gz](https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.6.tar.gz)
### Please describe the system on which you are running

* Operating system/version: debian 9 (stretch)
* Computer hardware: apple xserve 2,1
* Network type: 1Gb ethernet

-----------------------------

### symptoms

Here are the last lines displayed by the failed build :
```
make[3]: Entering directory '/root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi/mpi/java/java'
  JAVAC    MPI.class
JAVADOC    doc
make  all-am
make[4]: Entering directory '/root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi/mpi/java/java'
    JAR    mpi.jar
make[4]: *** No rule to make target 'mpi_CartParms.h', needed by 'all-am'.  Stop.
make[4]: Leaving directory '/root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi/mpi/java/java'
Makefile:1751: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi/mpi/java/java'
Makefile:1659: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi/mpi/java'
Makefile:3348: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi'
Makefile:1808: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@physix48:~/bug2587# cat ./build-without-debian.bash 
``` 

### way to reproduce

Here's the script that I used to reproduce the problem:

```bash
#!/bin/bash
mkdir -p ~/bug2587/builds/without-debian/build1
cd ~/bug2587/builds/without-debian/build1
wget https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.6.tar.gz
zcat openmpi-2.1.6.tar.gz | tar xvf -
cd openmpi-2.1.6
./configure --enable-mpi-java --with-devel-headers
make
```
### notes:

Here's a portion of the output of configure related to java:
```
*** Java compiler
checking OS X/macOS locations... not found
checking Linux locations... found (/usr/lib/jvm/java-1.8.0-openjdk-amd64/include)
checking --with-jdk-bindir value... sanity check ok (/usr/bin)
checking --with-jdk-headers value... sanity check ok (/usr/lib/jvm/java-1.8.0-openjdk-amd64/include)
checking for javac... /usr/bin/javac
checking for jar... /usr/bin/jar
checking for javadoc... /usr/bin/javadoc
checking for javah... /usr/bin/javah
checking javac -h... yes
checking jni.h usability... yes
checking jni.h presence... yes
checking for jni.h... yes
checking Java support available... yes

*** Java MPI bindings
checking if want Java bindings... yes
checking if shared libraries are enabled... yes
checking if Java support was found... yes
checking TargetConditionals.h usability... no
checking TargetConditionals.h presence... no
checking for TargetConditionals.h... no
checking for Dl_info... yes
configure: WARNING: ******************************************************
configure: WARNING: *** Java MPI bindings are provided on a provisional
configure: WARNING: *** basis.  They are NOT part of the current or
configure: WARNING: *** proposed MPI standard.  Continued inclusion of
configure: WARNING: *** the Java MPI bindings in Open MPI is contingent
configure: WARNING: *** upon user interest and developer support.
configure: WARNING: ******************************************************
```

**Comment by g-raffy** [comment] 2019-02-14 10:44
here are some additional tests that I made:
- openmpi builds fine with just  `--enable-java-mpi`
- openmpi 2.1.3 doesn't have this issue but openmpi 2.1.5 has it. This leads me to suspect the regression to have been introduced in commit [https://github.com/open-mpi/ompi/commit/a246c90523b249ccdc6d93e3d418395e0bdf4af6](https://github.com/open-mpi/ompi/commit/a246c90523b249ccdc6d93e3d418395e0bdf4af6).

**Comment by ggouaillardet** [comment] 2019-02-14 11:13
thanks for the report.
could you please run the following commands and upload the output ?

```
cd /root/bug2587/builds/without-debian/build1/openmpi-2.1.6/ompi/mpi/java/java
make clean
make V=1
```

**Comment by g-raffy** [comment] 2019-02-14 11:49
@ggouaillardet : sure, here it is : [make-output.log.gz](https://github.com/open-mpi/ompi/files/2864815/make-output.log.gz)

**Comment by kawashima-fj** [comment] 2019-02-14 12:28
I've confirmed this error in my machine.

@g-raffy For the released tarball, applying the following patch (removing four lines in `/ompi/mpi/java/java/Makefile.in`) and rerunning `configure` and `make` will resolve the issue.

```diff
--- a/ompi/mpi/java/java/Makefile.in	2018-11-29 01:36:07.000000000 +0900
+++ b/ompi/mpi/java/java/Makefile.in	2019-02-14 21:14:00.867854187 +0900
@@ -1689,7 +1689,6 @@
 # from JAVA_SRC_FILES.
 @OMPI_WANT_JAVA_BINDINGS_TRUE@JAVA_H = \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_MPI.h          \
-@OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_CartParms.h    \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_CartComm.h     \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Comm.h         \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Constant.h     \
@@ -1697,7 +1696,6 @@
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Datatype.h     \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Errhandler.h   \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_File.h         \
-@OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_GraphParms.h   \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_GraphComm.h    \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Group.h        \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Info.h         \
@@ -1707,9 +1705,7 @@
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Op.h           \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Prequest.h     \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Request.h      \
-@OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_ShiftParms.h   \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Status.h       \
-@OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Version.h	   \
 @OMPI_WANT_JAVA_BINDINGS_TRUE@	mpi_Win.h
 
 
```

As @g-raffy said, this is a regiression in a246c90. We had to cherry-pick 132ea1a6b06fa233c09a672f6572bcef98a54be1 in addition to 5370586d98b880d3e14659252620bebca92022af.

**Comment by kawashima-fj** [comment] 2019-02-14 12:45
OMPI developers:
v2.1.x, v3.0.x, and v3.1.x branches have this issue. v4.0.x branch is safe. Is v2.1.x branch still maintained? Error condition:

- `--enable-mpi-java` is enabled (default: disabled)
- `--with-devel-headers` is enabled (default: disabled)
- OpenJDK 8 or later is used (probably).

**Comment by jsquyres** [comment] 2019-02-14 15:30
Sure, having a fix for all those branches (including v2.x) would be fine.  It's highly unlikely that we'll do another v2.1.x release, though, but having the fix PR'ed means that the fix will be in the nightly v2.1.x tarball if it's needed.

**Comment by kawashima-fj** [comment] 2019-02-15 00:46
Ok. I'll create PRs to release branches after some more investigation.

**Comment by kawashima-fj** [comment] 2019-02-15 05:51
I pushed PRs to affected release branches.

In the commit a246c90523b249ccdc6d93e3d418395e0bdf4af6, we changed to use `javac -h` (available since OpenJDK 8) instead of `javah` (removed since OpenJDK 10) when `javac -h` is available. `javah` generates an almost-empty file for a no-`native` Java source file but `javac -h` does not generate a file. This difference it the cause. The almost-empty file which `javah` generates is not used anywhere. So it's safe to remove lines from `Makefile.am`. I tested with OpenJDK 7, 8, and 11.

@g-raffy thank for the report. The PR I created modified a file which is used only in git-cloned source (`Makefile.am`). Applying the patch against source in release tarballs does not solve the problem probably. The easiest workaround is the patch [in my comment](https://github.com/kawashima-fj) (`Makefile.in`). Or you can try [nightly snapshot tarballs](https://www.open-mpi.org/nightly/) after my PR is merged.

**Comment by g-raffy** [comment] 2019-02-15 15:25
thank you guys, that was very helpful, great work ! For your information, I used the following patch in the end because Makefile.in got overwritten in our process (while creating a debian package) : 
```
--- /root/bug2587/builds/ompi-2.1.6-with-debian-Fri_Feb_15_11_23_23_CET_2019/openmpi-2.1.6/ompi/mpi/java/java/Makefile.am.orig  2019-02-15 11:34:21.968687182 +0100
+++ /root/bug2587/builds/ompi-2.1.6-with-debian-Fri_Feb_15_11_23_23_CET_2019/openmpi-2.1.6/ompi/mpi/java/java/Makefile.am       2019-02-15 11:35:14.645373746 +0100
@@ -73,7 +73,6 @@
 # from JAVA_SRC_FILES.
 JAVA_H = \
 	mpi_MPI.h          \
-	mpi_CartParms.h    \
 	mpi_CartComm.h     \
 	mpi_Comm.h         \
 	mpi_Constant.h     \
@@ -81,7 +80,6 @@
 	mpi_Datatype.h     \
 	mpi_Errhandler.h   \
 	mpi_File.h         \
-	mpi_GraphParms.h   \
 	mpi_GraphComm.h    \
 	mpi_Group.h        \
 	mpi_Info.h         \
@@ -91,9 +89,7 @@
 	mpi_Op.h           \
 	mpi_Prequest.h     \
 	mpi_Request.h      \
-	mpi_ShiftParms.h   \
 	mpi_Status.h       \
-	mpi_Version.h	   \
 	mpi_Win.h
 
 # A little verbosity magic; see Makefile.ompi-rules for an explanation.
```

Thanks again !

**Comment by kawashima-fj** [comment] 2019-02-25 23:52
Merged to all release branches. Close.

**Closed by kawashima-fj** 2019-02-25 23:52 UTC
Labels: Target: v2.x, Target: v3.0.x, Target: v3.1.x, bug, java bindings
