### ISSUE TITLE
OMPIO symbol abstraction violation in v3.0.x/v3.1.x; only shows up with GCC 8.2.5, 8.3.1. (RHEL 8.0, RHEL 8.1)

### ISSUE THREAD

**Issue by mwheinz** [open-mpi/ompi#7309] opened 2020-01-15 19:29 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

OMPI 3.1.4, 3.1.5, 3.1.6

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Building from source using the IFS/OPA build scripts.

### Please describe the system on which you are running

* Operating system/version: RHEL 8.1 / GCC 8.3.1-4
* Computer hardware: Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
* Network type: OPA

-----------------------------

## Details of the problem

After building OMPI 3.1.4 for RHEL 8.1, I encountered the following warnings when I ran ompi_info. Problem does not seem to occur when building OMPI 4.0.2.

Is this expected or a known issue?
```
[LINUX hds1fna2271 20200115_1130 MPI]# /usr/mpi/gcc/openmpi-3.1.4/bin/ompi_info | grep btl
[hds1fna2271:81579] mca_base_component_repository_open: unable to open mca_fcoll_static: /usr/mpi/gcc/openmpi-3.1.4/lib64/openmpi/mca_fcoll_static.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
[hds1fna2271:81579] mca_base_component_repository_open: unable to open mca_fcoll_two_phase: /usr/mpi/gcc/openmpi-3.1.4/lib64/openmpi/mca_fcoll_two_phase.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
[hds1fna2271:81579] mca_base_component_repository_open: unable to open mca_fcoll_dynamic_gen2: /usr/mpi/gcc/openmpi-3.1.4/lib64/openmpi/mca_fcoll_dynamic_gen2.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
[hds1fna2271:81579] mca_base_component_repository_open: unable to open mca_fcoll_individual: /usr/mpi/gcc/openmpi-3.1.4/lib64/openmpi/mca_fcoll_individual.so: undefined symbol: mca_common_ompio_file_write (ignored)
[hds1fna2271:81579] mca_base_component_repository_open: unable to open mca_fcoll_dynamic: /usr/mpi/gcc/openmpi-3.1.4/lib64/openmpi/mca_fcoll_dynamic.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
                 MCA btl: vader (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                 MCA btl: self (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                 MCA btl: tcp (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                 MCA btl: usnic (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                 MCA btl: openib (MCA v2.1.0, API v3.0.0, Component v3.1.4)
                MCA fbtl: posix (MCA v2.1.0, API v2.0.0, Component v3.1.4)
```

**Comment by edgargabriel** [comment] 2020-01-15 20:08
@mwheinz Thank you for the report. I think I know what is wrong, but it would help if you could give us the precise configure line used for compiling Open MPI.

The OMPIO components used to share some symbols across different .so files. While this has been significantly improved in the 3.x series compared to the 2.x series, it was only fully resolved in the 4.x series. That being said, I have compiled Open MPI 3.1.x on RHEL 7 server without any problems numerous times ( I do not have access to a RHEL 8 server though). 

I recall however that there was a compiler flag that you could set in the 2.x series to resolve the issue. I will try to dig it up and provide it, in case you cannot upgrade to the 4.0.x

**Comment by ggouaillardet** [comment] 2020-01-16 00:06
@edgargabriel in this case, this is not an abstraction violation since the missing symbols are in `common/ompio` which is valid. The issue could be that these dll do not depend on `libmca_common_ompio.so` (e.g. this looks like a `Makefile.am` issue).

**Comment by mwheinz** [comment] 2020-01-16 13:40
Hey, guys - thanks for the feedback. I also spent some time with @jsquyres yesterday and he agrees that the issue is that the library is not being linked with with ``libmca_common_ompio.so`` and speculated the issue might be resolved in 3.1.5/6. I'm going to test that configuration this morning.

**Comment by mwheinz** [comment] 2020-01-16 17:50
Updated title and description to indicate that the issue exists with RHEL 8.0 as well as 8.1 and is present in 3.1.4, 3.1.5, and 3.1.6 - the problem seems to be non-obvious. The ompi_info commands are linked similarly:

```
[RHEL7.6 hdsmpriv02 20200116_1227 MPI]# ldd /usr/mpi/gcc/openmpi-3.1.6/bin/ompi_info
	linux-vdso.so.1 =>  (0x00007ffc34790000)
	libmpi.so.40 => /usr/mpi/gcc/openmpi-3.1.6/lib64/libmpi.so.40 (0x00007f75f1ff9000)
	libopen-rte.so.40 => /usr/mpi/gcc/openmpi-3.1.6/lib64/libopen-rte.so.40 (0x00007f75f1d43000)
	libopen-pal.so.40 => /usr/mpi/gcc/openmpi-3.1.6/lib64/libopen-pal.so.40 (0x00007f75f1a3a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f75f1836000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f75f162a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f75f1422000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f75f1120000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f75f0f1d000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f75f0d07000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f75f0aeb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f75f071e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f75f22f4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f75f0508000)
```

compare with:

```
[RHEL8.0 hdsmpriv01 20200116_1237 bin]# ldd /usr/mpi/gcc/openmpi-3.1.6/bin/ompi_info
	linux-vdso.so.1 (0x00007ffd4fbe9000)
	libmpi.so.40 => /usr/mpi/gcc/openmpi-3.1.6/lib64/libmpi.so.40 (0x00007f6e3a177000)
	libopen-rte.so.40 => /usr/mpi/gcc/openmpi-3.1.6/lib64/libopen-rte.so.40 (0x00007f6e39ebe000)
	libopen-pal.so.40 => /usr/mpi/gcc/openmpi-3.1.6/lib64/libopen-pal.so.40 (0x00007f6e39bc2000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6e399be000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f6e397b2000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f6e395a9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6e39227000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f6e39023000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f6e38e0c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6e38bec000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6e38828000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6e3a67d000)
```
but they produce different results:
```
[RHEL7.6 hdsmpriv02 20200116_1227 MPI]# /usr/mpi/gcc/openmpi-3.1.6/bin/ompi_info >/dev/null
[RHEL7.6 hdsmpriv02 20200116_1243 MPI]# 
```
versus
```
[RHEL8.0 hdsmpriv01 20200116_1242 bin]# /usr/mpi/gcc/openmpi-3.1.6/bin/ompi_info >/dev/null
[hdsmpriv01:46762] mca_base_component_repository_open: unable to open mca_fcoll_static: /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
[hdsmpriv01:46762] mca_base_component_repository_open: unable to open mca_fcoll_individual: /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_individual.so: undefined symbol: mca_common_ompio_file_write (ignored)
[hdsmpriv01:46762] mca_base_component_repository_open: unable to open mca_fcoll_two_phase: /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_two_phase.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
[hdsmpriv01:46762] mca_base_component_repository_open: unable to open mca_fcoll_dynamic: /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_dynamic.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
[hdsmpriv01:46762] mca_base_component_repository_open: unable to open mca_fcoll_dynamic_gen2: /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_dynamic_gen2.so: undefined symbol: mca_common_ompio_register_print_entry (ignored)
```
ld of /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so produces identical results:
```
[RHEL7.6 hdsmpriv02 20200116_1244 MPI]# ld /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so
ld: warning: cannot find entry symbol _start; not setting start address
/usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so: undefined reference to `mca_common_ompio_register_print_entry'
/usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so: undefined reference to `mca_common_ompio_full_print_queue'
```
versus
```
[RHEL8.0 hdsmpriv01 20200116_1242 bin]# ld /usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so
ld: warning: cannot find entry symbol _start; not setting start address
/usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so: undefined reference to `mca_common_ompio_register_print_entry'
/usr/mpi/gcc/openmpi-3.1.6/lib64/openmpi/mca_fcoll_static.so: undefined reference to `mca_common_ompio_full_print_queue'
```

On both machines, LD_LIBRARY_PATH is unset.

**Comment by mwheinz** [comment] 2020-01-16 17:51
Question: Is it possible that this really isn't an issue at all, that the issue is simply that the warnings being output in RHEL 8.x are just a bit of new verbosity that means nothing?

**Comment by jsquyres** [comment] 2020-01-16 19:00
@edgargabriel Mike and I looked at this a bit more on a webex.  It looks like there's an abstraction violation in the v3.0.x and v3.1.x branches.

Specifically, it looks like `libmca_common_ompio.so:common_ompio_file_open.c` uses the variable `mca_io_ompio_bytes_per_agg`, but this variable is instantiated in the `io/ompio` component.

This causes a problem -- at least on some platforms? -- when OMPI tries to `dlopen()` any component that uses `libmca_common_ompio.so` because it then can't find the `mca_io_ompio_bytes_per_agg` symbol.

I did not check to see if there are other symbols like `mca_io_ompio_bytes_per_agg`; this is just the one that we came across / the linker complained about.

This does not appear to be the case on master or the v4.0.x branch.  I looked through git history a _little_, but couldn't find an obvious commit that fixed it (can't `git blame` to find it because it's a line that disappeared over time).

Can you have a look?

**Comment by edgargabriel** [comment] 2020-01-16 19:34
@jsquyres if you look at my first comment above, this is exactly what I was referring to. The question to me is: is it worthwhile porting all the additional changes from master/v4.0.x to to the 3.1.x (and 3.0.x) series, since this was not an entirely trivial change?

Alternatively, I remember that there was a trick that could be done with RTLD_GLOBAL settings that would make it work, but I can not recall (or find the details). Also, static compilation will also still work.

**Comment by jsquyres** [comment] 2020-01-16 19:46
> @jsquyres if you look at my first comment above, this is exactly what I was referring to. 

Gotcha.

> The question to me is: is it worthwhile porting all the additional changes from master/v4.0.x to to the 3.1.x (and 3.0.x) series, since this was not an entirely trivial change?
> 
> Alternatively, I remember that there was a trick that could be done with RTLD_GLOBAL settings that would make it work, but I can not recall (or find the details). Also, static compilation will also still work.

A default compile makes OMPIO non-functional (and present some scary-looking warnings). That's a bit of a bummer.

Is there a "quick fix" that would make it work "well enough" for the rest of the v3.0.x/v3.1.x series?  I.e., perhaps not a complete revamp that might be necessary to fix the issue "for real", but perhaps just moving the instantiation of that variable (or variables) from io/ompio to common/ompio, without touching any other code?

v3.0.x is dying, but v3.1.x will still be around for a while.

**Comment by edgargabriel** [comment] 2020-01-16 19:51
@jsquyres let me look into that. The issue was how the mca parameters of ompio are accessed in other components, and it required touching all fcoll components to fix that ( in addition to moving the code to common and add the code that allowed the mca parameters to remain io_ompio parameters instead of common_ompio parameters). But I will check what it takes,

**Comment by edgargabriel** [comment] 2020-01-16 20:11
@jsquyres we would need the equivalent of this pr more or less.

https://github.com/open-mpi/ompi/pull/5263

**Comment by jsquyres** [comment] 2020-01-17 17:39
@edgargabriel On a scale of 1(none) to 5(huge), what's the level of risk of porting #5263 back to v3.0.x/v3.1.x?

**Comment by edgargabriel** [comment] 2020-01-17 17:43
@jsquyres I would say the risk is low, since it is being used in the v4.0.x branch already as well. I am more worried about the effort. Let me give it a try over the weekend to see how bad the conflicts are when cherry-picking the commits, will let you know. 

And also just to clarify my understanding: moving symbols from io/ompio to common/ompio does not represent an ABI change on any level, does it?

**Comment by edgargabriel** [comment] 2020-01-18 22:08
@jsquyres I filed a pr that I *think* fixes the issue. I tried cherry-picking the commits, but gave up after 1 hour, since the differences where to stark, and I couldn't follow the merged code anymore. So I created manually the minim set of changes required to fix the issue. I have however no platform to test, but I can confirm that on my machines the code still works and passes the same tests as before.

Can you please have a look?

**Comment by mwheinz** [comment] 2020-01-21 12:52
> Can you please have a look?

I can test on RHEL 8.0 and 8.1. I'll let you know.

**Comment by jsquyres** [comment] 2020-01-21 15:32
Thanks @edgargabriel!

I confirm that moving symbols from a component to a common library does not impact our backwards compatibility / ABI guarantees.

**Comment by mwheinz** [comment] 2020-03-03 15:43
As far as I know this has been fixed - should the issue be closed?

**Comment by edgargabriel** [comment] 2020-03-03 15:50
yes, we should close that.

**Closed by edgargabriel** 2020-03-03 15:50 UTC
Labels: Target: v3.0.x, Target: v3.1.x, bug
