### ISSUE TITLE
failures when running multiple mpirun instances on at least 3 nodes in a cluster

### ISSUE THREAD

**Issue by jhedev** [open-mpi/ompi#714] opened 2015-07-11 14:23 UTC
**Problem**
We have a cluster of 12-core and 24-core nodes using PBS/Torque where the following problem occurs with OpenMPI version `1.8.6`.
When running multiple `mpirun` instances on more than 2 nodes (so at least 3 nodes), some `mpirun` calls fail with
```
ORTE_ERROR_LOG: Not found in file base/plm_base_launch_support.c at line 99
```
I was able to track down a certain pattern, which is described in the following.

**How to reproduce**
The simplest way to reproduce I found is:

```bash
#! /bin/bash

# Create hostfiles assuming we're on 3 12-core nodes
# Will create hostfileaa, hostfileab and hostfileac
split --lines=12 $PBS_NODEFILE hostfile

mpirun -hostfile hostfileaa -np 1 hostname &  \
  mpirun -hostfile hostfileab -np 1 hostname &
  mpirun -hostfile hostfileac -np 1 hostname &

wait
```

In case we are on nodes `node1`, `node2` and `node3`, the `$PBS_NODESFILE` contains 12 lines for each node like this:

```
node1
...
node1
node2
...
node2
node3
...
node3
```

The `hostfileac` from the example above will only contain lines with `node3`. In this case the `mpirun` call that uses `hostfileac` as hostfile will fail with the error mentioned above. If we use more than 3 nodes, we can observe this failure with every additional node beginning with `node3`.

Interesting thing I observed: If we shuffle the lines of the hostfiles, like this:

```bash
! /bin/bash

# Create hostfiles assuming we're on 3 12-core nodes
# Will create hostfileaa, hostfileab and hostfileac
cat $PBS_NODEFILE | shuf | split --lines=12 - hostfile

mpirun -hostfile hostfileac -np 1 hostname &  \
  mpirun -hostfile hostfileab -np 1 hostname &
  mpirun -hostfile hostfileaa -np 1 hostname &

wait
```
*everything works fine*! This was also confirmed with a larger application, i.e. shuffling the hosts assigned to each task makes it working again.

**Versions tested**
We tested the following OpenMPI version: `1.6.5`, `1.8.4` and `1.8.6`, where `1.6.5` and `1.8.4` work fine and with `1.8.6` we get the problem described above. So it looks like this was introduced in either `1.8.5` or `1.8.6`.

**Environment**
All nodes use OpenSUSE 13.2. 

I hope this was understandable. I'm not familiar with all details of OpenMPI so I might have used some wrong terms :)

**Comment by rhc54** [comment] 2015-07-11 14:31
Could you please rerun the failing execution with --display-allocation and post the output?

**Comment by jhedev** [comment] 2015-07-11 14:47
Running the following script:
```
#! /bin/bash

# Create hostfiles assuming we're on 3 12-core nodes
# Will create hostfileaa, hostfileab and hostfileac
split --lines=12 $PBS_NODEFILE hostfile

mpirun -hostfile hostfileac --display-allocation -np 1 hostname &  \
  mpirun -hostfile hostfileab --display-allocation -np 1 hostname &
  mpirun -hostfile hostfileaa --display-allocation -np 1 hostname &

wait
```

The output is:
```
======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
	node3: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
=================================================================
node1

======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
	node3: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
=================================================================
[node1:14829] [[24837,0],0] ORTE_ERROR_LOG: Not found in file base/plm_base_launch_support.c at line 99
node2
```

**Comment by rhc54** [comment] 2015-07-11 15:02
Ah - yes, it sees the state is unknown and won't use the node. Looks like a bug in the code that reads the allocation. I'll fix it for the 1.8.7 release that is about to go out the door.

**Comment by rhc54** [comment] 2015-07-11 23:23
Okay, I pushed a fix in to the 1.8 repo - it will be available in tomorrow's nightly tarball. Could you please give it a try and let me know if the problem is fixed?

**Comment by jhedev** [comment] 2015-07-12 07:09
Unfortunately not :(

I've used the same script as above and get the following output:
```
======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UP
	node3: slots=12 max_slots=0 slots_inuse=0 state=UP
=================================================================
node1

======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UP
	node3: slots=12 max_slots=0 slots_inuse=0 state=UP
=================================================================
[node1:29561] [[57151,0],0] ORTE_ERROR_LOG: Not found in file ../../../../openmpi-v1.8.6-36-g71bfd7d/orte/mca/plm/base/plm_base_launch_support.c at line 99
node2
```
Looks like the state has changed to `UP`.

Verifying the version: `mpirun --version`:
```
mpirun (Open MPI) 1.8.7rc1

Report bugs to http://www.open-mpi.org/community/help/
```

Btw, I get the following output with last working version (1.8.4):
`mpirun --version`:
```
mpirun (Open MPI) 1.8.4

Report bugs to http://www.open-mpi.org/community/help/
```

Running the script from above:
```
======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
	node3: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
=================================================================
node1

======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
	node3: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
=================================================================

======================   ALLOCATED NODES   ======================
	node1: slots=12 max_slots=0 slots_inuse=0 state=UP
	node2: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
	node3: slots=12 max_slots=0 slots_inuse=0 state=UNKNOWN
=================================================================
node2
node3
```

**Comment by rhc54** [comment] 2015-07-12 14:48
Hmmm...okay, I dug some more and found the missing commit. It's in the 1.8 branch now, so you'll see it in tomorrow's nightly tarball. Sorry for the problem, and we do appreciate your help in tracking it down

**Comment by jhedev** [comment] 2015-07-13 06:52
It's fixed now! Thanks so much! When can expect a stable release including this patch?

**Comment by rhc54** [comment] 2015-07-13 13:34
I'm just waiting for confirmation of a configure fix, which looks like it passed yesterday, and then we will release. So figure on mid-week.

Thanks for the report and the assist!

**Closed by rhc54** 2015-07-13 13:34 UTC
Labels: bug
