### ISSUE TITLE
Segmentation Fault in MPI_Finalize if memory is not properly deallocated

### ISSUE THREAD

**Issue by rkowalewski** [open-mpi/ompi#2525] opened 2016-12-06 16:14 UTC
OpenMPI (v2.0.1) raises a segmentation fault if we allocate memory for one-sided communication by `MPI_Alloc_mem` but do not free it by `MPI_Free_mem`.
I have provided a [gist](https://gist.github.com/rkowalewski/0dab54d869470d60d3c063d0c52a8410#file-ompi-bug-free-mem-c-L73-L74) where you can test it. The relevant lines are highlighted. When you execute the statement in line 74 everything works fine. To my best knowledge, the MPI Standard does not require to explicitly free the allocated memory.

Below is some information about my build environment:

~~~bash
$ ompi_info
 Open MPI: 2.0.1
 Open MPI repo revision: v2.0.0-257-gee86e07
 Open MPI release date: Sep 02, 2016
 Open RTE: 2.0.1

$ mpicc --version
 gcc (GCC) 5.4.0
 Copyright (C) 2015 Free Software Foundation, Inc.
~~~

**Comment by jsquyres** [comment] 2016-12-06 17:25
@hjelmn Can you have a look?

**Comment by rkowalewski** [comment] 2016-12-13 10:38
I have checked this with the current tarball (see below), same compiler as above. The issue still persists.

~~~bash
  Open MPI: 2.0.2a1
  Open MPI repo revision: d0b97d7
  Open MPI release date: Unreleased developer cop
~~~

**Comment by jsquyres** [comment] 2016-12-13 15:32
Ok, thanks for checking.

@hjelmn Had a chance to check into this yet, perchance?

**Comment by hppritcha** [comment] 2017-07-03 15:27
@hjelmn any update for this issue?  Should it be moved to future milestone?

**Comment by hppritcha** [comment] 2017-09-25 16:08
@rkowalewski I'm trying to reproduce this problem, but so far no success using my IB/Intel OPA cluster.  Could you post the output of your config.log as well?

**Comment by hppritcha** [comment] 2017-09-25 19:12
I should say I was using the 2.0.3 release.  If you have a chance could you see if the problem is gone with 2.0.3?  If its still failing, we will need the config.log.

**Comment by jsquyres** [comment] 2017-10-10 15:07
@rkowalewski Unless you can provide further info, we're going to close this issue.

**Comment by rkowalewski** [comment] 2017-10-10 16:31
I will try to reproduce it until the end of this week, I am actually out of office at the moment.

**Comment by jsquyres** [comment] 2017-10-10 16:36
Excellent -- thanks!

**Closed** 2017-10-24 12:52 UTC
Labels: bug
