### ISSUE TITLE
usock error with many ranks on 1 node

### ISSUE THREAD

**Issue by plesn** [open-mpi/ompi#607] opened 2015-05-27 12:47 UTC
I am getting oob usock errors on master (dev-1802-gae0d577) when
launching more than 131 ranks on 1 node. I stumbled on this on a Xeon
Phi KNC, but it also happens on regular nodes just with `--oversubscribe`.

example:
``` shell
$ salloc -N1 --exclusive mpirun --oversubscribe -n 131 mpi_hello
salloc: Granted job allocation 51382
[sid437.bullx:17814] [[38531,1],129] usock_peer_send_blocking: send() to socket 12 failed: Transport endpoint is not connected (107)
[sid437.bullx:17814] [[38531,1],129] usock_complete_connect: unable to send connect ack to server
```

Usock must be reach some limit with > 130 ranks, but what is strange
is that I get the same error even whith `--mca oob ^usock`

**Comment by rhc54** [comment] 2015-05-27 12:55
The problem is that the pmix component is also using usock's for its
communication - we'll need to clarify the error message. Unfortunately,
there is no way around that one, so you'll need to discover the cause of
the problem. I can try to replicate tomorrow on my system - not sure why
you'd hit a limit down that low.

**Comment by plesn** [comment] 2015-05-28 10:24
Ah yes, indeed, I was confused by the message and looking at the wrong
place, this happens rather in the first call of pmix
get_attr(PMIX_JOBID,…) which uses usock.

By the way on a KNC (but also with --oversubscribe) this first
sendrecv/wait call to the orted is rather expensive : it takes 8s with
128 ranks. But this should be a separate issue…

**Comment by rhc54** [comment] 2015-05-28 14:43
There seems to be a limit being applied to the usock number - I'm investigating.

**Comment by rhc54** [comment] 2015-05-29 19:33
I've isolated the problem and am finalizing a fix - hope to commit it in the near future. Thanks for bringing this to my attention!

**Comment by rhc54** [comment] 2015-05-29 23:00
Okay, this has been committed to the master. There are still a few performance improvements that can be made, but it is at least working right now.

**Closed by rhc54** 2015-05-29 23:00 UTC
Labels: blocker, bug

**Comment by plesn** [comment] 2015-06-04 09:36
Thanks a lot, I had the occasion to run the fix on a KNC and this
solves the problem at 131 processes. It still bumps into a limit at
<202 processes on the node:

    [mo102-mic0:08157] [[45814,0],0] ORTE_ERROR_LOG: The system limit on number of network connections a process can open was reached in file util/listener.c at line 321

I have no problem running an openmpi-1.8 on the 240 hwthreads of the
KNC.

**Comment by rhc54** [comment] 2015-06-05 03:09
The problem lies in your system limit on the number of file descriptors a user can have open. The default limit on many systems is 1024, and that is too small when you are running hundreds of processes. You can check it with:

```
$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63852
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

It’s the “open files” limit that is the issue here. I’ve upped mine to 4096, and I can run over 300 procs locally. How you change it depends on the OS and your privileges - you might need a superuser to raise the default system limit so you can up your personal limits.
