### ISSUE TITLE
Fortran Bindings for MPI_File_get_size et al Return 31-bit Values

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#91] opened 2014-10-01 16:02 UTC
About 3 months ago, Markus Wittmann [Markus.Wittmann@rrze.uni-erlangen.de] sent a report to the developer mailing list about MPI_File_write_at(_all) and MPI_File_get_size issues for files with a size in excess of 2GB.

This really is two separate issues, although they are related.  First, OMPI does not honor MPI-IO write requests that exceed 2GB.
Probably, it does not honor read requests in excess of 2 GB either.
Second, that OMPI does not allow files that exceed 2 GB in size.

I have verified that this problem goes back at least as far as version 1.2.6.

**Comment by jsquyres** [comment] 2015-04-30 16:35
URL of Markus' original post: http://www.open-mpi.org/community/lists/devel/2009/09/6821.php

Gist for his 2 program attachments: https://gist.github.com/d551d98eba357bc85c01.git

**Comment by jsquyres** [comment] 2015-04-30 17:27
I cannot reproduce either of these problems at the 1.8 HEAD.  Closing the issue.

**Closed by jsquyres** 2015-04-30 17:27 UTC
Labels: bug
