### ISSUE TITLE
cuda & MPI_THREAD_MULTIPLE

### ISSUE THREAD

**Issue by dribbroc** [open-mpi/ompi#627] opened 2015-06-05 13:32 UTC
This maybe not a real issue, but at least unexpected behaviour.
Testet with cuda 7 and openmpi 1.8.5.

Background: If using hosts with only on gpu equipped, you ever hardly use the cudaSetDevice statement in your code, as all cuda calls default to the only existing device (0).

When allocating cuda device memory in the host thread and calling MPI_Send / Recv from other threads, mpi crashes with CUDA: Error in cuMemcpy.

A "workaround" is, to set the cudaDevice in every thread explitly, which definitly is a good advise at all.

Nevertheless, the cuda documentation states, that every thread's cudaDevice defaults to device 0, if not changed by the user.
This statement holds true, for cuda api calls in different threads, but openmpi seems to do some dark magic under the hood, changing this default device.

**Comment by rolfv** [comment] 2015-06-05 13:38
Can you provide a test program?  There is some special code in Open MPI for handling when there are threads to make sure we have a context for the threads.

**Comment by dribbroc** [comment] 2015-06-05 13:50
Testcase & output: https://gist.github.com/dribbroc/86422b72afe9c61b59d1

compiled with
mpic++ -std=c++11 -o testcase testcase.cpp -L/sfw/cuda/7.0/lib64 -lcudart -I/sfw/cuda/7.0/include

with openmpi 1.8.5, cuda 7.0, gcc 5.1

https://gist.github.com/dribbroc/86422b72afe9c61b59d1#file-testcase-cpp-L7
activating Line 7 resolves the issue

**Comment by rolfv** [comment] 2015-06-05 16:51
I know what the issue is.  This does not exist in CUDA 6.5 as I handle it properly.  I will look at how to fix this.

**Comment by dribbroc** [comment] 2015-06-08 15:42
Speaking of cuda 6.5 in general and the nvidia jetson k1 board in particular, this little test codes gets even more buggier.
(ompi 1.8.5, gcc 4.8.2, linux4tegra 21.3)

If I make the communication call synchronous (removing all threading stuff), see https://gist.github.com/dribbroc/86422b72afe9c61b59d1#file-testcase2-cpp ,then i get the following error on my jetson board:
https://gist.github.com/dribbroc/86422b72afe9c61b59d1#file-output2

**Comment by dribbroc** [comment] 2015-06-08 16:36
Further note to make things more clear:
https://github.com/open-mpi/ompi/issues/286 arose only at program exit.
Now the same issue arises during the program execution, when there are plenty of things to do.

**Comment by rolfv** [comment] 2015-08-11 19:16
This issue has been fixed in the master version of Open MPI and the v2.0.0 version.  Any chance you can try out v2.0.0 to see if this fixes your issue @dribbroc?

Nightly tarfiles are available here: http://www.open-mpi.org/nightly/v2.x

Any nightly build from August 10, 2015 or later.

**Comment by dribbroc** [comment] 2015-08-18 10:58
Ok, here we go:

jetson k1, openmpi-v2.x-dev-239-gb672e5c (Aug 17), gcc 4.8.4, cuda 6.5

code from https://gist.github.com/dribbroc/86422b72afe9c61b59d1
built with
mpic++ -std=c++11 -o testcase testcase.cpp -lcudart -I/usr/local/cuda/include -L/usr/local/cuda/lib
fails with
output in  https://gist.github.com/dribbroc/dde1a15e2caea9035773

Where the retun code 801 is defined in cuda.h as
CUDA_ERROR_NOT_SUPPORTED                  = 801

**Comment by rolfv** [comment] 2015-08-18 19:19
Great, thanks for testing.  I believe we have therefore fixed this specific issue about CUDA and MPI_THREAD_MULTIPLE.  The errors you are seeing are now the same as in bug #286. If you agree than I will close this issue as fixed in version v2.0.0 and we can continue discussion about #286 in #286.

@dribbroc   Do you agree with above statements?

**Comment by dribbroc** [comment] 2015-08-19 08:42
Sounds good to me.

**Comment by rolfv** [comment] 2015-08-19 12:48
Closing this issue as fixed in v2.0.0.

**Closed by rolfv** 2015-08-19 12:48 UTC
Labels: bug
