### ISSUE TITLE
Missing MPI_F08_STATUS[ES]_IGNORE in mpi.h

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#1575] opened 2016-04-23 12:12 UTC
MPI-3.1 p657:43-48 states:

> Two global variables of type MPI_F08_status*, MPI_F08_STATUS_IGNORE and MPI_F08_STATUSES_IGNORE are declared in mpi.h. They can be used to test, in C, whether f_status is the Fortran value of MPI_STATUS_IGNORE or MPI_STATUSES_IGNORE defined in the mpi_f08 module. These are global variables, not C constant expressions and cannot be used in places where C requires constant expressions. Their value is defined only between the calls to MPI_INIT and MPI_FINALIZE and should not be changed by user code.

OMPI is missing the declarations / definitions for `MPI_F08_STATUS[ES]_IGNORE`.

**Comment by ggouaillardet** [comment] 2016-04-23 14:09
this is a duplicate of #1475 
see my last two comments about the current issue.
basically, we cannot define MPI_F08_STATUS_IGNORE __and__ have all the mangling flavors in the fortran library (and we do not have all of them today)

**Closed** 2016-04-23 16:42 UTC
Labels: bug
