### ISSUE TITLE
Illegal instruction in v3.1.x / Fedora:

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6200] opened 2018-12-17 20:25 UTC
From @opoplawski in https://www.mail-archive.com/devel@lists.open-mpi.org/msg20833.html:

-----

I'm testing out rebuilding Fedora packages with openmpi 3.1 in Fedora COPR:

https://copr.fedorainfracloud.org/coprs/g/scitech/openmpi3.1/builds/

A number of packages are failing running tests only on Fedora Rawhide x86_64 with processes killed with signal 4 (Illegal instruction).  For example:

```
+ PYTHONPATH=/builddir/build/BUILDROOT/mpi4py-3.0.0-6.git39ca78422646.fc30.x86_64/usr/lib64/python2.7/site-packages/openmpi
+ mpiexec -n 1 python2 test/runtests.py -v --no-builddir --thread-level=serialized -e spawn
BUILDSTDERR: --------------------------------------------------------------------------
BUILDSTDERR: Primary job  terminated normally, but 1 process returned
BUILDSTDERR: a non-zero exit code. Per user-direction, the job has been aborted.
BUILDSTDERR: --------------------------------------------------------------------------
BUILDSTDERR: --------------------------------------------------------------------------
BUILDSTDERR: mpiexec noticed that process rank 0 with PID 0 on node 656ae442c6bf45fe9b45c5481f41bc45 exited on signal 4 (Illegal instruction).
BUILDSTDERR: --------------------------------------------------------------------------
```

Unfortunately I have been unable to reproduce this in any local mock builds.  So I'm left wondering if this is some kind of peculiarity with the COPR builders or if there is a real problem with openmpi.  Any suggestions for how to further debug this would be greatly appreciated.

(PID 0 seems very odd - that seems to be the same in the different failures)

**Comment by opoplawski** [comment] 2018-12-17 21:47
I don't think this is an openmpi issue, just a build issue with libpsm2 on Fedora.

**Comment by matcabral** [comment] 2018-12-25 21:30
as @opoplawski mentions, this is not an OMPI issue, but is inherent to libpsm2 support limited to processors with avx support (Haswell or newer). From there on the issue is the consequence of runtime selection landing on the OFI PSM2 provider that probably doesn't have https://github.com/ofiwg/libfabric/pull/4580, so tries to use it. 
If there are no objections, I would like to close this issue.

**Closed** 2018-12-27 15:56 UTC
Labels: Target: v3.1.x, question
