### ISSUE TITLE
osc/pt2pt fails with multiple threads

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/ompi#2614] opened 2016-12-20 20:53 UTC
Testing with the `osc/pt2pt` component revealed multiple hangs and wrong answers when running with two threads. Each thread is working with it's own communicator copy of `MPI_COMM_WORLD` and their own private windows.

The test is here:
 * https://github.com/open-mpi/ompi-tests/pull/25
 * https://gist.github.com/markalle/56f739c3c907e53960d22d5de2fe4bc9

```shell
% mpicc -o x mt_1sided.c mt_1sided_td1.c mt_1sided_td2.c
% mpirun -host hostA,hostB -mca osc pt2pt -mca pml ob1 -mca btl openib,self,vader ./x
```

PR #2630 will need to be reverted when a resolution to this issue is committed on v2.0.x branch.

**Comment by hjelmn** [comment] 2017-01-07 00:10
I can't get this to hang with osc/rdma. @markalle Was the 1sided.c test hanging with osc/rdma or just osc/pt2pt?

**Comment by hjelmn** [comment] 2017-01-07 01:38
Ok, I see what is happening. The restore of %ebx isn't working as expected. Looks like it might be selecting a register that is clobbered by cpuid. If the code is causing a problem here then it also is in the patcher. Will fix both.

**Comment by hjelmn** [comment] 2017-01-07 01:47
I see the problem. The code I copied for patcher only saves the lower 32 bits of b. Needs to save all 64 bits. Not sure why we are just discovering this now. Patch incoming.

**Comment by hjelmn** [comment] 2017-01-07 01:47
Wait, the other bit is a 32-bit only path. Thats why that worked. *face-palm*.

**Comment by hjelmn** [comment] 2017-01-07 01:52
Opps. Wrong bug :). Deleting those.

**Comment by hjelmn** [comment] 2017-01-09 18:40
Ok, I can reproduce the issue with osc/pt2pt. Looks like something is still not right with PSCW. Taking a look now.

**Comment by hjelmn** [comment] 2017-01-09 22:17
Found the bug. Its an artifact of the original design. I haven't had the time to move the counters into the sync object. Think I have a workaround. Testing it now.

**Comment by hjelmn** [comment] 2017-01-10 00:20
Ok, definitely fixed. Running it through the tests a couple more times to shake out any remaining bugs. Will have a PR open for master, v2.x, and v2.0.3.

**Comment by hjelmn** [comment] 2017-01-11 15:54
Still have one stubborn bug holding up the fix. It now hangs about 10% of the time. Will hopefully have this resolved today.

**Comment by hppritcha** [comment] 2017-05-22 11:12
@hjelmn can this issue be closed?

**Comment by markalle** [comment] 2017-06-19 21:22
I had been meaning to re-evaluate this one for a while. I built a vanilla OMPI v2.0.x with --enable-mpi-thread-multiple, and my results were:

mpirun -mca osc rdma -host hostA:2 ... :  passed
mpirun -mca osc rdma -host hostA:4 ... :  passed
mpirun -mca osc rdma -host hostA:1,hostB:1 ... :  segv quickly
mpirun -mca osc pt2pt ... : message that "OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release"

**Comment by hppritcha** [comment] 2017-07-12 14:37
@gpaulsen will check to see if we have more data on this issue.  @hjelmn says he'll work on it.

**Comment by hjelmn** [comment] 2017-09-14 21:26
Finally found the time to track this down. I see what is going wrong in osc/pt2pt. I should have a fix ready for testing tomorrow.

**Comment by hjelmn** [comment] 2017-09-20 14:51
Damn this is a nasty bug. Its getting a lot further but now I am running into another issue. Will keep cranking away at it until I know what the root cause is. Will start a parallel effort to ensure osc/rdma passes next month.

**Comment by gpaulsen** [comment] 2017-09-26 16:00
@hjelmn, Is this issue specific to osc_pt2pt or osc progress / multithreaded in general and only tickled by osc_pt2pt?

**Comment by jsquyres** [comment] 2018-03-26 19:50
Per discussion with @hjelmn and @hppritcha on 26 Mar 2018: 

* v2.0.x already disables osc/pt2pt in THREAD_MULTIPLE scenarios (because of this issue)
* v2.x does *not* disable itself in THREAD_MULTIPLE scenarios
    * It looks like we thought this would get fixed in time for v2.1.x.  But it didn't.
* At this point, it doesn't seem worth fixing this issue in the v2.x series.
* @hjelmn said he will fix in the v3.0.x series.
    * So I'll re-target this issue for v3.0.x.
* I will PR cherry-pick d0ffd660841 to the v2.x branch (i.e., disable osc/pt2pt in THREAD_MULTIPLE scenarios)

**Comment by jsquyres** [comment] 2018-05-29 15:17
Per discussion 2018-05-29: @hjelmn says that a better solution would be to get everything to support osc/rdma.  E.g., get vader, TCP, and the upcoming OFI BTLs to support RDMA, which then works with osc/rdma.

**Comment by matcabral** [comment] 2018-05-29 17:50
>Eventually delete osc/pt2pt (perhaps after v4.0.x series? Would be good to keep it around just until all the new osc/rdma support in the BTLs solidifies/matures)

Currently psm and psm2 MTLs use the osc/pt2pt understanding the limitations.  There is a workaround  using the OFI path, but still a workaround.

**Comment by jsquyres** [comment] 2018-05-29 17:57
@matcabral I think @hjelmn's plan is to make all the BTL's support put/get, and then all transports can use osc/rdma -- therefore the need for osc/pt2pt can go away.  That would be the purpose of the OFI BTL -- just for one-sided.  Make sense?

**Comment by matcabral** [comment] 2018-05-29 18:17
@jsquyres, yes, thanks for the clarification.

**Comment by hjelmn** [comment] 2018-05-29 19:01
I expect all transports that do not currently work with osc/rdma will see a performance improvement. How large will depend on the AMO and RDMA implementations.

**Closed** 2018-05-29 19:33 UTC
Labels: Target: v3.0.x, bug, critical
