### ISSUE TITLE
 Processes returns wrong results on OpenMPI 4.0.4 unless $OMPI_MCA_pml is set to "^ucx" 

### ISSUE THREAD

**Issue by ksiazekm** [open-mpi/ompi#8321] opened 2020-12-27 22:54 UTC
OpenMPI 4.0.4
Installed from official Fedora repository with use of dnf.
OS: Fedora 33, the latest 
gcc 10.2.1 20201125 (Red Hat 10.2.1-9)
AMD FX8350,  

some processes randomly return wrong results on the given configuration. When 
tested the same source code on Debian GNU/Linux 7 (wheezy) with OpenMPI 1.4.5 
it returns correct results each time. Test on each configuration was executed 
30 times in a loop. OpenMPI 4.0.4 started to work properly after set 
$OMPI_MCA_pml  to "^ucx".

The source code: [gist link](https://gist.github.com/ksiazekm/17046cad0d244188d0e2391262aa918c)

**Comment by hppritcha** [comment] 2021-01-04 20:42
It would be useful to know the version of UCX is being used.

**Comment by ksiazekm** [comment] 2021-01-05 12:48
> It would be useful to know the version of UCX is being used.

ucx.x86_64 1.8.1-3.fc33

**Comment by jsquyres** [comment] 2021-01-05 14:42
Can you provide more detail about exactly what is going wrong, and/or a small example showing the problem?

**Comment by jsquyres** [comment] 2021-01-05 16:05
I'm the worst -- you provided a gist link with a sample and I missed it.  We'll investigate...

**Comment by hppritcha** [comment] 2021-01-08 22:43
@ksiazekm i'm having reproducing this.  First how many MPI processes are you using when you observe the problem and what is the tabsize you're supplying?

**Comment by ksiazekm** [comment] 2021-01-09 13:09
Here you have 30 executions of the code from the previous gist: [Test Results](https://gist.github.com/ksiazekm/314083e4c8c9b6b00e2775ddab2aedf2)

**Comment by ggouaillardet** [comment] 2021-01-09 16:12
@hppritcha FWIW, I was able to reproduce the issue on a Fedora 33 virtual machine, using Open MPI and UCX provided by the distro. I was only able to find discarding the `pml/ucx` component was a workaround.
I did not have time to dig a bit more and figure out whether the root cause is in Open MPI, or UCX or both.

**Comment by awlauria** [comment] 2021-01-11 15:03
So far I can't reproduce on power9 + rhel8.2. I tried v4.0.x latest and also  the v4.0.4 release tarball.

**Comment by hoopoepg** [comment] 2021-01-12 14:36
> @hppritcha FWIW, I was able to reproduce the issue on a Fedora 33 virtual machine, using Open MPI and UCX provided by the distro

hi
have you any specific configuration in virtual machine? what processor of host system?
we are trying to reproduce issue but have no success

**Comment by ggouaillardet** [comment] 2021-01-12 14:48
That is a pretty standard Virtualbox VM running on a x86_64 (intel) processor.

**Comment by hoopoepg** [comment] 2021-01-12 14:50
what is number of CPU? memory volume?
and could you run there ```ucx_info -d``` there & post output here?

thank you

**Comment by ggouaillardet** [comment] 2021-01-12 15:07
1 GB
1 CPU

```
#
# Memory domain: sockcm
#     Component: sockcm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Memory domain: tcp
#     Component: tcp
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: tcp
#      Device: enp0s3
#
#      capabilities:
#            bandwidth: 113.16/ppn + 0.00 MB/sec
#              latency: 5776 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to iface
#             priority: 1
#       device address: 4 bytes
#        iface address: 2 bytes
#       error handling: none
#
#
# Connection manager: tcp
#      max_conn_priv: 2040 bytes
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: self
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 6911.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 12 bytes
#           rkey_ptr is supported
#
#   Transport: sysv
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: posix
#     Component: posix
#             allocate: unlimited
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#   Transport: posix
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
```

**Comment by ggouaillardet** [comment] 2021-01-12 15:08
use

```
mpirun --oversubscribe -np 4 a.out 120000000
```

you might have to run it several times to evidence the issue.

**Comment by jsquyres** [comment] 2021-01-12 16:10
I'm pre-emptively adding a v4.1 label on this issue too -- I'm *assuming* that the issue exists over there as well.

**Comment by gpaulsen** [comment] 2021-01-12 16:12
I set the blocker label until we have more information.

**Comment by ggouaillardet** [comment] 2021-01-13 00:51
@jsquyres @gpaulsen I was only able to reproduce this on a Fedora 33 (virtual) machine, and the workaround is to discard the `pml/ucx` component (built on top of the distro provided UCX).

I did not investigate more (lack of time) and could not reach a conclusion w.r.t. the root cause of this issue (Open MPI? UCX? Fedora? a combination of these?)

@opoplawski meanwhile, you might want to skip the `pml/ucx` component in the Fedora package by default. That can be achieved by adding a
```
pml = ^ucx
```
line into `/etc/openmpi-x86_64/openmpi-mca-params.conf`

**Comment by jsquyres** [comment] 2021-01-13 14:59
@jladd-mlnx @hoopoepg Someone from the UCX community needs to look into this.

**Comment by hoopoepg** [comment] 2021-01-13 15:00
we can't reproduce issue on our environment :(

**Comment by hoopoepg** [comment] 2021-01-13 15:01
300+ iterations in vieryal box VM can't identify any issues

**Comment by jsquyres** [comment] 2021-01-13 15:03
Another user posted a UCX error message yesterday -- I don't know if it's related or helps track this down: https://www.mail-archive.com/users@lists.open-mpi.org/msg34257.html.

**Comment by hoopoepg** [comment] 2021-01-13 15:21
@jsquyres 
> Another user posted a UCX error message yesterday -- I don't know if it's related or helps track this down: https://www.mail-archive.com/users@lists.open-mpi.org/msg34257.html.

on user's configuration there are different setup: on failed pair UCX is trying to use libverbs for communications, on node where it works - RC accelerated transport (RCX) - MOFED based. It seems issue is in configuration

**Comment by jsquyres** [comment] 2021-01-13 15:33
@hoopoepg Ok.  Could someone from the UCX community please engage the user on the list?  Thanks.

**Comment by hoopoepg** [comment] 2021-01-13 15:43
there is already reply with same point - non-unified configuration: https://www.mail-archive.com/users@lists.open-mpi.org/msg34258.html

**Comment by jsquyres** [comment] 2021-01-15 17:57
@hoopoepg Can you please reply to your customer on the list?  He already emailed me off list asking why no one has replied yet.  Thanks.

**Comment by hoopoepg** [comment] 2021-01-16 06:36
I can't - server rejects my answers

**Comment by marcindulak** [comment] 2021-01-18 17:31
Can we link the fedora bugzilla issue here after this is confirmed? Is this related to https://bugzilla.redhat.com/show_bug.cgi?id=1892128?

**Comment by hppritcha** [comment] 2021-01-19 19:13
I've tried to reproduce this on a RHEL7.6 system using UCX 1.8.1 and OMPI 4.0.4 and using the UCX_TLS transports that are available for the VM setups discussed so far and am unable to reproduce.  An interesting experiment would be to build UCX and OMPI on a fedora system and see if the problem is still observed.

**Comment by awlauria** [comment] 2021-01-21 18:33
Tried running this in a rhel8.1 container, and found that I could not reproduce with the latest ucx 1.9, but could reproduce with 1.8.1, which it appears  @ksiazekm is using. 

@ksiazekm can you try upgrading to ucx 1.9 and see if it goes away?

**Comment by jsquyres** [comment] 2021-01-26 16:19
@ksiazekm Can you provide some more details?

* Are you using one computer, or multiple computers?
* If using multiple computers, what kind of network / protocol are you using?  (E.g., InfiniBand?  Ethernet/TCP?  Ethernet/RoCE?  ...?)

**Comment by awlauria** [comment] 2021-01-26 16:46
To add a little more context,

- I did verify that ucx was being used.
- I found it failed with UCX v1.8.1 but worked with 1.9
- It was consistent behavior as described in https://www.mail-archive.com/users@lists.open-mpi.org/msg34258.html
IE. it worked when I added these mpirun lines:

```
Works
-x UCX_TLS=sm,ud
-x UCX_TLS=sm,rc_v
```
and failed otherwise.

**Comment by ksiazekm** [comment] 2021-01-26 17:04
@awlauria I will test it with ucx 1.9 when it will be available by official Fedora upgrade.
@jsquyres I use single machine.

**Comment by jsquyres** [comment] 2021-01-26 17:17
@open-mpi/ucx FYI

**Comment by opoplawski** [comment] 2021-01-28 14:07
I'm happy to push a ucx 1.9 update to Fedora 33 if that seems appropriate.  Is update UCX versions okay?  There isn't a soname bump.

**Comment by hppritcha** [comment] 2021-01-29 17:23
@opoplawski thanks Orion.  Transferring to Nvidia to let them decide how to deal with this from the Open MPI side.  Recommend a configure check to not build UCX pml and osc if the UCX being installed is older than 1.9. @hoopoepg

**Comment by jsquyres** [comment] 2021-01-29 17:30
@hppritcha Better to use the general "UCX" team name to alert all the relevant people on the UCX side, not just @hoopoepg.

FYI: @open-mpi/ucx

**Comment by yosefe** [comment] 2021-01-29 17:47
@hppritcha @jsquyres how about pml/ucx would disqualify itself at runtime, if UCX library version is older than v1.9, with some warning and mca var to override this?
I guess we could update that minimal version from time to time as we move to newer UCX versions

**Comment by jsquyres** [comment] 2021-01-29 18:04
If you really want to stop supporting older versions of UCX, you can certainly do that.

IMHO: It would be best to have both `configure.m4`-time and run time checks for versions, just to be safe.

**Comment by opoplawski** [comment] 2021-01-30 17:02
I've submitted ucx 1.9 to Fedora 33 - https://bodhi.fedoraproject.org/updates/FEDORA-2021-613166cadb  Please test and provide feedback.

**Comment by jsquyres** [comment] 2021-02-01 20:11
@ksiazekm Just out of curiosity, are you seeing the same behavior with Open MPI v4.1.0 as well?

**Comment by jsquyres** [comment] 2021-02-08 20:27
@open-mpi/ucx Can you give a definitive ruling on what you plan to do?  I.e., are UCX versions prior to v1.9.0 problematic?

**Comment by hoopoepg** [comment] 2021-02-09 07:17
there is one more issue https://github.com/open-mpi/ompi/issues/8442 which may be related to this one, and we reproduced it on our environment. working over idenrifying.

**Comment by hoopoepg** [comment] 2021-02-09 10:21
@ksiazekm could you test latest OMPI+UCX available in Fedora 33?

thank you

**Comment by ksiazekm** [comment] 2021-02-09 16:46
I can confirm that it works properly with:
- ucx.x86_64 1.9.0-1.fc33
- openmpi.x86_64 4.0.5-1.fc33

**Comment by hppritcha** [comment] 2021-02-11 18:49
@open-mpi/ucx just to note there seem to be some significant differences between this issue and #8442 namely this one doesn't seem to be reproducible when using RC UCX_TLS, whereas #8442 seems to be avoidable using sm, tcp.  Still they may be related although the conditions under which they appear wrt UCX_TLS are different.

**Comment by yosefe** [comment] 2021-02-14 09:36
@ksiazekm can you pls check if #8473 resolves the issue (with ucx v1.8.0)?

**Comment by hoopoepg** [comment] 2021-02-15 16:14
@ksiazekm could you provide output of command ```ucx_info -d" from system where data corruption happened?

thank you

**Comment by hoopoepg** [comment] 2021-02-16 13:57
> @open-mpi/ucx Can you give a definitive ruling on what you plan to do? I.e., are UCX versions prior to v1.9.0 problematic?

Hi @jsquyres
UCX v1.8 has data race in some configuration when used TCP and SHM transports simultaneously. In UCX v1.9 this data flow was updated and issue doesn’t appear anymore. The final fix was implemented in UCX v1.10 in PR https://github.com/openucx/ucx/pull/5936.

Is it still important enough to add warning given that we are pushing updated package for Fedora?

**Comment by jsquyres** [comment] 2021-02-16 15:38
Many people use Open MPI outside of Fedora.

If you want to restrict Open MPI to only use UCX >= v1.10, you need to update the configury.

Silent data corruption is ***BAD***.

**Comment by yosefe** [comment] 2021-02-16 15:57
@jsquyres IMO, runtime version check would be more strict (in case the user compiles OpenMPI with one UCX version, but runs with another version), WDYT?

**Comment by jsquyres** [comment] 2021-02-16 16:01
That would be fine as well.

But we definitely also like configure-time failures (with helpful explanation messages).  E.g., if someone tries to compile with an old/unsupported UCX, it should fail right away during configure (vs. succeeding to configure, build, and install, and then only fail at run time).

Make sense?

**Comment by yosefe** [comment] 2021-02-16 16:09
@jsquyres yes, that makes sense. just to make sure, it would not be a problem for OpenMPI that we essentially drop support for older UCX versions?

**Comment by yosefe** [comment] 2021-02-16 16:10
adding @shamisp as well

**Comment by ksiazekm** [comment] 2021-02-16 23:18
@hoopoepg here you have:

$ ucx_info -d
#
# Memory domain: sockcm
#     Component: sockcm
#           supports client-server connection establishment via sockaddr
#   < no supported devices found >
#
# Memory domain: tcp
#     Component: tcp
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: tcp
#      Device: enp3s6
#
#      capabilities:
#            bandwidth: 11.32/ppn + 0.00 MB/sec
#              latency: 10960 nsec
#             overhead: 50000 nsec
#            put_zcopy: <= 18446744073709551590, up to 6 iov
#  put_opt_zcopy_align: <= 1
#        put_align_mtu: <= 0
#             am_short: <= 8K
#             am_bcopy: <= 8K
#             am_zcopy: <= 64K, up to 6 iov
#   am_opt_zcopy_align: <= 1
#         am_align_mtu: <= 0
#            am header: <= 8037
#           connection: to iface
#             priority: 1
#       device address: 4 bytes
#        iface address: 2 bytes
#       error handling: none
#
#
# Connection manager: tcp
#      max_conn_priv: 2040 bytes
#
# Memory domain: self
#     Component: self
#             register: unlimited, cost: 0 nsec
#           remote key: 0 bytes
#
#   Transport: self
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 6911.00 MB/sec
#              latency: 0 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 8K
#             am_bcopy: <= 8K
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 0 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: sysv
#     Component: sysv
#             allocate: unlimited
#           remote key: 12 bytes
#           rkey_ptr is supported
#
#   Transport: sysv
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#
#
# Memory domain: posix
#     Component: posix
#             allocate: unlimited
#           remote key: 24 bytes
#           rkey_ptr is supported
#
#   Transport: posix
#      Device: memory
#
#      capabilities:
#            bandwidth: 0.00/ppn + 12179.00 MB/sec
#              latency: 80 nsec
#             overhead: 10 nsec
#            put_short: <= 4294967295
#            put_bcopy: unlimited
#            get_bcopy: unlimited
#             am_short: <= 100
#             am_bcopy: <= 8256
#               domain: cpu
#           atomic_add: 32, 64 bit
#           atomic_and: 32, 64 bit
#            atomic_or: 32, 64 bit
#           atomic_xor: 32, 64 bit
#          atomic_fadd: 32, 64 bit
#          atomic_fand: 32, 64 bit
#           atomic_for: 32, 64 bit
#          atomic_fxor: 32, 64 bit
#          atomic_swap: 32, 64 bit
#         atomic_cswap: 32, 64 bit
#           connection: to iface
#             priority: 0
#       device address: 8 bytes
#        iface address: 8 bytes
#       error handling: none
#

**Comment by hoopoepg** [comment] 2021-02-17 07:27
@ksiazekm thank you for info.
You have same configuration as we reproduced issue and upgrade to UCX 1.9 should resolve issue.

**Comment by ksiazekm** [comment] 2021-02-17 16:04
@hoopoepg indeed, as I wrote in [comment](https://github.com/open-mpi/ompi/issues/8321#issuecomment-776077448) :)

**Comment by jsquyres** [comment] 2021-02-22 20:49
@open-mpi/ucx What version of UCX is known to be good -- is it v1.9.0, or the upcoming v1.10.0?  (I ask because I see that 1.9.0 is still the current release on https://github.com/openucx/ucx).

Given that this is silent data corruption, and per the discussion above, it sounds like we need both a configure-time check and a run-time check to ensure that the UCX PML is running with >= UCX v1.GOOD_VERSION.  Is there any progress on this?  We need this ASAP to get new Open MPI releases out the door.

**Comment by shamisp** [comment] 2021-02-23 00:32
@jsquyres , FYI we documented this critical issue on the front page https://github.com/openucx/ucx#known-critical-issues

**Closed** 2021-02-23 20:16 UTC
Labels: Severity: blocker, Target: v4.0.x, Target: v4.1.x, bug
