### ISSUE TITLE
compilation error with external pmix

### ISSUE THREAD

**Issue by jiayulu** [open-mpi/ompi#1494] opened 2016-03-25 13:52 UTC
I was compiling the master branch on Centos 7 using https://github.com/pmix/master, I had to do the following in order to compile, does it work for you out of the box? Thanks!

cd ompi/opal/mca/pmix/external
ln -s path/to/pmix/src src

add 
#include "opal/util/argv.h"
in ompi/orte/mca/rml/base/rml_base_stubs.c

**Comment by rhc54** [comment] 2016-03-25 15:32
I'll fix these. The PMIx include file organization changed earlier this week, and I need to update OMPI's "external" component accordingly. Same for the RML.

**Comment by rhc54** [comment] 2016-03-25 16:08
Hmmm...I fixed the missing header file in rml_base_stubs.c. However, I cannot replicate the build problem when linked against the current pmix master. Could you try updating both code bases and see if the problem still exists? I'm wondering if there was something recently committed that resolved the problem.

**Comment by jiayulu** [comment] 2016-03-25 19:13
I still get this:

make[2]: Entering directory `/home/yjia/tmp/iof/_build.external/ompi/opal/mca/pmix/external'
  CC       mca_pmix_external_la-pmix_ext_component.lo
  CC       mca_pmix_external_la-pmix_ext.lo
  CC       mca_pmix_external_la-pmix_ext_client.lo
pmix_ext_client.c:33:39: fatal error: src/buffer_ops/buffer_ops.h: No such file or directory
 #include "src/buffer_ops/buffer_ops.h"

**Comment by rhc54** [comment] 2016-03-25 19:44
Yes, Jeff O. and I have exchanged some notes on this and I now see the issue - trying to understand root cause.

**Comment by rhc54** [comment] 2016-03-25 21:16
Okay, this should now be fixed. You will need to update your copy of the PMIx master, and then configure --with-devel-headers to get the required headers.

Sorry for the problem - there was an upstream change to PMIx that disabled installation of the headers.

**Closed by rhc54** 2016-03-25 21:16 UTC
