### ISSUE TITLE
Error in `configure` in v2.x-dev-96-g918650a

### ISSUE THREAD

**Issue by eschnett** [open-mpi/ompi#751] opened 2015-07-26 12:43 UTC
`configure` in version v2.x-dev-96-g918650a needs approximately this patch:
```
  --- configure
  +++ configure
  @@ -310405,10 +310405,11 @@
       case $prev$p in
   
       -L* | -R* | -l*)
  -       # Some compilers place space between "-{L,R}" and the path.
  +       # Some compilers place space between "-{L,R,l}" and the path.
          # Remove the space.
  -       if test x-L = "$p" ||
  -          test x-R = "$p"; then
  +       if test x-L = "x$p" ||
  +          test x-R = "x$p" ||
  +          test x-l = "x$p"; then
   	 prev=$p
   	 continue
          fi
  @@ -312363,10 +312364,11 @@
       case $prev$p in
   
       -L* | -R* | -l*)
  -       # Some compilers place space between "-{L,R}" and the path.
  +       # Some compilers place space between "-{L,R,l}" and the path.
          # Remove the space.
  -       if test x-L = "$p" ||
  -          test x-R = "$p"; then
  +       if test x-L = "x$p" ||
  +          test x-R = "x$p" ||
  +          test x-l = "x$p"; then
   	 prev=$p
   	 continue
          fi
```

Whether the check for the flag `-l` is necessary I don't know; however, the missing `x` prefix before the `$p` is crucial. This seems to come from an error in `config/libtool.m4`. As is, these test can never be true.

**Comment by ggouaillardet** [comment] 2015-07-26 15:11
This is coming from the config/libtool.m4 of hwloc
is this file even supposed to be here (e.g. in the ompi git) ?
could the root cause be a buggy libtool ?

**Comment by ggouaillardet** [comment] 2015-07-26 15:13
@eschnett out of curiosity, in which environment (compiler, configure command line) does this bug have an impact ?

**Comment by eschnett** [comment] 2015-07-26 15:15
This creates problems on a Cray XC30 (Edison at NERSC). It leads to stand-alone `-l` flags in the ldflags that `mpicc` uses. These are already visible in the `config.status` of OpenMPI. In the end, the compiler complains about options such as `-l-L/some/path`, which is treated as a library that cannot be found.

**Comment by ggouaillardet** [comment] 2015-07-27 01:25
please ignore what i wrote about hwloc and config/libtool.m4

the issue comes from libtool 2.4.3 and later. v1.8 and v1.10 uses libtool 2.4.2 (ok)
v2.x and master uses libtool 2.4.6 (ko)

i can access an other XC30, but i cannot reproduce exactly the problem.
could you please post
- the output of module list
- the configure command line
- you config.status
i can report this to the libtool maintainers, but i guess they will ask some more evidences before they accept any patch.

@jsquyres @rhc54 can you please confirm libtool 2.4.6 is used to build the v2.x and master tarballs ?
though the web site indicates libtool 2.4.6 is required, autogen.pl is happy with 2.4.2
(and i use libtool 2.4.2 that comes by default with rhel7 and never got any complain)
iirc, we noticed an other libtool bug in libtool > 2.4.2 and that was fixed by not using libltdl.
is there any point of using libtool 2.4.6 now ? if not, can we go back to 2.4.2 ? if yes, should we patch libtool 2.4.6 ?

**Comment by eschnett** [comment] 2015-07-27 01:31
I don't think you need evidence. The code is clearly broken. Using an `x` prefix for strings inside `test` is a common pattern (to avoid grammar ambiguities), and this needs to be done on both sides of the equals sign. (If you look for `test` in `configure`, you'll see this.) This is a clear case where someone forgot to add the `x` on the right hand side.

Whether the additional case handling `-l` is necessary or not is a different issue. This case wasn't there in earlier versions either, so it'll take more convincing to add it. However, the missing `x` is a regression.

**Comment by rhc54** [comment] 2015-07-27 01:41
I agree with Erik - I don’t think this is a libtool problem, regardless of version. It’s just a broken test that needs to be fixed on master and backported to the 2.x series. I’m not sure which .m4 has the problem in it, but it shouldn’t be too hard to find.

**Comment by ggouaillardet** [comment] 2015-07-27 06:00
@rhc54 i respectfully disagree

the broken test comes from libtool.m4 which is (indirectly) copied from the local libtool installation by autogen.pl

on my rhel7 box
```
$ rpm -q libtool
libtool-2.4.2-20.el7.x86_64
```
from /usr/share/aclocal/libtool.m4
```sh
       # Some compilers place space between "-{L,R}" and the path.
       # Remove the space.
       if test $p = "-L" ||
          test $p = "-R"; then
         prev=$p
         continue
       fi
```
and the very same code ends up in configure :-)

now on an other box with a custom install of libtool 2.4.6
```bash
       # Some compilers place space between "-{L,R}" and the path.
       # Remove the space.
       if test x-L = "$p" ||
          test x-R = "$p"; then
         prev=$p
         continue
       fi
```
and the same broken code end up in configure

**Comment by ggouaillardet** [comment] 2015-07-27 07:33
for the record, here is my email to the libtool folks http://lists.gnu.org/archive/html/bug-libtool/2015-07/msg00002.html

**Comment by rhc54** [comment] 2015-07-27 08:51
Kewl - as I said, I don't know (and I guess I missed your earlier comment about the source) which .m4 was the problem Given that it is from libtool itself, then they do indeed have a bug.

Going back to 2.4.2 isn't an option as too many users have the higher version. I'd have to look at the question of whether it is necessary to slurp it into OMPI (other than the fact we just install their tarball). Have you tried deleting it and rebuilding (probably have to autogen)?

**Comment by ggouaillardet** [comment] 2015-07-27 09:54
Ralph,

if I understand correctly (Jeff, feel free to join !), libtool.m4 is copied
by libtool (e.g. not by us...),
and this happens in autogen.pl

I can see only two options right now :
a) inform the community 2.4.6 has a bug, and generate tarballs for master
and v2.x with libtool 2.4.6
b) patch libtool 2.4.6 and generate the tarballs

Cheers,

Gilles

**Comment by ggouaillardet** [comment] 2015-07-28 04:09
i noticed we already "kind of" patch the libtool output in order to fix some known bugs.
this patch does the trick for libtool > 2.4.2

```patch
diff --git a/autogen.pl b/autogen.pl
index 9d2c3bb..f31c30e 100755
--- a/autogen.pl
+++ b/autogen.pl
@@ -5,6 +5,8 @@
 # Copyright (c) 2013      Mellanox Technologies, Inc.
 #                         All rights reserved.
 # Copyright (c) 2013-2014 Intel, Inc.  All rights reserved.
+# Copyright (c) 2014      Research Organization for Information Science
+#                         and Technology (RIST). All rights reserved.
 # $COPYRIGHT$
 #
 # Additional copyrights may follow
@@ -173,9 +175,11 @@ sub process_subdir {
     if (-x "autogen.pl") {
         print "--- Found autogen.pl; running...\n";
         safe_system("./autogen.pl");
+        patch_configure_output($dir);
     } elsif (-x "autogen.sh") {
         print "--- Found autogen.sh; running...\n";
         safe_system("./autogen.sh");
+        patch_configure_output($dir);
     } elsif (-f "configure.in" || -f "configure.ac") {
         print "--- Found configure.in|ac; running autoreconf...\n";
         safe_system("autoreconf -ivf");
@@ -970,6 +974,43 @@ sub patch_autotools_output {
     verbose "$indent_str"."Patching configure for IBM xlf libtool bug\n";
     $c =~ s/(\$LD -shared \$libobjs \$deplibs \$)compiler_flags( -soname \$soname)/$1linker_flags$2/g;
 
+    # Fix consequence of broken libtool.m4 from LT 2.4.3
+    # see http://lists.gnu.org/archive/html/bug-libtool/2015-07/msg00002.html
+    $c =~ s/test x-L = \"\$p\"/test x-L = \"x\$p\"/g;
+    $c =~ s/test x-R = \"\$p\"/test x-R = \"x\$p\"/g;
+
+    open(OUT, ">configure.patched") || my_die "Can't open configure.patched";
+    print OUT $c;
+    close(OUT);
+    # Use cp so that we preserve permissions on configure
+    safe_system("cp configure.patched configure");
+    unlink("configure.patched");
+}
+
+##############################################################################
+
+sub patch_configure_output {
+    my ($topdir) = @_;
+
+    # Set indentation string for verbose output depending on current directory.
+    my $indent_str = "    ";
+    if ($topdir eq ".") {
+        $indent_str = "=== ";
+    }
+
+    # Total ugh.  We have to patch the configure script itself.  See below
+    # for explainations why.
+    open(IN, "configure") || my_die "Can't open configure";
+    my $c;
+    $c .= $_
+        while(<IN>);
+    close(IN);
+
+    # Fix consequence of broken libtool.m4 from libtool 2.4.3
+    # see http://lists.gnu.org/archive/html/bug-libtool/2015-07/msg00002.html
+    $c =~ s/test x-L = \"\$p\"/test x-L = \"x\$p\"/g;
+    $c =~ s/test x-R = \"\$p\"/test x-R = \"x\$p\"/g;
+
     open(OUT, ">configure.patched") || my_die "Can't open configure.patched";
     print OUT $c;
     close(OUT);
@@ -1288,6 +1329,7 @@ foreach my $project (@{$projects}) {
         if (-d "$project->{dir}/config");
 }
 safe_system($cmd);
+patch_configure_output(".");
 
 #---------------------------------------------------------------------------
 
```

**Comment by ggouaillardet** [comment] 2015-07-29 07:33
@jsquyres i forgot to add you as a participant for this issue.
could you please check it out and comment ?

**Comment by jsquyres** [comment] 2015-08-05 21:49
Sorry for the delay.  I agree with @ggouaillardet -- the problem is libtool's .m4 file, which we don't control.  We can patch it (and we have done so in the past, as Gilles noted).

@ggouaillardet In principle, I agree with your patch.  Is there a reason add the new patch_configure_output() sub?  I.e., is it not safe to always call patch_autotools_output()?  If it's not safe, can we try to not duplicate the code?  E.g., move *all* the configure-patching stuff to patch_configure_output(), and then have patch_autotools_output() call patch_configure_output()?

**Comment by ggouaillardet** [comment] 2015-08-06 07:19
@jsquyres here is a snippet of autogen.pl
```perl
    if (-x "autogen.pl") {
        print "--- Found autogen.pl; running...\n";
        safe_system("./autogen.pl");
    } elsif (-x "autogen.sh") {
        print "--- Found autogen.sh; running...\n";
        safe_system("./autogen.sh");
    } elsif (-f "configure.in" || -f "configure.ac") {
        print "--- Found configure.in|ac; running autoreconf...\n";
        safe_system("autoreconf -ivf");
        print "--- Patching autotools output... :-(\n";
        patch_autotools_output($start);
    } else {
        my_die "Found subdir, but no autogen.sh or configure.in|ac to do anything";
    }
```
currently ```patch_autotools_output``` is only called when there is no autogen.{pl,sh}, and i just do not know why.
so unless this is a bug (e.g. ```patch_autotools_output``` should always be invoked) we need to fix all the generated ```configure``` files, regardless they "come from" autogen.{pl,sh} or configure.{in,ac}

if ```patch_autotools_output``` can/should always be invoked, then there is no need for code duplication and i will move the two sed-like lines into ```patch_autotools_output```
otherwise, i can always invoke ```patch_autotools_output``` and add a flag that indicates how configure was generated.

can you please advise how we should move forward ?

**Comment by jsquyres** [comment] 2015-08-06 11:00
@ggouaillardet I'm honestly not sure why we're not calling `patch_autotools_output()` in only one of the 3 cases.  The only reason I can think of would be that we can't assume/know that invoking `autogen.pl` or `autogen.sh` will necessarily invoke the GNU Autotools.  E.g., they *could* use CMake to build a component (no one has ever done that to my knowledge, but it's possible).

So perhaps we should shore up the error checking in `patch_autotools_output()` to patch `configure` only if it exists.  I can do that quickly.

For this issue, though, let's just try calling `patch_autotools_output()` in all 3 cases, and adding your new patch to that routine, and see if that works.

Do you want to make a PR for this, and we can continue the conversation on it?

**Comment by jsquyres** [comment] 2015-08-06 11:41
@ggouaillardet Ok, I just pushed a commit to `autogen.pl` that calls `patch_autotools_output()` in all cases.  Go ahead and add the bits for the new patch that @eschnett identified.

**Closed** 2015-08-07 02:52 UTC
