### ISSUE TITLE
master: Setting pmix_base_async_modex=1 is causing jobs to hang/fail

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#4277] opened 2017-09-27 14:28 UTC
Lots of Cisco MTT jobs are hanging on master when setting the MCA param `pmix_base_async_modex` equal to 1.

When I run on master HEAD across 2 nodes in a SLURM allocation (each with 16 cores):

```
$ mpirun --mca btl tcp,vader,self  --mca oob tcp  --mca pmix_base_async_modex 0 ./ring_c
Process 0 sending 10 to 1, tag 201 (32 processes in ring)
...process runs correctly and to completion
```

But if I set `pmix_base_async_modex=1`:

```
$ mpirun --mca btl tcp,vader,self  --mca oob tcp  --mca pmix_base_async_modex 1 ./ring_c
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[22313,1],11]) is on host: mpi003
  Process 2 ([[22313,1],0]) is on host: mpi003
  BTLs attempted: self vader tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[mpi003:10081] *** An error occurred in MPI_Init
[mpi003:10081] *** reported by process [1462304769,11]
[mpi003:10081] *** on a NULL communicator
[mpi003:10081] *** Unknown error
[mpi003:10081] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[mpi003:10081] ***    and potentially your MPI job)
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  mpi024
  System call: open(2) 
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
```

The first error message is about how two procs on the same host can't communicate with each other, even though it tried  the`tcp` and `vader` BTLs.  Both of these should enable loopback communication -- perhaps somehow some modex information didn't get through?

In an interactive run, it looks like this just cleanly aborts.  In MTT runs, it looks like it hangs -- I'm not sure why there's a difference.

@rhc54 Can you have a look?

**Comment by rhc54** [comment] 2017-09-27 16:09
Sigh - I can't run multi-node with TCP at all:
```
[rhc002][[6319,1],2][btl_tcp.c:549:mca_btl_tcp_recv_blocking] remote peer unexpectedly closed connection while I was waiting for blocking message
--------------------------------------------------------------------------
WARNING: Open MPI failed to handshake with a connecting peer MPI
process over TCP.  This should not happen.

Your Open MPI job may now fail.

  Local host: rhc002
  PID:        139968
  Message:    did not receive entire connect ACK from peer
--------------------------------------------------------------------------
[rhc002][[6319,1],3][btl_tcp.c:549:mca_btl_tcp_recv_blocking] remote peer unexpectedly closed connection while I was waiting for blocking message
```
I do have two NICs on the machines, and Warewulf has named them differently (i.e., the HNP is running with an interface called ens2f1 on the 10.x net, while the other node is on an interface called eth0 on the 10.x net). I tried passing btl_tcp_if_include and exclude options to resolve the problem, but nothing works.

Anyone have a suggestion?

**Comment by rhc54** [comment] 2017-09-27 16:09
Sigh - I can't run multi-node with TCP at all:
```
[rhc002][[6319,1],2][btl_tcp.c:549:mca_btl_tcp_recv_blocking] remote peer unexpectedly closed connection while I was waiting for blocking message
--------------------------------------------------------------------------
WARNING: Open MPI failed to handshake with a connecting peer MPI
process over TCP.  This should not happen.

Your Open MPI job may now fail.

  Local host: rhc002
  PID:        139968
  Message:    did not receive entire connect ACK from peer
--------------------------------------------------------------------------
[rhc002][[6319,1],3][btl_tcp.c:549:mca_btl_tcp_recv_blocking] remote peer unexpectedly closed connection while I was waiting for blocking message
```
I do have two NICs on the machines, and Warewulf has named them differently (i.e., the HNP is running with an interface called ens2f1 on the 10.x net, while the other node is on an interface called eth0 on the 10.x net). I tried passing btl_tcp_if_include and exclude options to resolve the problem, but nothing works.

Anyone have a suggestion?

**Comment by rhc54** [comment] 2017-09-27 16:09
Sigh - I can't run multi-node with TCP at all:
```
[rhc002][[6319,1],2][btl_tcp.c:549:mca_btl_tcp_recv_blocking] remote peer unexpectedly closed connection while I was waiting for blocking message
--------------------------------------------------------------------------
WARNING: Open MPI failed to handshake with a connecting peer MPI
process over TCP.  This should not happen.

Your Open MPI job may now fail.

  Local host: rhc002
  PID:        139968
  Message:    did not receive entire connect ACK from peer
--------------------------------------------------------------------------
[rhc002][[6319,1],3][btl_tcp.c:549:mca_btl_tcp_recv_blocking] remote peer unexpectedly closed connection while I was waiting for blocking message
```
I do have two NICs on the machines, and Warewulf has named them differently (i.e., the HNP is running with an interface called ens2f1 on the 10.x net, while the other node is on an interface called eth0 on the 10.x net). I tried passing btl_tcp_if_include and exclude options to resolve the problem, but nothing works.

Anyone have a suggestion?

**Comment by bosilca** [comment] 2017-09-27 16:17
There was a severe breakage in the TCP BTL. I am working on a fix (disclaimer: I'm at EuroMPI/USA and the progress might be slow)

**Comment by jsquyres** [comment] 2017-09-27 17:10
This looks like the same TCP BTL error I reported in #4263.

**Comment by bosilca** [comment] 2017-09-27 18:38
Yes, the same root cause (the handshaking fails similarly on both peers) so they fail to connect to each other).

**Comment by rhc54** [comment] 2017-10-10 15:25
I'll just capture what I was able to discover. I'm not sure where this breaks. On my system, the hang occurs only occasionally, so it appears there is some race condition. However, after printing out some debug stuff, it appears that the direct modex code path is never exercised even in the case of a hanging run on my systems.

What I see (even with the print statements in the dmodex path) is:
```
$ mpirun --mca btl tcp,vader,self  --mca oob tcp  --mca pmix_base_async_modex 1 ./ring_c
Process 0 sending 10 to 1, tag 201 (48 processes in ring)
Process 0 sent to 1
<hang>
```
So no evidence of any calls into dmodex.

**Comment by rhc54** [comment] 2017-10-10 16:01
@artpol84 @jladd-mlnx I will not be able to look into this any time soon. At this time, I believe UCX is the only one able to take advantage of the option as other transports all still require a data exchange, and so derive benefit from async_modex only in cases of sparse connectivity. Do you folks want to take a look at it?

**Comment by jladd-mlnx** [comment] 2017-10-10 16:36
@rhc54 Not sure I understand. TCP BTL is hanging when async modex is set, but TCP BTL doesn't support direct modex, so a full modex is executed. We don't have any expertise in TCP BTL, and from what I can tell this is a bug in the BTL, not PMIx.

**Comment by rhc54** [comment] 2017-10-10 16:43
When async modex is set, we don't execute a full modex. Instead, we do a direct modex call on each request for modex info. All of the BTLs only do this upon first communication between procs, and so it only happens on an as-needed basis.

What we don't know right now is where the problem lies - is there an issue with the direct modex support, or a problem in the TCP BTL?

What I was hoping you folks could do is try it with your transports to verify that direct modex is indeed working correctly. If so, then we would have a better idea of where to look. Since this is on master, I wasn't sure if you have tested it anytime recently.

**Comment by jladd-mlnx** [comment] 2017-10-10 18:35
I know for a fact that direct modex is working as expected with UCX on 2.x and 3.x branches. We do test it regularly and deploy OSHMEM in production with this setting. Master, not sure.

**Comment by rhc54** [comment] 2017-10-10 19:02
Okay, I'll take that to mean is is quite likely to be okay in master (please let us know if you get a chance to verify there).

@jsquyres Not sure where to move from here. I agree that it looks like a probably TCP issue, but given that this is only really useful at scale, I don't know how important it will be for the TCP/BTL folks to investigate.

**Comment by jsquyres** [comment] 2017-10-11 00:22
@bosilca @bwbarrett You guys care about the TCP BTL.  Per the above discussion, can you investigate why setting `pmix_base_async_modex=1` makes it unhappy?

**Comment by rhc54** [comment] 2017-10-11 01:24
@jsquyres Can you turn it "on" for your usnic runs? All it does is force us to lookup the modex information via a daemon-to-daemon request instead of doing a barrier. It _should_ work for any transport. What I'm concerned about is that I don't see _any_ modex requests occurring from the TCP use-case. I'd like to know if that is something specific to TCP/BTL, or if there is a general problem in the direct modex logic (possibly in PMIx itself).

**Comment by jsquyres** [comment] 2017-10-11 20:18
I didn't turn it on in my MTT, but I ran it manually for both the TCP and usNIC BTLs, and essentially got the same result for both:

## TCP

```
$ mpirun --mca btl tcp,vader,self --mca pmix_base_async_modex 1 ring_c
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[8146,1],16]) is on host: mpi002
  Process 2 ([[8146,1],17]) is on host: mpi002
  BTLs attempted: self vader tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[mpi002:10488] *** An error occurred in MPI_Init
[mpi002:10488] *** reported by process [533856257,16]
[mpi002:10488] *** on a NULL communicator
[mpi002:10488] *** Unknown error
[mpi002:10488] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[mpi002:10488] ***    and potentially your MPI job)
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  mpi001
  System call: open(2) 
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
```

## usNIC

```
$ mpirun --mca btl usnic,vader,self --mca pmix_base_async_modex 1 ring_c
Process 0 sending 10 to 1, tag 201 (32 processes in ring)
Process 0 sent to 1
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[1373,1],11]) is on host: mpi001
  Process 2 ([[1373,1],0]) is on host: mpi001
  BTLs attempted: self vader usnic

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[mpi001:13850] *** An error occurred in MPI_Init
[mpi001:13850] *** reported by process [89980929,12]
[mpi001:13850] *** on a NULL communicator
[mpi001:13850] *** Unknown error
[mpi001:13850] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[mpi001:13850] ***    and potentially your MPI job)
```

**Comment by rhc54** [comment] 2017-10-12 01:07
This is disturbing - I am getting a very different behavior. I just hang without any error messages appearing. However, your error messages indicate that the problem is in the shared memory (vader) startup - not in usnic or tcp. It looks like the backing file isn't ready before one of the other procs tries to access it.

I wonder if someone can take a look down there and see if vader isn't correctly coordinating that handshake minus the modex barrier? @hjelmn - might you have a minute?

**Comment by artpol84** [comment] 2017-10-12 09:53
Probably makes sense just to try without vader

**Comment by jsquyres** [comment] 2017-10-12 16:53
I can only test TCP with vader; usNIC does not do loopback communications.

Here's a control test (at master HEAD 12 Oct 2017) to show that it works fine with `async_modex=0`:

```
$ mpirun -npernode 1 -np 2 hostname
mpi002
mpi001
$ mpirun -npernode 1 -np 2 --mca btl tcp,self --mca pmix_base_async_modex 0 ring_c
Process 0 sending 10 to 1, tag 201 (2 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
Process 1 exiting
```

And here it is with `async_modex=1`:

```
$ mpirun -npernode 1 -np 2 --mca btl tcp,self --mca pmix_base_async_modex 1 ring_c
Process 0 sending 10 to 1, tag 201 (2 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
Process 1 exiting
```

😲 

It looks like I have to go up to about 12 procs (6 ppn) to get this issue to occur semi-reliably (i.e., maybe 50% of my manual invocations got this error; the other half ran successfully):

```
$ mpirun -npernode 6 -np 12 --mca btl tcp,self --mca pmix_base_async_modex 1 ring_c
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[438,1],8]) is on host: mpi002
  Process 2 ([[438,1],6]) is on host: mpi002
  BTLs attempted: self tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[mpi002:15826] *** An error occurred in MPI_Init
[mpi002:15826] *** reported by process [28704769,8]
[mpi002:15826] *** on a NULL communicator
[mpi002:15826] *** Unknown error
[mpi002:15826] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[mpi002:15826] ***    and potentially your MPI job)
Process 0 sending 10 to 1, tag 201 (12 processes in ring)
[mpi001][[438,1],5][btl_tcp.c:559:mca_btl_tcp_recv_blocking] recv(17) failed: Connection reset by peer (104)
Process 0 sent to 1
```

So it definitely feels like a race condition of some kind.  But not involving vader.

Does that help?

**Comment by rhc54** [comment] 2017-10-24 04:08
I did some work on another matter, and found that the MPI_Init modex/barrier wasn't quite right - there was a chance for a non-blocking fence to be initiated without a terminating release. I fixed that, but it hasn't completely resolved this problem.

If you look at the revised code, you see this for the modex:
```
        if (opal_pmix_base_async_modex && opal_pmix_collect_all_data) {
            /* execute the fence_nb in the background to collect
             * the data */
            background_fence = true;
            OPAL_PMIX_CONSTRUCT_LOCK(&lock);
            opal_pmix.fence_nb(NULL, true, fence_release, (void*)&lock);
        } else if (!opal_pmix_base_async_modex) {
            /* we want to do the modex */
            OPAL_PMIX_CONSTRUCT_LOCK(&lock);
            opal_pmix.fence_nb(NULL, opal_pmix_collect_all_data,
                               fence_release, (void*)&lock);
            /* cannot just wait on thread as we need to call opal_progress */
            OMPI_LAZY_WAIT_FOR_COMPLETION(lock.active);
            OPAL_PMIX_DESTRUCT_LOCK(&lock);
        }
        /* otherwise, we don't want to do the modex, so fall thru */
```
Note that setting ```-mca pmix_base_async_modex 1``` by itself will result in the "background fence" being executed as opal_pmix_base_collect_data defaults to true.  If we then look down to the barrier:
```
    if (background_fence) {
        OMPI_LAZY_WAIT_FOR_COMPLETION(lock.active);
        OPAL_PMIX_DESTRUCT_LOCK(&lock);
    } else if (!ompi_async_mpi_init) {
        /* wait for everyone to reach this point - this is a hard
         * barrier requirement at this time, though we hope to relax
         * it at a later point */
        if (NULL != opal_pmix.fence_nb) {
            OPAL_PMIX_CONSTRUCT_LOCK(&lock);
            opal_pmix.fence_nb(NULL, false,
                               fence_release, (void*)&lock);
            OMPI_LAZY_WAIT_FOR_COMPLETION(lock.active);
            OPAL_PMIX_DESTRUCT_LOCK(&lock);
        } else {
            opal_pmix.fence(NULL, false);
        }
    }
```
we see that we will do a lazy wait until the barrier is reached. The problem here is that we don't have a clean way of terminating the lazy wait as we must cycle calling opal_progress (so we can't just sit in a thread condition). Changing that lazy wait to an OPAL_PMIX_WAIT_THREAD (which calls condition wait), however, does not resolve the problem. For whatever reason, it appears that some processes do not receive their release and they hang in that lazy wait.

I am becoming convinced this must be in PMIx itself. The reason is that some of the procs on each node are indeed getting notified that the fence has completed. If that is true, then the orte and opal layers must have passed that completion notice down - otherwise, the PMIx server wouldn't have notified anyone.

Thus, it seems that either the PMIx server is failing to notify some local clients, or the clients are receiving the notification but failing to callback up thru opal to the release function. Somewhere in those chains we are failing to properly thread protect (or hitting a thread block condition).

Note that adding ```-mca pmix_base_collect_data 0```, which causes us to skip the modex all together, results in an error in vader:
```
$ mpirun -mca pmix_base_async_modex 1 -mca pmix_base_collect_data 0 ./ring
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[11748,1],4]) is on host: rhc001
  Process 2 ([[11748,1],9]) is on host: rhc001
  BTLs attempted: self tcp vader

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[rhc001:236615] *** An error occurred in MPI_Init
[rhc001:236615] *** reported by process [769916929,2]
[rhc001:236615] *** on a NULL communicator
[rhc001:236615] *** Unknown error
[rhc001:236615] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[rhc001:236615] ***    and potentially your MPI job)
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  rhc001
  System call: open(2) 
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
[rhc001:236607] 24 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
[rhc001:236607] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[rhc001:236607] 22 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:pml-add-procs-fail
[rhc001:236607] 22 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
[rhc001:236607] 15 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
```
Removing vader just moves the problem to tcp:
```
$ mpirun -mca pmix_base_async_modex 1 -mca pmix_base_collect_data 0 -mca btl tcp,self ./ring
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[62439,1],1]) is on host: rhc001
  Process 2 ([[62439,1],14]) is on host: rhc001
  BTLs attempted: self tcp

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[rhc001:16966] *** An error occurred in MPI_Init
[rhc001:16966] *** reported by process [4092002305,1]
[rhc001:16966] *** on a NULL communicator
[rhc001:16966] *** Unknown error
[rhc001:16966] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[rhc001:16966] ***    and potentially your MPI job)
[rhc001:16959] 23 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
[rhc001:16959] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[rhc001:16959] 23 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:pml-add-procs-fail
[rhc001:16959] 23 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
```

**Comment by rhc54** [comment] 2017-10-24 13:46
I found that skipping the modex altogether would frequently fail, and tracked it down to an issue in PMIx. With that fixed [here](https://github.com/open-mpi/ompi/pull/4387), it now works reliably for small ppn:
```
$ mpirun -mca pmix_base_async_modex 1
       -mca pmix_base_collect_data 0 -npernode 2 -mca pmix_server_verbose 5 ./ring
[rhc001:113078] [[2159,0],0] register nspace for [2159,1]
[rhc002.cluster:121988] [[2159,0],1] register nspace for [2159,1]
Rank 1 has cleared MPI_Init
Rank 0 has cleared MPI_Init
Rank 2 has cleared MPI_Init
Rank 3 has cleared MPI_Init
[rhc002.cluster:121988] [[2159,0],1] dmdx:recv request from proc [[2159,0],0] for proc [[2159,1],2]
[rhc001:113078] [[2159,0],0] dmdx:recv response from proc [[2159,0],1]
[rhc001:113078] [[2159,0],0] dmdx:recv request from proc [[2159,0],1] for proc [[2159,1],1]
[rhc002.cluster:121988] [[2159,0],1] dmdx:recv response from proc [[2159,0],0]
[rhc001:113078] [[2159,0],0] dmdx:recv request from proc [[2159,0],1] for proc [[2159,1],0]
[rhc002.cluster:121988] [[2159,0],1] dmdx:recv response from proc [[2159,0],0]
[rhc002.cluster:121988] [[2159,0],1] dmdx:recv request from proc [[2159,0],0] for proc [[2159,1],3]
[rhc001:113078] [[2159,0],0] dmdx:recv response from proc [[2159,0],1]
Rank 1 has completed ring
Rank 0 has completed ring
Rank 2 has completed ring
Rank 3 has completed ring
Rank 0 has completed MPI_Barrier
Rank 1 has completed MPI_Barrier
Rank 2 has completed MPI_Barrier
Rank 3 has completed MPI_Barrier
[rhc002.cluster:121988] [[2159,0],1] Finalizing PMIX server
[rhc001:113078] [[2159,0],0] Finalizing PMIX server
```
Still fails for large ppn (24ppn in this case):
```
$ mpirun -mca pmix_base_async_modex 1 -mca pmix_base_collect_data 0 ./ring
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[2951,1],3]) is on host: rhc001
  Process 2 ([[2951,1],15]) is on host: rhc001
  BTLs attempted: self tcp vader

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[rhc001:113255] *** An error occurred in MPI_Init
[rhc001:113255] *** reported by process [193396737,3]
[rhc001:113255] *** on a NULL communicator
[rhc001:113255] *** Unknown error
[rhc001:113255] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[rhc001:113255] ***    and potentially your MPI job)
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  rhc002.cluster
  System call: open(2) 
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
[rhc001:113246] 22 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
[rhc001:113246] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[rhc001:113246] 21 more processes have sent help message help-mpi-runtime.txt / mpi_init:startup:pml-add-procs-fail
[rhc001:113246] 20 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal unknown handle
[rhc001:113246] 12 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
```

**Comment by rhc54** [comment] 2017-10-24 16:00
One quick final comment - I added a little debug and found that the PMIx server thinks it successfully found and delivered the requested modex info. So I'm not sure why the procs are claiming that they cannot talk to each other when on the same node.

**Comment by rhc54** [comment] 2017-10-25 04:24
It wasn't in that location, but I added some more outputs and found the error occurring in the segment_attach function:
```
[rhc001:198295] shmem_mmap_module.c:503 FILE /tmp/ompi.rhc001.1000/pid.198268/1/3/vader_segment.rhc001.3
```
Does that help?

**Comment by bosilca** [comment] 2017-10-25 04:53
OK, so the problem is not when a process create it's own mmaped region, but when it tries to attach to the mmaped file of one of the other local processes. That's why you fail on segment_attach and not in segment_create. Honestly this is puzzling, because in order for a process to try to attach to a shared memory segment, it must receive the name from the modex and this clearly implies that the backend file has been successfully created.

Short answer: this is bad. Either the file system is not atomic (which is scary, hardly believable but not unheard of), or that we fail to properly synchronize before attaching to the mmap file (and as a result the slaves try to attach to the backed file before it gets properly created by its owner). But honestly I don't see how, as we know the file name from the modex, which means the creator put it there. That's a pretty strong synchronization.

@hjelmn how about each process succeed to check that there is enough room on the device because nobody created their backend file yet, but then when they all start to create it in same time, we run out of space ?

**Comment by rhc54** [comment] 2017-10-25 05:47
@bosilca @hjelmn Is it possible that we do a modex send _before_ we have actually created the file? In that case, the modex recv of the other process might occur fast enough that it attempts to attach before the initial process gets the file created.

**Comment by bosilca** [comment] 2017-10-25 06:05
I tend to say no. The backend file is first created (mca_btl_vader_component_init in ./btl_vader_component.c:501), then the process attach to it (this initialize some parts of the file), and only then line 530 we send the modex.

**Comment by rhc54** [comment] 2018-06-26 15:24
Appears fixed on master

**Closed by rhc54** 2018-06-26 15:24 UTC
Labels: Target: master, bug
