### ISSUE TITLE
mpi4py: Regression in MPI_Alltoallv() using MPI_INPLACE

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#9501] opened 2021-10-09 19:08 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

git master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

See logs.

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

Fresh clone in a GitHub Actions runner. See logs.

### Please describe the system on which you are running

* Operating system/version: Linux
* Computer hardware: x86_64
* Network type: 

-----------------------------

## Details of the problem

See logs: https://github.com/mpi4py/mpi4py-testing/runs/3847097248?check_suite_focus=true

This same test was working 6 days ago.

**Comment by gpaulsen** [comment] 2021-11-11 15:53
@dalcinl Can you please retest now with latest v5.0.x now that https://github.com/open-mpi/ompi/pull/9652 has been merged?

**Comment by dalcinl** [comment] 2021-11-11 16:19
@gpaulsen Off-topic, but anyway... I'm doing a manual build, as my ompi/master CI infrastructure is broken (one month by now, waiting for a resolution to issue 9501). I'm runing GCC 11.2.1 and configuring with `--enable-debug --enable-mem-debug`. I'm seeing tons of warnings (`-Wformat`, `-Wpedantic`, `-Wcompare`, etc). Are you aware of that? Or you just don't test with `--enable-debug` or with such a recent GCC version?

**Comment by awlauria** [comment] 2021-11-11 16:21
It's possible we need a warnings sweep in master. One day it would be nice to compile with -Werror...

**Comment by dalcinl** [comment] 2021-11-11 16:46
@gpaulsen This PR seems to fix the issue with current master.

@awlauria I fresh run of my testsuite with ompi built with ucx is sowing the following malloc zero warnings and aborts after failed assertion:

```
...
malloc debug: Request for 0 bytes (osc_ucx_comm.c, 661)
malloc debug: Request for 0 bytes (osc_ucx_comm.c, 972)
malloc debug: Request for 0 bytes (osc_ucx_active_target.c, 228)
malloc debug: Request for 0 bytes (osc_ucx_active_target.c, 104)
...
osc_ucx_component.c:610: ompi_osc_ucx_win_attach: Assertion `insert_index >= 0 && (uint64_t)insert_index < module->state.dynamic_win_count' failed.
```
Runinng with `OMPI_MCA_osc=sm`, the assertion abort goes away, and my OSC tests complete successfully.

PS: @jsquyres Will mpi4py ever be used to catch Open MPI regressions before they slip to master and release branches? I tried to do it by myself, but it is impossible, I've been waiting for a resolution to #9501 for about a month, my CI is [still broken](https://github.com/mpi4py/mpi4py-testing/actions/workflows/openmpi.yml) because of that, while other issues may slip in in master.

**Comment by dalcinl** [comment] 2021-11-11 16:52
@gpaulsen This PR seems to fix the issue with current master. I used a local build. Now I fired up a CI build in [GitHub Actions](https://github.com/mpi4py/mpi4py-testing/actions/runs/1449717505).

**Comment by awlauria** [comment] 2021-11-11 16:59
Cool, thanks @dalcinl for verifying. Closing this as the master and v5 pr's have been merged.

**Comment by dalcinl** [comment] 2021-11-11 17:01
@awlauria Please note my edit above. I messed up. I was asked to run `v5.0.x`, but I did `master` instead. If the fix is in both branches, then all is good.

**Comment by gpaulsen** [comment] 2021-11-11 17:03
Great Thanks.  Yes this fix got into both `master` and `v5.0.x`.

**Comment by dalcinl** [comment] 2021-11-11 17:20
@gpaulsen @awlauria Sorry, guys, looks like I messed up with my local testing. My CI is still broken, this is for branch `v5.0.x`: https://github.com/mpi4py/mpi4py-testing/runs/4180762484?check_suite_focus=true. Looks like I tested with only one MPI process. Using two MPI processes, failures are still in there.

**Comment by awlauria** [comment] 2021-11-11 17:32
Thanks - reopened.

**Comment by bwbarrett** [comment] 2021-11-15 23:33
I'm pretty sure the issue is https://github.com/open-mpi/ompi/pull/9493/commits/531735cd53157d1b56577041e4612af0f0b83ca7, which was part of https://github.com/open-mpi/ompi/pull/9493.  The rest of the patch series (that actually fixes https://github.com/open-mpi/ompi/issues/9329) seems ok w.r.t alltoallv.  Still trying to figure out the core issue

Jeff mentioned an alltoallv fix that was backported to all the release branches.  I do not believe that was the change in play here, based on testing.

**Comment by awlauria** [comment] 2021-11-23 17:55
@dalcinl is this now passing?

**Comment by dalcinl** [comment] 2021-11-23 20:18
@awlauria [CI ran 4 days ago](https://github.com/mpi4py/mpi4py-testing/runs/4270602228), all tests passed  [![openmpi](https://github.com/mpi4py/mpi4py-testing/actions/workflows/openmpi.yml/badge.svg)](https://github.com/mpi4py/mpi4py-testing/actions/workflows/openmpi.yml).

**Comment by awlauria** [comment] 2021-12-01 14:26
Thanks @dalcinl - closing

**Closed by awlauria** 2021-12-01 14:26 UTC
Labels: Severity: critical, Target: master, Target: v5.0.x
