### ISSUE TITLE
DYLD_FALLBACK_LIBRARY_PATH ignored on MacOS X

### ISSUE THREAD

**Issue by astrofrog** [open-mpi/ompi#2068] opened 2016-09-11 10:40 UTC
I am trying to build OpenMPI using gfortran on a MacOS X, specifically trying to make a [conda](https://github.com/conda/conda) package. In particular, I need to make sure the fortran bindings are included. The gfortran compiler included in conda produces binaries that include an ``@rpath``:

```
$ otool -L a.out
a.out:
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/Users/tom/miniconda3/envs/dev35/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/./libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

For other packages, the workaround has been to set ``DYLD_FALLBACK_LIBRARY_PATH`` to the appropriate path, but this doesn't seem to work with OpenMPI, and the configure step fails with:

```
configure:33210: gfortran -o conftest   -arch x86_64  conftest.f  >&5
configure:33210: $? = 0
configure:33210: ./conftest
dyld: Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from: /Users/tom/miniconda3/conda-bld/._1473589995858/work/openmpi-2.0.0/./conftest
  Reason: image not found
./configure: line 4975: 95039 Trace/BPT trap: 5       ./conftest$ac_exeext
configure:33210: $? = 133
configure: program exited with status 133
configure: failed program was:
|       program main
| 
|       end
configure:33226: result: no
configure:33240: error: Could not run a simple Fortran program.  Aborting.
```

To reproduce the full issue, you need a conda installation and you can then do:

```
git clone http://github.com/astrofrog/openmpi-feedstock.git
cd openmpi-feedstock/
git checkout fortran-osx
conda build .
```

In the last part, the build script looks like

```bash
OPTS=""

if [ "$(uname)" == "Darwin" ]; then
    export DYLD_FALLBACK_LIBRARY_PATH="${PREFIX}/lib"
    export CC=clang
    export CXX=clang++
    export MACOSX_DEPLOYMENT_TARGET="10.9"
    export CXXFLAGS="-stdlib=libc++ $CXXFLAGS"
    export CXXFLAGS="$CXXFLAGS -stdlib=libc++"
    export LIBRARY_PATH="${PREFIX}/lib"
    export LD_LIBRARY_PATH="${PREFIX}/lib"
fi

ls $DYLD_FALLBACK_LIBRARY_PATH

echo 'program test; end program test' > test.f90
gfortran test.f90
./a.out

./configure --prefix=$PREFIX \
            --disable-dependency-tracking


make -j $CPU_COUNT
make check
make install
```

Note that I do a test compilation before running ./configure, and that runs fine provided I have set ``$DYLD_FALLBACK_LIBRARY_PATH``. So it really does seem like a case of ``$DYLD_FALLBACK_LIBRARY_PATH`` being ignored inside the ``configure`` process.

**Comment by ggouaillardet** [comment] 2016-09-12 05:46
i was unable to reproduce this

that being said, i had to make a few change to the recipe (e.g. remove requirements for ```perl``` and ```libgfortran```)

i am a newbie to anaconda, so i might have done something wrong during the setup.
i initially installed ```libgfortran``` and ```perl``` from ```conda-forge```, but ```conda build .``` mark them as unavailable. anyway, in installed ```gcc``` from the standard repo, and ```perl``` from the ```conda-forge``` repo. this is gcc 4.8.5, and it comes with ```gfortran``` and ```libgfortran.3.dylib```.

fwiw, i understand why you ```perl``` is required, but i do not understand why ```libgfortran```
also, openmpi 2.0.1 has been released recently, and it contains a bunch of bug fixes compared to 2.0.0

can you please give it an other try with the following patch
```patch
diff --git a/recipe/build.sh b/recipe/build.sh
index 89833df..326041e 100755
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -19,6 +19,26 @@ echo 'program test; end program test' > test.f90
 gfortran test.f90
 ./a.out
 
+rm -rf /tmp/xyz ; mkdir /tmp/xyz
+cp a.out /tmp/xyz
+env | tee /tmp/xyz/a.env
+
+cat > /tmp/xyz/configure.patch << EOF
+--- configure.orig	2016-09-12 14:11:28.000000000 +0900
++++ configure	2016-09-12 14:13:47.000000000 +0900
+@@ -33211,7 +33211,7 @@
+   opal_cv_Fortran_works="yes"
+ else
+   opal_cv_Fortran_works="no"
+-fi
++fi; cp conftest\$ac_exeext /tmp/xyz/b.out ; env | tee /tmp/xyz/b.env ; echo Fortran is working : \$opal_cv_Fortran_works; exit 1
+ rm -f core *.core core.conftest.* gmon.out bb.out conftest\$ac_exeext \\
+   conftest.\$ac_objext conftest.beam conftest.\$ac_ext
+ fi
+EOF
+
+patch configure < /tmp/xyz/configure.patch
+
 ./configure --prefix=$PREFIX \
             --disable-dependency-tracking
 
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 445bd1c..70f7ce4 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -18,11 +18,8 @@ build:
 
 requirements:
     build:
-        - perl
         - gcc  # [not win]
-        - libgfortran  # [osx]
     run:
-        - libgfortran  # [osx]
         - libgcc  # [linux]
 
 test:
```

you will find some stuff in ```/tmp/xyz```
then you can run ```otool -L``` on ```a.out``` and ```b.out```
and you can find the ```DYLD_FALLBACK_LIBRARY_PATH``` value from ```a.log``` and ```b.log```
then you can try to run them manually by setting the ```DYLD_FALLBACK_LIBRARY_PATH``` and we can hopefully understand what is going wrong

**Comment by astrofrog** [comment] 2016-09-12 09:19
@ggouaillardet - thanks for the quick reply! First, a quick note regarding:

> but conda build . mark them as unavailable

I forgot to include the following step in the steps to reproduce the issue:

```
conda config --add channels conda-forge
```

This needs to be done before ``conda build .`` so that the build process recognizes the conda-forge channel. Could you try with this to see if you can reproduce the issue? So basically you should do:

```
git clone http://github.com/astrofrog/openmpi-feedstock.git
cd openmpi-feedstock/
git checkout fortran-osx
conda config --add channels conda-forge
conda build .
```

Now I tried the suggested patch (both with and without the changes to ``meta.yaml``, and in both cases the build fails with

```
Fortran is working : no
```

Here's the output of ``otool``, and also you can see that ``DYLD_FALLBACK_LIBRARY_PATH`` is not present in the environment variables:

```
$ otool -L a.out 
a.out:
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/Users/tom/miniconda3/conda-bld/._1473671232350/_b_env_placehold_placehold_place/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/./libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
$ otool -L b.out 
b.out:
	@rpath/./libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/Users/tom/miniconda3/conda-bld/._1473671232350/_b_env_placehold_placehold_place/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/./libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
$ grep DYLD_FALLBACK_LIBRARY_PATH a.env
$ grep DYLD_FALLBACK_LIBRARY_PATH b.env
$
```

However, in the log for ``conda build .`` you can see that ``DYLD_FALLBACK_LIBRARY_PATH`` was defined and the compilation works. So it really seems like for some unknown reason, that variable gets dropped when ``configure`` is run:

```
+ export DYLD_FALLBACK_LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
+ DYLD_FALLBACK_LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
+ export CC=clang
+ CC=clang
+ export CXX=clang++
+ CXX=clang++
+ export MACOSX_DEPLOYMENT_TARGET=10.9
+ MACOSX_DEPLOYMENT_TARGET=10.9
+ export 'CXXFLAGS=-stdlib=libc++  -arch x86_64'
+ CXXFLAGS='-stdlib=libc++  -arch x86_64'
+ export 'CXXFLAGS=-stdlib=libc++  -arch x86_64 -stdlib=libc++'
+ CXXFLAGS='-stdlib=libc++  -arch x86_64 -stdlib=libc++'
+ export LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
+ LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
+ export LD_LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
+ LD_LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
+ ls /Users/tom/miniconda3/conda-bld/._1473671413866/_b_env_placehold_placehold_place/lib
gcc			libgcc_ext.10.5.dylib	libgfortran.spec	libgomp.la		libmpc.dylib		libssp_nonshared.la
gcj-4.8.5-14		libgcc_s.1.dylib	libgij.14.dylib		libgomp.spec		libmpc.la		libstdc++.6.dylib
libasan.0.dylib		libgcc_s_ppc64.1.dylib	libgij.dylib		libiberty.a		libmpfr.4.dylib		libstdc++.a
libasan.dylib		libgcc_s_x86_64.1.dylib	libgij.la		libisl.10.dylib		libmpfr.a		libstdc++.a-gdb.py
libasan.la		libgcj-tools.14.dylib	libgmp.10.dylib		libisl.10.dylib-gdb.py	libmpfr.dylib		libstdc++.dylib
libasan_preinit.o	libgcj-tools.dylib	libgmp.a		libisl.a		libmpfr.la		libstdc++.la
libatomic.1.dylib	libgcj-tools.la		libgmp.dylib		libisl.dylib		libquadmath.0.dylib	libsupc++.a
libatomic.a		libgcj.14.dylib		libgmp.la		libisl.la		libquadmath.a		libsupc++.la
libatomic.dylib		libgcj.dylib		libgmpxx.4.dylib	libitm.1.dylib		libquadmath.dylib	logging.properties
libatomic.la		libgcj.la		libgmpxx.a		libitm.a		libquadmath.la		pkgconfig
libcloog-isl.4.dylib	libgcj.spec		libgmpxx.dylib		libitm.dylib		libssp.0.dylib		security
libcloog-isl.a		libgfortran.3.dylib	libgmpxx.la		libitm.la		libssp.a
libcloog-isl.dylib	libgfortran.a		libgomp.1.dylib		libitm.spec		libssp.dylib
libcloog-isl.la		libgfortran.dylib	libgomp.a		libmpc.3.dylib		libssp.la
libgcc_ext.10.4.dylib	libgfortran.la		libgomp.dylib		libmpc.a		libssp_nonshared.a
+ echo 'program test; end program test'
+ gfortran test.f90
+ ./a.out
```

Very strange!

**Comment by astrofrog** [comment] 2016-09-12 09:23
Huh but a.env should contain the environment variable... I'll try and investigate further.

**Comment by astrofrog** [comment] 2016-09-12 09:32
This is puzzling - I did:

```
echo $DYLD_FALLBACK_LIBRARY_PATH
env
```

in ``build.sh`` and I get:

```
+ echo /Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/lib
/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/lib
+ env
DIRTY=
LDFLAGS= -arch x86_64
CPU_COUNT=8
PYTHONNOUSERSITE=1
LIBRARY_PATH=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/lib
PERL_VER=5.20.3
R=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/bin/R
PY_VER=3.5
CMAKE_GENERATOR=Unix Makefiles
LUA_INCLUDE_DIR=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/include
CONDA_BUILD_STATE=BUILD
CXXFLAGS=-stdlib=libc++  -arch x86_64 -stdlib=libc++
PKG_BUILDNUM=0
CONDA_BUILD=1
PATH=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/bin:/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place:/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/bin:/opt/intel/composer_xe_2013.1.119/bin/intel64:/opt/intel/composer_xe_2013.1.119/mpirt/bin/intel64:/opt/intel/composer_xe_2013.1.119/bin:/Users/tom/.rvm/gems/ruby-2.2.3/bin:/Users/tom/.rvm/gems/ruby-2.2.3@global/bin:/Users/tom/.rvm/rubies/ruby-2.2.3/bin:/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin:/Users/tom/miniconda3/envs/dev35/bin:/Users/tom/miniconda3/bin:/Applications/git-annex.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/usr/local/heroku/bin:/Users/tom/usr/Montage_v3.3/bin:/Users/tom/Library/Python/3.4/bin:/Users/tom/usr/hyperion/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/tom/.rvm/bin
CONDA_PATH_BACKUP=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place:/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/bin:/opt/intel/composer_xe_2013.1.119/bin/intel64:/opt/intel/composer_xe_2013.1.119/mpirt/bin/intel64:/opt/intel/composer_xe_2013.1.119/bin:/Users/tom/.rvm/gems/ruby-2.2.3/bin:/Users/tom/.rvm/gems/ruby-2.2.3@global/bin:/Users/tom/.rvm/rubies/ruby-2.2.3/bin:/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin:/Users/tom/miniconda3/envs/dev35/bin:/Users/tom/miniconda3/bin:/Applications/git-annex.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/usr/local/heroku/bin:/Users/tom/usr/Montage_v3.3/bin:/Users/tom/Library/Python/3.4/bin:/Users/tom/usr/hyperion/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/tom/.rvm/bin
SRC_DIR=/Users/tom/miniconda3/conda-bld/._1473672666949/work/openmpi-2.0.0
CONDA_PREFIX=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place
PWD=/Users/tom/miniconda3/conda-bld/._1473672666949/work/openmpi-2.0.0
LUA=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/bin/lua
PY3K=1
PKG_VERSION=2.0.0
STDLIB_DIR=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/lib/python3.5
LANG=en_US.UTF-8
LUA_VER=5.2
CONDA_PY=35
PS1=(/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place) 
ROOT=/Users/tom/miniconda3
HTTPS_PROXY=
CXX=clang++
SHLVL=1
OSX_ARCH=x86_64
HOME=/Users/tom
PKG_BUILD_STRING=0
CFLAGS= -arch x86_64
CONDA_PS1_BACKUP=
SP_DIR=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/lib/python3.5/site-packages
HTTP_PROXY=
SYS_PREFIX=/Users/tom/miniconda3
SUBDIR=osx-64
MACOSX_DEPLOYMENT_TARGET=10.9
PREFIX=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place
RECIPE_DIR=/Users/tom/tmp/openmpi-feedstock/recipe
PKG_CONFIG_PATH=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/lib/pkgconfig
CONDA_DEFAULT_ENV=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place
ARCH=64
CC=clang
PKG_NAME=openmpi
SYS_PYTHON=/Users/tom/miniconda3/bin/python
PYTHON=/Users/tom/miniconda3/conda-bld/._1473672666949/_b_env_placehold_placehold_place/bin/python
_=/usr/bin/env
```

In other words, ``env`` doesn't show ``DYLD_FALLBACK_LIBRARY_PATH``

**Comment by ggouaillardet** [comment] 2016-09-12 09:46
I could admit that for security reasons this variable cannot be exported.
But in that case, you should not be able to run a.out in the first place ...

Can you write a dumb a.sh script that simply invokes a.out, and then
export DY_LD...
./a.out
./a.sh

Do you get a consistent result ?
e.g. both success or both fail ?

**Comment by astrofrog** [comment] 2016-09-12 09:47
By the way, I changed the patch you suggested to instead do ``echo \$DYLD_FALLBACK_LIBRARY_PATH`` inside the configure script, and it returns an empty string. However, if I look at that variable before running ``configure``, it is there.

**Comment by ggouaillardet** [comment] 2016-09-12 09:55
Well, if you echo, you do not fork&exec and build.sh does the meta expansion.
So strictly speaking
echo $xxx
is different from
env | grep '^xxx='
(And we know here you did not omit to export the variable)
Maybe a security feature is that the variable is dropped as soon as the libs are resolved,
But i do not see that in my environment which is an uptodate yosemite.

btw, can't you simply use LD_LIBRARY_PATH here ?
either with $PREFIX/lib or $HOME/anaconda/lib

**Comment by ggouaillardet** [comment] 2016-09-12 10:33
Well, if you echo, you do not fork&exec and build.sh does the meta expansion.
So strictly speaking
echo $xxx
is different from
env | grep '^xxx='
(And we know here you did not omit to export the variable)
Maybe a security feature is that the variable is dropped as soon as the libs are resolved,
But i do not see that in my environment which is an uptodate yosemite.

btw, can't you simply use LD_LIBRARY_PATH here ?
either with $PREFIX/lib or $HOME/anaconda/lib

**Comment by astrofrog** [comment] 2016-09-12 10:54
@ggouaillardet - the weird thing is that this has not been an issue for e.g. mpich and hdf5 (both of which required setting ``DYLD_FALLBACK_LIBRARY_PATH`` to be set for configure to work, hence why I thought maybe openMPI is doing something different with configure. ``LD_LIBRARY_PATH`` is also set (see initial description of issue) but that doesn't seem to work.

**Comment by ggouaillardet** [comment] 2016-09-12 10:58
Can you re-build mpich on your system right now ?
I have hard time understanding how this can be related to Open MPI

**Comment by ggouaillardet** [comment] 2016-09-13 09:02
@astrofrog 
i found this link : http://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1

so basically, both ```DYLD_FALLBACK_LIBRARY_PATH``` and ```LD_LIBRARY_PATH``` are reset after fork ... and this is a feature of El Capitan.
mpich cannot be build on this arch, see my logs at https://travis-ci.org/open-mpi/ompi/jobs/159506106

i was able to build Open MPI simply by running
```configure ... LD_LIBRARY_PATH=$LD_LIBRARY_PATH```
(now building, logs at https://travis-ci.org/open-mpi/ompi/builds/159526335)
my patch is at openmpi-feedstock@73f955fd203d1fc742dd608d9b62a3d74d5adb52

**Comment by astrofrog** [comment] 2016-09-13 09:06
@ggouaillardet - ah, thanks for looking into it and for the fix! Feel free to close this.

**Comment by ggouaillardet** [comment] 2016-09-16 11:21
this has been diagnosed as a new "El Capitan" feature, and this is independent of Open MPI

closing this issue

**Closed by ggouaillardet** 2016-09-16 11:21 UTC
