### ISSUE TITLE
2.0.2 and 2.1.0: orted assertion failure with output-filename and rankfile

### ISSUE THREAD

**Issue by tjb900** [open-mpi/ompi#3392] opened 2017-04-21 05:50 UTC
## Background information
First encountered this problem on startup of MPI jobs with 2.0.2, under slurm.  It presents as the orted segfaulting, and appears to occur when the following two things are true:

1) --output-filename is specified to mpirun, to write each rank to a separate file
2) a rankfile is specified, and rank 0 is not specified to be on the launch node 

Yielding the error (in the --enable-debug version of 2.1.0):

```
orted: class/opal_list.c:69: opal_list_item_destruct: Assertion `0 == item->opal_list_item_refcount' failed
```

or, for non-debug versions, a segmentation fault.

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Have reproduced this issue with 2.0.2, 2.1.0.  Have attempted to reproduce on master, but it appears that a separate rankfile-related problem gets in the way first.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
2.0.2 and 2.1.0 were built from a tarball, with --enable-mpi-thread-multiple, using 2017 intel compiler

The log below was made with a tarball from 2.1.0, compiled with --enable-mpi-thread-multiple and --enable-debug

### Please describe the system on which you are running

* Operating system/version: Centos 6.6
* Computer hardware: Intel, most reproductions on KNL but also seen on regular Xeon
* Network type: TCP/Ethernet

-----------------------------

## Details of the problem

Can be reproduced with the following script:

```#!/bin/bash
LOGDIR=/d/home/timb/openmpi_issue_20170421/2.1.0-mt-debug/${SLURM_JOB_ID}
rankfile=${LOGDIR}/rankfile.${SLURM_JOB_ID}
mkdir -p ${LOGDIR}
nodelist=$(scontrol show hostname ${SLURM_JOB_NODELIST} | tac)
> $rankfile
rank=0
for node in $nodelist; do
   echo "rank ${rank}=${node} slot=0:*" >> $rankfile
   rank=$(( $rank + 1 ))
done

echo "Script running on $(hostname)"
echo "=== contents of rankfile"
cat ${rankfile}
echo "=== end contents of rankfile"

export OPENMPI=/d/sw/openmpi/2.1.0-mt-debug
export LD_LIBRARY_PATH=${OPENMPI}/lib:/d/sw/intel/2017.03.17/lib
unset SLURM_EXPORT_ENV
${OPENMPI}/bin/mpirun \
   --debug-daemons \
   --display-map \
   --verbose \
   --mca rmaps_base_verbose 100 \
   --mca iof_base_verbose 100 \
   --rankfile $rankfile \
   --output-filename $LOGDIR/out \
   hostname
```

Yielding output:

```
Script running on hnod0010
=== contents of rankfile
rank 0=hnod0011 slot=0:*
rank 1=hnod0010 slot=0:*
=== end contents of rankfile
[hnod0010:177628] mca: base: components_register: registering framework rmaps components
[hnod0010:177628] mca: base: components_register: found loaded component mindist
[hnod0010:177628] mca: base: components_register: component mindist register function successful
[hnod0010:177628] mca: base: components_register: found loaded component ppr
[hnod0010:177628] mca: base: components_register: component ppr register function successful
[hnod0010:177628] mca: base: components_register: found loaded component rank_file
[hnod0010:177628] mca: base: components_register: component rank_file register function successful
[hnod0010:177628] mca: base: components_register: found loaded component resilient
[hnod0010:177628] mca: base: components_register: component resilient register function successful
[hnod0010:177628] mca: base: components_register: found loaded component round_robin
[hnod0010:177628] mca: base: components_register: component round_robin register function successful
[hnod0010:177628] mca: base: components_register: found loaded component seq
[hnod0010:177628] mca: base: components_register: component seq register function successful
[hnod0010:177628] mca: base: components_register: found loaded component staged
[hnod0010:177628] mca: base: components_register: component staged has no register or open function
[hnod0010:177628] [[34958,0],0] rmaps:base set policy with NULL
[hnod0010:177628] mca: base: components_open: opening rmaps components
[hnod0010:177628] mca: base: components_open: found loaded component mindist
[hnod0010:177628] mca: base: components_open: component mindist open function successful
[hnod0010:177628] mca: base: components_open: found loaded component ppr
[hnod0010:177628] mca: base: components_open: component ppr open function successful
[hnod0010:177628] mca: base: components_open: found loaded component rank_file
[hnod0010:177628] mca: base: components_open: component rank_file open function successful
[hnod0010:177628] mca: base: components_open: found loaded component resilient
[hnod0010:177628] mca: base: components_open: component resilient open function successful
[hnod0010:177628] mca: base: components_open: found loaded component round_robin
[hnod0010:177628] mca: base: components_open: component round_robin open function successful
[hnod0010:177628] mca: base: components_open: found loaded component seq
[hnod0010:177628] mca: base: components_open: component seq open function successful
[hnod0010:177628] mca: base: components_open: found loaded component staged
[hnod0010:177628] mca: base: components_open: component staged open function successful
[hnod0010:177628] mca:rmaps:select: checking available component mindist
[hnod0010:177628] mca:rmaps:select: Querying component [mindist]
[hnod0010:177628] mca:rmaps:select: checking available component ppr
[hnod0010:177628] mca:rmaps:select: Querying component [ppr]
[hnod0010:177628] mca:rmaps:select: checking available component rank_file
[hnod0010:177628] mca:rmaps:select: Querying component [rank_file]
[hnod0010:177628] mca:rmaps:select: checking available component resilient
[hnod0010:177628] mca:rmaps:select: Querying component [resilient]
[hnod0010:177628] mca:rmaps:select: checking available component round_robin
[hnod0010:177628] mca:rmaps:select: Querying component [round_robin]
[hnod0010:177628] mca:rmaps:select: checking available component seq
[hnod0010:177628] mca:rmaps:select: Querying component [seq]
[hnod0010:177628] mca:rmaps:select: checking available component staged
[hnod0010:177628] mca:rmaps:select: Querying component [staged]
[hnod0010:177628] [[34958,0],0]: Final mapper priorities
[hnod0010:177628] 	Mapper: rank_file Priority: 10000
[hnod0010:177628] 	Mapper: ppr Priority: 90
[hnod0010:177628] 	Mapper: seq Priority: 60
[hnod0010:177628] 	Mapper: resilient Priority: 40
[hnod0010:177628] 	Mapper: mindist Priority: 20
[hnod0010:177628] 	Mapper: round_robin Priority: 10
[hnod0010:177628] 	Mapper: staged Priority: 5
[hnod0010:177628] mca: base: components_register: registering framework iof components
[hnod0010:177628] mca: base: components_register: found loaded component hnp
[hnod0010:177628] mca: base: components_register: component hnp has no register or open function
[hnod0010:177628] mca: base: components_register: found loaded component mr_hnp
[hnod0010:177628] mca: base: components_register: component mr_hnp has no register or open function
[hnod0010:177628] mca: base: components_register: found loaded component mr_orted
[hnod0010:177628] mca: base: components_register: component mr_orted has no register or open function
[hnod0010:177628] mca: base: components_register: found loaded component orted
[hnod0010:177628] mca: base: components_register: component orted has no register or open function
[hnod0010:177628] mca: base: components_register: found loaded component tool
[hnod0010:177628] mca: base: components_register: component tool has no register or open function
[hnod0010:177628] defining endpt: file base/iof_base_frame.c line 281 fd 1
[hnod0010:177628] defining endpt: file base/iof_base_frame.c line 284 fd 2
[hnod0010:177628] mca: base: components_open: opening iof components
[hnod0010:177628] mca: base: components_open: found loaded component hnp
[hnod0010:177628] mca: base: components_open: component hnp open function successful
[hnod0010:177628] mca: base: components_open: found loaded component mr_hnp
[hnod0010:177628] mca: base: components_open: component mr_hnp open function successful
[hnod0010:177628] mca: base: components_open: found loaded component mr_orted
[hnod0010:177628] mca: base: components_open: component mr_orted open function successful
[hnod0010:177628] mca: base: components_open: found loaded component orted
[hnod0010:177628] mca: base: components_open: component orted open function successful
[hnod0010:177628] mca: base: components_open: found loaded component tool
[hnod0010:177628] mca: base: components_open: component tool open function successful
[hnod0010:177628] mca:base:select: Auto-selecting iof components
[hnod0010:177628] mca:base:select:(  iof) Querying component [hnp]
[hnod0010:177628] mca:base:select:(  iof) Query of component [hnp] set priority to 100
[hnod0010:177628] mca:base:select:(  iof) Querying component [mr_hnp]
[hnod0010:177628] mca:base:select:(  iof) Querying component [mr_orted]
[hnod0010:177628] mca:base:select:(  iof) Querying component [orted]
[hnod0010:177628] mca:base:select:(  iof) Querying component [tool]
[hnod0010:177628] mca:base:select:(  iof) Selected component [hnp]
[hnod0010:177628] mca: base: close: component mr_hnp closed
[hnod0010:177628] mca: base: close: unloading component mr_hnp
[hnod0010:177628] mca: base: close: component mr_orted closed
[hnod0010:177628] mca: base: close: unloading component mr_orted
[hnod0010:177628] mca: base: close: component orted closed
[hnod0010:177628] mca: base: close: unloading component orted
[hnod0010:177628] mca: base: close: component tool closed
[hnod0010:177628] mca: base: close: unloading component tool
srun: cluster configuration lacks support for cpu binding
[hnod0011:127518] mca: base: components_register: registering framework iof components
[hnod0011:127518] mca: base: components_register: found loaded component hnp
[hnod0011:127518] mca: base: components_register: component hnp has no register or open function
[hnod0011:127518] mca: base: components_register: found loaded component mr_hnp
[hnod0011:127518] mca: base: components_register: component mr_hnp has no register or open function
[hnod0011:127518] mca: base: components_register: found loaded component mr_orted
[hnod0011:127518] mca: base: components_register: component mr_orted has no register or open function
[hnod0011:127518] mca: base: components_register: found loaded component orted
[hnod0011:127518] mca: base: components_register: component orted has no register or open function
[hnod0011:127518] mca: base: components_register: found loaded component tool
[hnod0011:127518] mca: base: components_register: component tool has no register or open function
[hnod0011:127518] mca: base: components_open: opening iof components
[hnod0011:127518] mca: base: components_open: found loaded component hnp
[hnod0011:127518] mca: base: components_open: component hnp open function successful
[hnod0011:127518] mca: base: components_open: found loaded component mr_hnp
[hnod0011:127518] mca: base: components_open: component mr_hnp open function successful
[hnod0011:127518] mca: base: components_open: found loaded component mr_orted
[hnod0011:127518] mca: base: components_open: component mr_orted open function successful
[hnod0011:127518] mca: base: components_open: found loaded component orted
[hnod0011:127518] mca: base: components_open: component orted open function successful
[hnod0011:127518] mca: base: components_open: found loaded component tool
[hnod0011:127518] mca: base: components_open: component tool open function successful
[hnod0011:127518] mca:base:select: Auto-selecting iof components
[hnod0011:127518] mca:base:select:(  iof) Querying component [hnp]
[hnod0011:127518] mca:base:select:(  iof) Querying component [mr_hnp]
[hnod0011:127518] mca:base:select:(  iof) Querying component [mr_orted]
[hnod0011:127518] mca:base:select:(  iof) Querying component [orted]
[hnod0011:127518] mca:base:select:(  iof) Query of component [orted] set priority to 100
[hnod0011:127518] mca:base:select:(  iof) Querying component [tool]
[hnod0011:127518] mca:base:select:(  iof) Selected component [orted]
[hnod0011:127518] mca: base: close: component hnp closed
[hnod0011:127518] mca: base: close: unloading component hnp
[hnod0011:127518] mca: base: close: component mr_hnp closed
[hnod0011:127518] mca: base: close: unloading component mr_hnp
[hnod0011:127518] mca: base: close: component mr_orted closed
[hnod0011:127518] mca: base: close: unloading component mr_orted
[hnod0011:127518] mca: base: close: component tool closed
[hnod0011:127518] mca: base: close: unloading component tool
Daemon [[34958,0],1] checking in as pid 127518 on host hnod0011
[hnod0011:127518] [[34958,0],1] orted: up and running - waiting for commands!
[hnod0010:177628] mca:rmaps: mapping job [34958,1]
[hnod0010:177628] mca:rmaps: creating new map for job [34958,1]
[hnod0010:177628] [[34958,0],0] Starting with 2 nodes in list
[hnod0010:177628] [[34958,0],0] Filtering thru apps
[hnod0010:177628] [[34958,0],0] Retained 2 nodes in list
[hnod0010:177628] [[34958,0],0] node hnod0010 has 1 slots available
[hnod0010:177628] [[34958,0],0] node hnod0011 has 1 slots available
[hnod0010:177628] AVAILABLE NODES FOR MAPPING:
[hnod0010:177628]     node: hnod0010 daemon: 0
[hnod0010:177628]     node: hnod0011 daemon: 1
[hnod0010:177628] mca:rmaps: nprocs 2
[hnod0010:177628] mca:rmaps mapping given - using default
[hnod0010:177628] mca:rmaps:rank_file: mapping job [34958,1]
[hnod0010:177628] mca:rmaps:rank_file: using LOGICAL processors
[hnod0010:177628] [[34958,0],0] Starting with 2 nodes in list
[hnod0010:177628] [[34958,0],0] Filtering thru apps
[hnod0010:177628] [[34958,0],0] Retained 2 nodes in list
[hnod0010:177628] [[34958,0],0] node hnod0010 has 1 slots available
[hnod0010:177628] [[34958,0],0] node hnod0011 has 1 slots available
[hnod0010:177628] AVAILABLE NODES FOR MAPPING:
[hnod0010:177628]     node: hnod0010 daemon: 0
[hnod0010:177628]     node: hnod0011 daemon: 1
[hnod0010:177628] [[34958,0],0] rmaps:base:compute_usage
[hnod0010:177628] mca:rmaps: compute bindings for job [34958,1] with policy CPUSET:IF-SUPPORTED[500a]
 Data for JOB [34958,1] offset 0

 ========================   JOB MAP   ========================

 Data for node: hnod0011	Num slots: 1	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [34958,1] App: 0 Process rank: 0 Bound: UNBOUND

 Data for node: hnod0010	Num slots: 1	Max slots: 0	Num procs: 1
 	Process OMPI jobid: [34958,1] App: 0 Process rank: 1 Bound: UNBOUND

 =============================================================
[hnod0010:177628] [[34958,0],0] orted:comm:process_commands() Processing Command: ORTE_DAEMON_ADD_LOCAL_PROCS
[hnod0010:177628] [[34958,0],0] orted_cmd: received add_local_procs
[hnod0011:127518] [[34958,0],1] orted:comm:process_commands() Processing Command: ORTE_DAEMON_ADD_LOCAL_PROCS
[hnod0011:127518] [[34958,0],1] orted_cmd: received add_local_procs
[hnod0010:177628] [[34958,0],0] iof:hnp pushing fd 27 for process [[34958,1],1]
[hnod0010:177628] defining endpt: file iof_hnp.c line 212 fd 30
[hnod0010:177628] [[34958,0],0] defining read event for [[34958,1],1]: iof_hnp.c 219
[hnod0010:177628] [[34958,0],0] iof:hnp pushing fd 33 for process [[34958,1],1]
[hnod0010:177628] [[34958,0],0] defining read event for [[34958,1],1]: iof_hnp.c 222
[hnod0010:177628] [[34958,0],0] iof:hnp pushing fd 35 for process [[34958,1],1]
[hnod0010:177628] [[34958,0],0] defining read event for [[34958,1],1]: iof_hnp.c 225
[hnod0010:177628] [[34958,0],0] read 9 bytes from stdout of [[34958,1],1]
[hnod0010:177628] [[34958,0],0] write:output setting up to write 9 bytes to stdout for [[34958,1],1] on fd 30
[hnod0010:177628] [[34958,0],0] write:output adding write event
[hnod0010:177628] [[34958,0],0] read 0 bytes from stderr of [[34958,1],1]
[hnod0010:177628] [[34958,0],0] iof: closing fd 33 for process [[34958,1],1]
[hnod0010:177628] [[34958,0],0] read 0 bytes from stddiag of [[34958,1],1]
[hnod0010:177628] [[34958,0],0] iof: closing fd 35 for process [[34958,1],1]
[hnod0010:177628] [[34958,0],0] write:handler writing data to 30
[hnod0010:177628] [[34958,0],0] iof:hnp:read handler [[34958,1],1] Error on connection:27
[hnod0010:177628] [[34958,0],0] read 0 bytes from stdout of [[34958,1],1]
[hnod0010:177628] [[34958,0],0] iof: closing fd 27 for process [[34958,1],1]
[hnod0011:127518] [[34958,0],1] iof:orted pulling fd 27 for process [[34958,1],0]
[hnod0011:127518] defining endpt: file iof_orted.c line 257 fd 27
[hnod0011:127518] [[34958,0],1] iof:orted pushing fd 22 for process [[34958,1],0]
[hnod0011:127518] defining endpt: file iof_orted.c line 186 fd 25
[hnod0011:127518] [[34958,0],1] defining read event for [[34958,1],0]: iof_orted.c 193
[hnod0011:127518] [[34958,0],1] iof:orted pushing fd 28 for process [[34958,1],0]
[hnod0011:127518] [[34958,0],1] defining read event for [[34958,1],0]: iof_orted.c 196
[hnod0011:127518] [[34958,0],1] iof:orted pushing fd 30 for process [[34958,1],0]
[hnod0011:127518] [[34958,0],1] defining read event for [[34958,1],0]: iof_orted.c 199
[hnod0010:177628] [[34958,0],0] iof:hnp pushing fd 0 for process [[34958,1],0]
[hnod0010:177628] defining endpt: file iof_hnp.c line 267 fd -1
[hnod0010:177628] [[34958,0],0] defining read event for [[34958,1],0]: iof_hnp.c 329
[hnod0010:177628] [[34958,0],0] sending 0 bytes from stdin to daemon [[34958,0],1]
[hnod0010:177628] [[34958,0],0] iof: closing fd 0 for process [[34958,1],0]
[hnod0011:127518] [[34958,0],1] unpacked 0 bytes for local proc [[34958,1],0]
[hnod0011:127518] [[34958,0],1] writing data to local proc [[34958,1],0]
[hnod0011:127518] [[34958,0],1] write:output setting up to write 0 bytes to stdin for [[34958,1],0] on fd 27
[hnod0011:127518] [[34958,0],1] write:output adding write event
[hnod0011:127518] [[34958,0],1] writing data to local proc [[34958,1],0]
[hnod0011:127518] [[34958,0],1] write:output setting up to write 0 bytes to stdin for [[34958,1],0] on fd 25
[hnod0011:127518] [[34958,0],1] write:output adding write event
[hnod0011:127518] [[34958,0],1] orted:stdin:write:handler writing data to 27
[hnod0011:127518] [[34958,0],1] iof:orted closing fd 27 on write event due to zero bytes output
[hnod0011:127518] [[34958,0],1] iof: closing fd 27 for write event
[hnod0011:127518] [[34958,0],1] write:handler writing data to 25
[hnod0011:127518] [[34958,0],1] iof: closing sink for process [[34958,1],0]
[hnod0011:127518] [[34958,0],1] iof: closing fd 25 for write event
orted: class/opal_list.c:69: opal_list_item_destruct: Assertion `0 == item->opal_list_item_refcount' failed.
[hnod0011:127518] *** Process received signal ***
[hnod0011:127518] Signal: Aborted (6)
[hnod0011:127518] Signal code:  (-6)
[hnod0011:127518] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f6a036a5370]
[hnod0011:127518] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f6a0330a1d7]
[hnod0011:127518] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f6a0330b8c8]
[hnod0011:127518] [ 3] /lib64/libc.so.6(+0x2e146)[0x7f6a03303146]
[hnod0011:127518] [ 4] /lib64/libc.so.6(+0x2e1f2)[0x7f6a033031f2]
[hnod0011:127518] [ 5] /d/sw/openmpi/2.1.0-mt-debug/lib/libopen-pal.so.20(+0x3362a)[0x7f6a0441462a]
[hnod0011:127518] [ 6] /d/sw/openmpi/2.1.0-mt-debug/lib/libopen-rte.so.20(orte_iof_base_write_handler+0x11ce)[0x7f6a04883154]
[hnod0011:127518] [ 7] /d/sw/openmpi/2.1.0-mt-debug/lib/libopen-pal.so.20(opal_libevent2022_event_base_loop+0xa34)[0x7f6a044c4b24]
[hnod0011:127518] [ 8] /d/sw/openmpi/2.1.0-mt-debug/lib/libopen-rte.so.20(orte_daemon+0x35cc)[0x7f6a0484169c]
[hnod0011:127518] [ 9] /d/sw/openmpi/2.1.0-mt-debug/bin/orted[0x40114c]
[hnod0011:127518] [10] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f6a032f6b35]
[hnod0011:127518] [11] /d/sw/openmpi/2.1.0-mt-debug/bin/orted[0x400fa9]
[hnod0011:127518] *** End of error message ***
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[34958,0],0] on node hnod0010
  Remote daemon: [[34958,0],1] on node hnod0011

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
[hnod0010:177628] [[34958,0],0]:errmgr_default_hnp.c(389) updating exit status to -51
[hnod0010:177628] [[34958,0],0] orted:comm:process_commands() Processing Command: ORTE_DAEMON_HALT_VM_CMD
[hnod0010:177628] [[34958,0],0] orted_cmd: received halt_vm cmd
[hnod0010:177628] [[34958,0],0] orted_cmd: all routes and children gone - exiting
[hnod0010:177628] mca: base: close: component hnp closed
[hnod0010:177628] mca: base: close: unloading component hnp
[hnod0010:177628] mca: base: close: component mindist closed
[hnod0010:177628] mca: base: close: unloading component mindist
[hnod0010:177628] mca: base: close: component ppr closed
[hnod0010:177628] mca: base: close: unloading component ppr
[hnod0010:177628] mca: base: close: component rank_file closed
[hnod0010:177628] mca: base: close: unloading component rank_file
[hnod0010:177628] mca: base: close: component resilient closed
[hnod0010:177628] mca: base: close: unloading component resilient
[hnod0010:177628] mca: base: close: component round_robin closed
[hnod0010:177628] mca: base: close: unloading component round_robin
[hnod0010:177628] mca: base: close: component seq closed
[hnod0010:177628] mca: base: close: unloading component seq
[hnod0010:177628] mca: base: close: component staged closed
[hnod0010:177628] mca: base: close: unloading component staged
srun: error: hnod0011: task 0: Aborted
srun: Terminating job step 5720941.0
```

**Comment by ggouaillardet** [comment] 2017-04-24 08:00
@rhc54 can you please have a look at it ?

you can simply reproduce this with two nodes:
```
n0$ mpirun --host n1,n0 --output-filename out hostname < /dev/null
```

note the first listed node is __not__ the node on which ```mpirun``` is invoked.
also, stdin must be forced to ```/dev/null```

**Comment by ggouaillardet** [comment] 2017-04-24 08:02
fwiw, here is the ```orted``` stack trace

```
(gdb) bt
#0  0x00007fb82bd981d7 in raise () from /usr/lib64/libc.so.6
#1  0x00007fb82bd998c8 in abort () from /usr/lib64/libc.so.6
#2  0x00007fb82bd91146 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007fb82bd911f2 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x00007fb82d093d3a in opal_list_item_destruct (item=0x1e78df0) at ../../../src/ompi-v2.x/opal/class/opal_list.c:69
#5  0x00007fb82d40b0c3 in opal_obj_run_destructors (object=0x1e78df0) at ../../../../../src/ompi-v2.x/opal/class/opal_object.h:460
#6  0x00007fb82d40c15b in orte_iof_base_write_handler (fd=23, event=4, cbdata=0x1e78df0) at ../../../../../src/ompi-v2.x/orte/mca/iof/base/iof_base_output.c:288
#7  0x00007fb82d0fb6dc in event_process_active_single_queue (activeq=0x1d30eb0, base=0x1d30940) at ../../../../../../../src/ompi-v2.x/opal/mca/event/libevent2022/libevent/event.c:1370
#8  event_process_active (base=<optimized out>) at ../../../../../../../src/ompi-v2.x/opal/mca/event/libevent2022/libevent/event.c:1440
#9  opal_libevent2022_event_base_loop (base=0x1d30940, flags=1) at ../../../../../../../src/ompi-v2.x/opal/mca/event/libevent2022/libevent/event.c:1644
#10 0x00007fb82d3e8dad in orte_daemon (argc=45, argv=0x7fff0548ffb8) at ../../../src/ompi-v2.x/orte/orted/orted_main.c:849
#11 0x000000000040097a in main (argc=45, argv=0x7fff0548ffb8) at ../../../../../src/ompi-v2.x/orte/tools/orted/orted.c:63
```

**Comment by rhc54** [comment] 2017-04-24 13:49
One immediate thought comes to mind: just don't redirect the input to /dev/null. Hard to understand why anyone thinks that is a good idea 😄

**Comment by ggouaillardet** [comment] 2017-04-24 14:15
where do i start ...
i was initially unable to reproduce the issue, until i run this as a slurm job,
and then i finally realized slurm components were not the root cause,
but slurm having ```fd 0 -> /dev/null``` was.
so unless there is a slurm option to change this default behavior, a workaround would be to
````sleep_forever | mpirun ...``` when using outputfile under SLURM

**Comment by rhc54** [comment] 2017-04-24 14:34
Or just don't tie off stdin - if nothing is being directed into it, then it makes no difference if you tie it to /dev/null or not.

**Comment by ggouaillardet** [comment] 2017-04-25 02:04
@rhc54 i did not get that last comment

within a slurm job, ```mpirun``` _inherits_ ```fd 0 -> /dev/null``` from slurm,
that means ```read(0, ...)``` does return ```0```, and then ```mpirun``` sends this to MPI process ```0``` via its ```orted```.

if you do the same thing from the command line and outside of slurm, then the same ```read(0, ...)``` hangs, and then nothing is sent to ```orted```

so under slurm, ```sleep_forever | mpirun ...``` ensures ```read(0, ...``` hangs.
does that make sense ?

and by the way, an even simpler workaround is to have task ```0``` running on the same node running ```mpirun``` (e.g. get rid of ```| tac```) in the user script.

**Comment by tjb900** [comment] 2017-04-25 02:13
Thanks for looking into this.

Unfortunately the node ordering is desired behaviour for us - the nodes are heterogeneous, and we need to place rank 0 on a node with larger memory than some of the other tasks.  The reversal of the list was simply for the purposes of a simple reproducer.

As @ggouaillardet says, we inherit stdin already tied off by the batch system - probably not an uncommon situation.  That said, the input redirect might be the beginnings of a workaround.  

Experiments:

* redirecting the input from a small file doesn't work (crash)
* Redirecting from a long sleep causes the entire job to wait for the sleep to finish - undesirable
* redirecting from a short sleep causes a crash (predictably, at this point)
* redirecting from /dev/zero causes something in the mpi infrastructure to go crazy reading from it (line buffer?), despite the application itself never reading fd 0
* redirecting from a large text file crashes also - mpirun reads the whole lot (buffering it somewhere?) and then crashes.
* redirecting from /dev/random, curiously, works.  strace shows that mpirun's read(0, 4096) returns 16 bytes, and then it just moves on with life.
* redirecting from /dev/urandom, an strace shows mpirun reading (before I broke out of it) gigabytes of random data - doing what with it, I have no idea.

So I think I can get moving with </dev/random for now.

**Comment by rhc54** [comment] 2017-05-26 13:42
This was apparently fixed by removing an erroneous close of fd=0 by the PMIx dstore, so I'm closing this here. Please reopen if the problem resurfaces.

**Closed by rhc54** 2017-05-26 13:42 UTC
