### ISSUE TITLE
static static in pmix_s2

### ISSUE THREAD

**Issue by aaronk** [open-mpi/ompi#3177] opened 2017-03-15 16:26 UTC
I'm in the process of building openmpi 2.0.2 on a CentOS 6.8 system with gcc 6.2 using --with-pmi and --with-slurm.  Getting this compiler error.  Any reason there should be two statics here?

pmix_s2.c:98:1: error: duplicate 'static'
 static static OBJ_CLASS_INSTANCE(pmi_opcaddy_t,

**Comment by jsquyres** [comment] 2017-03-15 16:43
We wanted to be *really* sure that it's `static`.

(that's embarrassing-yet-kinda-funny... funbarrassing?)

It looks like this is already fixed in all of the Open MPI development branches:

* master
* v2.0.x (for the upcoming v2.0.3 release)
* v2.x (for the immanent v2.1.0 release)
* v3.x (for the several-months-away 3.0.0 release)

If you want, you can grab a v2.0.x nightly snapshot tarball that has the fix: https://www.open-mpi.org/nightly/v2.0.x/

**Comment by jsquyres** [comment] 2017-03-15 16:44
I'm going to close this issue, since the issue is already fixed in our repos, but thank you for a) noticing, and b) taking the time to report it!

**Closed by jsquyres** 2017-03-15 16:44 UTC
Labels: code cleanup, question
