### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Plume-SPH** [open-mpi/ompi#12221] opened 2024-01-09 06:03 UTC
I am installing openmpi using the tar distribution, so I directly run ./configure and then run make, when I run make, I got the following error: 

btl_tcp_proc.c: In function ‘mca_btl_tcp_proc_create_interface_graph’:
btl_tcp_proc.c:163:20: error: expected identifier or ‘(’ before ‘struct’
  163 |         opal_if_t *interface = OBJ_NEW(opal_if_t);
      |                    ^~~~~~~~~
btl_tcp_proc.c:164:21: error: expected expression before ‘struct’
  164 |         if (NULL == interface) {
      |                     ^~~~~~~~~

The only extra option that I added is the prefix=my/install/path. nothing else.

**Comment by janjust** [comment] 2024-01-09 15:27
@Plume-SPH can you be more specific, which version? what system? Please follow the template on opening issues.

**Comment by Plume-SPH** [comment] 2024-01-10 02:08
## Background information
The issue happened when I try to install openMPI from tar distribution. 

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
The version: 5.0.1
It is a tar distribution so has no git information.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Install open MPI from a source/distribution tarball
Downloaded from this website: https://www.open-mpi.org/software/ompi/v5.0/
The version: 5.0.1
I downloaded the tar.gz one: [openmpi-5.0.1.tar.gz](https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.1.tar.gz)


### Please describe the system on which you are running
The system is Cygwin on Windows desktop. More details: 
$ uname -a
CYGWIN_NT-10.0-22621 zcao_tf 3.4.10-1.x86_64 2023-11-29 12:12 UTC x86_64 Cygwin

Here is more details about the computer hardware:
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Organization:   HP
System Manufacturer:       HP
System Model:              HP Laptop 15-dy2xxx
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2400 Mhz
BIOS Version:              AMI F.32, 7/4/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     7,835 MB
Available Physical Memory: 960 MB
Virtual Memory: Max Size:  25,243 MB
Virtual Memory: Available: 11,600 MB
Virtual Memory: In Use:    13,643 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5032007
                           [02]: KB5033920
                           [03]: KB5012170
                           [04]: KB5034123
                           [05]: KB5032393
Network Card(s):           4 NIC(s) Installed.
                           [01]: Realtek RTL8822CE 802.11ac PCIe Adapter
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.14
                                 [02]: fe80::66f5:9fa8:7162:7d2f
                                 [03]: 2601:249:1001:c940:7052:5d3d:784f:27da
                                 [04]: 2601:249:1001:c940:48cd:d6d0:a0de:3fa0
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [04]: Sangfor SSL VPN CS Support System VNIC
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.



* Network type:
ipconfig

Windows IP Configuration

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : hsd1.vt.comcast.net.

Unknown adapter Local Area Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : hsd1.il.comcast.net.
   IPv6 Address. . . . . . . . . . . : 
   Temporary IPv6 Address. . . . . . : 
   Link-local IPv6 Address . . . . . : 
   IPv4 Address. . . . . . . . . . . : 
   Subnet Mask . . . . . . . . . . . : 
   Default Gateway . . . . . . . . . : 

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
-----------------------------

## Details of the problem
What I did is simple, I tried to install the open MPI. I did the following: 
```shell
./configure --prefix=/cygdrive/c/Users/hitca/Documents/research/dependencies/mpi
make
```
I did not see error when running the ./configure
But encountered the following error when run make:

'''
make[2]: Leaving directory '/cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1/opal/mca/btl/sm'
Making all in mca/btl/tcp
make[2]: Entering directory '/cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1/opal/mca/btl/tcp'
  CC       btl_tcp.lo
  CC       btl_tcp_component.lo
  CC       btl_tcp_endpoint.lo
  CC       btl_tcp_frag.lo
  CC       btl_tcp_proc.lo
In file included from /usr/include/w32api/objbase.h:14,
                 from /usr/include/w32api/ole2.h:17,
                 from /usr/include/w32api/wtypes.h:13,
                 from /usr/include/w32api/winscard.h:10,
                 from /usr/include/w32api/windows.h:97,
                 from /cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1/3rd-party/hwloc-2.7.1/include/hwloc/autogen/config.h:210,
                 from /cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1/3rd-party/hwloc-2.7.1/include/hwloc.h:56,
                 from ../../../../opal/mca/hwloc/hwloc-internal.h:139,
                 from ../../../../opal/util/proc.h:27,
                 from ../../../../opal/class/opal_hash_table.h:41,
                 from btl_tcp_proc.c:40:
btl_tcp_proc.c: In function ‘mca_btl_tcp_proc_create_interface_graph’:
btl_tcp_proc.c:163:20: error: expected identifier or ‘(’ before ‘struct’
  163 |         opal_if_t *interface = OBJ_NEW(opal_if_t);
      |                    ^~~~~~~~~
btl_tcp_proc.c:164:21: error: expected expression before ‘struct’
  164 |         if (NULL == interface) {
      |                     ^~~~~~~~~
btl_tcp_proc.c:174:56: error: expected ‘{’ before ‘->’ token
  174 |             memcpy(&((struct sockaddr_in *) &(interface->if_addr))->sin_addr, remote_addrs[i].addr,
      |                                                        ^~
btl_tcp_proc.c:174:66: error: expected expression before ‘)’ token
  174 |             memcpy(&((struct sockaddr_in *) &(interface->if_addr))->sin_addr, remote_addrs[i].addr,
      |                                                                  ^
btl_tcp_proc.c:176:45: error: expected ‘{’ before ‘->’ token
  176 |             ((struct sockaddr *) &(interface->if_addr))->sa_family = AF_INET;
      |                                             ^~
btl_tcp_proc.c:176:55: error: expected expression before ‘)’ token
  176 |             ((struct sockaddr *) &(interface->if_addr))->sa_family = AF_INET;
      |                                                       ^
btl_tcp_proc.c:177:22: error: expected ‘{’ before ‘->’ token
  177 |             interface->af_family = AF_INET;
      |                      ^~
In file included from ../../../../opal/class/opal_list.h:71,
                 from ../../../../opal/class/opal_hash_table.h:40,
                 from btl_tcp_proc.c:40:
../../../../opal/class/opal_object.h:331:63: error: expected ‘{’ before ‘)’ token
  331 |             if (0 == opal_obj_update((opal_object_t *) (object), -1)) { \
      |                                                               ^
btl_tcp_proc.c:190:13: note: in expansion of macro ‘OBJ_RELEASE’
  190 |             OBJ_RELEASE(interface);
      |             ^~~~~~~~~~~
btl_tcp_proc.c:190:25: error: expected expression before ‘struct’
  190 |             OBJ_RELEASE(interface);
      |                         ^~~~~~~~~
../../../../opal/class/opal_object.h:333:31: note: in definition of macro ‘OBJ_RELEASE’
  333 |                 free((void *) object);                                  \
      |                               ^~~~~~
../../../../opal/class/opal_object.h:334:24: error: expected ‘{’ before ‘=’ token
  334 |                 object = NULL;                                          \
      |                        ^
btl_tcp_proc.c:190:13: note: in expansion of macro ‘OBJ_RELEASE’
  190 |             OBJ_RELEASE(interface);
      |             ^~~~~~~~~~~
../../../../opal/class/opal_object.h:331:63: error: expected ‘{’ before ‘)’ token
  331 |             if (0 == opal_obj_update((opal_object_t *) (object), -1)) { \
      |                                                               ^
btl_tcp_proc.c:196:13: note: in expansion of macro ‘OBJ_RELEASE’
  196 |             OBJ_RELEASE(interface);
      |             ^~~~~~~~~~~
btl_tcp_proc.c:196:25: error: expected expression before ‘struct’
  196 |             OBJ_RELEASE(interface);
      |                         ^~~~~~~~~
../../../../opal/class/opal_object.h:333:31: note: in definition of macro ‘OBJ_RELEASE’
  333 |                 free((void *) object);                                  \
      |                               ^~~~~~
../../../../opal/class/opal_object.h:334:24: error: expected ‘{’ before ‘=’ token
  334 |                 object = NULL;                                          \
      |                        ^
btl_tcp_proc.c:196:13: note: in expansion of macro ‘OBJ_RELEASE’
  196 |             OBJ_RELEASE(interface);
      |             ^~~~~~~~~~~
btl_tcp_proc.c:203:18: error: expected ‘{’ before ‘->’ token
  203 |         interface->if_mask = remote_addrs[i].addr_mask;
      |                  ^~
btl_tcp_proc.c:204:18: error: expected ‘{’ before ‘->’ token
  204 |         interface->if_bandwidth = remote_addrs[i].addr_bandwidth;
      |                  ^~
In file included from ../../../../opal/class/opal_hash_table.h:40,
                 from btl_tcp_proc.c:40:
btl_tcp_proc.c:206:50: error: expected ‘{’ before ‘->’ token
  206 |         opal_list_append(remote_list, &(interface->super));
      |                                                  ^~
../../../../opal/class/opal_list.h:531:57: note: in definition of macro ‘opal_list_append’
  531 | #    define opal_list_append(l, i) _opal_list_append(l, i)
      |                                                         ^
../../../../opal/class/opal_list.h:531:58: error: expected expression before ‘)’ token
  531 | #    define opal_list_append(l, i) _opal_list_append(l, i)
      |                                                          ^
btl_tcp_proc.c:206:9: note: in expansion of macro ‘opal_list_append’
  206 |         opal_list_append(remote_list, &(interface->super));
      |         ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1570: btl_tcp_proc.lo] Error 1
make[2]: Leaving directory '/cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1/opal/mca/btl/tcp'
make[1]: *** [Makefile:1965: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1/opal'
make: *** [Makefile:1533: all-recursive] Error 1
'''

**Comment by Plume-SPH** [comment] 2024-01-10 02:31
```shell
$ automake --version
automake (GNU automake) 1.16.5
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

hitca@zcao_tf /cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1
$ libtool --version
libtool (GNU libtool) 2.4.7
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.


hitca@zcao_tf /cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1
$ autoconfig --version
-bash: autoconfig: command not found

hitca@zcao_tf /cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1
$ g++ --version
g++ (GCC) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


hitca@zcao_tf /cygdrive/c/Users/hitca/Documents/research/dependencies_source/openmpi-5.0.1
$ gcc --version
gcc (GCC) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by jsquyres** [comment] 2024-01-11 16:41
@Plume-SPH Instead of building under Cygwin, can you build under Windows Services for Linux (WSL) instead?

**Comment by ggouaillardet** [comment] 2024-01-12 04:31
I do not think Open MPI is officially supported on Windows.
That being said @matzeri actively maintains the cygwin package.

You can refer to https://cygwin.com/cgit/cygwin-packages/openmpi/tree to check what has been done with the `v4` series.

It seems `interface` is now a cygwin macro, so renaming the local variable was enough to pass compilation

```
--- orig/openmpi-5.0.1/opal/mca/btl/tcp/btl_tcp_proc.c  2023-12-21 07:06:34.000000000 +0900
+++ openmpi-5.0.1/opal/mca/btl/tcp/btl_tcp_proc.c       2024-01-11 22:58:34.220257800 +0900
@@ -160,8 +160,8 @@
        fields needed in the proc version */
     for (i = 0; i < btl_proc->proc_addr_count; i++) {
         /* Construct opal_if_t objects for the remote interfaces */
-        opal_if_t *interface = OBJ_NEW(opal_if_t);
-        if (NULL == interface) {
+        opal_if_t *interface_ = OBJ_NEW(opal_if_t);
+        if (NULL == interface_) {
             rc = OPAL_ERR_OUT_OF_RESOURCE;
             goto out;
         }
@@ -171,39 +171,39 @@
                    sizeof(struct in_addr));
             btl_proc->proc_addrs[i].addr_family = AF_INET;

-            memcpy(&((struct sockaddr_in *) &(interface->if_addr))->sin_addr, remote_addrs[i].addr,
+            memcpy(&((struct sockaddr_in *) &(interface_->if_addr))->sin_addr, remote_addrs[i].addr,
                    sizeof(struct in_addr));
-            ((struct sockaddr *) &(interface->if_addr))->sa_family = AF_INET;
-            interface->af_family = AF_INET;
+            ((struct sockaddr *) &(interface_->if_addr))->sa_family = AF_INET;
+            interface_->af_family = AF_INET;
         } else if (MCA_BTL_TCP_AF_INET6 == remote_addrs[i].addr_family) {
 #if OPAL_ENABLE_IPV6
             memcpy(&btl_proc->proc_addrs[i].addr_union.addr_inet6, remote_addrs[i].addr,
                    sizeof(struct in6_addr));
             btl_proc->proc_addrs[i].addr_family = AF_INET6;

-            memcpy(&((struct sockaddr_in6 *) &(interface->if_addr))->sin6_addr,
+            memcpy(&((struct sockaddr_in6 *) &(interface_->if_addr))->sin6_addr,
                    remote_addrs[i].addr, sizeof(struct in6_addr));
             ((struct sockaddr *) &(interface->if_addr))->sa_family = AF_INET6;
             interface->af_family = AF_INET6;
 #else
             rc = OPAL_ERR_NOT_SUPPORTED;
-            OBJ_RELEASE(interface);
+            OBJ_RELEASE(interface_);
             goto out;
 #endif
         } else {
             BTL_ERROR(("Unexpected address family %d", (int) remote_addrs[i].addr_family));
             rc = OPAL_ERR_BAD_PARAM;
-            OBJ_RELEASE(interface);
+            OBJ_RELEASE(interface_);
             goto out;
         }

         btl_proc->proc_addrs[i].addr_port = remote_addrs[i].addr_port;
         btl_proc->proc_addrs[i].addr_ifkindex = remote_addrs[i].addr_ifkindex;

-        interface->if_mask = remote_addrs[i].addr_mask;
-        interface->if_bandwidth = remote_addrs[i].addr_bandwidth;
+        interface_->if_mask = remote_addrs[i].addr_mask;
+        interface_->if_bandwidth = remote_addrs[i].addr_bandwidth;

-        opal_list_append(remote_list, &(interface->super));
+        opal_list_append(remote_list, &(interface_->super));
     }

     rc = opal_bp_graph_create(NULL, NULL, &graph);
```

**Comment by Plume-SPH** [comment] 2024-01-15 02:28
Thanks all for your suggestions, I will switch to use the branch maintained by @matzeri.

**Comment by jsquyres** [comment] 2024-01-16 16:15
@Plume-SPH Ok, sounds good.  You might still have better luck with WSL, too.  

Sounds like we can close this issue.

**Closed by jsquyres** 2024-01-16 16:15 UTC
Labels: question

**Comment by matzeri** [comment] 2025-02-25 15:21
Sorry for commenting so late but last year I was away from maintaining the Cygwin packages in general. and I am still catching up.

On the 5.0.x series the issue is caused by "interface" on "opal/mca/btl/tcp/btl_tcp_proc.c" 
being already used inside the Window headers so there is a collision in definition.

I think in the past we already hit the same issue and "interface" was renamed (local_interface maybe, not sure).
Attached the workaround I am using to build and deploy 5.0.7 on cygwin.

It should be up as soon I finish some testing.

[CYGWIN-interface-workaround.patch](https://github.com/user-attachments/files/18967199/CYGWIN-interface-workaround.patch)
