### ISSUE TITLE
Issues with opal session dir caused by change to opal/util/os_dirpath.c

### ISSUE THREAD

**Issue by tjb900** [open-mpi/ompi#2754] opened 2017-01-18 17:03 UTC
Hi!

Sorry to hassle you guys again.  We are just in the process of trying to migrate to v2.x, and are hitting a condition that appears to have been introduced in 58d1b3f4d0e295184c25bca862eb0aadd0799c87.

Some of our nodes have a per-job TMPDIR on Lustre, and we are getting tripped up because when calling mkdir on an existing path, where the user would not have permissions to create the directory, Lustre returns EACCES rather than EEXIST.  This breaks the new form of the check in opal/util/os_dirpath.c

```
[user@host ompi ((58d1b3f4d0...))]$ mkdir /p5
mkdir: cannot create directory `/p5': File exists
(i.e. root filesystem behaves as you expected)

[user@host ompi ((58d1b3f4d0...))]$ mkdir /p5/000scratch
mkdir: cannot create directory `/p5/000scratch': Permission denied
(this causes a problem)

[user@host ompi ((58d1b3f4d0...))]$ mkdir /p5/000scratch/my_temp_dir
(but if we ignore it and just carry on trying to make the deeper components, it will work fine)
```

Without wanting to start an argument over whether Lustre is doing the right thing here, this seems like it might be a not-terribly-uncommon configuration?

Cheers,
Tim

**Comment by rhc54** [comment] 2017-01-18 18:30
it looks like this was intended as an optimization so we didn't check for existence before doing mkdir. should be a trivial change to check eaccess, and then if we fail in the next step it won't hurt

**Comment by rhc54** [comment] 2017-01-18 19:07
now that is interesting - the referenced change was never done in OMPI's master! It somehow went directly into the release branch. I'll have to talk to the release managers about how they want to address it.

**Comment by tjb900** [comment] 2017-01-18 19:55
It seems to be an ancestor of master now though?

On the topic of the return code - it seems to me that if the stat() after the mkdir failure succeeds, then we should just move on regardless of mkdir's errno?  Just need to keep it in case the stat fails, so we can report why we couldn't make it exist.

Happy to submit a patch later this evening.

**Comment by rhc54** [comment] 2017-01-18 19:57
We require that patches go into master first so we can fully check them out prior to going into a release branch, so this one somehow didn't follow the normal route. Regardless, I have a fix coming shortly.

**Comment by ggouaillardet** [comment] 2017-01-19 00:16
@rhc54 this was committed into master before we fork the v2 branches.
if you look at https://github.com/open-mpi/ompi/commit/58d1b3f4d0e295184c25bca862eb0aadd0799c87 just above the commit date, there is an information that this commit is present in
- ```master``` (as part of PR #601)
- ```v2.0.x```
- ```v2.x```

i will comment on directly on #2756

**Comment by rhc54** [comment] 2017-01-19 00:21
Odd - the copy of master I have doesn't match that code at all. In fact, it looked exactly like the code prior to your change. Did someone later revert your change?

**Comment by ggouaillardet** [comment] 2017-01-19 00:29
4b47daeeb03f1d28dc57969380763b86e26e52e4 and 8fd1c3f0df6d520d9d3985684848a033254d7862 update that.
these commit only improve the error message (e.g. they do not change the logic of 58d1b3f4d0e295184c25bca862eb0aadd0799c87, ```mkdir()``` first and then ```stat()```)

**Comment by jsquyres** [comment] 2017-01-28 12:06
@ggouaillardet @rhc54 Is this now resolved?

**Comment by ggouaillardet** [comment] 2017-01-28 14:11
@jsquyres per the comments on the relared pr, this is now resolved

**Closed** 2017-01-28 14:26 UTC
