### ISSUE TITLE
ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107

### ISSUE THREAD

**Issue by balay** [open-mpi/ompi#7049] opened 2019-10-05 19:25 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

```
                Open MPI: 4.0.1
 ```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Install from source tarball with:
```
 Open MPI repo revision: v4.0.1
   Open MPI release date: Mar 26, 2019
                Open RTE: 4.0.1
  Open RTE repo revision: v4.0.1
   Open RTE release date: Mar 26, 2019
                    OPAL: 4.0.1
      OPAL repo revision: v4.0.1
       OPAL release date: Mar 26, 2019
                 MPI API: 3.1.0
            Ident string: 4.0.1
                  Prefix: /home/petsc/soft/openmpi-4.0.1-cuda
 Configured architecture: x86_64-unknown-linux-gnu
          Configure host: frog
           Configured by: petsc
           Configured on: Thu Sep 26 16:01:13 CDT 2019
          Configure host: frog
  Configure command line: '--prefix=/home/petsc/soft/openmpi-4.0.1-cuda' '--with-cuda=/usr/local/cuda'
```

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04.6
* Computer hardware: Intel(R) Xeon(R) CPU X5550  @ 2.67GHz [4-core/8-ht]
* Network type:  ethernet [but single node runs]

-----------------------------

## Details of the problem

This issue came up once [over many runs]. We run a test suite - which runs many MPI jobs on a single machine - some of them are scheduled simultaneously [in oversubscribe mode]

One of the tests crashed with this error. Perhaps there is some race condition in the code that handles creating/using these temp dirs/files

```
#	--------------------------------------------------------------------------
#	A call to mkdir was unable to create the desired directory:
#	
#	  Directory: /tmp/ompi.frog.1001/pid.434
#	  Error:     No such file or directory
#	
#	Please check to ensure you have adequate permissions to perform
#	the desired operation.
#	--------------------------------------------------------------------------
#	[frog:00434] [[43708,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 107
#	[frog:00434] [[43708,0],0] ORTE_ERROR_LOG: Error in file util/session_dir.c at line 346
#	--------------------------------------------------------------------------
#	It looks like orte_init failed for some reason; your parallel process is
#	likely to abort.  There are many reasons that a parallel process can
#	fail during orte_init; some of which are due to configuration or
#	environment problems.  This failure appears to be an internal failure;
#	here's some additional information (which may only be relevant to an
#	Open MPI developer):
#	
#	  orte_session_dir failed
#	  --> Returned value Error (-1) instead of ORTE_SUCCESS
#	--------------------------------------------------------------------------
```

**Comment by mkre** [comment] 2020-04-23 16:14
We recently ran into the same issue with Open MPI 4.0.2. Can anyone please comment here? Is my assumption correct, that the issue can only occur if

* at least two Open MPI jobs are running on the same host at the same time,
* they are launched by different users (otherwise, the permissions should be fine and `orte_create_dir()` should return successfully),
* their `mpirun` (or `orterun`?) has the same PID, so we obtain a file name conflict.

Without having much knowledge of the code, it seems like ORTE could do a better job creating a unique tmp directory name (instead of just appending what seems like the PID).

Is there any way to safely prevent this issue?

**Comment by rhc54** [comment] 2020-04-23 16:36
How is it possible for two unique processes to have the same pid at the same time on your machine?

**Comment by rhc54** [comment] 2020-04-23 16:41
Just to be clear: the original problem reported here is clearly that something happened that caused ORTE not to completely cleanup (e.g., the daemon died unexpectedly), thus leaving a directory behind. Once the PID table cycles around, another job comes along with the same pid and "collides" with the leftover directory from the prior job.

The only answer to that problem is to periodically pause the activity and scrub the tmp directory, or perhaps to scrub it if mpirun indicates that it abnormally terminated (just to be safe). Would have to be done on the backend nodes as well, which is why pausing things is helpful to ensure you don't whack an active directory.

**Comment by mkre** [comment] 2020-04-23 16:55
Thanks for your assessment!

> How is it possible for two unique processes to have the same pid at the same time on your machine?

Sure, that's not possible and I was a bit inaccurate in my post above. The same PID obviously does not have to be present at the same time.

As you explained, the root cause is abnormal terminal which causes the tmp directory to not be deleted.

Can the tmp directory be set from outside, e.g. by passing a parameter to `mpirun`? By this, we could clean only this directory manually after `mpirun` terminates, or also in a signal handler to handle (some) cases of abnormal termination. Otherwise, it really seems what's left to do is to scrub the entirety of  `/tmp` periodically or after abnormal termination.

**Comment by rhc54** [comment] 2020-04-23 17:17
> Can the tmp directory be set from outside, e.g. by passing a parameter to mpirun?

Yes - and we generally recommend people do that for precisely the cleanup problem. You can do it in several ways:

* set `TMPDIR` in the environment, though that might impact your application too
* set `OMPI_MCA_orte_tmpdir_base` in your environment or default MCA param file
* add `--mca orte_tmpdir_base <foo>` to your mpirun cmd line

The last two will only impact ORTE and not the app.

**Comment by rhc54** [comment] 2020-04-23 17:21
I suppose we could adapt the code a bit to help - for example, if the session directory already exists, we could probably safely assume that the PID table has cycled and we are hitting a leftover crumb, remove it, and replace it with a fresh one.

I'm not sure there really is a risk in doing so - the directory name is uniquely marked by the pid of the daemon creating it, so the only way we can have a collision is if we have been assigned the same pid...and as we just agreed, that cannot happen if the original owner of that pid is still around :smile:

Does that make sense? Would it be of help?

**Comment by mkre** [comment] 2020-04-23 17:44
Great, I guess we'd like to look into `orte_tmpdir_base` then 👍 .

bq. I suppose we could adapt the code a bit to help - for example, if the session directory already exists, we could probably safely assume that the PID table has cycled and we are hitting a leftover crumb, remove it, and replace it with a fresh one.

I suppose that would only work if the previous job was from the same user. Otherwise, we wouldn't be able to remove the directory, right? As far as my understanding of `orte_create_dir()` goes, this case (directory already exists and permissions are OK) is already treated correctly..? See here: https://github.com/open-mpi/ompi/blob/v4.0.x/orte/util/session_dir.c#L93

Anyway, some treatment of this inside Open MPI would surely be of help as a second safety net, but I would assume that `orte_tmpdir_base` already fits our needs.

**Comment by rhc54** [comment] 2020-04-23 18:09
>  suppose that would only work if the previous job was from the same user. Otherwise, we wouldn't be able to remove the directory, right? 

Good point - still, easy to add and at least it has the potential of providing a little help. The referenced code returns an error in this case - it doesn't remove/recreate the directory. I suspect the result is that ORTE errors out. I'll check and implement a solution if it does.

**Comment by rhc54** [comment] 2020-04-23 18:40
Had to dig a layer or two down, but bottom line is that you are correct - so long as the "new" user has adequate permissions, the current code should do the correct thing. Thus, the underlying problem here is that it is a different user that lacks the required permissions.

Afraid there is nothing more we can do here. Setting the temp directory head and ensuring it gets cleaned out is the only real solution, so I'll close this now.

**Closed by rhc54** 2020-04-23 18:40 UTC

**Comment by mkre** [comment] 2020-04-24 06:40
Thanks Ralph!
