### ISSUE TITLE
error when install openmpi 4.0.1

### ISSUE THREAD

**Issue by upuil** [open-mpi/ompi#6581] opened 2019-04-09 15:28 UTC
I try to install the new version of ompi  from source code.
`CC=icc CXX=icpc FC=ifort F77=ifort ./configure --prefix=/home/opt/apps/openmpi/3.1.3/intel/2017a`
```
In file included from common_ucx.c(12):
common_ucx.h(133): warning #266: function "ucp_request_free" declared implicitly
      MCA_COMMON_UCX_WAIT_LOOP(request, worker, msg, ucp_request_free(request));
      ^

In file included from common_ucx.c(18):
/opt/ucx/include/ucm/api/ucm.h(11): catastrophic error: cannot open source file "ucs/sys/compiler.h"
  #include <ucs/sys/compiler.h>
                               ^

compilation aborted for common_ucx.c (code 4)
make[2]: *** [libmca_common_ucx_la-common_ucx.lo] Error 1
make[2]: Leaving directory `/home/pu/openmpi-4.0.1/opal/mca/common/ucx'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/pu/openmpi-4.0.1/opal'
make: *** [all-recursive] Error 1

```

**Comment by jsquyres** [comment] 2019-04-09 16:50
Are you compiling Open MPI v4.0.1 or 3.1.3?  Both are listed in your output.

This looks like a bug in the UCX header file (i.e., not an Open MPI header file).

If the problem is really in `/opt/ucx/include/ucm/api/ucm.h` (i.e., is there a `ucs/sys/compiler.h` file on your machine anywhere?), this issue should probably be reported to the UCX community.

FYI @yosefe @jladd-mlnx

**Comment by hppritcha** [comment] 2019-04-09 18:47
What version of UCX is installed on the system?

**Comment by ggouaillardet** [comment] 2019-04-10 04:09
the root cause is a UCX header cannot find an other UCX header. This strongly suggests the issue is not in Open MPI but is either caused by an UCX bug or a local and busted UCX install.

**Comment by dmitrygladkov** [comment] 2019-04-10 06:41
The similar problem was fixed in the https://github.com/openucx/ucx/pull/1336
The latest release [1.5.1](https://github.com/openucx/ucx/releases/tag/v1.5.1) contains this fix

@upuil Could you check with UCX master or v1.5.1, please?

**Comment by jsquyres** [comment] 2019-04-10 17:02
Let's go ahead and close the issue here -- sounds like followups with the UCX community are warranted if the problem persists.

**Closed by jsquyres** 2019-04-10 17:02 UTC
