### ISSUE TITLE
bug in Dynamic Process Management (MPI_Comm_accept) in open-mpi 2.0.0

### ISSUE THREAD

**Issue by xldrx** [open-mpi/ompi#1905] opened 2016-07-26 23:25 UTC
`MPI_Comm_accept` doesn't work properly in 2.0.0 release.

I used the following code:

```
#include <mpi.h> 
int main(){ 
  char port_name[MPI_MAX_PORT_NAME]; 
  int provided; 
  int thread_level = MPI_THREAD_MULTIPLE; 
  MPI_Comm inter_comm; 
  MPI_Init_thread(0, 0, thread_level, &provided); 
  MPI_Open_port(MPI_INFO_NULL, port_name); 
  MPI_Comm_accept(port_name, MPI_INFO_NULL, 0, MPI_COMM_SELF, &inter_comm); 
  // Code never reach here. 
  MPI_Comm_disconnect(&inter_comm); 
  MPI_Close_port(port_name); 
  MPI_Finalize(); 
  return 0; 
} 
```

The code is compiled and run with the following commands: 

```
> mpic++ server.cc 
> mpiexec -mp ./a.out 
```

Unfortunately it is crashed immediately after start with the following 
error messages:

```
$ mpiexec -np 1 ./a.out 
[myhost:32527] OPAL ERROR: Timeout in file base/pmix_base_fns.c at line 195 
[myhost:32527] *** An error occurred in MPI_Comm_accept 
[myhost:32527] *** reported by process [776667137,0] 
[myhost:32527] *** on communicator MPI_COMM_SELF 
[myhost:32527] *** MPI_ERR_UNKNOWN: unknown error 
[myhost:32527] *** MPI_ERRORS_ARE_FATAL (processes in this communicator 
will now abort, 
[myhost:32527] *** and potentially your MPI job) 
```

The code works just find on previous versions of open-mpi (1.10.x, 1.8.x) 
and `MPICH`. 

I've compile the open-mpi myself with both default configurations, and the 
following: 

```
> ./configure --enable-mpi-thread-multiple 
```

**Comment by rhc54** [comment] 2016-07-26 23:35
have you tried it without threading enabled?

**Comment by rhc54** [comment] 2016-07-27 00:34
actually, i see the problem - the implementation currently assumes that two procs are involved, and you are doing it all with the same proc looping onto itself. I'll have to explore a solution.

**Comment by ggouaillardet** [comment] 2016-07-27 10:44
I would expect the test hang because no one is calling MPI_Comm_connect()
did I miss something ?

**Comment by rhc54** [comment] 2016-07-27 15:23
Agreed - I wondered that myself, but the @xldrx says this works on prior versions and MPICH, so I assume there must be some MPI standard corner-case about doing this operation to yourself? Or maybe it was just a fluke before?

**Comment by xldrx** [comment] 2016-07-27 15:26
It should hang until a client call `MPI_Comm_conncet()`. But in `open-mpi 2.0.0` it just crashed immediately, not wait.
The code is the first part of a *Dynamic Process Management* hello world example.

**Comment by rhc54** [comment] 2016-07-27 15:34
Ah, now that is a very different statement than your initial report! It is actually doing exactly what it is supposed to do as there is a default timeout being applied. This was implemented to help people avoid wasting an entire allocation time and cost while waiting for a connect that would never appear.

If you want it to wait without timeout, then you need to pass an appropriate info key telling us not to set the timer. I'll ensure that code path is defined and enabled.

**Comment by xldrx** [comment] 2016-07-27 15:36
Well what you are saying is the blocking calls are going to fail unless the default timeout is increased?

**Comment by rhc54** [comment] 2016-07-27 15:40
as currently configured, it will _eventually_ timeout. The default setting is 60 seconds. However, I'm happy to make it default to an infinite timeout and let someone specify something - more of a "user beware" issue really. Just had people asking for the timeout behavior, and so we set it to something.

**Comment by xldrx** [comment] 2016-07-27 16:10
My observation is the default timeout is way less than 30 seconds. I fact the timeout error is triggered in matter of microseconds.

**Comment by rhc54** [comment] 2016-07-27 16:19
Oh? I'm seeing the timeout as a full 60 seconds, but that is after I fixed a few minor bugs I discovered, and so that may be influencing things.

**Comment by ggouaillardet** [comment] 2016-07-27 22:14
I saw this error message before, and it was related to a 2 seconds pmix timeout, not the 60 seconds pmix timeout.

**Comment by rhc54** [comment] 2016-07-27 22:27
this particular call down there defaults to 60 as that is what the calling MPI layer specified

**Comment by ggouaillardet** [comment] 2016-07-28 00:07
well, it should but it does not :-(

by default
```
[gilles@c7 ~]$ time mpirun -np 1 ./a.out 
[c7:4212] *** An error occurred in MPI_Comm_accept
[c7:4212] *** reported by process [140421219418113,21474836480]
[c7:4212] *** on communicator MPI_COMM_SELF
[c7:4212] *** MPI_ERR_UNKNOWN: unknown error
[c7:4212] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[c7:4212] ***    and potentially your MPI job)
[c7.kmc.kobe.rist.or.jp:04212] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195

real	0m2.483s
user	0m0.122s
sys	0m0.296s
```

when playing with ```orte_pmix_server_max_wait"

```
$ time mpirun --mca orte_pmix_server_max_wait 10 ./a.out 
[c7:04170] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04171] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04173] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:4171] *** An error occurred in MPI_Comm_accept
[c7:4171] *** reported by process [140399742877697,21474836481]
[c7:4171] *** on communicator MPI_COMM_SELF
[c7:4171] *** MPI_ERR_UNKNOWN: unknown error
[c7:4171] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[c7:4171] ***    and potentially your MPI job)
[c7:04172] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04165] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[c7:04165] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

real	0m10.747s
user	0m1.706s
sys	0m6.408s
```

```
$ time mpirun --mca orte_pmix_server_max_wait 30 ./a.out 
[c7:04191] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7.kmc.kobe.rist.or.jp:04196] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04190] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:4190] *** An error occurred in MPI_Comm_accept
[c7:4190] *** reported by process [139678188634113,21474836480]
[c7:4190] *** on communicator MPI_COMM_SELF
[c7:4190] *** MPI_ERR_UNKNOWN: unknown error
[c7:4190] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[c7:4190] ***    and potentially your MPI job)
[c7:04192] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04185] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[c7:04185] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

real	0m30.857s
user	0m2.103s
sys	0m14.967s
```

```
$ time mpirun --mca orte_pmix_server_max_wait 120 ./a.out 
[c7:04223] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04224] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04226] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:04225] OPAL ERROR: Timeout in file ../../../../../src/ompi-v2.x/opal/mca/pmix/base/pmix_base_fns.c at line 195
[c7:4223] *** An error occurred in MPI_Comm_accept
[c7:4223] *** reported by process [140459874844673,21474836480]
[c7:4223] *** on communicator MPI_COMM_SELF
[c7:4223] *** MPI_ERR_UNKNOWN: unknown error
[c7:4223] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[c7:4223] ***    and potentially your MPI job)
[c7:04218] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[c7:04218] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

real	2m0.811s
user	0m8.137s
sys	1m23.144s
```

bottom line,
- the 60 seconds timeout never expires
- the ```orte_pmix_server_max_wait``` timeout expires.

```orte_pmix_server_max_wait``` default value is 2 seconds, so my guess is this is a watchdog for operations that should complete shortly (e.g. send/recv between pmix client and server).
```MPI_Comm_accept()``` can take a while before an other communicator (possibly from an other Open MPI job) invokes ```MPI_Comm_connect()```, so if my initial guess was right, then this ```orte_pmix_server_max_wait``` timeout/watchdog should be disabled when doing ```MPI_Comm_accept()```
as a side note
- ```orte_pmix_server_max_wait``` is not listed by ompi_info --all
```
$ ompi_info --all | grep server_max_wait
$ 
```

the ``60`` seconds value is hard coded, and we could/should make it a MCA parameter.


back to MPI stuff, ```MPI_Comm_accept()``` and ```MPI_Comm_connect()``` are collective operations.
they create an inter-communicator (the output communicator) out of two intra communicators (the input communicator). in this context, ```MPI_COMM_SELF``` is just an intra-communicator with one task.
i will double check there is no issue with that.

**Comment by rhc54** [comment] 2016-07-28 00:37
is this with or without the patch? You are welcome to play with this as you like - I honestly have no bias in how connect/accept works. There is no MPI_Info key in the API by which the caller can control things, so MCA param would be the only option. For now, I simply hardcoded it to not timeout at all, though the ORTE server may time out separately.

**Comment by ggouaillardet** [comment] 2016-07-28 00:44
here is a test program that must be submitted with 2 tasks or more, bottome line, when ```MPI_Comm_accept()``` and ```MPI_Comm_connect()``` do not have to wait each other more than 2 seconds, there is nothing wrong with using ```MPI_COMM_SELF``` nor single task communicators

```c
#include <stdio.h>

#include <mpi.h> 
int main(){ 
  char port_name[MPI_MAX_PORT_NAME]; 
  int provided; 
  int thread_level = MPI_THREAD_MULTIPLE; 
  int rank, size, color;
  MPI_Comm inter_comm, split_comm; 
  MPI_Init_thread(0, 0, thread_level, &provided); 
  MPI_Comm_rank(MPI_COMM_WORLD, &rank);
  MPI_Comm_size(MPI_COMM_WORLD, &size);
  if (0 == rank) {
      MPI_Open_port(MPI_INFO_NULL, port_name); 
  }
  MPI_Bcast(port_name, MPI_MAX_PORT_NAME, MPI_CHAR, 0, MPI_COMM_WORLD);

  color = (0 != rank);
  MPI_Comm_split(MPI_COMM_WORLD, color, rank, &split_comm);

  if (0 == rank) printf("accept split_comm(1), connect split_comm(%d)\n", size-1);
  MPI_Barrier(MPI_COMM_WORLD);
  if (0 == color) {
    MPI_Comm_accept(port_name, MPI_INFO_NULL, 0, split_comm, &inter_comm); 
  } else {
    MPI_Comm_connect(port_name, MPI_INFO_NULL, 0, split_comm, &inter_comm); 
  }
  MPI_Comm_disconnect(&inter_comm); 

  if (0 == rank) printf("accept MPI_COMM_SELF(1), connect split_comm(%d)\n", size-1);
  MPI_Barrier(MPI_COMM_WORLD);
  if (0 == color) {
    MPI_Comm_accept(port_name, MPI_INFO_NULL, 0, MPI_COMM_SELF, &inter_comm); 
  } else {
    MPI_Comm_connect(port_name, MPI_INFO_NULL, 0, split_comm, &inter_comm); 
  }
  MPI_Comm_disconnect(&inter_comm); 

  MPI_Comm_free(&split_comm);

  color = ((size-1) == rank);
  MPI_Comm_split(MPI_COMM_WORLD, color, rank, &split_comm);

  if (0 == rank) printf("accept split_comm(%d), connect split_comm(1)\n", size-1);
  MPI_Barrier(MPI_COMM_WORLD);
  if (0 == color) {
    MPI_Comm_accept(port_name, MPI_INFO_NULL, 0, split_comm, &inter_comm); 
  } else {
    MPI_Comm_connect(port_name, MPI_INFO_NULL, 0, split_comm, &inter_comm); 
  }
  MPI_Comm_disconnect(&inter_comm); 

  if (0 == rank) printf("accept split_comm(%d), connect MPI_COMM_SELF(1)\n", size-1);
  MPI_Barrier(MPI_COMM_WORLD);
  if (0 == color) {
    MPI_Comm_accept(port_name, MPI_INFO_NULL, 0, split_comm, &inter_comm); 
  } else {
    MPI_Comm_connect(port_name, MPI_INFO_NULL, 0, MPI_COMM_SELF, &inter_comm); 
  }
  MPI_Comm_disconnect(&inter_comm); 

  MPI_Comm_free(&split_comm);



  if (0 == rank) {
    MPI_Close_port(port_name); 
  }
  MPI_Finalize(); 
  return 0; 
} 
```

**Comment by ggouaillardet** [comment] 2016-07-28 00:45
that was without the patch, i will try it from now

**Comment by opoplawski** [comment] 2016-10-23 14:26
I'm seeing this timeout message in the mpi4py tests with openmpi 2.0.1 on Fedora rawhide on i386:
```
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf) ... [buildvm-06.phx2.fedoraproject.org:15489] OPAL ERROR: Timeout in file base/pmix_base_fns.c at line 193
```
Not sure how reproducible this is yet.  This test appeared to succeed on x86_64.

**Comment by ggouaillardet** [comment] 2016-10-24 11:47
Does the timeout occur after ~2 seconds or ~60 seconds ?

Out of curiosity, are you running rawhide as a virtualbox.org guest ?
stock F24 works fine, but uptodate F24 nor rawhide can even boot. Stock F24 kernel works just fine thought

**Comment by opoplawski** [comment] 2016-10-24 15:55
The next test seemed to fail on x86_64:
```
testArgsOnlyAtRoot (test_spawn.TestSpawnSelf) ... ok
testArgsOnlyAtRootMultiple (test_spawn.TestSpawnSelf) ... --------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):
  ompi_dpm_dyn_init() failed
  --> Returned "Timeout" (-15) instead of "Success" (0)
--------------------------------------------------------------------------
[buildvm-07.phx2.fedoraproject.org:28504] OPAL ERROR: Timeout in file base/pmix_base_fns.c at line 193
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
```
No idea yet how long the timeout is.  These are koji builds - http://koji.fedoraproject.org/koji/taskinfo?taskID=16182090  - working on reproducing in mock or VM...

**Comment by opoplawski** [comment] 2016-10-24 17:46
hmm, in mock on my machine,  testArgsOnlyAtRoot (test_spawn.TestSpawnSelf) seems to hang for a very long time - I killed it after almost 2 hours.  I can open a new issue if this seems to be something else.

**Comment by rhc54** [comment] 2016-10-24 17:52
Can you tell me something about this app? Is it just s singleton that calls comm_spawn?

**Comment by opoplawski** [comment] 2016-10-25 21:38
Some other info - turns out that the upstream mpi4py test suite has disabled the spawn tests, so I've disabled them in the Fedora builds as well.  So perhaps problems are expected in the mpi4py test suite.

TestSpawnSelf is doing something like:
```
    COMM = MPI.COMM_SELF
    COMMAND = sys.executable
    ARGS = [CHILDSCRIPT, MPI4PYPATH,
            "mpe" if HAVE_MPE else
            "vt"  if HAVE_VT  else ""]
    MAXPROCS = 1
    INFO = MPI.INFO_NULL
    ROOT = 0

    def testArgsOnlyAtRoot(self):
        self.COMM.Barrier()
        rank = self.COMM.Get_rank()
        if rank == self.ROOT:
            child = self.COMM.Spawn(self.COMMAND, self.ARGS, self.MAXPROCS,
                                    info=self.INFO, root=self.ROOT)
        else:
            child = self.COMM.Spawn(None, None, -1,
                                    info=None, root=self.ROOT)
        child.Barrier()
        child.Disconnect()
        self.COMM.Barrier()
```
Unfortunately I'm not having any luck with gdb at the moment so I can't see where it's hanging.  And I can't reproduce the timeout error locally.

**Comment by rhc54** [comment] 2016-11-02 03:54
I know this has now been solved by a patch from @hjelmn - but the precise PR escapes me. Still, we are updating all the v2.0 and v2.x branches, so I'm going to close this now as the fix will be in the next releases.

**Closed by rhc54** 2016-11-02 03:54 UTC
