### ISSUE TITLE
Multiple successive Barriers hangs

### ISSUE THREAD

**Issue by tomMoral** [open-mpi/ompi#4314] opened 2017-10-08 14:08 UTC
## Background information

* openMPI installed with package manager. (version version 2.1.1-2)
* Operating system/version: archlinux
* Computer hardware: HP zbook G3
* Network type: local nodes

-----------------------------

I am not familiar with the openMPI internals, so sorry if the question is naive. I have a piece of code, which send multiple arrays using `Bcast`. This piece of software is working on the server I used (which run openMPI1.6.5) but hangs on my personal laptop with openMPI2.1.1-2. Actually, the first broadcast goes well but after that, the other hang and my program get stuck.

While debugging, I realised that successive collective calls seem to cause a hang. Here is [an example](https://gist.github.com/tomMoral/cbb6047eeeea74e3682850ce41d2ae1c) that I am able to run with openMPI1.6.5 but which hangs after 2 Barriers with openMPI2.1

```bash
#OpenMPI 1.6.5
$ ./main_barriers 
Remote size root: 4
Barrier
Started worker rank: 0/4
Root comm size: 1
Barrier1: ok
Started worker rank: 1/4
Started worker rank: 2/4
Started worker rank: 3/4
Barrier2: ok
0 - Barrier1: ok
0 - Barrier2: ok
1 - Barrier1: ok
1 - Barrier2: ok
2 - Barrier1: ok
2 - Barrier2: ok
3 - Barrier1: ok
3 - Barrier2: ok
Barrier3: ok
1 - Barrier3: ok
3 - Barrier3: ok
2 - Barrier3: ok
0 - Barrier3: ok
Barrier4: ok
3 - Barrier4: ok
1 - Barrier4: ok
0 - Barrier4: ok
2 - Barrier4: ok
Barrier5: ok
1 - Barrier5: ok
0 - Barrier5: ok
3 - Barrier5: ok
2 - Barrier5: ok
```

```bash
#OpenMPI2.1
$ ./main_barriers 
Remote size root: 4
Barrier
Started worker rank: 0/4
Root comm size: 1
Started worker rank: 1/4
Started worker rank: 2/4
Started worker rank: 3/4
Barrier1: ok
Barrier2: ok
0 - Barrier1: ok
1 - Barrier1: ok
2 - Barrier1: ok
3 - Barrier1: ok
3 - Barrier2: ok
2 - Barrier2: ok
0 - Barrier2: ok
1 - Barrier2: ok
#HANGS there
```

Is this an issue in openMPI or is there something that I did not understand?

**Comment by bosilca** [comment] 2017-10-08 16:58
Can you please share you code ?

**Comment by tomMoral** [comment] 2017-10-08 20:15
Sorry, the link to the gist is not clear: https://gist.github.com/tomMoral/cbb6047eeeea74e3682850ce41d2ae1c

**Comment by bosilca** [comment] 2017-10-09 17:20
@tomMoral your application looks correct, and the fact that 2 barriers on the intercomm have been successfully completed means that OMPI was able to correctly setup the communication channels. I can't replicate your issue with any version of OMPI I have. Can you give it a try with the latest in the 2.x series ?

**Comment by ggouaillardet** [comment] 2017-10-10 00:21
@tomMoral i was also unable to replicate the issue.

as a side note, be aware that MPI C++ bindings have been removed from the MPI standard.
As far as Open MPI is concerned, C++ bindings are still available, but they are no more built by default since Open MPI 2.0.0

**Comment by tomMoral** [comment] 2017-10-10 10:43
@ggouaillardet thanks for the pointer to C++ wrappers!

With the latest branch repo, it works like a charm but compiling with v2.1.2 (which is the shipped version in archlinux), I can reproduce the failure.

**Comment by ggouaillardet** [comment] 2017-10-10 11:51
@tomMoral thanks, i will try to reproduce the issue on archlinux

**Comment by ggouaillardet** [comment] 2017-10-11 11:49
i was unable to reproduce the issue with an up to date archlinux.

fwiw, here is the ```PKGBUILD``` for Open MPI 2.1.2 is submitted to the maintainer
```
# Maintainer: Levente Polyak <anthraxx[at]archlinux[dot]org>
# Contributor: Anatol Pomozov <anatol dot pomozov at gmail>
# Contributor: Stéphane Gaudreault <stephane@archlinux.org>
# Contributor: Gilles Gouaillardet <gilles[at]rist[dot]or[dot]jp>

pkgname=openmpi
pkgver=2.1.2
pkgrel=1
pkgdesc='High performance message passing library (MPI)'
url='https://www.open-mpi.org'
arch=('i686' 'x86_64')
license=('custom:OpenMPI')
depends=('libltdl' 'hwloc' 'openssh')
makedepends=('inetutils' 'valgrind' 'gcc-fortran')
optdepends=('gcc-fortran: fortran support')
options=('staticlibs')
source=(https://www.open-mpi.org/software/ompi/v${pkgver%.*}/downloads/${pkgname}-${pkgver}.tar.bz2)
sha256sums=('3cc5804984c5329bdf88effc44f2971ed244a29b256e0011b8deda02178dd635')
sha512sums=('8a27a67cab384f9f03efe69bfdd51a8e8790f47a156e3a7e34f26a29d033889653070981c0105f142a96f00293fc069536bd020ae28a97afb564eab747e60457')

build() {
  cd ${pkgname}-${pkgver}
  ./configure --prefix=/usr \
    --sysconfdir=/etc/${pkgname} \
    --enable-mpi-fortran=all \
    --libdir=/usr/lib/${pkgname} \
    --enable-mpi-thread-multiple \
    --enable-builtin-atomics \
    --enable-mpi-cxx \
    --with-valgrind \
    --enable-memchecker \
    --enable-pretty-print-stacktrace \
    --without-slurm \
    --with-hwloc=external \
    --with-libltdl \
    FC=/usr/bin/gfortran \
    LDFLAGS="${LDFLAGS} -Wl,-z,noexecstack"
  make
}

check() {
  cd ${pkgname}-${pkgver}
  make check
}

package() {
  cd ${pkgname}-${pkgver}
  make DESTDIR="${pkgdir}" install

  # FS#28583
  install -dm 755 "${pkgdir}/usr/lib/pkgconfig"
  for i in ompi-c.pc ompi-cxx.pc ompi-f77.pc ompi-f90.pc ompi.pc; do
    ln -sf "/usr/lib/openmpi/pkgconfig/${i}" "${pkgdir}/usr/lib/pkgconfig/"
  done

  install -dm 755 "${pkgdir}/etc/ld.so.conf.d"
  echo "/usr/lib/${pkgname}" > "${pkgdir}"/etc/ld.so.conf.d/${pkgname}.conf
  install -Dm 644 LICENSE -t "${pkgdir}/usr/share/licenses/${pkgname}"
}

# vim: ts=2 sw=2 et:
```

would this fix the problem for you ?

**Comment by thananon** [comment] 2018-03-21 15:24
Last respond was 5 months ago. I'm closing this issue. It can be reopened if need be.

**Closed by thananon** 2018-03-21 15:24 UTC
