### ISSUE TITLE
users reporting poor sm/vader bandwidth for 2.0.0 when openib BTL active

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#1943] opened 2016-08-05 13:34 UTC
Several users have reported poor bandwidth for larger messages (osu_bw) for sm/vader BTLs' using the 2.0.0 release  when the openib BTL is active.

See
https://mail-archive.com/devel@lists.open-mpi.org/msg00024.html

I think this should be investigated prior to 2.0.1 release.

**Comment by jsquyres** [comment] 2016-08-05 14:20
@hppritcha @hjelmn Is this related to https://github.com/open-mpi/ompi-release/pull/1287 ("Fix performance regression caused by enabling opal thread support")?

**Comment by jsquyres** [comment] 2016-08-16 14:28
Fixed in open-mpi/ompi-release#1315.

**Closed by jsquyres** 2016-08-16 14:28 UTC
Labels: bug
