### ISSUE TITLE
install problem macOS High Sierra

### ISSUE THREAD

**Issue by thierrygosselin** [open-mpi/ompi#4373] opened 2017-10-22 18:30 UTC
Trying to install Open MPI v.3.0.0 on macOS High Sierra (10.13)

Compiler installed: `gcc version 7.1.0 (GCC) `

The command:
```
cd Downloads
wget https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz
tar -xvf openmpi-3.0.0.tar.gz
cd openmpi-3.0.0
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
export CXX1X=/usr/local/bin/g++
export FC=/usr/local/bin/gfortran
export TMPDIR=/tmp
./configure
```

no error, everything looks fine

then running `make` gives these errors:

```
output.c: In function ‘opal_output_init’:
output.c:152:49: error: ‘LOG_INFO’ undeclared (first use in this function); did you mean ‘SIGINFO’?
             opal_output_redirected_syslog_pri = LOG_INFO;
                                                 ^~~~~~~~
                                                 SIGINFO
output.c:152:49: note: each undeclared identifier is reported only once for each function it appears in
output.c:154:49: error: ‘LOG_ERR’ undeclared (first use in this function); did you mean ‘SIG_ERR’?
             opal_output_redirected_syslog_pri = LOG_ERR;
                                                 ^~~~~~~
                                                 SIG_ERR
output.c:156:49: error: ‘LOG_WARNING’ undeclared (first use in this function)
             opal_output_redirected_syslog_pri = LOG_WARNING;
                                                 ^~~~~~~~~~~
output.c: In function ‘opal_output_close’:
output.c:354:13: warning: implicit declaration of function ‘closelog’; did you mean ‘close’? [-Wimplicit-function-declaration]
             closelog();
             ^~~~~~~~
             close
output.c: In function ‘do_open’:
output.c:621:13: warning: implicit declaration of function ‘openlog’; did you mean ‘openat’? [-Wimplicit-function-declaration]
             openlog(redirect_syslog_ident, LOG_PID, LOG_USER);
             ^~~~~~~
             openat
output.c:621:44: error: ‘LOG_PID’ undeclared (first use in this function); did you mean ‘P_PID’?
             openlog(redirect_syslog_ident, LOG_PID, LOG_USER);
                                            ^~~~~~~
                                            P_PID
output.c:621:53: error: ‘LOG_USER’ undeclared (first use in this function); did you mean ‘SI_USER’?
             openlog(redirect_syslog_ident, LOG_PID, LOG_USER);
                                                     ^~~~~~~~
                                                     SI_USER
output.c: In function ‘output’:
output.c:956:13: warning: implicit declaration of function ‘syslog’; did you mean ‘ttyslot’? [-Wimplicit-function-declaration]
             syslog(ldi->ldi_syslog_priority, "%s", str);
             ^~~~~~
             ttyslot
make[3]: *** [output.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Last time I used openmp i was with an older version of macOS and openmpi `openmpi-1.8.4` and I had no problem installing and using.

Best
Thierry

**Comment by bosilca** [comment] 2017-10-22 20:41
I saw this few days ago on my laptop. The problem is that the latest gcc (> 7.1) struggle with the syslog header on OSX 10.13 ([gcc bug](https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg544669.html)). This is exactly what is bitting us. If you look in the config.log we identify that syslog.h is present, but we can't use it
```
/usr/include/sys/syslog.h:227:124: error: expected ',' or ';' before '__asm'
 20192  void syslog(int, const char *, ...) __printflike(2, 3) __not_tail_called __DARWIN_ALIAS_STARTING(__MAC_10_13, __IPHONE_NA, __DARWIN_EXTSN(syslog));
```
Thus HAVE_SYSLOG_H is undefined. However, as we find the syslog function in the lib (successful link), we are half happy and we proceed with enabling the SYSLOG support.

The patch is more complicated that expected. Meanwhile you can use clang to compile Open MPI on OSX 10.13.

**Comment by thierrygosselin** [comment] 2017-10-23 02:17
yes it does.
For macOS users:

**Update clang with openMPI enabled**
```
cd Downloads
wget http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-x86_64-apple-darwin.tar.xz
tar -xzvf clang+llvm-5.0.0-x86_64-apple-darwin.tar.xz
sudo mv clang+llvm-5.0.0-x86_64-apple-darwin /NEW/FOLDER_IN_PATH/clang
```

**Install Open MPI, compiled with clang**
```
cd Downloads
wget https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz
tar -xvf openmpi-3.0.0.tar.gz
cd openmpi-3.0.0
export TMPDIR=/tmp
./configure CC=/clang/bin/clang CXX=/clang/bin/clang-5.0
make -j 4
sudo make install
```

**Comment by bosilca** [comment] 2017-10-23 06:02
No, I prefer to keep this open until we push a real fix.

**Comment by ggouaillardet** [comment] 2017-10-23 12:17
@bosilca is your (short term) plan to disable syslog on High Sierra ? or make it work ?

**Comment by bosilca** [comment] 2017-10-23 13:25
In the PR associated here I plan to turn it off. I don't see how we can make it work with gcc without providing our own header to shadow the one from the OS (but that's ugly). The only thing left right now in my PR is to turn off the syslog notifier.

**Comment by jsquyres** [comment] 2017-10-23 15:22
Note that this issues probably affects *all* Open MPI release series.  I just tried 2.0.x, and it has the problem (I didn't bother testing 1.10.x).

**Comment by thierrygosselin** [comment] 2017-10-23 16:12
I did test some of the 1.x series and same problem

**Comment by bosilca** [comment] 2017-10-23 16:54
Well, it's a gcc issue with interpreting the syslog.h header, so obviously it will affect all software using syslog that compile with gcc.

**Comment by bwbarrett** [comment] 2017-12-21 00:05
not sure why this got reopened; closing...

**Closed by bwbarrett** 2017-12-21 00:05 UTC
Labels: bug, Target: v2.x, Target: v3.0.x, Target: v3.1.x

**Comment by angerhang** [comment] 2018-03-07 10:09
I think this issue should be reopened as I ran into the same issue on mac `High Sierra 10.13.3`. Trying installation using clang.

**Comment by ggouaillardet** [comment] 2018-03-07 10:17
@angerhang which version of Open MPI did you try to install ?

**Comment by angerhang** [comment] 2018-03-07 10:18
openmpi-3.0.0

**Comment by ggouaillardet** [comment] 2018-03-07 10:21
Since the error was reported in the same version, it is no surprise this version still does not work.

Please give `3.0.1rc3`  (available at https://www.open-mpi.org/software/ompi/v3.0/) a try and re-open the issue if it still does not work.

**Comment by angerhang** [comment] 2018-03-07 10:53
Great 3.0.1rc works perfectly :D thanks

**Comment by examachine** [comment] 2018-03-27 00:34
On High Sierra with MacPorts, the default version of openmpi using clang works fine. FYI.
