### ISSUE TITLE
Fix case when RM/hostfile-provided names do not match hostname(1)

### ISSUE THREAD

**Issue by martinkontsek** [open-mpi/ompi#2328] opened 2016-11-01 17:31 UTC
We have found out that running OpenMPI job via Moab/TORQUE will lead to this error:

```
[pacini002:01000] [[37987,0],1] bind() failed on error Address already in use (98)
[pacini002:01000] [[37987,0],1] ORTE_ERROR_LOG: Error in file oob_usock_component.c at line 247
[pacini002:01003] [[37987,1],0] usock_peer_recv_connect_ack: received unexpected process identifier [[37987,0],0] from [[37987,0],1]
[pacini002:00989] [[37987,0],0]-[[37987,1],0] mca_oob_usock_peer_recv_handler: invalid socket state(1)
[pacini002:00989] [[37987,0],0]-[[37987,1],0] mca_oob_usock_peer_recv_handler: invalid socket state(1)
[pacini002:00989] [[37987,0],0]-[[37987,1],0] mca_oob_usock_peer_recv_handler: invalid socket state(1)
[pacini002:01004] [[37987,1],1] usock_peer_recv_connect_ack: received unexpected process identifier [[37987,0],0] from [[37987,0],1]
```

Running the program directly via mpirun without Moab/TORQUE works perfectly. The same issue is present in `stable v2.0.1` and `nightly v2.0.1-134-g52bea1d from 2.0.x branch` and `nightly v2.0.1-270-g87a79fa from 2.x branch`.

However issue is NOT present in `stable v1.10.4` and `nightly v2.x-dev-3109-g6074c2a from master` as it is working properly directly via mpirun and also with Moab/TORQUE. We use Moab v9.0.2 and TORQUE v6.0.2 supplied as RPM by Adaptive Computing, LibFabric 1.3.0 and we are running on RHEL 7.2. We have multiple OpenMPI versions installed and we use Environment Modules to select version needed.

We build RPM from tarball using this command with specfile included in the tarball.

```
rpmbuild -bb --define 'mflags -j40' --define '_source_filedigest_algorithm md5'  --define '_binary_filedigest_algorithm md5' --define '_name openmpi2' --define 'install_in_opt 1' --define 'build_debuginfo_rpm 1' --define '_topdir /var/tmp/rpmbuild' --define 'build_all_in_one_rpm 1' --define 'configure_options  --enable-mpirun-prefix-by-default --enable-orterun-prefix-by-default --with-usnic --without-memory-manager --enable-mca-no-build=btl-openib,common-verbs,oob-ud --enable-mpi-ext=all --with-libfabric=/opt/cisco/libfabric "LDFLAGS=-Wl,--build-id -Wl,-rpath -Wl,/opt/cisco/libfabric/lib -Wl,--enable-new-dtags" --with-tm=/usr/local/include/torque' /var/tmp/rpmbuild/SPECS/openmpi-2.0.1.spec`
```

We also tried to build source tarball directly with this configure line:

```
./configure --prefix=/opt/openmpi2/2.0.1 --enable-mpirun-prefix-by-default --enable-orterun-prefix-by-default --with-usnic --without-memory-manager --enable-mca-no-build=btl-openib,common-verbs,oob-ud --enable-mpi-ext=all --with-libfabric=/opt/cisco/libfabric "LDFLAGS=-Wl,--build-id -Wl,-rpath -Wl,/opt/cisco/libfabric/lib -Wl,--enable-new-dtags" --with-tm=/usr/local/include/torque'`
```

For testing we use `ring_c.c` example from Open MPI, which was recompiled for each OpenMPI version tested.

Without Moab/TORQUE the testing program is launched directly on the compute node `pacini002` with this command:

```
mpirun /home/mkontsek/usnic/ring_c2
```

With Moab/TORQUE the testing program is submited as batch job on head node with this batch script and command `msub`:

```
#!/bin/bash
#MSUB -l nodes=pacini002:ppn=2
#MSUB -l walltime=60
#MSUB -l pmem=1024mb
#MSUB -N test_OpenMPI2

module purge
module load mpi/openmpi/2.0.1
module list
startexe="mpirun /home/mkontsek/usnic/ring_c2"
echo $startexe
exec $startexe
```

@jsquyres 
Thank you very much for your help with this issue.

***EDIT:*** Minor verbatim / formatting changes made for readability.

**Comment by jsquyres** [comment] 2016-11-01 17:35
@rhc54 Could you have a look?  Thanks!

**Comment by jjhursey** [comment] 2016-11-01 18:00
This looks like something I've seen related to the shortening of hostnames. @martinkontsek can you try this patch (I don't have a machine with TORQUE to test)?

The diff was generated from `master`, but should apply (fairly) cleanly to either the `v2.x` or `v2.0.x` builds.
```diff
diff --git a/orte/mca/ras/tm/ras_tm_module.c b/orte/mca/ras/tm/ras_tm_module.c
index 4daed28a..ed60a8b9 100644
--- a/orte/mca/ras/tm/ras_tm_module.c
+++ b/orte/mca/ras/tm/ras_tm_module.c
@@ -27,6 +27,7 @@
 
 #include "orte/util/show_help.h"
 #include "opal/util/os_path.h"
+#include "opal/util/net.h"
 
 #include "orte/mca/errmgr/errmgr.h"
 #include "orte/runtime/orte_globals.h"
@@ -168,6 +169,11 @@ static int discover(opal_list_t* nodelist, char *pbs_jobid)
 
     nodeid=0;
     while (NULL != (hostname = tm_getline(fp))) {
+        if( !orte_keep_fqdn_hostnames && !opal_net_isaddr(hostname) ) {
+            if (NULL != (ptr = strchr(hostname, '.'))) {
+                *ptr = '\0';
+            }
+        }
 
         OPAL_OUTPUT_VERBOSE((1, orte_ras_base_framework.framework_output,
                              "%s ras:tm:allocate:discover: got hostname %s",
```

**Comment by martinkontsek** [comment] 2016-11-01 21:52
Hello.
The patch didn't help. The issue is still present. I have tested in on both `nightly v2.0.1-134-g52bea1d from 2.0.x branch` and `nightly v2.0.1-270-g87a79fa from 2.x branch`.

**Comment by rhc54** [comment] 2016-11-01 22:06
This actually looks like we have daemons either getting launched on the master node (where mpirun is executing), or we have confusion in the way daemons are computing their vpids.

Can you please configure OMPI with --enable-debug, and then add "-mca plm_base_verbose 5" to your cmd line? I'm looking for something that tells me if a daemon is being launched onto the same node where mpirun is executing - if so, then you would indeed hit this error.

**Comment by martinkontsek** [comment] 2016-11-01 22:51
I have recompiled OpenMPI v2.0.1-134-g52bea1d nightly with --enable-debug.
Here is log from pure mpirun: [debug_mpirun_2.0.x.txt](https://github.com/open-mpi/ompi/files/565242/debug_mpirun_2.0.x.txt)
Here is log from Moab/TORQUE run: [debug_Moab_2.0.x.txt](https://github.com/open-mpi/ompi/files/565244/debug_Moab_2.0.x.txt)

**Comment by rhc54** [comment] 2016-11-01 23:30
I see that the Moab run thinks it has been allocated node "pacini002-11". Your output shows that mpirun is executing on a node "pacini002". The mpirun ssh-based run shows only one node, "pacini002", in the allocation.

Are "pacini002" and "pacini002-11" the same node?

**Comment by martinkontsek** [comment] 2016-11-01 23:33
Yes, they are same nodes. Moab/TORQUE uses pacini002-11.<domain> as we are running it on VLAN11.

**Comment by rhc54** [comment] 2016-11-02 00:18
Ah, well that is the problem! The different node names confuse us into thinking they are different nodes, and hence we launch an orted when we shouldn't.

What does the PBS_NODEFILE look like?

**Comment by martinkontsek** [comment] 2016-11-02 00:34
I suppose by PBS_NODEFILE you mean node definition file for Torque. [nodes.txt](https://github.com/open-mpi/ompi/files/565413/nodes.txt)

I should also mention, that I am removing domain name from all the outputs.
so pacini002 looks like pacini002.xxx.yyy.com
and pacini002-11 looks like pacini002.xxx.yyy.com

**Comment by rhc54** [comment] 2016-11-02 01:57
Okay, I see the problem, though I'm not immediately sure how to solve it. You have Moab configured in a way that causes it to add a "-11" to the end of each node name. However, "hostname" on the nodes isn't returning that string - it returns the actual nodename, which doesn't include the "-11" suffix. As a result, we don't see the nodes as being the same, and think the nodes are different - which is what causes the problem.

Sadly, faking out "hostname" can cause a number of packages to have problems, so you might want to reconsider that setup. Meantime, I'll give some thought as to how to possibly solve the nodename resolution problem.

**Comment by martinkontsek** [comment] 2016-11-02 02:47
But this issue is NOT present in `stable v1.10.4` and `nightly v2.x-dev-3109-g6074c2a from master`. Shouldn't this behaviour be consistent between branches?

**Comment by rhc54** [comment] 2016-11-02 03:27
Not necessarily - there are differences in the code based on what patches may have come across, the timing of those patches, and changes in Torque. We frankly don't often see this kind of problem as folks generally don't modify the hostname. I've seen this pattern more commonly in places like Hadoop clusters, but we historically had separate code (since removed) for dealing with them.

Like I said, I'll have to give some thought to the matter, and will look at the code diffs to see if something pops out. It may be that updating to the 2.1 release (when it comes out) may be your best path forward, though if something immediate presents itself we may (though it is late in the game) be able to squeeze it into 2.0.2. Otherwise, 2.1 would be the next target.

**Comment by jsquyres** [comment] 2016-11-02 14:33
@martinkontsek Out of curiosity, is there a reason you're using the `-11` names for Torque?  I ask because it is a popular misconception that MPI libraries use the hostnames provider by the resource manager to determine which network interfaces should be used for MPI traffic.  To be clear: the hostnames/IP addresses given to Open MPI by the resource manager have no bearing on which network interfaces are used for MPI traffic.

**Comment by martinkontsek** [comment] 2016-11-02 17:28
@jsquyres The reason for using `-11` name s for Moab/TORQUE is that we want the Moab/TORQUE control communication between head node and compute nodes to be in VLAN11. This config was suggested by Adaptive support as the only way of ensuring the communication will go via VLAN11.

**Comment by rhc54** [comment] 2016-11-02 18:21
One solution is to just rename your nodes with that extension so that "hostname" returns the -11 name. I'm sorry to hear that Moab/Torque has adopted the rather odd Hadoop convention of tagging a node's name to a specific interface as that creates considerable confusion - I'll address that with them directly. Meantime, renaming the nodes would be your quickest solution.

**Comment by martinkontsek** [comment] 2016-11-03 21:52
@rhc54 Thank you very much for the information. Sadly renaming hostnames is not an option for us as we have production environment. So we will wait with OpenMPI v2 deployment until this issue is resolved.

**Comment by jsquyres** [comment] 2017-02-22 18:18
@rhc54 and I re-synced on this today.  Fixing this issue has missed the v2.1.x train, and is just about to miss the v3.0.x train, too.

1. This isn't a Torque/Moab-specific issue.  It's more of a "when the `hostname(1)` doesn't match the name given to Open MPI" issue, which, for @martinkontsek, just happened to come up in his particular Torque/Moab setup.
1. This is also a fairly uncommon configuration for HPC clusters (where the resource manager -- or hostfile -- gives Open MPI a resolvable name that is different than what `hostname(1)` reports).  Meaning: this is an actual issue -- just not a common one.
1. Our first preference would be that the resource manager always gives Open MPI what `hostname(1)` reports, even if it's using a different interface (or set of interfaces) that the one that -- by convention -- `hostname(1)` implies.  The would avoid the issue from Open MPI's perspective.
1. Alternatively, a possible way to solve this issue is to launch on the name that was given to Open MPI, and then check what `hostname(1)` / `gethostname(2)` returns, and send that back to the HNP so that both names can be used as aliases for the mapping process.  Open MPI nominally does this, but apparently it isn't working properly, and would take some effort to debug/fix.  😦 
1. Since this isn't a common configuration, we unfortunately have to prioritize this lower than some other, more urgent issues.

We're therefore going to leave this issue open, but leave it marked in the "Future" milestone.

**Comment by boegel** [comment] 2017-03-22 17:55
We are hitting a problem with OpenMPI 2.0.x (more specifically v2.0.2) in our systems that use Torque that we haven't seen with earlier versions of OpenMPI, that looks very much related to this.

This is the error we are getting:

```
A hostfile was provided that contains at least one node not
present in the allocation:

 hostfile:  /user/home/example/.mympirun_2p5k4s/938045.master19.golett.gent.vsc_20170322_184546/nodes
 node:      node2527

If you are operating in a resource-managed environment, then only
nodes that are in the allocation can be used in the hostfile.
```

(see also https://github.com/hpcugent/vsc-mympirun/issues/113)

The hostfile (provided via `-machinefile` to `mpirun`) contains hostnames like:

```
node2527.golett.gent.vsc
node2532.golett.gent.vsc
```

The `.vsc` network *has* to be used to talk to Torque/MOAB.

The `hostname` command returns the same (short) hostname but in a different network:

```
$ hostname
node2527.golett.os
```

The IB network has yet another domain name (`.golett.data` in this case), but that's mostly irrelevant here.

As far as I know, a 'multihome' setup like this isn't that uncommon on HPC systems.

Even though we can probably work around this in our `mympirun` tool that wraps around different MPI libraries by making sure we use the `.os` hostnames in the hostfile, I wanted to mention this here to make it clear that the problem reported by @martinkontsek may not be so uncommon after all, and that this issue should maybe be given higher priority.

In our case, the problem is slightly different some it's mostly an issue with domains rather than (short) hostnames being different, so I was wondering how OpenMPI exactly compares the hostnames in the hostfile with what `get_hostname` returns...

Does it compare short or FQDN hostnames on both sides (or a mix, which I'd consider a bug)?

The exact error message is quite confusing since it only mentions the short hostname, so it's non-intuitive: the hostname mentioned *is* in fact part of the allocation, so it's somewhat unclear why OpenMPI is complaining at first.

Thoughts @jsquyres?

**Comment by rhc54** [comment] 2017-03-22 18:29
I honestly haven't seen such an arrangement (outside of Hadoop clusters) more than a handful of times, and it was always trouble. FWIW, the Moab folks assured me they were going to fix this (a simple configuration parameter to indicate the network to be used was all that was required) as it causes problems beyond just OMPI.

The default mpirun operation is to use the short hostname - i.e., we strip everything after the first "dot". However, as you note, that means it won't work with Moab in this configuration, and so you have to pass the param to retain the FQDN. This gets done everywhere, not just in mpirun, but it cannot help with this problem as the FQDN being passed in the allocation and machinefile does not match that being returned by gethostname.

As @jsquyres said, we can try to provide a workaround until Moab gets updated. However, it is a low priority (as no other RM is making this error, to our knowledge) and I'm not sure when I'll get around to it.

**Comment by boegel** [comment] 2017-03-22 19:07
@rhc54 To be clear, the issue that should be fixed in Torque (MOAB is the scheduler, Torque is the resource manager typically used with MOAB) is that it should be specifying short hostnames in the hostfile (`$PBS_NODEFILE`), is that right?
And OpenMPI will strip the `node2527.golett.os` to `node2527` before it compares with the entries in the hostfile?

**Comment by rhc54** [comment] 2017-03-22 19:11
It doesn't matter if it specifies short or long, what matters is that whatever it specifies must match what the host itself returns.

Yes, we strip the gethostname return immediately, just as we do with the entries in the nodefile and/or machinefile.

**Comment by boegel** [comment] 2017-03-22 21:15
@rhc54 Hold on, if you strip both what `gethostname` returns and what is specified in the file provided to `-machinefile`, why are we seeing the error in the first place?

Our short hostnames (for example `node2527`) *do* match is you disregard the domain (`.golett.os` or `.golett.gent.vsc`)...

**Comment by jjhursey** [comment] 2017-03-22 21:25
@boegel You are using `v2.0.x`, right? Have you tried with `v2.x` (the `v2.1.0` release)?

I mention this because I fixed some FQDN items in `master` and `v2.x`, but only a part of it was allowed into the `v2.0.x` by the release managers. In particular, the non-LSF portion was left out since we couldn't test easily.

It should have fixed a case where we were not stripping the hostname down as they were read from the hostfile:
 * PR #2329 to `master`: in particular commit https://github.com/open-mpi/ompi/pull/2329/commits/9643175e401a1476e3a7d2d7b0a64ebfe6dc9882
 * The full commit as it went into `v2.x` is in PR #2388

**Comment by boegel** [comment] 2017-03-23 09:29
@jjhursey I'm happy to confirm that our problem is indeed fixed in OpenMPI 2.1.0, thank you very much!

**Comment by rhc54** [comment] 2017-03-23 09:33
Thanks @jjhursey for clarifying things - my comments reflected the current state, not the past. Glad to hear the problem is fixed!

**Comment by boegel** [comment] 2017-03-23 09:58
@rhc54 Note that the original reported problem, where short hostnames do not match exactly, still isn't fixed, so I'm not sure if this issue should be closed already?
Cfr. comments by @jsquyres.

**Comment by jjhursey** [comment] 2017-03-23 14:16
@boegel I'm glad that worked. I'll file a PR to bring that TM patch over to v2.0.x so it'll be included in the next release of that series.

The note from the original reporter @martinkontsek said that patch didn't work for their case - so we should probably keep this open.

**Comment by martinkontsek** [comment] 2017-05-16 22:36
I am happy to report, that also our issues were resolved. 

We have updated to Moab 9.1.1.1/Torque 6.1.1.1 and now we are able to use both Open MPI v2.1.0 and Open MPI v2.0.2 with Moab/Torque. I am not sure, if the issue was solved on Torque or Open MPI side, as we have upgraded all the software at once.

Thank you very much for your help with this issue.

**Comment by jsquyres** [comment] 2017-05-16 22:38
Great!  Thanks for following up.

**Closed by jsquyres** 2017-05-16 22:38 UTC
Labels: bug

**Comment by pkienzle** [comment] 2018-07-16 20:47
I'm encountering a similar issue with slurm on ubuntu 18.04, which goes away when nodename matches nodehostname.  Ubuntu is using OpenMPI 2.1.1 (may, 2017) and slurm 17.11.2 (Jan, 2018) so somewhat old and the issue may or may not have been fixed.  

I'm posting here so that an internet searches may save somebody time debugging when they encounter the same problem, not to request any testing or fixes.

**Comment by AnkBurov** [comment] 2019-02-22 14:54
@pkienzle same here. Ubuntu 18.04, Openmpi 2.1.1, the same problem.
