### ISSUE TITLE
comm.spawn not working on cray xe6

### ISSUE THREAD

**Issue by marksantcroos** [open-mpi/ompi#346] opened 2015-01-15 16:28 UTC
Hi @hppritcha,

I have trouble getting spawn working on Hopper.
The example code I use works fine on my laptop of course ;-)

The code that I'm using is similar to [cpi-master.c](https://bitbucket.org/mpi4py/mpi4py/raw/3e694b6c8a84f11b5bab2d45ba99d518f8f528f8/demo/spawning/cpi-master.c) and [cpi-worker.c](https://bitbucket.org/mpi4py/mpi4py/raw/3e694b6c8a84f11b5bab2d45ba99d518f8f528f8/demo/spawning/cpi-worker.c).

Have tried with various configurations of core counts in both launching and spawning, making sure there is enough cores "free" within the allocation.

Whatever I do, spawn() never returns, and I get no errors.
Non-spawn applications work fine with this setup.
This is using the latest ompi from master branch.

Any suggestions on how to get more information?

Thanks!

Mark

**Comment by hppritcha** [comment] 2015-01-15 16:32
I'll take a look.  Actually taking day off today, so may not get far today. Are you using master or 1.8 on hopper?

**Comment by rhc54** [comment] 2015-01-15 16:32
FWIW: OMPI has direct support for MR workloads. I added it several years ago.

**Comment by marksantcroos** [comment] 2015-01-15 16:35
@hppritcha 
Latest and greatest master from git.
Enjoy your day :-)

**Comment by marksantcroos** [comment] 2015-01-15 16:36
@rhc54
Thats good to know.

**Comment by marksantcroos** [comment] 2015-01-15 16:37
@hppritcha 
Btw, if this might be build or config related, I would be happy to rebuild/reconfig with a "known to work setup" from one of you on Edison.

**Comment by hppritcha** [comment] 2015-01-15 18:55
Doubt its that simple.  I'd forgotten that the current config still requires an explicit --with-cray-pmi when building on eslogins running CLE 4.2UP02 or older (ancient ancient stuff, worked on that 2-3 years ago at cray).  I'll fix that.

On edison, you ought to be able to
./autogen.pl
./configure --prefix=my_install_dir
make -j 4 install

and that's it, modulo having the PrgEnv-cray loaded.  On Edison, I make sure PrgEnv-gnu is loaded
before doing the config stage.

**Comment by marksantcroos** [comment] 2015-01-16 00:18
> Doubt its that simple. I'd forgotten that the current config still requires an explicit --with-cray-pmi when building on eslogins running CLE 4.2UP02 or older (ancient ancient stuff, worked on that 2-3 years ago at cray). I'll fix that.

Im not sure if that comment applies to hopper. And whether I parsed it correctly.
Anyway, I tried to build with "cray-pmi" and then I end up with a non-functional installation.

Hopper is down now, so I'll have to wait to try it out there.

In the meanwhile I've been trying on another Cray too (XC30) and there I have similar issues.

**Comment by hppritcha** [comment] 2015-01-16 16:49
Looks like the alps/odls needs to have some smarts about how many times its gotten the GNI rdma credentials.

**Comment by hppritcha** [comment] 2015-01-16 17:06
The alps/odls problem is easy to fix, but after that, things fall apart even with the ugni btl turned off.
Some kind of memory corruption in mca_ess_pmi during MPI_Finalize.

**Comment by rhc54** [comment] 2015-01-16 17:30
Hmmm....I'm not seeing a problem on my machine or on the odin machine (with IB). Must be something specific to the Cray pmix component?

**Comment by hppritcha** [comment] 2015-01-18 22:49
Cray PMI is no longer involved when using mpirun to launch jobs on a cray XE/XC system.  There may be something owing to cray/odls or plm/alps, but nothing to do with cray pmi.

**Comment by marksantcroos** [comment] 2015-01-19 05:44
@hppritcha 
Is there some document describing how OpenMPI is implemented on Cray?
If not, can you give me a minimum description of the components that are supposed to play a role, especially for dynamic process management?

**Comment by hppritcha** [comment] 2015-01-19 16:06
The closest thing to current documentation about Open MPI on Cray is at https://cug.org/proceedings/cug2014_proceedings/includes/files/pap142.pdf .
I've done some significant reworking of the way the launch of the job on the compute nodes is handled so that with mpirun launched jobs, there is no need to use the Cray PMI.  That was where one small problem showed up in reproducing your problem.  However, more significantly for you two things have happened since that paper was written.  One was that the BTL's were moved from OMPI into OPAL.  I suspect something got busted there when uGNI BTL was moved.  Also, some aspects of the job launch have undergone significant changes owing to the introduction of a PMIX MCA component.  There was no regular testing of the spawn feature on Cray while all these changes took place, so now its busted.

The dynamic process management when using MPI_Comm_spawn within an existing reservation is in principle simple.  Since mpirun launches an orte daemon on all nodes in the batch scheduled reservation, regardless of whether or not on the mpirun command line you ask for enough ranks to fill
the reservation, there are slots available for additional ranks when the app calls MPI_Comm_spawn.  This concept of more orted's than required for the job is referred to as the "VM" within the code.  Don't confused this with a real VM!  Anyway, when the app does an MPI_Comm_spawn, it results in an out-of-band message being sent back to mpirun, which then determines where to place the new app in the VM, then sends messages, again out of band, to the orted's where the new app will be fired up.  Then it is very much like just launching the original job.

The launch and run of the worker seems to go fine.  Its something in the app or orted teardown at the end of the job that causes the blowup.

**Comment by rhc54** [comment] 2015-01-19 16:23
FWIW: I’ve tested the master with comm_spawn on several non-Cray machines and it works fine, so this does appear to be something about the Cray support at this time

**Comment by marksantcroos** [comment] 2015-01-19 16:29
While we are at it, build of master (on Cray) is broken now.
I've commented here:
https://github.com/open-mpi/ompi/commit/661c35ca677512129cef9bca1bbbf5b5b71d951b#commitcomment-9342075
Is that the proper way in this project to address these matters or will that never get read?

**Comment by hppritcha** [comment] 2015-01-19 16:38
Commenting on a commit probably won't get very far with this project.
It would be better to open an issue and blame the commit.

The MTT smoke test on edison recently uncovered badness that may be
related to this commit.  See PR #350.

Are you also trying to configure with --enable-mpi-thread-multiple?

Please open an issue about your build problem.

Thanks, hopefully patience will be rewarded.


2015-01-19 9:29 GMT-07:00 Mark Santcroos <notifications@github.com>:

**Comment by marksantcroos** [comment] 2015-01-19 16:41
@hppritcha 
Thanks for the link. I had read that paper earlier, and that is actually what brought me here ;-)
It hasn't a lot of details though.

One other paper [1] I found states "PMI — process manager interface — support is required for systems that provide only a micro-kernel, for which ORTE is not an option."
I guess that is incompatible with your statement about orted. Is that paper outdated/off thus? 

1. [1] G. Vallee, T. Naughton, S. Bohm, and C. Engelmann, “A Runtime Environment for Supporting Research in Resilient HPC System Software & Tools,” Computing and Networking (CANDAR), 2013 First International Symposium on, pp. 213–219, 2013.

**Comment by marksantcroos** [comment] 2015-01-19 16:43
> Commenting on a commit probably won't get very far with this project. It would be better to open an issue and blame the commit.

ACK.

> The MTT smoke test on edison recently uncovered badness that may be related to this commit. See PR #350.

That looks like my problem indeed. FWIW I moved my development to Edison now, to be on a bit more beaten path.

**Comment by hppritcha** [comment] 2015-01-19 18:09
Hmm...  I'm not sure I quite understand what Vallee, etc. meant with that
statement.    I wrote a good portion of the PMI in question,  and know how
it works with other components of the job launch system on Crays.  I'll
take a look at the Vallee paper.

2015-01-19 9:41 GMT-07:00 Mark Santcroos <notifications@github.com>:

**Comment by marksantcroos** [comment] 2015-01-20 04:11
Hi @hppritcha 

Whether it is due to your commits over the last days or not, but I'm able to successfully spawn children on Edison now from a fresh master.

The "teardown problem" you see, is that for very short running children?
I can reproduce that quite reliably. If I add some sleeps to the children then everything finishes correctly.

**Comment by marksantcroos** [comment] 2015-01-21 13:17
Ok, now that I have the spawning working, I actually wanted to do something with the processes (go figure!).

Intra-communication between the children seems to work fine.
However, inter-communication between the children and master seems busted.
I tried send-recv in both directions, bcast, barrier. All with no effect. Dont get any errors either.
(To state the obvious, this code works on non-Cray systems)

How can I go about to debug this further? (given that I dont get any errors ...)

Thanks!

**Comment by hppritcha** [comment] 2015-01-22 03:34
For the child/master communication issue, are you running within a single node, or are you running across multiple nodes?

As for your comment about the "teardown problem" I am using the cpi-master/cpi-worker test case.  Perhaps it is hitting the short child run problem you're seeing.  Still looking in to that.

**Comment by hppritcha** [comment] 2015-01-22 06:25
Well, after a lot of struggling with stuff in the show_help part of orte when the rlm/routed/proc info stuff not being set up when the show_help method is being called, finally got a spawn run in.  Somehow I'd thought that when using a single node, that the vader BTL could be used for spawned processes, but apparently not.

If you launch your job with

mpirun --mca btl self,vader,tcp .....

does the communication work?

**Comment by hppritcha** [comment] 2015-01-22 07:01
Okay,  found a problem with the ugni btl, or maybe something wrong with the OPAL_MODEX stuff,
not sure which.  Anyway, apply the patch at

https://gist.github.com/hppritcha/0314f18d65e66ff1df76

and see if that gets your test to work with

mpirun --mca btl self,vader,ugni

The simple cpi-master/cpi-worker does to master/slave communication, and its passing for me now on
one node at least with this patch.

**Comment by marksantcroos** [comment] 2015-01-22 08:16
> For the child/master communication issue, are you running within a single node, or are you running across multiple nodes?

Both.

> As for your comment about the "teardown problem" I am using the cpi-master/cpi-worker test case. Perhaps it is hitting the short child run problem you're seeing. Still looking in to that.

ACK.

> If you launch your job with
> 
> mpirun --mca btl self,vader,tcp .....
> 
> does the communication work?

Yes!


> Anyway, apply the patch at
> 
> https://gist.github.com/hppritcha/0314f18d65e66ff1df76
> 
> and see if that gets your test to work with
> 
> mpirun --mca btl self,vader,ugni

Compiling now, will report back on that.

**Comment by marksantcroos** [comment] 2015-01-22 08:20
> If you launch your job with
> 
>     mpirun --mca btl self,vader,tcp .....
> 
>     does the communication work?
> 
> Yes!

Though only within a single node, if I run it on more than one I get:

```
[nid05981][[8137,2],0][../../../../../opal/mca/btl/tcp/btl_tcp_endpoint.c:811:mca_btl_tcp_endpoint_complete_connect] connect() to 128.55.34.21 failed: Connection refused (111)
[nid00973][[8137,2],1][../../../../../opal/mca/btl/tcp/btl_tcp_endpoint.c:811:mca_btl_tcp_endpoint_complete_connect] connect() to 128.55.34.25 failed: Connection refused (111)
```

But maybe that is expected?

**Comment by marksantcroos** [comment] 2015-01-22 09:06
> Anyway, apply the patch at
> 
>     https://gist.github.com/hppritcha/0314f18d65e66ff1df76
> 
>     and see if that gets your test to work with
> 
>     mpirun --mca btl self,vader,ugni
> 
> Compiling now, will report back on that.

Great! With the patch it also works on multi-node!
(And I dont need to specify any mca parameters to make it work either)

**Comment by marksantcroos** [comment] 2015-01-22 21:09
@hppritcha 
I pulled in your latest changes that included the modified patch and that works fine for me too.
Additionally, even with removing the sleeps, I didn't manage to trigger the hanging teardown.

**Comment by marksantcroos** [comment] 2015-01-22 21:19
@hppritcha, @rhc54 

So, thanks very much so far! AFAIK I'm all set on this issue and am happy to consider this ticket closed.

**Comment by hppritcha** [comment] 2015-01-23 02:01
Looks like 4de512a addressed the current issues.  So closing this bug.  Need to make sure spawn is covered in the MTT smoke tests on edison though.

**Closed by hppritcha** 2015-01-23 02:01 UTC
