### ISSUE TITLE
spack gcc install fails for openmpi@4.0.0 

### ISSUE THREAD

**Issue by hightower8083** [open-mpi/ompi#6105] opened 2018-11-23 10:53 UTC
Spack installation 
```
spack install -v openmpi@4.0.0 %gcc@5.5
```
fails for `gcc@5.5` and `gcc@5.3`. 
The error message is:
```
Making all in mpi/fortran/mpiext-use-mpi
make[2]: Entering directory `/tmp/user/spack-stage/spack-stage-hha2r68p/openmpi-4.0.0/ompi/mpi/fortran/mpiext-use-mpi'
  PPFC     mpi-ext-module.lo
mpi-ext-module.F90:29:132:

       include '/home/user/src/spack/var/spack/stage/openmpi-4.0.0-unyxc2ryo7zedsnvqwjx6spiia6vs6j5/openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h'
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
mpi-ext-module.F90:29:6:

       include '/home/user/src/spack/var/spack/stage/openmpi-4.0.0-unyxc2ryo7zedsnvqwjx6spiia6vs6j5/openmpi-4.0.0/ompi/mpiext/pcollreq/mpif-h/mpiext_pcollreq_mpifh.h'
      1
Error: Unclassifiable statement at (1)
```

Reproduced at OS RedHat 7.3, CentOS 7 and ubuntu16.04

**Comment by ggouaillardet** [comment] 2018-11-25 23:50
Duplicate of #6106

**Comment by jsquyres** [comment] 2018-11-26 23:02
Even though this issue was filed first, we'll follow up on #6106.

**Closed by jsquyres** 2018-11-26 23:02 UTC
