### ISSUE TITLE
Incorrect binding

### ISSUE THREAD

**Issue by rzambre** [open-mpi/ompi#11589] opened 2023-04-12 23:31 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

`main` branch pointing to 3676f54598.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

../../../configure --prefix=/path/to/install --with-ucx=/path/to/ucx --without-verbs --disable-man-pages --with-pmix=internal --with-hwloc=internal --enable-mpi-fortran=no --enable-oshmem-fortran=no

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

 7d25bd021b57d4e3cea40d23bd3662180c269827 3rd-party/openpmix (v1.1.3-3825-g7d25bd02)
 4725d89abe53c52343eeb49c90986c4d407d6392 3rd-party/prrte (psrvr-v2.0.0rc1-4609-g4725d89abe)
 3b9e6e346d6d807ca820fbfb5e86734136f4889b config/oac (heads/main)

### Please describe the system on which you are running

HPCAC cluster helios partition

* Operating system/version: Linux
* Computer hardware: x86 CPU
* Network type: IB

-----------------------------

## Details of the problem

Binding PEs to specific cores seems to work incorrectly. I'd like to bind my PE to a core of the second socket since that my NIC of interest is attached to it.

These two fail (my usage may be incorrect, but I can't seem to figure out what the correct usage would be):

```
[rzambre@thor001 ~]$ oshrun -n 2 -N 1 --map-by pe-list=31 --host thor001,thor002 --report-bindings hostname
--------------------------------------------------------------------------
When resolving deprecated command line options, the result generated
too many directives for the target option:

  Command line option: map-by
  Initial value: pe-list=31
  Deprecated option: N ppr:1:node

Please correct the command line and try again.
--------------------------------------------------------------------------

[thor001.hpcadvisorycouncil.com:952945] PRTE ERROR: Out of resource in file ../../../../../../../../3rd-party/prrte/src/mca/rmaps/base/rmaps_base_binding.c at line 434
```

```
[rzambre@thor001 ~]$ oshrun -n 2 --map-by pe-list=31 --host thor001,thor002 --report-bindings hostname
[thor001.hpcadvisorycouncil.com:952981] PRTE ERROR: Out of resource in file ../../../../../../../../3rd-party/prrte/src/mca/rmaps/base/rmaps_base_binding.c at line 434
```

This works, but the binding is incorrect on PE 0:

```
[rzambre@thor001 ~]$ oshrun -n 2 --map-by pe-list=30,31 --host thor001,thor002 --report-bindings hostname
[thor001.hpcadvisorycouncil.com:952990] Rank 0 bound to package[1][core:29,31]
thor001.hpcadvisorycouncil.com
[thor002.hpcadvisorycouncil.com:89496] Rank 1 bound to package[1][core:31]
thor002.hpcadvisorycouncil.com
```

**Comment by rhc54** [comment] 2023-04-12 23:54
The error message is unfortunately terse, but the problem is right here:
```text
-n 2 --map-by pe-list=31
```
You are telling us to map two processes onto a single cpu, which is an overloaded situation. If you want us to ignore the overload, then you need to tell us to do so by adding `--bind-to :overload` to the cmd line. I doubt you really want to do that, though - I suspect you should bind each proc to a separate cpu, but that's up to you.

**Comment by rzambre** [comment] 2023-04-12 23:59
> You are telling us to map two processes onto a single cpu, which is an overloaded situation.

Yes, I agree.

I want to spawn 2 processes with 1 process per node, and with each process bound to the same core (31) on each node. How can I achieve that?

**Comment by rhc54** [comment] 2023-04-12 23:59
I suspect the submodules on OMPI main are out-of-date, but with this cmd line:
```text
-n 2 --map-by pe-list=30,31
```
I get the following map:
```text
        Data for proc: [prterun-Ralphs-iMac-2-52736@1,0]
                Pid: 0	Local rank: 0	Node rank: 0	App rank: 0
                State: INITIALIZED	App_context: 0
        	Binding: package[1][core:30-31]
        Data for proc: [prterun-Ralphs-iMac-2-52736@1,1]
                Pid: 0	Local rank: 1	Node rank: 1	App rank: 1
                State: INITIALIZED	App_context: 0
        	Binding: package[1][core:30-31]
```
which is correct. If you want each proc bound to one of the specified cpus, then you need to modify your cmd line:
```text
-n 2 --map-by pe-list=30,31:ordered
```
which yields the following map:
```text
        Data for proc: [prterun-Ralphs-iMac-2-52758@1,0]
                Pid: 0	Local rank: 0	Node rank: 0	App rank: 0
                State: INITIALIZED	App_context: 0
        	Binding: package[1][core:30]
        Data for proc: [prterun-Ralphs-iMac-2-52758@1,1]
                Pid: 0	Local rank: 1	Node rank: 1	App rank: 1
                State: INITIALIZED	App_context: 0
        	Binding: package[1][core:31]
```

**Comment by rhc54** [comment] 2023-04-13 00:04
> I want to spawn 2 processes with 1 process per node, and with each process bound to the same core (31) on each node. 

There does appear to be an issue in PRRTE with that cmd, so I'll have to take a look at it.

**Comment by rhc54** [comment] 2023-04-13 03:15
Fixed in PRRTE master [here](https://github.com/openpmix/prrte/pull/1733)

**Comment by rzambre** [comment] 2023-04-14 16:56
Thanks! I attempted to try prrte main yesterday but ran into build issues that I have not looked further into yet. If you'd like to close this issue, please go ahead.

**Closed** 2023-04-19 18:46 UTC
