### ISSUE TITLE
"Socket closed" messages from TCP BTL

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#5849] opened 2018-10-05 15:25 UTC
Cisco MTT is getting a lot of "Socket closed" messages from the TCP BTL.

For example: https://mtt.open-mpi.org/index.php?do_redir=2762

That message appears to come from here:

https://github.com/open-mpi/ompi/blob/5f1c940c8b252763b9714f5a3b813b3bf2847479/opal/mca/btl/tcp/btl_tcp_endpoint.c#L542-L558

I don't know if this is an actual error (that the user should be informed about) or a "it's ok, we'll just ignore it and move on to the next interface in the list" kind of issue (that could probably only be reported with a high enough verbosity).  Regardless, "Socket closed" is probably not enough of a detailed message to convey meaningful information to the end user.  😄 

I don't know if this is related to https://github.com/open-mpi/ompi/issues/3035 or https://github.com/open-mpi/ompi/issues/5818, but it's worth cross-referencing them here.

**Comment by bwbarrett** [comment] 2018-10-11 01:39
https://github.com/open-mpi/ompi/pull/5892 is a workaround for this problem.  This is unrelated to  #3035 or #5818 and only happens on master.

Jeff actually got the code slightly wrong.  The issue is on the next line down, where the BTL calls back to the PML with the disconnect.  OB1 just aborts the job on an error callback, but in this case, the callback is fired because readv() returned 0 because the other side was in MPI_FINALIZE and shut down the socket.

**Comment by bwbarrett** [comment] 2018-10-18 17:49
Based on MTT results, da1189d77142df412592fb815cb59f688028e528 (which reverted 6acebc4) fixed the test failures.  Since there are open issues for all the other issues we're seeing, I'm going to close this ticket.

**Closed by bwbarrett** 2018-10-18 17:49 UTC
Labels: Target: master, bug
