### ISSUE TITLE
4.1.1: test suite is failing in partial unit

### ISSUE THREAD

**Issue by kloczek** [open-mpi/ompi#8863] opened 2021-04-27 08:30 UTC
Linux x86_64, gcc 11.0.1, OpenMPI compiled with LTOP optimisation.
Content of the test/datatype/test-suite.log:
```
=====================================================
   Open MPI gitclone: test/datatype/test-suite.log
=====================================================

# TOTAL: 13
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: partial
=============

[barrel:2477002] Datatype 0x5638600ade80[] id -1 size 96 align 8 opal_id 0 length 4 used 3
true_lb 0 true_ub 160 (true_extent 160) lb 0 ub 160 (extent 160)
nbElems 12 loops 2 flags 104 (committed )-c-----GD--[---][---]
   contain OPAL_FLOAT8:*
-------G---[---][---]    OPAL_LOOP_S 2 times the next 2 elements extent 80
--C---P-D--[---][---]    OPAL_FLOAT8 count 3 disp 0x0 (0) blen 2 extent 32 (size 48)
-------G---[---][---]    OPAL_LOOP_E prev 2 elements first elem displacement 0 size of data 48
-------G---[---][---]    OPAL_LOOP_E prev 3 elements first elem displacement 0 size of data 96
Optimized description
--C---P-D--[---][---]    OPAL_FLOAT8 count 3 disp 0x0 (0) blen 2 extent 32 (size 48)
--C---P-D--[---][---]    OPAL_FLOAT8 count 3 disp 0x50 (80) blen 2 extent 32 (size 48)
-------G---[---][---]    OPAL_LOOP_E prev 2 elements first elem displacement 0 size of data 96




Error during check for the 4 element, length 56 (chunk 28)
Error at position 4 [0:0:2:0] found 4.68375e-310 expected 0


0x5638600a2070:   0    1    0    1   <4.68375e-310>   4.68375e-310    0    4.68375e-310
            : 0000000000000000 000000000000fffffff03f 0000000000000000 000000000000fffffff03f  <60fffffffe096038560000> ffffff90fffffffe096038560000 0000000000000000 60ffff
ffff096038560000

FAIL partial (exit status: 255)
```
From the config.log file:
`$ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --disable-silent-rules --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --runstatedir=/run --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-builtin-atomics --enable-memchecker --enable-mpi1-compatibility --enable-mpi-cxx --enable-mpi-java --sysconfdir=/etc/openmpi --with-hwloc=/usr --with-libevent=external --with-pmix=external --enable-ipv6 --with-sge --with-valgrind`

Please let me know if may need other details.

**Comment by gpaulsen** [comment] 2021-04-27 14:39
Thanks for reporting.  This is a duplicate of https://github.com/open-mpi/ompi/issues/8856, so we'll close this, and track it there, however your data will be visible from that issue, and is useful for reproducing / fixing.

**Closed by gpaulsen** 2021-04-27 14:39 UTC
