### ISSUE TITLE
MPI_Status_f082f not part of the mpi_f08 interface

### ISSUE THREAD

**Issue by aradi** [open-mpi/ompi#12587] opened 2024-05-29 16:01 UTC
### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)

v5.0.3

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built official 5.0.3 tarball.

### Please describe the system on which you are running

* Operating system/version:
x86_64/Linux (Fedora 40)
* Computer hardware: X86_64
* Network type: not relevant for the problem

-----------------------------

## Details of the problem

Following minimal Fortran working example fails to compile with OpenMPI 5.0.3:

```fortran
program test_mpistatus
  ! use mpi_f08
  use mpi_f08, only : MPI_Init, MPI_Finalize, MPI_Status, MPI_Status_f082f, MPI_STATUS_SIZE
  implicit none

  type(MPI_Status) :: mpistat_f08
  integer :: mpistat_f90(MPI_STATUS_SIZE)

  call MPI_Init()
  call MPI_Status_f082f(mpistat_f08, mpistat_f90)
  call MPI_Finalize()

end program test_mpistatus
```
with following error message
```
/home/aradi/test-mpistatus.f90:3:57:

    3 |   use mpi_f08, only : MPI_Init, MPI_Finalize, MPI_Status, MPI_Status_f082f, MPI_STATUS_SIZE
      |                                                         1
Error: Symbol ‘mpi_status_f082f’ referenced at (1) not found in module ‘mpi_f08’
```
Interestingly, using just `use mpi_f08` without the `only` clause works. However, that is not a valid workaround, as Fortran would not know the subroutine signature at compile time. Consequently, no type checking would be carried out. Also, leaving away the optional error argument might cause segfaults in that case with certain compilers.

**Comment by hppritcha** [comment] 2024-05-29 17:54
i cannot reproduce this.  I'm using gfortran 8.5.0.  Which fortran compiler are you using?

**Comment by aradi** [comment] 2024-05-29 19:13
```
mpifort --version
GNU Fortran (GCC) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Oh, that is interesting. Do you really mean, gfortran 8.5.0? Just, because I am somewhat unsure, whether gfortran 8.5 implements the Fortran 2008 constructs  `type(*)` and `dimension(..)`, which are in theory necessary for the `mpi_f08` interface. (But I could be wrong about this.)

**Comment by bosilca** [comment] 2024-05-29 19:51
I can't replicate either
```
mpifort --version
GNU Fortran (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)
```

Can you find your OMPI libraries and send back the output of `nm libmpi_usempif08.so | grep -i MPI_Status_`

**Comment by hppritcha** [comment] 2024-05-29 20:28
unfortunately Open MPI currently does not know about assumed rank fortran option.  we're still at assumed shape.  hopefully this will be fixed soon.

**Comment by aradi** [comment] 2024-05-30 08:58
@bosilca Sure, I obtain following output
```
nm libmpi_usempif08.so | grep -i MPI_Status_
00000000000233db T mpi_status_f082f_f08_
0000000000023419 T mpi_status_f2f08_f08_
0000000000023457 T mpi_status_set_cancelled_f08_
0000000000023495 T mpi_status_set_elements_f08_
00000000000234d8 T mpi_status_set_elements_x_f08_
                 U ompi_status_f082f_f
                 U ompi_status_f2f08_f
                 U ompi_status_set_elements_f
                 U ompi_status_set_elements_x_f
0000000000030533 T pmpi_status_f082f_f08_
0000000000030571 T pmpi_status_f2f08_f08_
                 U pmpi_status_set_cancelled_
00000000000305af T pmpi_status_set_cancelled_f08_
00000000000305ed T pmpi_status_set_elements_f08_
0000000000030630 T pmpi_status_set_elements_x_f08_
```
But, please note, that the problem is not, that the routine is not part of the library; the problem is, that the routine is not  part of the `mpi_f08` Fortran module. I get compilation error, not a linking error. If I replace
```
use mpi_f08, only : ..., MPI_Status_f082f, ...
```
with
```
use mpi_f08
```
the code compiles (but for the wrong reason):
* In the former case, the compiler explicitly checks the `mpi_f08.mod` module file (generated during the build of OpenMPI) whether it contains information about the signature of the `MPI_Status_f082f()` routine. And it fails, because it is not found.
* In the latter case, the module file is also checked and the signature is not found either, but the compiler is allowed then to assume, that `MPI_Status_f082f()` is an arbitrary external routine with unknown signature. The compiler builds the program then, but no checking of argument number or types is done, you just hope for the best. You can test it yourself: use `use mpi_f08` without the `only` clause and remove one of the arguments in the call to `MPI_Status_f08`. The code will still happily compile (and then very likely crash on execution).

**Comment by hppritcha** [comment] 2024-05-30 15:46
another thing to check is the mpi_f08.mod.  Its actually just gzipped text in the case of the gnu compiler.
When I gunzip the module file generated by gfortran 8.5.0 i see an entry of this form
```
4952 'mpi_status_f082f' 'mpi_f08_interfaces' '' 1 ((PROCEDURE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN UNKNOWN 0 0 SUBROUTINE GENERIC
ARRAY_OUTER_DEPENDENCY) () (UNKNOWN 0 0 0 0 UNKNOWN ()) 0 0 () () 0 () ()
() 0 0)
```

**Comment by aradi** [comment] 2024-05-30 15:54
@hppritcha That's a good point. I've checked it and
```
zcat mpi_f08.mod | grep -i mpi_status_f082f
```
is empty.

**Comment by aradi** [comment] 2024-05-30 16:04
Just one more info, I am using the `--enable-mpi1-compatibility` configure option. Could that make a difference?

**Comment by bosilca** [comment] 2024-05-30 16:33
MPI1 compatibility should not remove this API, it only adds back some deprecated API. However, the inclusion of the `status_f08` accessors is driven by `OMPI_FORTRAN_HAVE_TYPE_MPI_STATUS`, which is detected during configure by the macro `OMPI_FORTRAN_CHECK_BIND_C_TYPE_NAME`. This macro tries to detect if the compiler supports `TYPE(...), BIND(C, NAME=...)`, and apparently your compiler fails this test. Can you please check in your config.log for 'if Fortran compiler supports` to see why the test failed.

**Comment by hppritcha** [comment] 2024-05-30 20:02
uh oh.  i forgot i was testing on our main branch.  there seems to be a problem with 5.0.3.  checking if its fixed in the 5.0.x branch.  i can reproduce this issue using the gcc 13.2.0 and ompi 5.0.3

**Comment by hppritcha** [comment] 2024-05-30 20:46
this seems to not be fixed on 5.0.x branch

**Comment by hppritcha** [comment] 2024-05-30 21:19
looks like 83eb116f88f190c33ac6ddc67b8959fabc07d356 was not cherry picked back to v5.0.x

**Comment by janjust** [comment] 2024-06-10 19:35
change backported - closing

**Closed by janjust** 2024-06-10 19:35 UTC
Labels: bug, fortran bindings, Target: v5.0.x
