### ISSUE TITLE
New PRRTE/PMIX breaks -- and --mca

### ISSUE THREAD

**Issue by bosilca** [open-mpi/ompi#12153] opened 2023-12-08 04:54 UTC
mpirun converts all arguments removing `--` (which is supposed to mean "stop processing and pass to the next"). Also, all `--mca` prefixed arguments, even those that are not meant for PMIX (because they are located on the other side of the application to be executed) get converted to meaningless strings.

Example
`mpirun -n 1 ./a.out -x -y -- --mca donttouch gotya`
gets converted into 
` ./a.out -x -y --pmixmca donttouch gotya`

and 
`mpirun -n 1 ./a.out -x -y --mca donttouch gotya` (note `--` has been removed)
gets converted into the same
` ./a.out -x -y --pmixmca donttouch gotya`

**Comment by rhc54** [comment] 2023-12-08 12:39
I wasn't able to completely reproduce those results - I can't get the MCA option to the application to get converted to a `--pmixmca`. However, I fixed a few places where we explicitly need to stop at the `--` delineator. Now seeing this:
```shell
$ prterun -n 1 ./clichk -x -y -- --mca donttouch gotya
CMDLINE: ./clichk -x -y -- --mca donttouch gotya

$ prterun -n 1 ./clichk -x -y --mca donttouch gotya
CMDLINE: ./clichk -x -y --mca donttouch gotya
```
Please note that the `mpirun` cmd line is the responsibility of the OMPI community. I did go ahead and add similar stop code to where you do some cmd line conversion to get this:
```shell
$ prterun -n 1 --personality ompi ./clichk -x -y -- --mca donttouch gotya
CMDLINE: ./clichk -x -y -- --mca donttouch gotya

$ prterun -n 1 --personality ompi ./clichk -x -y --mca donttouch gotya
CMDLINE: ./clichk -x -y --mca donttouch gotya
```
I have no idea where the conversion to `pmixmca` was coming from - as I say, I cannot reproduce it here, even without the patch I created.

My patch is here: https://github.com/openpmix/prrte/pull/1886. Will be transferred to the release branch.

**Comment by bosilca** [comment] 2023-12-08 16:08
Unfortunately I updated all my branches to the current OMPI HEAD and I cannot replicate the `pmixmca` part anymore. The `--` is however removed in all cases. 

Thanks @rhc54 for your patch, with it everything looks good.

**Comment by janjust** [comment] 2023-12-12 16:10
fixed with submodule updates

**Closed by janjust** 2023-12-12 16:10 UTC
Labels: bug
