### ISSUE TITLE
Libfabric link error when using openmpi master

### ISSUE THREAD

**Issue by rashikakheria** [open-mpi/ompi#6360] opened 2019-02-05 20:27 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
```
ubuntu@ip-10-0-1-51:~/ompi$ git log -1 |head -1
commit ea40d488993e3f1be8b7de943f4a751cfcfe37a6
```

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Using clone

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04 LTS

-----------------------------

## Details of the problem

mca_mtl_ofi.so is unable to link against libfabric.so even when built using --with-ofi flag.

```
ubuntu@ip-10-0-1-51:~/ompi$ git log -1 |head -1
commit ea40d488993e3f1be8b7de943f4a751cfcfe37a6
ubuntu@ip-10-0-1-51:~/ompi$ head config.log |grep -e "./configure"
  $ ./configure --with-ofi --prefix=/home/ubuntu/ompi/install
ubuntu@ip-10-0-1-51:~/ompi$ ldd ./install/lib/openmpi/mca_mtl_ofi.so
	linux-vdso.so.1 =>  (0x00007ffd4cd68000)
	libmpi.so.0 => /home/ubuntu/ompi/install/lib/libmpi.so.0 (0x00007f14f1e0d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f14f1bf0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f14f1826000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f14f2335000)
	libopen-rte.so.0 => /home/ubuntu/ompi/install/lib/libopen-rte.so.0 (0x00007f14f156d000)
	libopen-pal.so.0 => /home/ubuntu/ompi/install/lib/libopen-pal.so.0 (0x00007f14f1259000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f14f1051000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f14f0d48000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f14f0b44000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f14f0941000)
```

@jsquyres Here are the outputs you requested: https://gist.github.com/rashikakheria/c07a6ef78806a8a81b729b19c0855019

**Comment by matcabral** [comment] 2019-02-05 23:38
@jsquyres , I don't think we need two different issues since they are essentially for the same issue. Lets just close one of them.

**Comment by ggouaillardet** [comment] 2019-02-06 00:15
@rashikakheria Did you manually patch Open MPI with https://github.com/open-mpi/ompi/pull/6313.patch ? If not, try it first (note you need recent autotools).

**Comment by matcabral** [comment] 2019-02-06 00:30
@ggouaillardet, I am not able to reproduce the issue  in "Ubuntu 16.04.5 LTS" without applying the patch with master "as is". I'm inspecting the logs to see what the diff may be, so far I have not seen anything evident.

**Comment by matcabral** [comment] 2019-02-06 01:12
I see you have libtool  "2.4.6 Debian-2.4.6-0.1"  while mine is just GNU 2.4.6. Where are you getting yours from? I wonder is Debian is adding some spices in there.

**Comment by ggouaillardet** [comment] 2019-02-06 01:18
with latest master (well, I had to patch it because `VPATH` does not work, and I will issue a separate PR)
I can reproduce the issue.

Note I installed `libfabric` in my home directory and __not__ in `/usr`, not sure if that makes a difference.

```
$ libtoolize --version
libtoolize (GNU libtool) 2.4.6
Written by Gary V. Vaughan <gary@gnu.org>, 2003

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
gilles@ubuntu:~/build/ompi$ ./libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
gilles@ubuntu:~/build/ompi$ ldd ~/local/ompi/lib/libmca_common_ofi.so
	linux-vdso.so.1 =>  (0x00007ffdb9f64000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe663964000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe66359a000)
	/lib64/ld-linux-x86-64.so.2 (0x000056106a0e1000)
gilles@ubuntu:~/build/ompi$ ldd ~/local/ompi/lib/openmpi/mca_mtl_ofi.so 
	linux-vdso.so.1 =>  (0x00007ffe37f9a000)
	libmpi.so.0 => /home/gilles/local/ompi/lib/libmpi.so.0 (0x00007f8a648aa000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8a64686000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8a642bc000)
	/lib64/ld-linux-x86-64.so.2 (0x000055af4f02e000)
	libopen-rte.so.0 => /home/gilles/local/ompi/lib/libopen-rte.so.0 (0x00007f8a63f9b000)
	libopen-pal.so.0 => /home/gilles/local/ompi/lib/libopen-pal.so.0 (0x00007f8a63c2f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8a63a27000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8a6371d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8a63519000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8a63316000)
```

**Comment by jsquyres** [comment] 2019-02-06 01:20
Ok hold on here, are we working on this issue or #2519?  I thought @matcabral said we were working on #2519...?

**Comment by ggouaillardet** [comment] 2019-02-06 01:22
I am __not__ working on this.

I suggested #2519 as a temporary workaround (that worked for me) and I am double checking it works for me.

**Comment by jsquyres** [comment] 2019-02-06 01:32
Ok, thanks.  Let's close this issue and work on #2519.  There's a link from #2519 to here, so all this content isn't lost.

But let's keep all the followups in a single place (sorry, I suggested moving to a separate issue, but @matcabral feels that this *isn't* a separate issue -- so let's keep all the discussion over there).

**Closed by jsquyres** 2019-02-06 01:32 UTC
