### ISSUE TITLE
`./configure --disable-wrapper-rpath` does nothing

### ISSUE THREAD

**Issue by NAThompson** [open-mpi/ompi#521] opened 2015-04-11 16:38 UTC
Found this trying to distribute binaries. My own directory is hard-coded into RPATH even using `--disable-wrapper-rpath`:

Full build sequence:

     ./autogen.pl; make distclean; make clean; ./configure --prefix=/home/nthompson/openmpi --enable-mpi-thread-multiple --with-threads=posix --disable-wrapper-rpath && make -j6 && make install

Now to verify that this didn't disable the RPATH:

    readelf --dynamic /home/nthompson/openmpi/lib/libmpi.so
    Dynamic section at offset 0xc2f38 contains 33 entries:
    Tag        Type                         Name/Value
     0x0000000000000001 (NEEDED)             Shared library: [libopen-rte.so.7]
     0x0000000000000001 (NEEDED)             Shared library: [libopen-pal.so.6]
     0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
     0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
     0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
     0x0000000000000001 (NEEDED)             Shared library: [libutil.so.1]
     0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
     0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
     0x000000000000000e (SONAME)             Library soname: [libmpi.so.1]
     0x000000000000000f (RPATH)              Library rpath: [/home/nthompson/openmpi/lib]

**Comment by rhc54** [comment] 2015-04-11 18:22
what version is this with - master? or 1.8.x?

**Comment by NAThompson** [comment] 2015-04-11 21:38
I tried it on master, then switched to branch 1.7. It was present in both. `gcc -v` is 4.8; CentOS 7.

**Comment by miked-mellanox** [comment] 2015-04-12 05:40
same issue on v1.8 as well.

**Comment by jsquyres** [comment] 2015-04-14 18:32
This is intended behavior.  Open MPI uses rpath in its libraries; there is no option to turn it off.  This is mainly to make it easier to find libmpi's dependent libraries (especially if they are not in the same dir as libmpi).

`--disable-wrapper-rpath` disables the specification of the rpath/runpath arguments from the wrapper compilers (i.e., mpicc and friends).  In short: this switch controls the rpath/runpath behavior in executables generated by the wrapper compilers.

For example:

```shell
# An OMPI build with --disable-wrapper-rpath
$ mpicc --showme
gcc -I/home/jsquyres/bogus/include -pthread -Wl,-rpath -Wl,/home/jsquyres/bogus/lib -Wl,--enable-new-dtags -L/home/jsquyres/bogus/lib -lmpi

# An OMPI build without --disable-wrapper-rpath (or --enable-wrapper-rpath)
$ mpicc --showme
gcc -I/home/jsquyres/bogus/include -pthread -L/home/jsquyres/bogus/lib -lmpi
```

See https://github.com/open-mpi/ompi/blob/master/README#L775-L811 for details.

That same section of the README also explains how to override rpath/runpath defaults (in short: set LD_LIBRARY_PATH on the target system).

We don't really have any plans to make rpath/runpath behavior disable-able in OMPI's libraries.  Is there a specific use case / problem you're trying to solve that can't be addressed via setting LD_LIBRARY_PATH on the target system?

**Comment by NAThompson** [comment] 2015-04-14 20:38
Forcing users to edit the `LD_LIBRARY_PATH` is annoying to them; and anyone can edit it, making the `mpi.so` which is picked up indeterminate. But in any case,  I'll just use `patchelf --replace-rpath $ORIGIN` to get around this.

**Comment by jsquyres** [comment] 2015-04-14 20:47
I think you're falling into the tiny minority of our users.  :-(

The vast majority of our users are happy with a single installation location, and therefore the same "forcing them to edit `LD_LIBRARY_PATH` is annoying" rationale applies: they just want OMPI to work in the single location where it is installed.  So using rpath/runpath (to pick up dependent libraries) is a good idea.

Moving libraries after installation is always a bit dicey; frobbing `LD_LIBRARY_PATH` is one way to make it work, `patchelf` is another.  That being said, unless the original dir exists on the target system, having the rpath/runpath set in libmpi.so isn't harmful; the non-existent directory will simply be skipped.  I've seen packagers install into a tempdir (e.g., /tmp/b3234jlk23jd) to "guarantee" that it won't exist on the target system.  Shrug.

I'll close this issue since you have a workaround.  Let us know if you find any other issues; thanks.

**Closed by jsquyres** 2015-04-14 20:47 UTC
Labels: bug
