### ISSUE TITLE
MPI-IO : file_get_offset and others fail in MTT

### ISSUE THREAD

**Issue by sjeaugey** [open-mpi/ompi#2828] opened 2017-01-25 18:03 UTC
Many MPI-IO tests are crashing this morning on MTT :

https://mtt.open-mpi.org/index.php?do_redir=2384

Assigning Edgar as a best guess after looking at the git backlog.

**Comment by edgargabriel** [comment] 2017-01-25 19:02
I am fairly confident, that the problems were caused by the same thing that I worked on yesterday, and it should be fixed by pr #2800 . I could just not merge that fix into master because travis didn't finish before I went to bed. I will look out for it however tomorrow, and see if the problems are gone.

**Comment by sjeaugey** [comment] 2017-01-25 19:04
No problem, just wanted to make sure you saw it that. If that's no longer on MTT tomorrow you can close it.

**Comment by edgargabriel** [comment] 2017-01-26 14:27
@sjeaugey  if I read the MTT output correctly, the problems are indeed gone with the new nightly snapshot. Will close this issue.

**Closed by edgargabriel** 2017-01-26 14:27 UTC
