### ISSUE TITLE
Atest iallgather wrong result

### ISSUE THREAD

**Issue by karasevb** [open-mpi/ompi#9884] opened 2022-01-18 11:49 UTC
## Background information
The issue reproduces on a single node for 2 procs with vader btl. 

I've checked for following versions:
v4.1.x  commit: open-mpi/ompi@5ef48ea
master commit: open-mpi/ompi@9704f0f

OMPI built with no  `./configure` extra args except `--prefix`.

Example:
Failed for the vader btl:

```BASH
$mpirun -np 2 --report-bindings --map-by slot -mca pml ob1 -mca btl self,vader -mca coll '^hcoll' atest     -r 1 --test-correctness 1 -t 'Iallgather-*-packed' -e 1000 --test-cross 0 --test-maxcomm 0 --test-noise 0     --test-slow 0 -r 1000
[jazz07:128751] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././././.][./././././././././././././.]
[jazz07:128751] MCW rank 1 bound to socket 0[core 1[hwt 0]]: [./B/./././././././././././.][./././././././././././././.]
atest: ver. 2.1.1

        test_name   coll_op            datatype        op                          comm    num_el      root        np    time (us)      slow     noise    status       init_val                        result               expected_result                                                                                             fail_msg

================================================================================================================================================================================================================================================================================================================================================

  test_iallgatheriallgather              packed       n/a                MPI_COMM_WORLD      1000         0         2            0       OFF       OFF      FAIL      Ai=i(r+1)                           N/A                           N/A                                         tests/iallgather.c:244 - atest_compare_arrays returned false
  test_iallgatheriallgather              packed       n/a                MPI_COMM_WORLD      1000         0         2            0       OFF       OFF      FAIL      Ai=i(r+1)                           N/A                           N/A                                         tests/iallgather.c:244 - atest_compare_arrays returned false

      comm_size  avg_time (us)      num_comms
=============================================

Total tests:                    1000
Total tests exec time (secs):   30
Total failed:                   2
Total success:                  998

Test environment:               n/a
```

And cannot reproduce with btl tcp;
```BASH
$mpirun -np 2 --report-bindings --map-by node -mca pml ob1 -mca btl self,tcp --mca btl_tcp_if_include ib0 -mca coll '^hcoll' atest     -r 1 --test-correctness 1 -t 'Iallgather-*-packed' -e 1000 --test-cross 0 --test-maxcomm 0 --test-noise 0     --test-slow 0 -r 1000
[jazz07:129371] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././././.][./././././././././././././.]
[jazz23:79833] MCW rank 1 bound to socket 0[core 0[hwt 0]]: [B/././././././././././././.][./././././././././././././.]
atest: ver. 2.1.1

        test_name   coll_op            datatype        op                          comm    num_el      root        np    time (us)      slow     noise    status       init_val                        result               expected_result                                                                                             fail_msg

================================================================================================================================================================================================================================================================================================================================================


      comm_size  avg_time (us)      num_comms
=============================================

Total tests:                    1000
Total tests exec time (secs):   54
Total failed:                   0
Total success:                  1000

Test environment:               n/a
```

**Comment by jsquyres** [comment] 2022-01-18 16:38
@karasevb Can you post a small reproducer here on this issue?

**Comment by karasevb** [comment] 2022-01-21 06:28
This issue stops reproducing with certain conditions. I will update.

**Comment by jsquyres** [comment] 2022-03-07 20:20
@karasevb It's been a while since you've commented here -- is this still an issue?

**Comment by brminich** [comment] 2022-03-08 14:35
@jsquyres, the issue can't be reproduced anymore, so closing this issue

**Closed by brminich** 2022-03-08 14:35 UTC
Labels: bug, Target: master, Target: v5.0.x, Target: v4.1.x
