### ISSUE TITLE
2.0.0rc2: Regression in MPI_Type_get_envelope() after MPI_File_get_view()

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#1632] opened 2016-05-04 19:59 UTC
Querying the envelope of etype/filetype obtained with ``MPI_File_get_view()`` errors with ``MPI_ERR_INTERN``.

```python
from mpi4py import MPI
comm = MPI.COMM_SELF
mode = MPI.MODE_RDWR | MPI.MODE_CREATE
info = MPI.INFO_NULL
fh = MPI.File.Open(comm, "/tmp/datafile", mode, info)
disp, etype, ftype, datarep = fh.Get_view()
assert disp == 0
assert datarep == 'native'
print(etype.Get_envelope())
print(ftype.Get_envelope())
```
```shell
$ python test-ompi-3.py 
Traceback (most recent call last):
  File "test-ompi-3.py", line 9, in <module>
    print(etype.Get_envelope())
  File "MPI/Datatype.pyx", line 469, in mpi4py.MPI.Datatype.Get_envelope (src/mpi4py.MPI.c:65712)
mpi4py.MPI.Exception: MPI_ERR_INTERN: internal error
```

**Comment by edgargabriel** [comment] 2016-05-04 20:39
I *think* ompio does the right thing here and the error comes from the datatype engine (there is the possibility that I might use the wrong function to duplicate the datatype after it moved to the opal layer, but in the debugger  I can see the datatype as "dup dup MPI_Byte". @bosilca would you mind having a quick look at that? C version of this test is attached.

**Comment by edgargabriel** [comment] 2016-05-04 20:41
#include <stdio.h>
#include "mpi.h"

int main ( int argc, char **argv )
{
    int rank, size, ret;
    MPI_File fh;
    MPI_Datatype etype, ftype;
    MPI_Offset disp;
    char datarep[64];

    MPI_Init ( &argc, &argv);
    MPI_Comm_rank ( MPI_COMM_WORLD, &rank );
    MPI_Comm_size ( MPI_COMM_WORLD, &size );
                                                                                                                                                                                                
    MPI_File_open (MPI_COMM_WORLD, "test.out", MPI_MODE_RDWR | MPI_MODE_CREATE,                                                                                                                 
                   MPI_INFO_NULL, &fh );                                                                                                                                                        
                                                                                                                                                                                                
                                                                                                                                                                                                
    ret = MPI_File_get_view (fh, &disp, &etype, &ftype, datarep);                                                                                                                               
    if ( ret != MPI_SUCCESS ) {                                                                                                                                                                 
        printf("Error in MPI_File_get_view\n" );                                                                                                                                                
    }                                                                                                                                                                                           
                                                                                                                                                                                                
    int num_integers, num_addresses, num_datatypes, combiner;                                                                                                                                   
    MPI_Type_get_envelope ( etype, &num_integers, &num_addresses,                                                                                                                               
                            &num_datatypes, &combiner);                                                                                                                                         
    printf("etype: num_integers=%d, num_addresses=%d, num_datatypes=%d, "                                                                                                                       
           "combiner=%d\n", num_integers, num_addresses, num_datatypes,                                                                                                                         
           combiner );                                                                                                                                                                          
                                                                                                                                                                                                
                                                                                                                                                                                                
    MPI_Finalize ();                                                                                                                                                                            
    return 0;                                                                                                                                                                                   

}

**Comment by dalcinl** [comment] 2016-05-04 20:42
```python
>>> from mpi4py import MPI
>>> MPI.BYTE.Dup().Dup().Get_envelope()
(0, 0, 1, 1)
```

**Comment by edgargabriel** [comment] 2016-05-04 20:58
I  was referring to the name of the datatype as shown in the internal datatype structure of OMPI. Basically, it shows that MPI_BYTE was duplicated twice during the process. But then ompi_datatype_get_args returns with MPI_ERR_INTERNAL

**Comment by dalcinl** [comment] 2016-05-04 21:00
I know, I'm just showing you that duplicating twice and getting the envelope seems to work just fine.

**Comment by edgargabriel** [comment] 2016-05-04 21:08
so basically what it comes down to is whether 

ompi_datatype_duplicate (&ompi_mpi_byte.dt, ...);

is identical to using MPI_Type_dup (MPI_BYTE,...)

**Comment by bosilca** [comment] 2016-05-04 21:30
Calling ompi_datatype_duplicate is not enough, the args (which is the placeholder used for the enveloppe) is not created. In fact only the MPI level functions are creating the args, because returning a datatype is not a usual operation for any of the MPI functions.

**Comment by edgargabriel** [comment] 2016-05-05 01:05
ok, so what else do I have for that? And I agree that it is fairly unusual scenario that I honestly have not seen in any of the MPI I/O applications or benchmarks

**Comment by edgargabriel** [comment] 2016-05-05 12:21
looking at the code of type_dup.c, I see there is a function ompi_datatype_set_args, I will try to use this one. Following the logic in that function, I am however not sure whether I would also need to copy the attributes in a similar manner, i.e. if a user set some attributes on the filetype for example, and he retrieves a copy of the file type using get_view, would who expect the attributes to be available?

**Comment by edgargabriel** [comment] 2016-05-05 18:54
I have a solution coded up for this one, but I have now a question to the MPI spec experts @bosilca and @jsquyres . What is the combiner supposed to be e.g. for the etype returned by MPI_File_get_envelope? Since I dup the datatypes on the handle, the combiner in my solution is COMBINER_DUP. If you run it with ROMIO, it is the original combiner (e.g. COMBINER NAMED if the original datatypes as e.g. MPI_BYTE).

MPI 3.1 says on page 506: The etype and filetype are new datatypes with
typemaps equal to the typemaps of the current etype and filetype, respectively.

which would support my solution. However, 3 lines later 
If etype or filetype are derived datatypes, the user is responsible for freeing them. The etype and
filetype returned are both in a committed state

which would support ROMIOs solution.

**Comment by bosilca** [comment] 2016-05-05 19:07
It doesn't say that it returns a duplicate of the datatype, which allows me to think that:
 - we don't have to copy the attributes, and
 - we should not return a duplicate of the datatype.

I would simply call ompi_datatype_copy_args on the datatype to be returned.

**Comment by edgargabriel** [comment] 2016-05-05 19:11
well, ok, but that is then a bigger change, because right know I do dupliucate all the datatypes. Would the standard in your opinion support that? In the end, it does say that it returns a 'new' datatype

**Comment by bosilca** [comment] 2016-05-05 19:27
Technically it has to be a new datatype, because the user is requested to call free on them. As the user is only allowed to call free once on any MPI objects, if we return a pointer to the original datatype we will have a problem.

**Comment by edgargabriel** [comment] 2016-05-05 19:29
ok, I see. So bottom line would be to still call ompi_datatype_duplicate, but instead of calling ompi_datatype_set_args () we should call ompi_datatype_copy_args, right?
I have this coded, but forwhatever reason, the copy_args routine segfaults on me, the setargs version did work however. Still looking into it.

**Comment by bosilca** [comment] 2016-05-05 19:33
Yes, I think this should be correct. If you send me a patch I'll take a look.

**Comment by jsquyres** [comment] 2016-05-05 19:53
@edgargabriel @bosilca I wrote tests for all of @dalcinl's tests in the `ibm/io` and `ibm/collective` dirs -- but you have gone back and forth on this one so much that I'm not sure what to test.  😸  So I leave it up to you to write the test...

**Comment by edgargabriel** [comment] 2016-05-05 19:54
ok, thanks. I sent the test directly to George.

**Comment by bosilca** [comment] 2016-05-06 03:27
@edgargabriel After looking at the code I cleaned your solution a little bit (not create a duplicate if there is a predefined type, and not recommit the data as it inherit the commit state of the parent through _dup).

**Comment by edgargabriel** [comment] 2016-05-06 12:25
thank you George! Will add UTK copyrights to that file

**Comment by bosilca** [comment] 2016-05-06 13:06
btw, I wonder if this is the only place in the standard where we use this notion of "new datatype" without clearly stating that it is a duplicate. We might want to bring this to the Forum, we clarify the behavior.

**Comment by edgargabriel** [comment] 2016-05-06 13:13
A good question, I don't know. I just noticed btw. that the wrong commit closes this bug. argh:-( Not sure whether this can be fixed. @jsquyres should I redo the commits on my private branch?

**Comment by edgargabriel** [comment] 2016-05-06 13:14
actually, let me add a commit each that I squash and I can fix the commit message in that case, isn;t it?

**Closed** 2016-05-06 16:46 UTC
Labels: bug

**Comment by jsquyres** [comment] 2016-05-07 15:25
Sorry, I was out yesterday, but it looks like you figured it out.  😄 

A `git rebase -i` on your private branch before merging allows you to do all kinds of things -- including rewording an existing commit message (i.e., you don't have to squash if you just want to reword an existing commit message).
