### ISSUE TITLE
MPI_IN_PLACE problem in openmpi-1.8.4 (FORTRAN)

### ISSUE THREAD

**Issue by howarthjw** [open-mpi/ompi#330] opened 2014-12-30 18:27 UTC
The test code for "MPI_IN_PLACE problem in openmpi-1.8.3 (FORTRAN) #259"...

```
program main
   use mpi
   implicit none
   integer :: ierr, rank
   real(8) :: a
   call MPI_INIT(ierr)
   call MPI_COMM_RANK(MPI_COMM_WORLD, rank, ierr)
   select case (rank)
   case (0)
      a=10._8
   case (1)
      a=-300._8
   case(2)
      a=-150._8
    end select
    print*,rank,a
    call MPI_Allreduce(MPI_IN_PLACE,a,1,MPI_DOUBLE_PRECISION,MPI_MIN,MPI_COMM_WORLD,ierr)
    print*,rank,"---",a
    call MPI_Finalize(ierr)
end program 
```

produces different output on OS X when compiled and run under openmpi 1.8.4

```
mpirun -np 3 ./a.out
           1  -300.00000000000000     
           0   10.000000000000000     
           2  -150.00000000000000     
           1 ---  -300.00000000000000     
           2 ---  -300.00000000000000     
           0 ---  -300.00000000000000
```

compared to x86_64 linux.

```
mpirun -np 3 ./a.out
           0   10.000000000000000     
           0 ---   10.000000000000000     
           1  -300.00000000000000     
           1 ---  -300.00000000000000     
           2  -150.00000000000000     
           2 ---  -150.00000000000000     
```

**Comment by jsquyres** [comment] 2015-01-06 19:43
I am unable to reproduce this problem.  I've tried on OS X 10.9.5 with XCode 6.1.1 / clang (see below) + gfortran 4.9.1, and gcc 4.9.1+gfortran 4.9.1:

```shell
$ uname -a
Darwin JSQUYRES-M-H05C 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64
$ where gcc
gcc: aliased to nocorrect gcc
/usr/bin/gcc
/usr/local/bin/gcc
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
$ /usr/local/bin/gcc --version
gcc (GCC) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ where gfortran
/usr/local/bin/gfortran
$ gfortran --version
GNU Fortran (GCC) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

$ 
```

I tried with a git checkout and with a production tarball, both at the HEAD of master and the v1.8 branch.  In all cases, the output of the program shows -300 for the out value from all 3 MPI processes.

**Comment by howarthjw** [comment] 2015-01-07 18:04
So you have confirmed my observation that -300 is returned for three MPI processes on darwin. The real question is what the normal behavior is on linux. I tested with a build of openmpi 1.8.4 on x86_64 Fedora 15 using binutils-2.24 and

Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.6.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.6.3 20120306 (Red Hat 4.6.3-2) (GCC) 

and see 

$ mpirun -np 3 ./a.out 
           0   10.000000000000000     
           0 ---   10.000000000000000     
           1  -300.00000000000000     
           1 ---  -300.00000000000000     
           2  -150.00000000000000     
           2 ---  -150.00000000000000

**Comment by jsquyres** [comment] 2015-01-08 12:33
I'm still unable to reproduce the behavior you're seeing, even on Linux.  I tried with both the default gcc/gfortran compiler and gcc/gfortran 4.9.1, both with the v1.8 branch HEAD and the production 1.8.4 tarball.

Are you using the wrong mpif.h, perchance?  (e.g., an mpif.h from a different MPI implementation)

Try running this C version of the same program and see if you get the same results:

```c
#include <stdio.h>
#include <mpi.h>

int main()
{
    int rank;
    double a;

    MPI_Init(NULL, NULL);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    if (0 == rank) {
        a = 10;
    } else if (1 == rank) {
        a = -300;
    } else {
        a = -150;
    }
    printf("IN: %d %g\n", rank, a);
    MPI_Allreduce(MPI_IN_PLACE, &a, 1, MPI_DOUBLE, MPI_MIN, MPI_COMM_WORLD);
    printf("OUT: %d %g\n", rank, a);
    MPI_Finalize();
    return 0;
}
```

**Comment by jsquyres** [comment] 2015-02-23 21:58
@howarthjw Can you reply to the previous comment? Or should we close this issue?

**Comment by howarthjw** [comment] 2015-02-25 21:08
The c version produces...

$ mpicc  testmpi.c
$ mpirun -np 3 ./a.out
IN: 1 -300
IN: 2 -150
IN: 0 10
OUT: 0 -300
OUT: 2 -300
OUT: 1 -300

while the fortran version still produces...

$ mpif90 testmpi.f90
$ mpirun -np 3 ./a.out
           0   10.000000000000000     
           0 ---   10.000000000000000     
           1  -300.00000000000000     
           1 ---  -300.00000000000000     
           2  -150.00000000000000     
           2 ---  -150.00000000000000

**Comment by jsquyres** [comment] 2015-02-25 21:45
Is there any chance that you are using a stale mpi.mod?

**Comment by howarthjw** [comment] 2015-02-25 22:32
```
$ ls /home/howarth/dist_openmpi/lib/*mod
/home/howarth/dist_openmpi/lib/mpi.mod
$ mpif90 -I/home/howarth/dist_openmpi/lib testmpi.f90
$ mpirun -np 3 ./a.out
           0   10.000000000000000     
           0 ---   10.000000000000000     
           1  -300.00000000000000     
           1 ---  -300.00000000000000     
           2  -150.00000000000000     
           2 ---  -150.00000000000000     
```

**Comment by howarthjw** [comment] 2015-02-25 22:35
Also...
```
$ mpif90 -I/home/howarth/dist_openmpi/lib testmpi.f90 -v
Driving: /usr/bin/gfortran -I/home/howarth/dist_openmpi/lib testmpi.f90 -v -I/home/howarth/dist_openmpi/include -pthread -I/home/howarth/dist_openmpi/lib -Wl,-rpath -Wl,/home/howarth/dist_openmpi/lib -Wl,--enable-new-dtags -L/home/howarth/dist_openmpi/lib -lmpi_usempi -lmpi_mpifh -lmpi -l gfortran -l m -shared-libgcc
Using built-in specs.
COLLECT_GCC=/usr/bin/gfortran
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.6.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.6.3 20120306 (Red Hat 4.6.3-2) (GCC) 
COLLECT_GCC_OPTIONS='-I' '/home/howarth/dist_openmpi/lib' '-v' '-I' '/home/howarth/dist_openmpi/include' '-pthread' '-I' '/home/howarth/dist_openmpi/lib' '-L/home/howarth/dist_openmpi/lib' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.6.3/f951 testmpi.f90 -I /home/howarth/dist_openmpi/lib -I /home/howarth/dist_openmpi/include -I /home/howarth/dist_openmpi/lib -quiet -dumpbase testmpi.f90 -mtune=generic -march=x86-64 -auxbase testmpi -version -fintrinsic-modules-path /usr/lib/gcc/x86_64-redhat-linux/4.6.3/finclude -o /tmp/ccxfcWVk.s
GNU Fortran (GCC) version 4.6.3 20120306 (Red Hat 4.6.3-2) (x86_64-redhat-linux)
	compiled by GNU C version 4.6.3 20120306 (Red Hat 4.6.3-2), GMP version 4.3.2, MPFR version 3.0.0, MPC version 0.8.3-dev
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
GNU Fortran (GCC) version 4.6.3 20120306 (Red Hat 4.6.3-2) (x86_64-redhat-linux)
	compiled by GNU C version 4.6.3 20120306 (Red Hat 4.6.3-2), GMP version 4.3.2, MPFR version 3.0.0, MPC version 0.8.3-dev
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
COLLECT_GCC_OPTIONS='-I' '/home/howarth/dist_openmpi/lib' '-v' '-I' '/home/howarth/dist_openmpi/include' '-pthread' '-I' '/home/howarth/dist_openmpi/lib' '-L/home/howarth/dist_openmpi/lib' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 as --64 -o /tmp/ccIVTlMS.o /tmp/ccxfcWVk.s
Reading specs from /usr/lib/gcc/x86_64-redhat-linux/4.6.3/libgfortran.spec
rename spec lib to liborig
COLLECT_GCC_OPTIONS='-I' '/home/howarth/dist_openmpi/lib' '-v' '-I' '/home/howarth/dist_openmpi/include' '-pthread' '-I' '/home/howarth/dist_openmpi/lib' '-L/home/howarth/dist_openmpi/lib' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.6.3/:/usr/libexec/gcc/x86_64-redhat-linux/4.6.3/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.6.3/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.6.3/:/usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-I' '/home/howarth/dist_openmpi/lib' '-v' '-I' '/home/howarth/dist_openmpi/include' '-pthread' '-I' '/home/howarth/dist_openmpi/lib' '-L/home/howarth/dist_openmpi/lib' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.6.3/collect2 --build-id --no-add-needed --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -dynamic-linker /lib64/ld-linux-x86-64.so.2 /usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.6.3/crtbegin.o -L/home/howarth/dist_openmpi/lib -L/usr/lib/gcc/x86_64-redhat-linux/4.6.3 -L/usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../.. /tmp/ccIVTlMS.o -rpath /home/howarth/dist_openmpi/lib --enable-new-dtags -lmpi_usempi -lmpi_mpifh -lmpi -lgfortran -lm -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-redhat-linux/4.6.3/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.6.3/../../../../lib64/crtn.o
```

**Comment by jsquyres** [comment] 2015-02-26 00:10
I admit that I am a bit befuddled as to what is going on here.  I am totally unable to reproduce this, on multiple different machines with different versions of OMPI, and with different compilers.

What is different between our setups?

Is there any chance you can run this through a debugger and see what is going on?  And just for giggles, please also update to OMPI 1.8.4.

**Comment by howarthjw** [comment] 2015-02-26 15:15
I am already at openmpi 1.8.4 for the local installation. The linkage looks like....
```
$ ldd ./a.out
	linux-vdso.so.1 =>  (0x00007fffca7de000)
	libmpi_usempi.so.1 => /home/howarth/dist_openmpi/lib/libmpi_usempi.so.1 (0x00007fae9424b000)
	libmpi_mpifh.so.2 => /home/howarth/dist_openmpi/lib/libmpi_mpifh.so.2 (0x00007fae93ff5000)
	libmpi.so.1 => /home/howarth/dist_openmpi/lib/libmpi.so.1 (0x00007fae93d1b000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x0000003c80200000)
	libm.so.6 => /lib64/libm.so.6 (0x000000372a200000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003c78a00000)
	libquadmath.so.0 => /usr/lib64/libquadmath.so.0 (0x0000003c82a00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000000372a600000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003729e00000)
	libopen-rte.so.7 => /home/howarth/dist_openmpi/lib/libopen-rte.so.7 (0x00007fae93a70000)
	libopen-pal.so.6 => /home/howarth/dist_openmpi/lib/libopen-pal.so.6 (0x00007fae9379e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000372aa00000)
	librt.so.1 => /lib64/librt.so.1 (0x000000372ae00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x0000003739a00000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003729a00000)
```
I am still have trouble puzzling out how to run this through gdb but the results from valgrind are...
```
$ mpirun -np 3 valgrind -enable-memchecker --enable-debug ./a.out
valgrind: Bad option: -enable-memchecker
valgrind: Use --help for more information or consult the user manual.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50818,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by jsquyres** [comment] 2015-02-28 19:25
I think valgrind failed because you need to use `--enable-memchecker` (two dashes, not one).

But that's ok -- this does not feel like a valgrind issue.  The issue is why https://github.com/open-mpi/ompi-release/blob/v1.8/ompi/mpi/fortran/mpif-h/allreduce_f.c#L81 does not return MPI_IN_PLACE in this line of code:

```c
    sendbuf = (char *) OMPI_F2C_IN_PLACE(sendbuf);
```

OMPI_F2C_IN_PLACE is a macro that effectively expands to this (https://github.com/open-mpi/ompi-release/blob/v1.8/ompi/mpi/fortran/base/constants.h#L253 and https://github.com/open-mpi/ompi-release/blob/v1.8/ompi/mpi/fortran/base/constants.h#L128) (typed in github -- forgive typos):

```c
    sendbuf = (char *)  (addr == (void*) &MPI_FORTRAN_IN_PLACE || \
        sendbuf == (void*) &mpi_fortran_in_place || \
        sendbuf == (void*) &mpi_fortran_in_place_ || \
        sendbuf == (void*) &mpi_fortran_in_place__) ? MPI_IN_PLACE : (sendbuf);
```

So the question is why `sendbuf` is (apparently) not getting assigned MPI_IN_PLACE, but rather just getting its own value back.

Try putting [the file in this gist](https://gist.github.com/jsquyres/496e741bd00196ef2d64) in place of your existing `ompi/mpi/fortran/mpif-h/allreduce_f.c`, and invoke "make install" from the top-level Open MPI build tree.  This will put in a few debug output statements when you call MPI_ALLREDUCE from Fortran, and let's see what we get.

This is what I get when I run it:

```
$ mpirun -np 3 ./a.out
[savbu-usnic-a:09979] Have weak symbols: 0x2aaaab4dc578 0x2aaaaacdbcc0 0x601600 0x2aaaab4dc560
[savbu-usnic-a:09979] Fortran MPI_ALLREDUCE: got input buffer 0x601600
[savbu-usnic-a:09979] Fortran MPI_ALLREDUCE 2: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
[savbu-usnic-a:09979] Fortran MPI_ALLREDUCE 3: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
[savbu-usnic-a:09980] Have weak symbols: 0x2aaaab4dc578 0x2aaaaacdbcc0 0x601600 0x2aaaab4dc560
[savbu-usnic-a:09980] Fortran MPI_ALLREDUCE: got input buffer 0x601600
[savbu-usnic-a:09980] Fortran MPI_ALLREDUCE 2: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
[savbu-usnic-a:09980] Fortran MPI_ALLREDUCE 3: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
[savbu-usnic-a:09978] Have weak symbols: 0x2aaaab4dc578 0x2aaaaacdbcc0 0x601600 0x2aaaab4dc560
[savbu-usnic-a:09978] Fortran MPI_ALLREDUCE: got input buffer 0x601600
[savbu-usnic-a:09978] Fortran MPI_ALLREDUCE 2: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
[savbu-usnic-a:09978] Fortran MPI_ALLREDUCE 3: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
           2 IN  -150.00000000000000     
           0 IN   10.000000000000000     
           1 IN  -300.00000000000000     
           1 OUT  -300.00000000000000     
           0 OUT  -300.00000000000000     
           2 OUT  -300.00000000000000
```

I.e., you can clearly see that the incoming `sendbuf` equals one of the MPI_IN_PLACE symbols, and therefore the switch is made when we call C.

**Comment by howarthjw** [comment] 2015-02-28 22:42
Oddly I don't see those debug messages output after rebuilding and reinstalling openmpi. What exact shell commands do you use locally to insure that the local build of openmpi is used rather the system one? The linkage looks correct here...

$ ldd ././a.out
	linux-vdso.so.1 =>  (0x00007fff5b9ff000)
	libmpi_usempi.so.1 => /home/howarth/dist_openmpi/lib/libmpi_usempi.so.1 (0x00007f4c651bb000)
	libmpi_mpifh.so.2 => /home/howarth/dist_openmpi/lib/libmpi_mpifh.so.2 (0x00007f4c64f65000)
	libmpi.so.1 => /home/howarth/dist_openmpi/lib/libmpi.so.1 (0x00007f4c64c8b000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x0000003c80200000)
	libm.so.6 => /lib64/libm.so.6 (0x000000372a200000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003c78a00000)
	libquadmath.so.0 => /usr/lib64/libquadmath.so.0 (0x0000003c82a00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000000372a600000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003729e00000)
	libopen-rte.so.7 => /home/howarth/dist_openmpi/lib/libopen-rte.so.7 (0x00007f4c649e0000)
	libopen-pal.so.6 => /home/howarth/dist_openmpi/lib/libopen-pal.so.6 (0x00007f4c6470e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000000372aa00000)
	librt.so.1 => /lib64/librt.so.1 (0x000000372ae00000)
	libutil.so.1 => /lib64/libutil.so.1 (0x0000003739a00000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003729a00000)

**Comment by jsquyres** [comment] 2015-03-01 20:17
Ah -- if you're not seeing the debug files, then you are, indeed, likely running the with "wrong" libmpi or module, and that could be the problem here.

Note that it's not sufficient to ensure that your PATH and LD_LIBRARY_PATH are set properly in your local shell, but also for non-interactive logins on your servers, too.  Check out these 3 FAQ items and see if they help:

1. http://www.open-mpi.org/faq/?category=running#run-prereqs
1. http://www.open-mpi.org/faq/?category=running#adding-ompi-to-path
1. http://www.open-mpi.org/faq/?category=running#mpirun-prefix

**Comment by jsquyres** [comment] 2015-03-10 15:12
@howarthjw Any update?

**Comment by jsquyres** [comment] 2015-03-24 15:12
@howarthjw Any update?

**Comment by howarthjw** [comment] 2015-03-25 20:29
Jeff,
    I am stymied in trying to get the debug output to work with x86_64
Fedora 15's gcc 4.6.3 compilers. Setting PATH and LD_LIBRARY_PATH seems to
be insufficient to keep the system openmpi from being used during the
linkage.
            Jack

**Comment by jsquyres** [comment] 2015-04-03 15:42
I somehow missed your last comment -- sorry!

I typically build and install Open MPI under my $HOME -- e.g., install Open MPI to $HOME/local, and then put $HOME/local/bin in my $PATH And $HOME/local/lib in my $LD_LIBRARY_PATH.  As noted above, you need to ensure to *prefix* your PATH / LD_LIBRARY_PATH, and ensure to do it in your shell startup files *before* they exit for non-interactive logins (although you should be able to test this on a single machine, which makes this a little easier).

You should be able to test that you're getting the "right" stuff via:

```
$ which mpifort
/path/to/your/locally-installed-mpifort
$ mpifort your_test.f90 -o your_test
$ ldd your_test
...should include some mention of /path/to/your/locally-installed-mpifort/lib/libmpi.so
```

**Comment by jsquyres** [comment] 2015-04-30 16:30
@howarthjw There's been no real progress on this for quite a while, and I can't reproduce it.  I'm going to close this issue.  Please feel free to add comments on here; we can re-open it if you have the cycles to debug, etc.

**Closed by jsquyres** 2015-04-30 16:30 UTC
Labels: bug

**Comment by iskakoff** [comment] 2018-02-26 22:47
This problem appears when I try to build openmpi (versions starting from at least 2.0) on OS X 10.10 - 10.11 with intel compiler.

The reason is the compiler  flag `lt_prog_compiler_pic_FC='-fno-common'`

with this flag set on the object file `mpi-ignore-tkr.o` has the following content:

     SYMBOL TABLE:
     0000000000000160 l       0e SECT   03 0000 [.eh_frame] EH_frame0
     0000000000000000 g       0f SECT   01 0000 [.text] _mpi._
     0000000000000020 g       0f SECT   02 0080 [__DATA.__datacoal_nt] _mpi_fortran_bottom_
     0000000000000040 g       0f SECT   02 0080 [__DATA.__datacoal_nt] _mpi_fortran_in_place_
     .....

where the `_mpi_fortran_in_place_` common block has type `SECT` which means that it has its own memory allocation instead of using the allocation defined in `ompi/include/mpif-c-constants.h`. And the gist you suggest return the following:

     Have CAPS3: 0x108bea27c
     Fortran MPI_ALLREDUCE: got input buffer 0x1088426a0
     Fortran MPI_ALLREDUCE 2: after IN_PLACE 0x1088426a0 (MPI_IN_PLACE = 0x1)
     Fortran MPI_ALLREDUCE 3: after IN_PLACE 0x1088426a0 (MPI_IN_PLACE = 0x1)

Which makes it clear to see that `OMPI_F2C_IN_PLACE` does not work. If I simply set `lt_prog_compiler_pic_FC=''` I will get:

     SYMBOL TABLE:
     0000000000000020 l       0e SECT   02 0000 [.eh_frame] EH_frame0
     0000000000000000 g       0f SECT   01 0000 [.text] _mpi._
     0000000000000038 g       0f SECT   02 0000 [.eh_frame] _mpi._.eh
     0000000000000004         01 COM    00 0000 _mpi_fortran_bottom_
     0000000000000004         01 COM    00 0000 _mpi_fortran_in_place_
     ....

where 'mpi_fortran_in_place_' is now a common block, and the gist will return:

     Have CAPS3: 0x10fff127c
     Fortran MPI_ALLREDUCE: got input buffer 0x10fff127c
     Fortran MPI_ALLREDUCE 2: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)
     Fortran MPI_ALLREDUCE 3: after IN_PLACE 0x1 (MPI_IN_PLACE = 0x1)

 In case of gcc symbol-table has common blocks

     SYMBOL TABLE:
     0000000000000001         01 COM    00 0400 _mpi_fortran_argv_null_
     0000000000000001         01 COM    00 0400 _mpi_fortran_argvs_null_
     0000000000000004         01 COM    00 0400 _mpi_fortran_bottom_
     0000000000000004         01 COM    00 0400 _mpi_fortran_errcodes_ignore_
     0000000000000004         01 COM    00 0400 _mpi_fortran_in_place_

**Comment by eschnett** [comment] 2021-11-12 20:56
@iskakoff Can you clarify your statement above? Are you saying that the change to using `flat_namespace` is not necessary any more if one instead removes the linker flag `no-common`?
