### ISSUE TITLE
Performance regression: placeholder for v2.0.2 release

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2592] opened 2016-12-16 17:00 UTC
See #2591 -- that issue might also affect the v2.0.x series, so I wanted to open an issue on the v2.0.2 milestone to track it here, too.

It is potentially a blocker, but we'll know more when @hjelmn reports findings on #2591.

**Comment by matcabral** [comment] 2016-12-16 17:49
Hi @jsquyres,  I see we may have different issues and/or sources degradation  and impacts. As discussed in #1831, I have seen a latency and bw_mr degradation (especially in small messages) when moving from 1.10.4 to 2.0.x. in PSM2 and OFI MTLs. I've been looking at it but have found nothing concrete.  Saw an increase in cache misses and minor page faults, but suspect this is not the source of the degradation since vader btl shows the same percentage of misses but increased performance.

**Comment by hppritcha** [comment] 2016-12-23 16:09
closed via #2596, #2611, and #2612

**Closed by hppritcha** 2016-12-23 16:09 UTC
Labels: blocker, bug, Target v2.0.x, Target: 1.10, Target: 2.x

**Comment by matcabral** [comment] 2016-12-23 17:41
Hi @hppritcha and @jsquyres, 
Would the scope of this issue be limited to the "clocks" degradation only? I'm asking because I'm still seeing the regression described in #1831 when comparing #2611 with #2599 (%5 to %13 latency degradation in osu_latency for message sizes<=4k running over PSM). 
thanks,

**Comment by rhc54** [comment] 2016-12-23 18:00
Yeah, I think you should probably open another issue to track that further problem. There are clearly several things going on, so let's focus this one on the clock problem.

**Comment by matcabral** [comment] 2016-12-28 00:34
opened #2644
