### ISSUE TITLE
hang on an IMB test in a loop

### ISSUE THREAD

**Issue by alinask** [open-mpi/ompi#433] opened 2015-02-26 12:50 UTC
Hello all,

We observe a hang which happens after running the Exchange benchmark from the IMB tests in a loop. The hang happens at the end, after:
```
# All processes entering MPI_Finalize
```
It reproduces with any PML/BTL combination on the master and v1.8 branches with four nodes and ppn=10. Several iterations are required to reproduce this (can take around 20 minutes until it reproductes).

The command line to reproduce is (with btl tcp) :
```
while true ; do …/mpirun -v -d -bind-to core -display-map  --map-by core -H node03, node04, node05, node06  -mca pml ob1 -mca btl tcp,self,sm –np 40 …/IMB-4.0/IMB-MPI1 -npmin 40 Exchange ; sleep 1 ; done
```

During the run and when the job hangs the following output is printed out many times:
```
sess_dir_finalize: proc session dir does not exist
sess_dir_finalize: proc session dir does not exist
sess_dir_finalize: proc session dir does not exist
sess_dir_finalize: proc session dir does not exist
sess_dir_finalize: proc session dir does not exist
hang…
```

During the hang, one of the nodes always has several IMB zombie processes in it and non of the other hosts has any IMB processes. 
This hang was only reproduced on SUSE hosts so far. Couldn't reproduce this on RH.

When searching the ompi mailing list, I saw several threads where this message “sess_dir_finalize: proc session dir does not exist” appeared after a failure but I didn’t find any solutions there…

**Comment by jsquyres** [comment] 2015-02-26 20:19
@rhc54 Any ideas here?  Is this possibly part of the code that you're just about to replace?

**Comment by rhc54** [comment] 2015-02-26 20:38
I honestly have no idea. I assume it is doing a lot of runs during that time? Since each one is independent, it's hard to imagine the mechanism. Best guess would be that the tmp dir is getting filled?

**Comment by alinask** [comment] 2015-03-05 09:49
@rhc54 I checked the tmp dir during the hang on all the nodes and they aren't full.

**Comment by rhc54** [comment] 2015-03-05 16:32
I gather all the daemons are gone, but mpirun remains? Only thing I can think of is that somehow mpirun doesn't realize that the job is "done" even though the daemons quit. More disturbing frankly are the zombies. It sounds like something is happening in IMB (in the MPI layer or whatever) that has frozen the job so we can't kill the procs even with a SIGKILL.

**Comment by jsquyres** [comment] 2015-03-24 15:20
@alinask Any update, perchance?

**Comment by alinask** [comment] 2015-03-25 09:23
@jsquyres no update, a reproducer was provided and it can be reproduced on any setup as described above.

**Comment by jsquyres** [comment] 2015-03-25 10:19
@alinask We've been unable to reproduce it.  I think @rhc54 asked an (indirect) question in his last reply: can you dig a little further?  He asked if the daemons (and MPI processes) were all gone / dead, but mpirun was still running.

**Comment by alinask** [comment] 2015-03-25 11:00
yes, mpirun was still running and almost all the IMB processes were gone except for several zombies.

**Comment by jsquyres** [comment] 2015-03-25 12:01
So just to be clear:

* mpirun was still there
* some IMB processes were running, but some were dead
  * could you manually kill the remaining IMB processes (e.g., via `kill -HUP <pid>`), or were they really unkillable zombies?
  * can you get some backtraces of the still-running IMB processes?
* were any orteds left?  If so, were they left *only* on the servers where IMB processes were left?

@rhc54 Is there a verbose level @alinask should run with to show verbose output of what ORTE is noticing during this sequence?

**Comment by rhc54** [comment] 2015-03-25 23:04
If you can make the job small enough so the output isn't overwhelming, set "--leave-session-attached --mca state_base_verbose" as a starting point. This will tell us what the state machines of each daemon are trying to do.

It sounds like the daemons are terminating without (a) killing their local procs, and (b) mpirun realizing it. I should have thought the keepalive commit would help fix this scenario, but perhaps that isn't included here?

**Comment by alinask** [comment] 2015-03-26 15:07
Unfortunately I don't have the setup anymore and therefore can't reproduce this issue. 
As far as I remember, there were orteds left, not only on the host which had the zombies

**Comment by jsquyres** [comment] 2015-03-26 15:16
When you say "zombies", do you really mean unkillable MPI processes?  Or just MPI processes that happened to still be running?

**Comment by alinask** [comment] 2015-03-26 15:34
Well, I saw this when I checked what was running on the host:
[IMB-MPI1] < defunct >
[IMB-MPI1] < defunct >
...

There was only one host which had this output.

**Comment by jsquyres** [comment] 2015-03-31 16:20
Ah, ok -- un-reaped processes.

Since we don't have a way to test this further, I deferred this to v1.8.6.  If you can ever replicate this problem again, let's keep digging.

**Comment by jsquyres** [comment] 2015-07-25 12:25
@alinask I'm assuming you haven't been able to reproduce this again, so let's go ahead and close it.  If necessarily, please re-open it.  Thanks.

**Closed by jsquyres** 2015-07-25 12:25 UTC
Labels: bug
