### ISSUE TITLE
Possible Fortran API changes in 4.0.3

### ISSUE THREAD

**Issue by opoplawski** [open-mpi/ompi#7374] opened 2020-02-08 19:01 UTC
I update openmpi in Fedora Rawhide to 4.0.3rc3 from 4.0.2.  The ABI check returned the following:
```
ABI changes between build openmpi-4.0.2-5.fc32 and its latest stable build
================================================================================

This file contains possible ABI changes which have occurred due to this package update against latest stable build available in koji for the given Fedora release.

If you want to filter out these kind of ABI changes in the future, you can add a proper .abignore file to this package. To know more about how to write one, please look at the wiki page https://fedoraproject.org/wiki/Taskotron/Tasks/dist.abicheck#filtering .

On armv7hl architecture
*************************

* Incompatible ABI changes between:
openmpi-4.0.3rc3-1.fc32.armv7hl.rpm
openmpi-4.0.2-5.fc32.armv7hl.rpm
ABI comparison took 9.30 second(s). Please review them.

================ changes of 'libmpi_usempif08.so.40.21.0'===============
  Functions changes summary: 0 Removed, 0 Changed, 0 Added function
  Variables changes summary: 43 Removed, 0 Changed, 0 Added variables
  Function symbols changes summary: 0 Removed, 0 Added function symbol not referenced by debug info
  Variable symbols changes summary: 106 Removed, 0 Added variable symbols not referenced by debug info

  43 Removed variables:

    'ompi_fortran_08_handle_t ompi_f08_mpi_2int'    {ompi_f08_mpi_2int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_bool'    {ompi_f08_mpi_c_bool}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_complex'    {ompi_f08_mpi_c_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_double_complex'    {ompi_f08_mpi_c_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_float_complex'    {ompi_f08_mpi_c_float_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_long_double_complex'    {ompi_f08_mpi_c_long_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_char'    {ompi_f08_mpi_char}
    'ompi_fortran_08_handle_t ompi_f08_mpi_count'    {ompi_f08_mpi_count}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_bool'    {ompi_f08_mpi_cxx_bool}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_complex'    {ompi_f08_mpi_cxx_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_double_complex'    {ompi_f08_mpi_cxx_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_float_complex'    {ompi_f08_mpi_cxx_float_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_long_double_complex'    {ompi_f08_mpi_cxx_long_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_double'    {ompi_f08_mpi_double}
    'ompi_fortran_08_handle_t ompi_f08_mpi_double_int'    {ompi_f08_mpi_double_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_float'    {ompi_f08_mpi_float}
    'ompi_fortran_08_handle_t ompi_f08_mpi_float_int'    {ompi_f08_mpi_float_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int'    {ompi_f08_mpi_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int16'    {ompi_f08_mpi_int16}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int32'    {ompi_f08_mpi_int32}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int64'    {ompi_f08_mpi_int64}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int8'    {ompi_f08_mpi_int8}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long'    {ompi_f08_mpi_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_double'    {ompi_f08_mpi_long_double}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_double_int'    {ompi_f08_mpi_long_double_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_int'    {ompi_f08_mpi_long_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_long'    {ompi_f08_mpi_long_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_long_int'    {ompi_f08_mpi_long_long_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_no_op'    {ompi_f08_mpi_no_op}
    'ompi_fortran_08_handle_t ompi_f08_mpi_offset'    {ompi_f08_mpi_offset}
    'ompi_fortran_08_handle_t ompi_f08_mpi_short'    {ompi_f08_mpi_short}
    'ompi_fortran_08_handle_t ompi_f08_mpi_short_int'    {ompi_f08_mpi_short_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_signed_char'    {ompi_f08_mpi_signed_char}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint16'    {ompi_f08_mpi_uint16}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint32'    {ompi_f08_mpi_uint32}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint64'    {ompi_f08_mpi_uint64}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint8'    {ompi_f08_mpi_uint8}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned'    {ompi_f08_mpi_unsigned}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_char'    {ompi_f08_mpi_unsigned_char}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_long'    {ompi_f08_mpi_unsigned_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_long_long'    {ompi_f08_mpi_unsigned_long_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_short'    {ompi_f08_mpi_unsigned_short}
    'ompi_fortran_08_handle_t ompi_f08_mpi_wchar'    {ompi_f08_mpi_wchar}

  106 Removed variable symbols not referenced by debug info:

    [D] __mpi_f08_types_MOD_mpi_2complex
    [D] __mpi_f08_types_MOD_mpi_2double_complex
    [D] __mpi_f08_types_MOD_mpi_2double_precision
    [D] __mpi_f08_types_MOD_mpi_2int
    [D] __mpi_f08_types_MOD_mpi_2integer
    [D] __mpi_f08_types_MOD_mpi_2real
    [D] __mpi_f08_types_MOD_mpi_aint
    [D] __mpi_f08_types_MOD_mpi_band
    [D] __mpi_f08_types_MOD_mpi_bor
    [D] __mpi_f08_types_MOD_mpi_bxor
    [D] __mpi_f08_types_MOD_mpi_byte
    [D] __mpi_f08_types_MOD_mpi_c_bool
    [D] __mpi_f08_types_MOD_mpi_c_complex
    [D] __mpi_f08_types_MOD_mpi_c_double_complex
    [D] __mpi_f08_types_MOD_mpi_c_float_complex
    [D] __mpi_f08_types_MOD_mpi_c_long_double_complex
    [D] __mpi_f08_types_MOD_mpi_char
    [D] __mpi_f08_types_MOD_mpi_character
    [D] __mpi_f08_types_MOD_mpi_comm_null
    [D] __mpi_f08_types_MOD_mpi_comm_self
    [D] __mpi_f08_types_MOD_mpi_comm_world
    [D] __mpi_f08_types_MOD_mpi_complex
    [D] __mpi_f08_types_MOD_mpi_complex16
    [D] __mpi_f08_types_MOD_mpi_complex32
    [D] __mpi_f08_types_MOD_mpi_complex8
    [D] __mpi_f08_types_MOD_mpi_count
    [D] __mpi_f08_types_MOD_mpi_cxx_bool
    [D] __mpi_f08_types_MOD_mpi_cxx_complex
    [D] __mpi_f08_types_MOD_mpi_cxx_double_complex
    [D] __mpi_f08_types_MOD_mpi_cxx_float_complex
    [D] __mpi_f08_types_MOD_mpi_cxx_long_double_complex
    [D] __mpi_f08_types_MOD_mpi_datatype_null
    [D] __mpi_f08_types_MOD_mpi_double
    [D] __mpi_f08_types_MOD_mpi_double_complex
    [D] __mpi_f08_types_MOD_mpi_double_int
    [D] __mpi_f08_types_MOD_mpi_double_precision
    [D] __mpi_f08_types_MOD_mpi_errhandler_null
    [D] __mpi_f08_types_MOD_mpi_errors_are_fatal
    [D] __mpi_f08_types_MOD_mpi_errors_return
    [D] __mpi_f08_types_MOD_mpi_file_null
    [D] __mpi_f08_types_MOD_mpi_float
    [D] __mpi_f08_types_MOD_mpi_float_int
    [D] __mpi_f08_types_MOD_mpi_group_empty
    [D] __mpi_f08_types_MOD_mpi_group_null
    [D] __mpi_f08_types_MOD_mpi_info_env
    [D] __mpi_f08_types_MOD_mpi_info_null
    [D] __mpi_f08_types_MOD_mpi_int
    [D] __mpi_f08_types_MOD_mpi_int16_t
    [D] __mpi_f08_types_MOD_mpi_int32_t
    [D] __mpi_f08_types_MOD_mpi_int64_t
    [D] __mpi_f08_types_MOD_mpi_int8_t
    [D] __mpi_f08_types_MOD_mpi_integer
    [D] __mpi_f08_types_MOD_mpi_integer1
    [D] __mpi_f08_types_MOD_mpi_integer16
    [D] __mpi_f08_types_MOD_mpi_integer2
    [D] __mpi_f08_types_MOD_mpi_integer4
    [D] __mpi_f08_types_MOD_mpi_integer8
    [D] __mpi_f08_types_MOD_mpi_land
    [D] __mpi_f08_types_MOD_mpi_lb
    [D] __mpi_f08_types_MOD_mpi_logical
    [D] __mpi_f08_types_MOD_mpi_logical1
    [D] __mpi_f08_types_MOD_mpi_logical2
    [D] __mpi_f08_types_MOD_mpi_logical4
    [D] __mpi_f08_types_MOD_mpi_logical8
    [D] __mpi_f08_types_MOD_mpi_long
    [D] __mpi_f08_types_MOD_mpi_long_double
    [D] __mpi_f08_types_MOD_mpi_long_double_int
    [D] __mpi_f08_types_MOD_mpi_long_int
    [D] __mpi_f08_types_MOD_mpi_long_long
    [D] __mpi_f08_types_MOD_mpi_long_long_int
    [D] __mpi_f08_types_MOD_mpi_lor
    [D] __mpi_f08_types_MOD_mpi_lxor
    [D] __mpi_f08_types_MOD_mpi_max
    [D] __mpi_f08_types_MOD_mpi_maxloc
    [D] __mpi_f08_types_MOD_mpi_message_no_proc
    [D] __mpi_f08_types_MOD_mpi_message_null
    [D] __mpi_f08_types_MOD_mpi_min
    [D] __mpi_f08_types_MOD_mpi_minloc
    [D] __mpi_f08_types_MOD_mpi_no_op
    [D] __mpi_f08_types_MOD_mpi_offset
    [D] __mpi_f08_types_MOD_mpi_op_null
    [D] __mpi_f08_types_MOD_mpi_packed
    [D] __mpi_f08_types_MOD_mpi_prod
    [D] __mpi_f08_types_MOD_mpi_real
    [D] __mpi_f08_types_MOD_mpi_real16
    [D] __mpi_f08_types_MOD_mpi_real2
    [D] __mpi_f08_types_MOD_mpi_real4
    [D] __mpi_f08_types_MOD_mpi_real8
    [D] __mpi_f08_types_MOD_mpi_replace
    [D] __mpi_f08_types_MOD_mpi_request_null
    [D] __mpi_f08_types_MOD_mpi_short
    [D] __mpi_f08_types_MOD_mpi_short_int
    [D] __mpi_f08_types_MOD_mpi_signed_char
    [D] __mpi_f08_types_MOD_mpi_sum
    [D] __mpi_f08_types_MOD_mpi_ub
    [D] __mpi_f08_types_MOD_mpi_uint16_t
    [D] __mpi_f08_types_MOD_mpi_uint32_t
    [D] __mpi_f08_types_MOD_mpi_uint64_t
    [D] __mpi_f08_types_MOD_mpi_uint8_t
    [D] __mpi_f08_types_MOD_mpi_unsigned
    [D] __mpi_f08_types_MOD_mpi_unsigned_char
    [D] __mpi_f08_types_MOD_mpi_unsigned_long
    [D] __mpi_f08_types_MOD_mpi_unsigned_long_long
    [D] __mpi_f08_types_MOD_mpi_unsigned_short
    [D] __mpi_f08_types_MOD_mpi_wchar
    [D] __mpi_f08_types_MOD_mpi_win_null

================ end of changes of 'libmpi_usempif08.so.40.21.0'===============
```
These seem like very odd variable names and I suspect that their previous definition was a mistake, but I'm posting here out of an abundance of caution.

**Comment by ggouaillardet** [comment] 2020-02-09 02:32
Thanks a lot for the report!

These symbols have been removed from `master` on purpose, but they were supposed to be there in the release branch(es) not to break the ABI.

I will have a look at it!

**Comment by ggouaillardet** [comment] 2020-02-09 05:43
@opoplawski I cannot reproduce this issue.

I installed the latest `rawhide`, and rebuilt from `openmpi-4.0.2-0.5.rc2.fc31.src.rpm` (I could not find package for `4.0.2-5.fc32`), and then

```
$ nm /usr/lib/debug/usr/lib64/openmpi/lib/libmpi_usempif08.so.40.20.1-4.0.2-0.5.rc2.fc32.x86_64.debug  | grep 2int
000000000003c01c B ompi_f08_mpi_2integer
```

so I could not find anything related to `ompi_f08_mpi_2int` nor `__mpi_f08_types_MOD_mpi_2int`.

Just to be clear on the changes, some Fortran definitions were revamped (C binding was replaced by a `parameter` definition), but the C binding symbols were preserved not to break the ABI compatibility.

Could you please post guidelines on how to reproduce this issue?

**Comment by opoplawski** [comment] 2020-02-09 20:33
This is strange.  Currently the openmpi update tests are not working (https://bodhi.fedoraproject.org/updates/FEDORA-2020-bb851fb93e show "no previous stable build").  So, I downloaded the openmpi, -devel, and -debuginfo packages for the 4.0.2-5.fc32 and 4.0.3rc3 builds from here:

https://koji.fedoraproject.org/koji/packageinfo?packageID=17

and ran:
```
$ abipkgdiff --d1 openmpi-debuginfo-4.0.2-5.fc32.x86_64.rpm --d2 openmpi-debuginfo-4.0.3rc3-1.fc32.x86_64.rpm --devel1 openmpi-devel-4.0.2-5.fc32.x86_64.rpm --devel2 openmpi-devel-4.0.3rc3-1.fc32.x86_64.rpm openmpi-4.0.2-5.fc32.x86_64.rpm openmpi-4.0.3rc3-1.fc32.x86_64.rpm
================ changes of 'libmpi_usempif08.so.40.20.1'===============
  Functions changes summary: 0 Removed, 0 Changed, 0 Added function
  Variables changes summary: 0 Removed, 0 Changed, 43 Added variables
  Function symbols changes summary: 0 Removed, 0 Added function symbol not referenced by debug info
  Variable symbols changes summary: 0 Removed, 106 Added variable symbols not referenced by debug info

  43 Added variables:

    'ompi_fortran_08_handle_t ompi_f08_mpi_2int'    {ompi_f08_mpi_2int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_bool'    {ompi_f08_mpi_c_bool}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_complex'    {ompi_f08_mpi_c_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_double_complex'    {ompi_f08_mpi_c_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_float_complex'    {ompi_f08_mpi_c_float_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_c_long_double_complex'    {ompi_f08_mpi_c_long_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_char'    {ompi_f08_mpi_char}
    'ompi_fortran_08_handle_t ompi_f08_mpi_count'    {ompi_f08_mpi_count}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_bool'    {ompi_f08_mpi_cxx_bool}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_complex'    {ompi_f08_mpi_cxx_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_double_complex'    {ompi_f08_mpi_cxx_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_float_complex'    {ompi_f08_mpi_cxx_float_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_cxx_long_double_complex'    {ompi_f08_mpi_cxx_long_double_complex}
    'ompi_fortran_08_handle_t ompi_f08_mpi_double'    {ompi_f08_mpi_double}
    'ompi_fortran_08_handle_t ompi_f08_mpi_double_int'    {ompi_f08_mpi_double_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_float'    {ompi_f08_mpi_float}
    'ompi_fortran_08_handle_t ompi_f08_mpi_float_int'    {ompi_f08_mpi_float_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int'    {ompi_f08_mpi_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int16'    {ompi_f08_mpi_int16}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int32'    {ompi_f08_mpi_int32}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int64'    {ompi_f08_mpi_int64}
    'ompi_fortran_08_handle_t ompi_f08_mpi_int8'    {ompi_f08_mpi_int8}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long'    {ompi_f08_mpi_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_double'    {ompi_f08_mpi_long_double}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_double_int'    {ompi_f08_mpi_long_double_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_int'    {ompi_f08_mpi_long_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_long'    {ompi_f08_mpi_long_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_long_long_int'    {ompi_f08_mpi_long_long_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_no_op'    {ompi_f08_mpi_no_op}
    'ompi_fortran_08_handle_t ompi_f08_mpi_offset'    {ompi_f08_mpi_offset}
    'ompi_fortran_08_handle_t ompi_f08_mpi_short'    {ompi_f08_mpi_short}
    'ompi_fortran_08_handle_t ompi_f08_mpi_short_int'    {ompi_f08_mpi_short_int}
    'ompi_fortran_08_handle_t ompi_f08_mpi_signed_char'    {ompi_f08_mpi_signed_char}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint16'    {ompi_f08_mpi_uint16}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint32'    {ompi_f08_mpi_uint32}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint64'    {ompi_f08_mpi_uint64}
    'ompi_fortran_08_handle_t ompi_f08_mpi_uint8'    {ompi_f08_mpi_uint8}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned'    {ompi_f08_mpi_unsigned}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_char'    {ompi_f08_mpi_unsigned_char}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_long'    {ompi_f08_mpi_unsigned_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_long_long'    {ompi_f08_mpi_unsigned_long_long}
    'ompi_fortran_08_handle_t ompi_f08_mpi_unsigned_short'    {ompi_f08_mpi_unsigned_short}
    'ompi_fortran_08_handle_t ompi_f08_mpi_wchar'    {ompi_f08_mpi_wchar}

  106 Added variable symbols not referenced by debug info:

    [A] __mpi_f08_types_MOD_mpi_2complex
    [A] __mpi_f08_types_MOD_mpi_2double_complex
    [A] __mpi_f08_types_MOD_mpi_2double_precision
    [A] __mpi_f08_types_MOD_mpi_2int
    [A] __mpi_f08_types_MOD_mpi_2integer
    [A] __mpi_f08_types_MOD_mpi_2real
    [A] __mpi_f08_types_MOD_mpi_aint
    [A] __mpi_f08_types_MOD_mpi_band
    [A] __mpi_f08_types_MOD_mpi_bor
    [A] __mpi_f08_types_MOD_mpi_bxor
    [A] __mpi_f08_types_MOD_mpi_byte
    [A] __mpi_f08_types_MOD_mpi_c_bool
    [A] __mpi_f08_types_MOD_mpi_c_complex
    [A] __mpi_f08_types_MOD_mpi_c_double_complex
    [A] __mpi_f08_types_MOD_mpi_c_float_complex
    [A] __mpi_f08_types_MOD_mpi_c_long_double_complex
    [A] __mpi_f08_types_MOD_mpi_char
    [A] __mpi_f08_types_MOD_mpi_character
    [A] __mpi_f08_types_MOD_mpi_comm_null
    [A] __mpi_f08_types_MOD_mpi_comm_self
    [A] __mpi_f08_types_MOD_mpi_comm_world
    [A] __mpi_f08_types_MOD_mpi_complex
    [A] __mpi_f08_types_MOD_mpi_complex16
    [A] __mpi_f08_types_MOD_mpi_complex32
    [A] __mpi_f08_types_MOD_mpi_complex8
    [A] __mpi_f08_types_MOD_mpi_count
    [A] __mpi_f08_types_MOD_mpi_cxx_bool
    [A] __mpi_f08_types_MOD_mpi_cxx_complex
    [A] __mpi_f08_types_MOD_mpi_cxx_double_complex
    [A] __mpi_f08_types_MOD_mpi_cxx_float_complex
    [A] __mpi_f08_types_MOD_mpi_cxx_long_double_complex
    [A] __mpi_f08_types_MOD_mpi_datatype_null
    [A] __mpi_f08_types_MOD_mpi_double
    [A] __mpi_f08_types_MOD_mpi_double_complex
    [A] __mpi_f08_types_MOD_mpi_double_int
    [A] __mpi_f08_types_MOD_mpi_double_precision
    [A] __mpi_f08_types_MOD_mpi_errhandler_null
    [A] __mpi_f08_types_MOD_mpi_errors_are_fatal
    [A] __mpi_f08_types_MOD_mpi_errors_return
    [A] __mpi_f08_types_MOD_mpi_file_null
    [A] __mpi_f08_types_MOD_mpi_float
    [A] __mpi_f08_types_MOD_mpi_float_int
    [A] __mpi_f08_types_MOD_mpi_group_empty
    [A] __mpi_f08_types_MOD_mpi_group_null
    [A] __mpi_f08_types_MOD_mpi_info_env
    [A] __mpi_f08_types_MOD_mpi_info_null
    [A] __mpi_f08_types_MOD_mpi_int
    [A] __mpi_f08_types_MOD_mpi_int16_t
    [A] __mpi_f08_types_MOD_mpi_int32_t
    [A] __mpi_f08_types_MOD_mpi_int64_t
    [A] __mpi_f08_types_MOD_mpi_int8_t
    [A] __mpi_f08_types_MOD_mpi_integer
    [A] __mpi_f08_types_MOD_mpi_integer1
    [A] __mpi_f08_types_MOD_mpi_integer16
    [A] __mpi_f08_types_MOD_mpi_integer2
    [A] __mpi_f08_types_MOD_mpi_integer4
    [A] __mpi_f08_types_MOD_mpi_integer8
    [A] __mpi_f08_types_MOD_mpi_land
    [A] __mpi_f08_types_MOD_mpi_lb
    [A] __mpi_f08_types_MOD_mpi_logical
    [A] __mpi_f08_types_MOD_mpi_logical1
    [A] __mpi_f08_types_MOD_mpi_logical2
    [A] __mpi_f08_types_MOD_mpi_logical4
    [A] __mpi_f08_types_MOD_mpi_logical8
    [A] __mpi_f08_types_MOD_mpi_long
    [A] __mpi_f08_types_MOD_mpi_long_double
    [A] __mpi_f08_types_MOD_mpi_long_double_int
    [A] __mpi_f08_types_MOD_mpi_long_int
    [A] __mpi_f08_types_MOD_mpi_long_long
    [A] __mpi_f08_types_MOD_mpi_long_long_int
    [A] __mpi_f08_types_MOD_mpi_lor
    [A] __mpi_f08_types_MOD_mpi_lxor
    [A] __mpi_f08_types_MOD_mpi_max
    [A] __mpi_f08_types_MOD_mpi_maxloc
    [A] __mpi_f08_types_MOD_mpi_message_no_proc
    [A] __mpi_f08_types_MOD_mpi_message_null
    [A] __mpi_f08_types_MOD_mpi_min
    [A] __mpi_f08_types_MOD_mpi_minloc
    [A] __mpi_f08_types_MOD_mpi_no_op
    [A] __mpi_f08_types_MOD_mpi_offset
    [A] __mpi_f08_types_MOD_mpi_op_null
    [A] __mpi_f08_types_MOD_mpi_packed
    [A] __mpi_f08_types_MOD_mpi_prod
    [A] __mpi_f08_types_MOD_mpi_real
    [A] __mpi_f08_types_MOD_mpi_real16
    [A] __mpi_f08_types_MOD_mpi_real2
    [A] __mpi_f08_types_MOD_mpi_real4
    [A] __mpi_f08_types_MOD_mpi_real8
    [A] __mpi_f08_types_MOD_mpi_replace
    [A] __mpi_f08_types_MOD_mpi_request_null
    [A] __mpi_f08_types_MOD_mpi_short
    [A] __mpi_f08_types_MOD_mpi_short_int
    [A] __mpi_f08_types_MOD_mpi_signed_char
    [A] __mpi_f08_types_MOD_mpi_sum
    [A] __mpi_f08_types_MOD_mpi_ub
    [A] __mpi_f08_types_MOD_mpi_uint16_t
    [A] __mpi_f08_types_MOD_mpi_uint32_t
    [A] __mpi_f08_types_MOD_mpi_uint64_t
    [A] __mpi_f08_types_MOD_mpi_uint8_t
    [A] __mpi_f08_types_MOD_mpi_unsigned
    [A] __mpi_f08_types_MOD_mpi_unsigned_char
    [A] __mpi_f08_types_MOD_mpi_unsigned_long
    [A] __mpi_f08_types_MOD_mpi_unsigned_long_long
    [A] __mpi_f08_types_MOD_mpi_unsigned_short
    [A] __mpi_f08_types_MOD_mpi_wchar
    [A] __mpi_f08_types_MOD_mpi_win_null

================ end of changes of 'libmpi_usempif08.so.40.20.1'===============

================ changes of 'libmpi_cxx.so.40.20.1'===============
  Functions changes summary: 0 Removed, 0 Changed, 0 Added function
  Variables changes summary: 0 Removed, 1 Changed, 0 Added variable

  1 Changed variable:

    [C]'const char MPI::ompi_libcxx_version_string[]' was changed at mpicxx.h:233:1:
      size of symbol changed from 6 to 9


================ end of changes of 'libmpi_cxx.so.40.20.1'===============
```
So with that I see added symbols, not removed ones, and so no ABI incompatibility.
```
$ nm libmpi_usempif08.so.40.20.1-4.0.2-5.fc32.x86_64.debug | grep ompi_f08_mpi_2int
000000000003c01c B ompi_f08_mpi_2integer
$ nm libmpi_usempif08.so.40.21.0-4.0.3rc3-1.fc32.x86_64.debug | grep ompi_f08_mpi_2int
000000000003f03c B ompi_f08_mpi_2int
000000000003f02c B ompi_f08_mpi_2integer
```
Also, I think the original report posted may have been attempting a comparison between 4.0.2-5.fc32 and 4.0.2-4.fc32 - though that seems odd that anything would have changed there.  Anyway, I think we are okay on the Fedora side.  Feel free to close if there isn't anything else you want to follow up on.

**Comment by ggouaillardet** [comment] 2020-02-10 05:23
Thanks for the update, I observe the same behavior : some symbols were added, but none were removed, so I will close this issue.

**Closed by ggouaillardet** 2020-02-10 05:23 UTC
