### ISSUE TITLE
Fix OSC RDMA to work in cases where one BTL cannot reach all communicator group members

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#7830] opened 2020-06-16 16:18 UTC
Cisco MTT shows that `MPI_WIN_CREATE` is failing since the OSC pt2pt component was removed (i.e., `MPI_WIN_CREATE` fails because there is no OSC component available).  [Here's an example of a simple test failing because `MPI_WIN_CREATE` failed](https://mtt.open-mpi.org/index.php?do_redir=3238).

After discussion on the 16 June 2020 weekly Open MPI webex, @hjelmn said that he could add a few functions to make OSC RDMA work in all cases (not just in cases where a single BTL can reach all members in the communicator group).

Marking this as a blocker for v5.0 because it's preventing MPI_WIN_CREATE from working in at least some environments, and because -- per the discussion between @hjelmn and @bwbarrett -- the fix to OSC RDMA doesn't seem too difficult.

**Comment by hjelmn** [comment] 2020-06-23 14:52
I have the implementation mostly complete. It will require reworking how BTL receive completions are handled but that is a good thing. Been looking at reworking those for years. I have a branch with the changes but I can not test usnic or portals4. I verified vader, tcp, and self. Will validate uGNI and UCX today.

**Comment by jsquyres** [comment] 2020-06-23 15:00
Send me the branch and what tests to run, and I'll check usnic.

**Comment by hjelmn** [comment] 2020-06-23 15:14
https://github.com/hjelmn/ompi/tree/btl_base_atomics_are_awesome

This only has the changes to the BTL receive logic. Please run a standard set of two-sided tests. IMB would work. Feel free to push back and changes btl/usnic needs.

The old receive callback got btl, tag, descriptor, cbdata. The new callback gets the btl and a new receive descriptor which contains the tag, endpoint, received message, and cbdata.

**Comment by hjelmn** [comment] 2020-06-23 15:15
Really curious if there are any performance regressions. There shouldn't be but that is going to be where any pushback will be.

**Comment by hjelmn** [comment] 2020-07-06 17:23
@jsquyres Ping. Please take a look at the branch mentioned above. I need to know if this change works for you as I can not verify the usnic BTL changes. I want to get this change approved and in this week so I can get the btl base atomics support finished.

**Comment by jsquyres** [comment] 2020-07-07 12:30
@hjelmn Sorry for the delay.  I ran the https://github.com/hjelmn/ompi/tree/btl_base_atomics_are_awesome branch last night and things generally look good.  I'm getting some random failures, but I'm apparently getting some random failures with master, too.  Specifically: with the btl_base_atomics_are_awesome branch, I'm seeing most (all?) of the one-sided tests that were failing are now passing.

We'll have to address the other random failures in another issue.

**Comment by jsquyres** [comment] 2020-08-26 17:09
This is still causing terabytes of corefiles with Cisco's MTT that I regularly have to manually clear out to avoid filling my filesystem.

I'm going to have to disable Cisco MTT's one-sided testing until this is fixed.

**Comment by jsquyres** [comment] 2020-08-26 17:42
I don't know if this is related to #7892 or not, but I figured I'd put in the cross-reference.

**Comment by gpaulsen** [comment] 2021-05-13 13:32
Austen said he has some time next week to take a look.  Thanks!

**Comment by awlauria** [comment] 2021-05-25 20:28
osc/rdma will internally call `MPI_Comm_split(MPI_COMM_TYPE_NODE)` to create a local group, and is getting some interesting/weird results. For example, I'm seeing the comm size on return be 3 when running 4 processes across 2 nodes, with 2 procs per node.

I have to think that https://github.com/open-mpi/ompi/issues/9010 is related.

**Comment by gpaulsen** [comment] 2021-06-17 17:12
@jsquyres @awlauria #9010 has been closed (some PMIx/PRRTE change, not root caused), so perhaps this issue also just needs to be retested?

**Comment by awlauria** [comment] 2021-06-17 17:29
It helps but I still run into issues.

Unfortunately I haven't had time to press on it much since the last update, and am out next week. Earliest I can give cycles on it would be the 28th.

**Comment by gpaulsen** [comment] 2021-08-31 15:34
oops, I accidentally clicked close, then re-opened it immediately.

**Comment by jsquyres** [comment] 2021-08-31 15:35
FYI @bosilca

**Comment by hjelmn** [comment] 2021-08-31 15:41
I plan to take a look this week.

**Comment by gpaulsen** [comment] 2021-09-16 14:31
@hjelmn Have you been able to reproduce?

**Comment by bosilca** [comment] 2021-09-17 23:35
Bad news. I run the onesided tests on one of our clusters with the current master (gf882930). They pass with the UCX OSC, and with RDMA OSC as long as only the sm BTL is in use.  As soon as I spread the rank across multiple nodes all one-sided tests fail (basic two-sided test pass so my BTL selection is legit).

**Comment by hjelmn** [comment] 2021-09-18 04:11
Same issue as described here? Where the comm split is wrong?

**Comment by bosilca** [comment] 2021-09-18 19:23
The communicator seems to be correct. I attached to one of the processes before it segfault, and the issue is in osc_rdma_lock.h, function ompi_osc_rdma_btl_fop, where the state_index is -1. The stack and peer variable do not look corrupted or uninitialized but both btl_index (state and data) of the peer object are set to 255 (because unsigned) and the selected_btl is then some memory location outside of the allocated array of BTLs.

**Comment by wzamazon** [comment] 2021-09-24 13:30
@bosilca Can you elaborate on the error you are seeing? what type of btl? what test? This may be related to https://github.com/open-mpi/ompi/issues/8983.

**Comment by bosilca** [comment] 2021-09-24 14:19
Any test from the onesided directory in ompi-tests. BTL: tcp and sm. As I said above I see either segfaults or deadlocks.

**Comment by rhc54** [comment] 2021-09-24 14:31
FWIW: the Cisco MTT now only shows segfaults from onesided tests and from the datatype "pack" function. It is otherwise running pretty well. Strictly tcp and sm there.

**Comment by bosilca** [comment] 2021-09-24 14:58
I applied the patch from #9400 and rerun the tests. Similar story as before, segfaults and deadlocks. To give a precise example, here is how I run it:
```shell
$ salloc -N 2 -wa,b
$ mpirun -np 4 --map-by node --mca osc rdma --mca btl tcp,self -ca btl_tcp_if_include ib0 ./test_dan1
```
The test segfault in lock_unlock stage. However, the same test segfault when using UCX as well.
```shell
$ mpirun -np 4 --map-by node --mca pml ucx ./test_dan1
```

**Comment by wzamazon** [comment] 2021-09-24 17:08
@bosilca I can reproduce the segfault when running `test_dan1`, I will look into it.

**Comment by wzamazon** [comment] 2021-09-24 22:36
@bosilca The segfault from the `lock_unlock` stage in `test_dan1` is because of locking type being two level. When locking type is two level, a process will first lock a global leader then lock the peer. The segfault happens when global leader is the process itself, in that case, because btl/tcp cannot do self communication, btl_index is 255, and selected_btl is NULL. adding `--mca osc_rdma_locking_mode on_demand` fixed this segfault. If I understand correctly, two level locking is an optimization, not a mandate, so we should just disable two level locking when btl/tcp is used.

However, even with on_demand locking, I encountered numerous issues like hang, segfault, and data corruption when running other tests under `ompi/onesided`.

I will make a list and keep looking into it.

**Comment by hjelmn** [comment] 2021-09-24 22:46
Honestly let's just change the default to on demand locking in this case.  The performance is not bad with on demand.

**Comment by wzamazon** [comment] 2021-09-27 21:11
I just updated https://github.com/open-mpi/ompi/pull/9400 to address several new issues I found

The biggest issue continue to be that btl/tcp does not support self communication. To address this issue, I added https://github.com/open-mpi/ompi/pull/9400/commits/b0197d91d828401ba0b7b8593e026f2215cb70eb which uses btl/self for self communication (if selected btl does not support self communication).

To make it work, I had to do some [refactor work](https://github.com/open-mpi/ompi/pull/9400/commits/6c4cb758da7b2d4ddaa2e9b241988bd0773eaa80) , and make some [change to btl/self](https://github.com/open-mpi/ompi/pull/9400/commits/ef501d88a0b5a320ec2b54b5ee3ee944c55212a0), and [change to osc/rdma](https://github.com/open-mpi/ompi/pull/9400/commits/5d9e5a2c18daf3ce8d461a21b6775eeee7ead41b).

Then there is another bug in osc/rdma in that the shm file name is not unique. I added https://github.com/open-mpi/ompi/pull/9400/commits/3c0ae03e48dd543ca941ac29e26953e4c89b2158 to address it.

With the current PR, most of the test under ompi-tests/onesided directory pass. except:

One negative test in t_winerror failed. The test was trying to free a non-existent window, and expect MPI_Win_free() to return MPI_WIN_ERROR, however, the error is considered fatal, so MPI aborted. I am not sure how (or should) we can fix it. Similar issue with test_start1.

lock4, get2 randomly hang on two nodes, I will continue investigate

put1, put4 data validation error on two nodes. I will continue investigate.

**Comment by hjelmn** [comment] 2021-09-28 02:12
Catching up. Can btl/sm not be used? It allows self communication. When using tcp it should always also use btl/sm.

**Comment by hjelmn** [comment] 2021-09-28 02:15
But I could be remembering incorrectly :).

**Comment by wzamazon** [comment] 2021-09-28 04:05
>  Can btl/sm not be used?

Problem is people are running tests with the sm btl excluded (by specifying `--mca btl self,tcp`).

I do not have the full background. I wonder if there is an agreement that btl/tcp must be used with btl/sm (for osc/rdma)?

**Comment by gpaulsen** [comment] 2021-12-02 16:11
@bosilca You're assigned to this, but are you working this?

**Comment by wzamazon** [comment] 2021-12-02 17:00
https://github.com/open-mpi/ompi/pull/9696 will fix this issue too.

**Comment by awlauria** [comment] 2022-03-29 19:12
@jsquyres can we close this?

**Comment by awlauria** [comment] 2022-05-12 14:42
@jsquyres ping. can this be closed?

**Comment by awlauria** [comment] 2022-06-21 18:39
I think this is done.. @jsquyres if this is still an issue please re-open.

**Closed by awlauria** 2022-06-21 18:39 UTC
Labels: bug, Severity: blocker, Target: main, Target: v5.0.x
