### ISSUE TITLE
One-Sided: MPI_Put drop of performance compared with MPI_Send.

### ISSUE THREAD

**Issue by cayrols** [open-mpi/ompi#8652] opened 2021-03-18 23:44 UTC
### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)
I am using the current ompi master branch.

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

```shell
shell$ ompi_info                                                                                                                                   
                 Package: Open MPI scayrols@login3 Distribution                                                                              
                Open MPI: 5.1.0a1                                                                                                            
  Open MPI repo revision: v2.x-dev-8559-g09eb050                                                                                             
   Open MPI release date: Unreleased developer copy                                                                                          
                 MPI API: 3.1.0                                                                                                              
            Ident string: 5.1.0a1                                                                                                            
                  Prefix: /ccs/home/scayrols/Installs/ompi-git/gcc-7.4.0/gcc-/hwloc-1.11.11/cuda-11.2.0/ucx-1.10.0/summit                    
 Configured architecture: powerpc64le-unknown-linux-gnu                                                                                      
           Configured by: scayrols                                                                                                           
           Configured on: Thu Mar 18 19:33:06 UTC 2021                                                                                       
          Configure host: login3                                                                                                             
  Configure command line: '--prefix=/ccs/home/scayrols/Installs/ompi-git/gcc-7.4.0/gcc-/hwloc-1.11.11/cuda-11.2.0/ucx-1.10.0/summit'         
                          '--enable-picky' '--enable-visibility'                                                                             
                          '--enable-contrib-no-build=vt'                                                                                     
                          '--enable-mpirun-prefix-by-default'                                                                                
                          '--enable-dlopen' '--enable-mpi1-compatibility'                                                                    
                          '--enable-shared'                                                                                                  
                          '--enable-mpirun-prefix-by-default' '--with-cma'                                                                   
                          '--with-hwloc=/ccs/home/scayrols/Installs/hwloc-1.11.11/gcc-7.4.0/gcc-'                                            
                          '--with-cuda=/sw/summit/cuda/11.2.0'                                                                               
                          '--with-zlib=/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/zlib-1.2.11-tdykbkiueylpgx2rshpms3k3ncw5g3f6'                                                                                                          
                          '--with-ucx=/ccs/home/scayrols/Installs/ucx-1.10.0/gcc-7.4.0/gcc-/hwloc-1.11.11/cuda-11.2.0/gdrcopy-'              
                          '--with-mxm=/opt/mellanox/mxm'                                                                                     
                          '--with-pmix=internal' '--with-wrapper-ldflags='                                                                   
                          '--without-lsf' '--without-psm'                                                                                    
                          '--without-libfabric' '--without-verbs'                                                                            
                          '--without-psm2' '--without-alps' '--without-sge'                                                                  
                          '--without-slurm' '--without-tm'                                                                                   
                          '--without-loadleveler' '--disable-debug'                                                                          
                          '--disable-memchecker' '--disable-oshmem'                                                                          
                          '--disable-java' '--disable-mpi-java'                                                                              
                          '--disable-man-pages'                                                                                              
                Built by: scayrols                                                                                                           
                Built on: Thu Mar 18 19:44:30 UTC 2021
```
Note that we also installed the latest UCX 1.10

```shell
shell$ ucx_info -v
# UCT version=1.10.0 revision 20697e5
# configured with: --disable-logging --disable-debug --disable-assertions --disable-params-check --prefix=/ccs/home/scayrols/Installs/ucx-1.10.0/gcc-7.4.0/gcc-/hwloc-1.11.11/cuda-11.2.0/gdrcopy- --enable-compiler-opt=3 --enable-optimizations --disable-profiling --disable-frame-pointer --disable-memtrack --disable-debug --disable-debug-data --disable-params-check --disable-backtrace-detail --disable-logging --disable-mt --with-cuda=/sw/summit/cuda/11.2.0 --with-gdrcopy=/sw/summit/gdrcopy/2.0
```

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.

```shell
shell$ git submodule status
 7145774ed059c9c3eca277805b419a16b8a68ca3 3rd-party/openpmix (v1.1.3-2852-g7145774)
 284d15d7b9be51c07ae3a3964b1567fde1a106e2 3rd-party/prrte (dev-31005-g284d15d)
```

### Please describe the system on which you are running
I am running on Summit.

* Operating system/version: 
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

We are comparing the classical MPI_Alltoall with a ring implementation of it using either MPI_Isend/MPI_Irecv/MPI_Waitall or MPI_Put/MPI_Win_fence.
We observe a lower bandwidth when we are using MPI_Put, as shown below. 
  | #Node |   ROUTINE     |      sendcount     |  sizeof(double)    |   TotVolume | totTime       |    avgTime |   BW (GB/s) |
  | :--- | :--- |  - | - | ---: | ---: | ---: | ---: |
  |one|      MPI_Alltoall  |   1000000    |         8  |  48000000     |      83.16    |        4.16    |       10.75|
  ||         RingSend  |   1000000    |         8  |  48000000     |      51.34    |        2.57    |       17.41|
  ||          RingPut    |   1000000    |         8  |  48000000     |     296.60   |        14.83  |        **3.01**|
  |two|  MPI_Alltoall  |   1000000  |           8|    96000000   |       445.53  |         22.28    |        4.01|
  ||          RingSend   |  1000000   |         8  |  96000000     |     400.23   |        20.01  |          4.47|
  ||           RingPut     |1000000      |      8    |96000000       |   638.39     |      31.92    |        **2.80**|
|three| MPI_Alltoall  |   1000000     |        8 |  144000000   |       789.32|           39.47|            3.40|
  ||          RingSend  |   1000000     |        8 |  144000000   |       750.75|           37.54|            3.57|
  ||           RingPut    |   1000000     |        8 |  144000000   |       975.07|           48.75|            **2.75**|
|four| MPI_Alltoall    |   1000000     |        8 |  192000000   |      1123.84 |          56.19    |        3.18|
  ||          RingSend  |   1000000      |       8 |  192000000   |      1098.05 |          54.90    |        3.26|
  ||           RingPut    |   1000000      |       8 |  192000000   |      1321.54 |          66.08    |        **2.71**|

In this table, we display the routine used, the number of double sent to each destination ( 1e6, 8 Bytes ) and the total volume, total time to perform 20 all2all, the average time to perform one all2all, the bandwidth.
From this, we note a large drop in terms of performance (60 to 80% of what MPI_Alltoall can achieve).

We attach a reproducer to make more experiments.
[measure_bw.txt](https://github.com/open-mpi/ompi/files/6167729/measure_bw.txt)

Therefore, it would be great to have your feedback about this performance issue.
@bosilca any idea ?

Thank you,
Sébastien Cayrols

PS: Note that this behavior is also observed for p2p communication. We cannot reach the 12,5GB/s on Summit using MPI_Put, or even the 25GB/s when using two rails.

### Compilation
The code got compiled as follows:
```shell
shell$ nvcc -std=c++11 -o build/measure_bw.o -c measure_bw.cu -I /ccs/home/scayrols/Installs/ompi-git/gcc-7.4.0/gcc-/hwloc-1.11.11/cuda-11.2.0/ucx-1.10.0/summit/include -I /sw/summit/cuda/11.2.0/targets/ppc64le-linux/include -O3 -Xcompiler " -fPIC -Wall -Wno-unused-function " -std=c++11 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70
shell$ nvcc -o ../bin/measure_bw build/measure_bw.o -L /ccs/home/scayrols/Installs/ompi-git/gcc-7.4.0/gcc-/hwloc-1.11.11/cuda-11.2.0/ucx-1.10.0/summit/lib -lmpi -L /sw/summit/cuda/11.2.0/targets/ppc64le-linux/lib -lcudart -lm -lcuda
```

### Execution
We run the code in interactive session, providing the list of hosts with six ranks per node, like this:
```shell
shell$ mpirun -n <nprocs, i.e., nnode * 6> -H <list of hosts:6>-x LD_LIBRARY_PATH --mca pml ucx --mca osc ucx -x UCX_ZCOPY_THRESH=1 -x UCX_RNDV_SCHEME=get_zcopy -x UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy -x UCX_MAX_RNDV_RAILS=1 -x UCX_NET_DEVICES=mlx5_0:1,mlx5_3:1 ./measure_bw
```

**Comment by janjust** [comment] 2021-04-20 15:59
@cayrols Just to confirm, the ppn count = gpu count? In these experiments?

**Comment by janjust** [comment] 2021-04-20 16:01
I did a quick, 1ppn, on 2 nodes on a local system:

$mpirun -n 2 -H ops003:1,ops004:1 -x LD_LIBRARY_PATH -mca pml ucx -mca osc ucx -x UCX_ZCOPY_THRESH=1 -x UCX_RNDV_SCHEME=get_zcopy -x UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy -x UCX_MAX_RNDV_RAILS=1 -x UCX_NET_DEVICES=mlx5_0:1 ./measure_bw
```
        MPI_Alltoall     1000000             8    16000000           78.48            3.92            3.80
            RingSend     1000000             8    16000000           66.72            3.34            4.47
             RingPut     1000000             8    16000000           67.00            3.35            4.45
```

Here put implementation is faster, but, I'm just in the stages to reproduce the issue.

**Comment by cayrols** [comment] 2021-04-20 16:12
@janjust Thank you for doing this !

Yes, the ppn is the number of GPUs per node.

About your initial test, it is kind of a point to point communication plus a local mem copy.
Is it normal to reach only 4.5GB/s on your machine ? What is the output bandwidth on your machine ?
What do you get on a single node ? single socket if you have more than one ?

**Comment by janjust** [comment] 2021-04-20 18:04
I wouldn't call this normal :)

**Comment by janjust** [comment] 2021-04-20 22:21
@cayrols 

So the original system had an issue, so I moved over to another system and here osu_bw/bibw achieves line rate.

However, after looking at the benchmark I think I know what the issue is:

Has to do with ucx' put/get API not supporting TAGGED api.
Seems that put get will not use nvlink hence the drop in performance when you’re increasing ppn count.
This can be demonstrated when removing cuda_ipc TLS in UCX.
```

$ mpirun -x CUDA_VISIBLE_DEVICES=0,2 -np 2 --map-by ppr:1:socket --report-bindings --hostfile host.list -x LD_LIBRARY_PATH -mca pml ucx -mca osc ucx -x UCX_ZCOPY_THRESH=1 -x UCX_RNDV_SCHEME=get_zcopy -x UCX_TLS=ib,cuda_copy,gdr_copy -x UCX_MAX_RNDV_RAILS=1 --tag-output ./run_wrapper.sh ./measure_bw
[1,0]<stderr>:[swx-dgx03.swx.labs.mlnx:67734] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../../../..]
[1,1]<stderr>:[swx-dgx03.swx.labs.mlnx:67734] MCW rank 1 bound to socket 1[core 20[hwt 0-1]]: [../../../../../../../../../../../../../../../../../../../..][BB/../../../../../../../../../../../../../../../../../../..]
[1,0]<stdout>:gpu = 0
[1,1]<stdout>:gpu = 1
[1,0]<stdout>:        MPI_Alltoall     1000000       8    16000000           28.12            1.41           10.60
[1,0]<stdout>:            RingSend     1000000       8    16000000           18.25            0.91           16.33
[1,0]<stdout>:             RingPut     1000000       8    16000000           17.49            0.87           17.04
tomislavj@swx-dgx03 /hpc/mtr_scrap/users/tomislavj/tests
$ mpirun -x CUDA_VISIBLE_DEVICES=0,2 -np 2 --map-by ppr:1:socket --report-bindings --hostfile host.list -x LD_LIBRARY_PATH -mca pml ucx -mca osc ucx -x UCX_ZCOPY_THRESH=1 -x UCX_RNDV_SCHEME=get_zcopy -x UCX_TLS=ib,cuda_ipc,cuda_copy,gdr_copy -x UCX_MAX_RNDV_RAILS=1 --tag-output ./run_wrapper.sh ./measure_bw
[1,0]<stderr>:[swx-dgx03.swx.labs.mlnx:67832] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../../../../../../../..][../../../../../../../../../../../../../../../../../../../..]
[1,1]<stderr>:[swx-dgx03.swx.labs.mlnx:67832] MCW rank 1 bound to socket 1[core 20[hwt 0-1]]: [../../../../../../../../../../../../../../../../../../../..][BB/../../../../../../../../../../../../../../../../../../..]
[1,1]<stdout>:gpu = 1
[1,0]<stdout>:gpu = 0
[1,0]<stdout>:        MPI_Alltoall     1000000       8    16000000           17.81            0.89           16.73
[1,0]<stdout>:            RingSend     1000000       8    16000000            8.06            0.40           36.98
[1,0]<stdout>:             RingPut     1000000       8    16000000           17.51            0.88           17.02
```

**Comment by janjust** [comment] 2021-04-21 13:49
@bosilca @cayrols
IMO this should be a feature request for the UCX community.

**Comment by janjust** [comment] 2022-03-21 13:57
Closing since it's a feature req. for UCX not an ompi issue.

**Closed by janjust** 2022-03-21 13:57 UTC
Labels: performance
