### ISSUE TITLE
btl/smcuda using NUMA nodes

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#7690] opened 2020-05-04 21:15 UTC
NUMA nodes don't really mean what they used to mean - as a result, "get_location" will almost always return that the process is "on" multiple NUMA nodes. The algorithm needs to be updated to look at some other indicator for locality.

**Comment by bosilca** [comment] 2021-01-21 18:51
I do not recall the specifics of this discussion. Looking in the smcuda BTL at what we do with the NUMA locality information it seems unnecessary to bother find it in an accurate way, simply because we never use it. If someone else can confirm that I correctly understood the code path, we should demote, or even completely scrap, this issue.

**Comment by rajachan** [comment] 2021-01-21 18:56
@Akshay-Venkatesh, for comment.

**Comment by Akshay-Venkatesh** [comment] 2021-01-27 17:33
@bosilca Not sure if I follow the problem. Can you elaborate if you don't mind?

**Comment by bosilca** [comment] 2021-01-27 18:06
Neither do I. I recall long ago we were careful to place the temporary memory on the local NUMA node to minimize the burden, but I don't see that logic in the code anymore. Plus, I think that even for same node GPU to GPU transfers we are not falling back to UCX, so this issue might be irrelevant now.

**Comment by gpaulsen** [comment] 2021-05-13 13:43
Not a blocker as this issue is referencing a potential performance issue.
It's unclear in what use-cases that btl/smcuda is used today in master/v5.0.x.  Does anyone know?  @bosilca ?

**Comment by janjust** [comment] 2024-01-25 17:59
Not a bug, maybe a performance issue, but until we see the performance impact I find this issue unnecessary. Closing please reopen if needed.

**Closed by janjust** 2024-01-25 17:59 UTC
Labels: performance, Target: v5.0.x
