### ISSUE TITLE
about  ialltoallw

### ISSUE THREAD

**Issue by mathbird** [open-mpi/ompi#3480] opened 2017-05-08 20:34 UTC
Hi, 
 
[ialltoallvw_zero.c.txt](https://github.com/open-mpi/ompi/files/984770/ialltoallvw_zero.c.txt)

 The attached test code pass with MPICH well, but has problems with OpenMPI.
 
There are three tests in the code, the first passes, the second one hangs, and the third one results in seg. fault and core dump.
 
The hanging seemed caused by the handle in the function ompi_coll_libnbc_ialltoallw in mca/coll/libnbc/nbc_ialltoallw.c, where it is not set correctly for the request, based on the input parameters.
 
The the seg fault is caused by ompi_datatype_type_size(sendtypes[me], &sendtype_size); //sendtypes[me] = NULL.

 any suggestion?

 Dahai

**Comment by ggouaillardet** [comment] 2017-05-09 01:47
@mathbird thanks for the report, a few fixes were not backported into the ```v2``` branches, and i made PR for both.
fwiw, ```master``` and ```v3.x``` are fine
btw, which Open MPI version are you running ?

**Comment by mathbird** [comment] 2017-05-09 15:18
I am using openmpi 2.1.  with your updated code, the tests did pass.  Thanks

**Comment by hppritcha** [comment] 2017-08-09 15:39
@ggouaillardet can this issue be closed now?

**Comment by ggouaillardet** [comment] 2017-08-10 00:00
yes, the issue is fixed from ```v2```, so let's close this issue

**Closed by ggouaillardet** 2017-08-10 00:00 UTC
Labels: bug, Target v2.0.x, Target: 2.x
