### ISSUE TITLE
MPIX_Query_cuda_support always returns 0

### ISSUE THREAD

**Issue by eromero-vlc** [open-mpi/ompi#11070] opened 2022-11-14 20:26 UTC
I'm not able to make `MPIX_Query_cuda_support` to return a nonzero value with OpenMPI version 5.

This is the definition of `MPIX_Query_cuda_support`:
```
int MPIX_Query_cuda_support(void)
{
    return opal_built_with_cuda_support && opal_cuda_runtime_initialized;
}
```
I look into the code and I didn't find where `opal_cuda_runtime_initialized` is set to true.

**Comment by jsquyres** [comment] 2022-11-14 20:38
What version of Open MPI are you using?  Can you provide all the information that was requested in the github issue template?

**Comment by eromero-vlc** [comment] 2022-11-14 21:00
## Background information

### What version of Open MPI are you using? (e.g., v3.0.5, v4.0.2, git branch name and hash, etc.)

5.0.0rc9

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Source distribution tarball

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.



### Please describe the system on which you are running

* Operating system/version: Ubuntu 20.04
* Computer hardware: intel core I9; NVIDIA Quadro T2000
* Network type: none

-----------------------------

## Details of the problem

I compile UCX and OpenMPI with cuda support. I checked the value of `mpi_butil_with_cuda_support`:
```bash
$ ompi_info --parsable --all | grep mpi_built_with_cuda_support:value
mca:mpi:base:param:mpi_built_with_cuda_support:value:true
```
But a simple program like this never prints anything for OpenMPI version 5.0.0rc9 but prints something for OpenMPI 4.1.4
```
#include "mpi.h"
#include "mpi-ext.h"
#include <stdio.h>

int main(int argc, char **argv) {
    MPI_Init(&argc, &argv);
    if (MPIX_Query_cuda_support() != 0) printf("mpi with cuda support\n");
    MPI_Finalize();
    return 0;
}
```

**Comment by jsquyres** [comment] 2022-11-14 21:02
@eromero-vlc Thanks.

FYI @open-mpi/ucx team.

**Comment by wckzhang** [comment] 2022-11-14 23:01
Ah I think this is a miss when I added the cuda component. I can write a quick fix for this

**Comment by wckzhang** [comment] 2022-11-14 23:12
Do you want to test with - https://github.com/open-mpi/ompi/pull/11071 That should fix it I believe.

**Comment by janjust** [comment] 2022-12-01 21:12
@eromero-vlc #11071 is merged - please retest and let's close if fixed

**Comment by EricHallahan** [comment] 2023-01-17 20:09
As far as I can tell, the described test now succeeds in printing as intended and this issue is resolved.

**Closed** 2023-01-17 20:10 UTC
Labels: bug, Target: main, Target: v5.0.x
