### ISSUE TITLE
flush_and_invalidate_cache is not valid for ARM64 platform

### ISSUE THREAD

**Issue by hoopoepg** [open-mpi/ompi#5631] opened 2018-08-30 11:48 UTC
Thank you for taking the time to submit an issue!

## Background information
ARM64 based platforms need actions to invalidate instruction cache after code-modification

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
Actual for all OMPI versions 3.0+ (not tested on other versions)

### Please describe the system on which you are running

* Operating system/version: 
* Computer hardware: 
ARM64
* Network type: 

-----------------------------

## Details of the problem
Implementing binary patching in UCX we found that ARM64 processor's instruction cache is actual for a long time which makes binary patching not effective some time after patching completed (may be executed original code instead of updated instructions). To force flushing instruction cache compiler intrinsic __clear_cache may be used, for reference UCX sources may be used:
https://github.com/openucx/ucx/blob/bac22184987518b990b006bf9f02bbff46745d28/src/ucs/arch/cpu.h#L79
and
https://github.com/openucx/ucx/blob/bac22184987518b990b006bf9f02bbff46745d28/src/ucs/arch/aarch64/cpu.h#L99

@hjelmn what do you think?

**Comment by jsquyres** [comment] 2018-08-30 14:35
FYI @shamisp @jjones-cavium @bosilca @ggouaillardet @nSircombe

**Comment by shamisp** [comment] 2018-08-30 15:41
@hjelmn DSB is not enough. Please see [https://community.arm.com/processors/b/blog/posts/caches-and-self-modifying-code](https://community.arm.com/processors/b/blog/posts/caches-and-self-modifying-code)

**Comment by rhc54** [comment] 2018-08-30 15:43
@shamisp Since this is an ARM issue, perhaps someone from your community could provide the necessary patch? Seems unfair for us to automatically dump these things on @hjelmn all the time.

**Comment by shamisp** [comment] 2018-08-30 15:51
Since historically @hjelmn has been maintaining this code, @hoopoepg is trying to be polite and brought this up to @hjelmn attention for further discussion, instead of dumping some code without proper discussion. From the thread I don't see anybody dumping anything on @hjelmn . This what I would consider constructive technical discussion.

**Comment by hjelmn** [comment] 2018-08-30 16:00
@shamisp Thanks for the info. We will make the change.

**Comment by rhc54** [comment] 2018-08-30 16:01
I wasn't trying to be nasty or imply you were doing anything wrong - my point was solely to suggest that ARM take a more active role in supporting ARM-related code. In other words, rather than posting a bug and telling someone the current code doesn't work, another approach is to file a PR and ask for comment.

I'd like to see some organizations be a bit more proactive - hence the comment.

**Comment by jjones-cavium** [comment] 2018-08-30 18:44
As a starting point, here is the code from the ARM Architecture Manual, section B2.2.5, for invalidating modified instructions. [ARM DDI 0487C.a]
```assembly
; Coherency example for data and instruction accesses within the same Inner Shareable domain.
; Enter this code with <Wt> containing a new 32-bit instruction, 
; to be held in Cacheable space at a location pointed to by Xn. 
        STR Wt, [Xn]
        DC CVAU, Xn   ; Clean data cache by VA to point of unification (PoU) 
        DSB ISH       ; Ensure visibility of the data cleaned from cache 
        IC IVAU, Xn   ; Invalidate instruction cache by VA to PoU
        DSB ISH       ; Ensure completion of the invalidations
```

**Comment by shamisp** [comment] 2018-08-30 20:05
Arguably, more productive approach is an opening of issue and conducting technical discussion about potential resolution instead of spending time on unacceptable solution or re-inventing the wheel.

Regardless, ARM has multiple partners developing hardware based on ARM ISA (or uarch). Not necessary all issues and solutions will be coming directly from ARM. In many cases, issues are discovered and resolved by our partners without arm been directly in the loop. In this case @hoopoepg  identified the problem and came up with a solution that works for UCX. It is not granted that it is the best fit for OpenMPI (after all it is self modifying code!) and this is something that we discuss here with the original author of the code.

Obviously, there is always room for improvement what/how arm can contribute to the project. Over the last year we have been ramping up efforts in this space. We deployed Open MPI ThunderX1 regression machine in HPCAC and we are in process of adding and deploying additional servers based on Arm architecture to CI. In addition we provided some of the OpenMPI developers with Arm based desktops. BTW, if you need one please shoot me an email. In the same time @nSircombe and I are catching up with recent discussions on mailing list and github.

If for whatever reason anybody here felt that we ``` automatically dump```- I really apologies about this. Clearly this was not the intend.

**Comment by rhc54** [comment] 2018-08-30 21:26
I have no issue with any of that - the original conversation seemed to say "here is a problem and some links to technical stuff relating to it". It never gave an indication that ARM would be providing the solution, or was offering to do so. Knowing @hjelmn for many years, he would probably take this as a "you need to fix this" directive...as would I if you had cited me under similar circumstances.

What I'd like to see is more members contributing to the code. It feels at least as if there is a growing trend that has fewer and fewer people actually contributing, with more just filing issues and declaring "it's not my code". As a community, we need to reverse that trend. Only way I know to do that is to start pointing out places where those who file an issue could just as easily have filed the solution.

Whether this is such a case or not is something we could argue forever. I think perhaps the best solution would be to suggest that people make clear when filing an issue that they intend to also submit the eventual solution and are seeking technical discussion towards that objective. Maybe assign it to yourself as a way of doing so?

It would clarify your intent. I'm glad to hear you were intending to provide the fix anyway, and apologize for the miscommunication.

**Comment by hjelmn** [comment] 2018-08-30 21:58
There are two issues here:
 1) We should use the compiler ___cache_flush intrinsic when it is available. I am working on a patch now.
 2) The current flush form for ARM64 is not correct. The fix was provided in this bug and will be in the patch. I will run some smoke tests but it will need testing from ARM.

**Comment by jsquyres** [comment] 2018-08-30 22:02
@hjelmn Minor correction: "...will need testing from *the ARM community.*"

I only mention this because @shamisp made the good point that ARM is one company, but there are many vendors who make products based on the ARM architecture.

**Comment by hjelmn** [comment] 2018-08-30 22:04
@jsquyres Indeed.

**Closed** 2018-09-10 21:43 UTC
Labels: question
