### ISSUE TITLE
UCX and MPI one-sided in v4.1.0

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#8379] opened 2021-01-14 16:08 UTC
From https://www.mail-archive.com/users@lists.open-mpi.org/msg34261.html:

> Why does 4.1 still not use the right defaults with UCX?
> 
> Without specifying osc=ucx, IMB-RMA crashes like 4.0.5.  I haven't checked what else it is UCX says you must set for openmpi to avoid memory corruption, at least, but I guess that won't be right either. Users surely shouldn't have to explore notes for a fundamental library to be able to run even IMB.

FYI @loveshack

**Comment by hoopoepg** [comment] 2021-01-14 16:31
Hi

I tried to send e-mail to original thread, but it was rejected... So, duplicate it here:

Thank you for bug report.

Could you describe your system:

- What OS is used? How OMPI/UCX were installed
- Is your application launched on single node or multiple nodes were used
- What is command line?
- Could you also provide output from commands:
```
ompi_info --version
ucx_info -v
ucx_info -pwe -D net -u t
ucx_info -pwe -D net -u r
ucx_info -pwe -D shm -u t
ucx_info -pwe -D shm -u r
ucx_info -d
```

Thank you

**Comment by loveshack** [comment] 2021-01-14 18:40
The problem is #8102.

However, I mis-remembered that osc=ucx came from the ucx doc, apologies.
That just says you must avoid the uct btl, which OMPI 4.1 still builds
and uses.  I realize that with btl ^uct, at least that failure goes
away.

**Comment by bosilca** [comment] 2021-01-19 17:26
The UCT BTL is only built with a version of UCX prior to [1.9](https://github.com/open-mpi/ompi/blob/53bb30f6d163c09d117f781763fe9034cf03c66a/opal/mca/btl/uct/configure.m4#L55). What version of UCX are you using here ?

**Comment by jsquyres** [comment] 2021-01-26 16:05
@loveshack Can you reply?  Thanks!

**Comment by loveshack** [comment] 2021-01-29 14:17
See my reply in #8379

**Comment by jsquyres** [comment] 2021-02-15 20:25
@loveshack Should I interpret your last comment to mean that we can close this issue (and #8102)?

**Comment by loveshack** [comment] 2021-02-17 10:37
> @loveshack Should I interpret your last comment to mean that we can
> close this issue (and #8102)?

This one can be closed as the openmpi configure does avoid building the
uct btl, despite what the UCX doc still says (although That doesn't
solve the fundamental problem with RMA on POWER).

It would be helpful if someone authoritative could get
https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX
changed.

**Comment by yosefe** [comment] 2021-02-17 10:40
> It would be helpful if someone authoritative could get https://github.com/openucx/ucx/wiki/OpenMPI-and-OpenSHMEM-installation-with-UCX changed.

@loveshack do you mean that the note to disable "btl_uct" is no longer relevant because it's already disabled automatically by OpenMPI?

**Closed** 2021-02-17 15:02 UTC
Labels: Target: v4.1.x

**Comment by loveshack** [comment] 2021-02-22 19:32
> @loveshack do you mean that the note to disable "btl_uct" is no longer
> relevant because it's already disabled automatically by OpenMPI?

Yes.  At least it is with ucx 1.9 (but not <1.9 as far as I remember).
I don't know whether or not it's relevant for older versions.

**Comment by hjelmn** [comment] 2021-02-22 19:41
Thats the thing. It is not built with UCX 1.9 (though it works so I am bumping the version). By default the allowed TLs is set to none. That effectively disables the BTL. Not sure why osc/rdma continues to try to use it as it should not even appear in the active BTL module list.

I plan to look into this as soon as I have a chance. I need to get the osc/rdma changes for non-RDMA systems in before I do anything with this.
