### ISSUE TITLE
OSHMEM breaks static builds on master

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#1412] opened 2016-02-28 17:59 UTC
I get the following error on master when configured --enable-static --disable-shared:

```shell
runtime/oshmem_shmem_init.c:82:2: warning: #ident is a GCC extension [enabled by default]
 #ident OSHMEM_IDENT_STRING
  ^
/usr/bin/ld: ../../../oshmem/.libs/liboshmem.a(memheap_base_static.o): undefined reference to symbol '_end'
/usr/bin/ld: note: '_end' is defined in DSO /usr/lib64/libselinux.so.1 so try adding it to the linker command line
/usr/lib64/libselinux.so.1: could not read symbols: Invalid operation
```

@miked-mellanox could you please have someone address this?

**Comment by miked-mellanox** [comment] 2016-02-28 18:14
@rhc54 - does it happen on linux or macos?

**Comment by rhc54** [comment] 2016-02-28 18:17
This was on a CentOS7 box - haven't tried Mac yet

**Comment by igor-ivanov** [comment] 2016-03-01 16:19
Very close issue https://www.open-mpi.org/community/lists/users/2015/11/28015.php

**Comment by igor-ivanov** [comment] 2016-03-04 16:23
@rhc54 just if it is easy. Do you know ld version was used?

**Comment by rhc54** [comment] 2016-03-04 16:28
Sure

```shell
GNU ld version 2.23.52.0.1-30.el7_1.2 20130226
```

**Comment by igor-ivanov** [comment] 2016-03-09 15:36
_end is a symbol defined by the linker. I do not think that force adding libselinux.so is a way to go.
I would like to find out a root of issue.
I checked ompi/trunk 67e4502 on my system (it is not SentOS7) with binutils-2.23.52 and did not get issue.
Configure line:
```
--disable-vt --enable-orterun-prefix-by-default --enable-oshmem --with-slurm=/usr --with-pmix=/hpc/home/USERS/ivanovi/prj/pmix/pmix/build/install --with-libevent=/hpc/home/USERS/ivanovi/prj/pmix/tmp/libevent-2.0.22-stable/install --with-hwloc=/hpc/home/USERS/ivanovi/prj/pmix/tmp/hwloc-1.11/install --enable-static --disable-shared
```

``gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)``

``GNU ld version 2.20.51.0.2-5.36.el6 20100205``
and
``GNU ld (GNU Binutils) 2.23.52.20130918``

**Comment by jladd-mlnx** [comment] 2016-03-09 17:29
@rhc54 I am not completely in the details here (i.e. why is it breaking with this particular linker) , but I'm trying to figure out how urgent this is and what has changed. This code hasn't changed in three years and is running fine in several production Linux environments. So, is it accurate to say that OSHMEM breaks static builds or is more like CentOS7 breaks static OSHMEM builds? I think the latter.

**Comment by rhc54** [comment] 2016-03-09 20:02
I honestly don't know the extent of the problem. FWIW, I can't replicate it on the Mac - don't know about other Linux versions. I do recall that we have been seeing/reporting this for awhile, so it isn't something particularly new. I know that the OSHMEM code has changed quite a bit over the last year, but I don't know when we started seeing the issue, and so I don't know if we can really say whether it is something in OSHMEM or CentOS.

**Comment by igor-ivanov** [comment] 2016-03-10 15:42
@rhc54 I would appreciate it if you could share centos version (you can use https://linuxconfig.org/how-to-check-centos-version) and exact configure line.

**Comment by rhc54** [comment] 2016-03-10 15:50
CentOS Linux release 7.2.1511 (Core) 

```shell
./configure --prefix=<foo> --enable-static --disable-shared
```

**Comment by igor-ivanov** [comment] 2016-03-10 15:54
thank you

**Comment by jsquyres** [comment] 2016-03-10 16:26
I notice a specific indication of SE Linux in @rhc54's original report.  Could SE Linux be a factor here?

**Comment by igor-ivanov** [comment] 2016-03-11 09:19
@jsquyres interesting point. I will check (my system has it disabled ``SELINUX=disabled``).

**Comment by jsquyres** [comment] 2016-10-04 19:32
@igor-ivanov Is this issue moot / solved these days?

**Comment by igor-ivanov** [comment] 2016-10-05 05:28
@jsquyres I was not able to reproduce on my side. So probably it exists.

**Comment by jsquyres** [comment] 2016-10-05 09:50
@igor-ivanov I'll assume your first sentence was the correct one, and the 2nd sentence was a typo.  I'll go ahead and close this issue; feel free to re-open (or open a new one) if static building with OSHMEM is a problem.

**Closed by jsquyres** 2016-10-05 09:50 UTC
Labels: bug

**Comment by igor-ivanov** [comment] 2016-10-06 05:29
@rhc54 have you observed this issue more than once?
