### ISSUE TITLE
IBM MTT "make check" fail

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2966] opened 2017-02-14 17:07 UTC
@gpaulsen @jjhursey IBM is getting an MTT `make check` fail: https://mtt.open-mpi.org/index.php?do_redir=2391

The error is that the `opal_fifo` test is failing in 32 bit POWER on master.

**Comment by jjhursey** [comment] 2017-02-14 17:26
Duplicate of Issue #1893 - we need to investigate. It's intermittent so hard to pin down.

here is the output from `test-suite.log` in case it helps:
```
=====================================================================
   Open MPI master-201702120422-81e57bb: test/class/test-suite.log
=====================================================================

# TOTAL: 10
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: opal_fifo
===============

Exhaustive atomics thread finished. Popped 168490 items. Time: 6 s 451012 us 38287 nsec/poppush
Exhaustive atomics thread finished. Popped 170672 items. Time: 6 s 498624 us 38076 nsec/poppush
Exhaustive atomics thread finished. Popped 170704 items. Time: 6 s 555723 us 38404 nsec/poppush
Exhaustive atomics thread finished. Popped 171759 items. Time: 6 s 559438 us 38189 nsec/poppush
Exhaustive atomics thread finished. Popped 167076 items. Time: 6 s 625385 us 39654 nsec/poppush
Exhaustive atomics thread finished. Popped 167749 items. Time: 6 s 661287 us 39709 nsec/poppush
Exhaustive atomics thread finished. Popped 151657 items. Time: 6 s 659123 us 43909 nsec/poppush
Exhaustive atomics thread finished. Popped 149946 items. Time: 6 s 666284 us 44457 nsec/poppush
 Failure :  fifo push/pop multi-threaded with atomics when there are insufficient items
 Failure :  fifo pop all items
SUPPORT: OMPI Test failed: opal_fifo_t (2 of 8 failed)
Single thread test. Time: 0 s 71404 us 71 nsec/poppush
Atomics thread finished. Time: 0 s 124363 us 124 nsec/poppush
Atomics thread finished. Time: 8 s 346324 us 8346 nsec/poppush
Atomics thread finished. Time: 8 s 362706 us 8362 nsec/poppush
Atomics thread finished. Time: 8 s 398374 us 8398 nsec/poppush
Atomics thread finished. Time: 8 s 403718 us 8403 nsec/poppush
Atomics thread finished. Time: 8 s 600248 us 8600 nsec/poppush
Atomics thread finished. Time: 8 s 658165 us 8658 nsec/poppush
Atomics thread finished. Time: 8 s 870449 us 8870 nsec/poppush
Atomics thread finished. Time: 8 s 859184 us 8859 nsec/poppush
All threads finished. Thread count: 8 Time: 8 s 874685 us 1109 nsec/poppush
All threads finished. Thread count: 8 Time: 6 s 671116 us 833 nsec/poppush
FAIL opal_fifo (exit status: 1)
```

**Comment by jjhursey** [comment] 2017-05-09 15:08
PR #3468 might be related (might fix this issue - need to check)

**Comment by jsquyres** [comment] 2017-05-09 15:24
@jjhursey Let us knwo if #3468 fixes the issue -- we have corresponding PRs for v2.0.x, v2.1.x, and v3.0.x.

**Comment by jjhursey** [comment] 2017-05-09 17:27
😞  That PR does not seem to fix the `make check` issue. We'll have to keep investigating.

**Comment by jjhursey** [comment] 2017-05-11 11:42
Instead of failing now it is hanging (I have to manually kill it as it will hang the MTT runs - there is no timeout mechanism in `make check`). Here is a link to an MTT failure:
 * https://mtt.open-mpi.org/index.php?do_redir=2439

I suspect that the change made to fix Issue #3450 made this failure a hang now.

**Comment by jsquyres** [comment] 2017-05-11 15:10
@bosilca @hjelmn It looks like the recent changes to opal_fifo just changed the failure mode for IBM.  Can you have a look at Josh's comment (https://github.com/open-mpi/ompi/issues/2966#issuecomment-300764540)?

**Comment by bosilca** [comment] 2017-05-11 19:54
First and foremost, the failure is on ppc64le, I have no access to such an architecture. What is puzzling is that I was under the impresison that for PPC we were using atomic load/store (via OPAL_HAVE_ATOMIC_LLSC_PTR) but apparently this is not the case.

I run 10k tests on different Intel architectures with an OMPI compiler is optimized mode, and I had no failure. No really sure how to approach this issue.

**Comment by jsquyres** [comment] 2017-05-11 20:03
@jjhursey Looks like we're going to need some IBM help on this one...

**Comment by jjhursey** [comment] 2017-05-12 14:51
Yeah that's fine. I can investigate, but I'm not back full time yet so it'll be a little while before I can probably get eyes on this. I just wanted to keep this issue updated.
The hang mode is helpful though since I can then attach a debugger and poke around a bit.

**Comment by gpaulsen** [comment] 2017-05-12 16:34
I'm going to ask @nysal to drive this from our side, since Josh is apparently skydiving.

**Comment by jjhursey** [comment] 2017-06-12 17:27
There was a request to re-assess this ticket after PR #3661 - I did so and the problem still persists. We'll continue to investigate.

**Comment by gpaulsen** [comment] 2017-06-16 16:42
I thought we'd agreed not to support 32bit anymore in master.

**Comment by jjhursey** [comment] 2017-06-16 16:59
I can reproduce this on the 64 bit default build. I think the `32 bit` from the original message was a MTT config mistake on our end.

**Comment by hjelmn** [comment] 2017-07-05 16:03
Its possible the LL/SC fifo implementation has a bug. I will take a look this week and see if there is anything obvious.

**Comment by nmorey** [comment] 2017-07-07 07:32
I also see this problem pop up once in a while with SUSE openmpi2 packaging, on ppc64le only.

**Comment by jjhursey** [comment] 2017-08-24 13:44
Ref: PR #3988 Issue #3697

**Comment by jjhursey** [comment] 2017-08-24 13:53
Ref: PR #2526

**Comment by AdamWill** [comment] 2017-08-24 16:01
I am seeing the same test - `test_fifo` - hang on ppc64le during attempts to build openmpi 2.1.1 for Fedora. Every other arch completes successfully, but ppc64le just hangs after `test_lifo` passes, and eventually the job is killed when it reaches the build system's timeout.

**Comment by opoplawski** [comment] 2018-11-29 04:54
test_fifo still hangs in Fedora on ppc64le with 2.1.6rc1

**Comment by hjelmn** [comment] 2018-11-29 05:40
Ok.  Will dig deeper tomorrow. I know we have this fixed on master. Need to see what could be missing.

**Comment by jjhursey** [comment] 2021-03-17 14:17
@awlauria We were talking about this the other day. Is this resolved now?

We activated 'make check' for IBM's MTT runs. From last night's [run](https://mtt.open-mpi.org/index.php?&text_start_timestamp=2021-03-16+14%3A16%3A26+-+2021-03-17+14%3A16%3A26&show_start_timestamp=show&text_http_username=ibm&show_http_username=show&text_local_username=all&show_local_username=hide&text_platform_name=all&show_platform_name=show&text_platform_hardware=all&show_platform_hardware=show&text_os_name=all&show_os_name=show&text_mpi_name=all&show_mpi_name=show&text_mpi_version=all&show_mpi_version=show&text_configure_arguments=&show_configure_arguments=show&text_compiler_name=&show_compiler_name=show&text_bitness=&show_bitness=show&text_endian=&show_endian=show&go=summary&phase=mpi_install&text_trial=&text_compute_cluster_id=&text_os_version=&text_platform_type=&text_submit_id=&text_hostname=&text_mpi_get_id=&text_mpi_install_compiler_id=&text_mpi_install_configure_id=&text_mpi_install_id=&text_compiler_version=&text_vpath_mode=&text_exit_value=&text_exit_signal=&text_duration=&text_client_serial=&text_result_message=&text_result_stdout=&text_result_stderr=&text_environment=&text_description=&lastgo=summary) it looks like PGI  might still have a problem here with the v4.1.x branch.

**Comment by awlauria** [comment] 2021-03-17 14:32
Yeah, mtt hasn't run yet for 5.0.x and master last night, so we'll see where we stand then. So far pgi on the v4.1.x branch is the only failure.

**Comment by awlauria** [comment] 2021-03-18 17:50
https://github.com/open-mpi/ompi/pull/8649

may resolve this.

**Comment by jjhursey** [comment] 2021-03-25 15:51
Now that https://github.com/open-mpi/ompi/pull/8649 is merged are the `make check` issues resolved?

**Comment by awlauria** [comment] 2021-03-25 16:07
I need to cherry-pick that back to v4 and v5, but yeah I think we're probably good here.

**Comment by awlauria** [comment] 2021-03-25 17:59
v4.0.x: https://github.com/open-mpi/ompi/pull/8709
v4.1.x: https://github.com/open-mpi/ompi/pull/8708
v5.0.x: https://github.com/open-mpi/ompi/pull/8710

**Comment by awlauria** [comment] 2021-03-26 19:10
Note that the pr for v4.0.x was rejected, so we should consider adding

`--disable-builtin-atomics` to our v4.0.x mtt builds.

**Comment by awlauria** [comment] 2021-03-26 20:01
Our internal MTT has been updated to build v4.0.x with `--disable-builtin-atomics`

**Comment by awlauria** [comment] 2021-03-31 21:02
Closing this, haven't seen an mtt make-check failure recently. Will re-open if it pops up again.

**Closed by awlauria** 2021-03-31 21:02 UTC
Labels: bug
