### ISSUE TITLE
Race in pml_ob1_send_request_* code

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#137] opened 2014-10-01 16:20 UTC
In the pml_ob1_send_request_* code I believe there is a race condition which can result in a mca_pml_ob1_send_request_t object being returned to the free list by one thread while another thread still has a reference to that object. I don't have a test case for this as I found it by inspection. However I have seen it occur in the debugger while I was investigating a different race when some threads were artificially slowed  down. 

By design multiple threads can end up calling mca_pml_ob1_send_request_schedule. Threads are excluded from accessing critical regions at the same by using an atomic - threads are only allowed in incrementing the atomic results in a value of 1 indicating that they are the only thread active in the critical region. Threads are not blocked and return if another thread is active.

However there is nothing in place to ensure that all threads actually have returned and dropped any reference to the send request before another thread realises the send request has been completed and returns the request object to the free list.  If this object is then allocated for another request, the former thread will still be operating on the object potentially causing corruption.

So I think we need a use counter of some kind. I've attached a prototype patch that I believe fixes the problem for the path through ob1_frag_completion case. 

There are other similar cases but thought I'd throw this out first to get some feedback. Firstly although I think window for the race condition is really small, it can happen. Also if others think this is the right approach to fixing it.

**Comment by jsquyres** [comment] 2015-06-24 23:34
@bosilca Will this issue be resolved by #661?

**Comment by jsquyres** [comment] 2015-06-25 01:24
From verbal discussion at the dev meeting in June 2015: yes, this can happen.  It won't be fixed by #661.  @bosilca thinks that he knows how to fix it: make sure that all threads read whatever they need to read from the request before decrementing the length.

**Comment by bosilca** [comment] 2015-06-25 16:41
I spent some time looking at this again. It is a plausible but extremely unlikely. The problem is that we are trying to complete the request by calling send_request_pml_complete_check with the lock help, so the function does nothing. This force us to check the completion of the request once we release the lock, so outside the protected section.

**Comment by jsquyres** [comment] 2016-06-20 19:19
@bosilca @thananon It's over a year later.  Is it still an issue?

**Comment by bosilca** [comment] 2016-06-24 16:18
With the new request completion code I think this issue vanished.

**Comment by jsquyres** [comment] 2016-06-24 16:21
Sweet.  Should I close it?  I.e., it "should" have vanished, or "did" vanish?  😸

**Closed** 2016-08-09 15:16 UTC
Labels: bug, critical
