### ISSUE TITLE
buildrpm.sh build failed with internel libevent: Invalid version (double separator '-'): 2.1.12-stable-omp

### ISSUE THREAD

**Issue by xin3liang** [open-mpi/ompi#12469] opened 2024-04-16 08:59 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v4.1.6, v5.0.1, git branch name and hash, etc.)
branch: v5.0.x commit 1f87690b7d

### If you are building/installing from a git clone, please copy-n-paste the output from `git submodule status`.
```
(.venv) [root@client1 ompi]# git submodule status
 33e93469e1e1f69904ff3e3827394719aa6b3671 3rd-party/openpmix (v5.0.2)
 3a70fac9a21700b31c4a9f9958afa207a627f0fa 3rd-party/prrte (v3.0.5)
 dfff67569fb72dbf8d73a1dcf74d091dad93f71b config/oac (heads/main)

```

### Please describe the system on which you are running

* Operating system/version: 
```
(.venv) [root@client1 ompi]# lsb_release -a
LSB Version:    n/a
Distributor ID: openEuler
Description:    openEuler release 22.03 (LTS-SP3)
Release:        22.03
Codename:       LTS-SP3

```
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

when building rpm with buildrpm.sh it fails
```shell
git submodule update --init --recursive
diff --git a/VERSION b/VERSION
index 4388a23ce5..1361d960da 100644
--- a/VERSION
+++ b/VERSION
@@ -58,7 +58,7 @@ repo_rev=
 # tarball_version is not empty, the tarball filename will be of the
 # form openmpi-<tarball_version>.tar.*.

-tarball_version=gitclone
+#tarball_version=gitclone
./autogen.pl && ./configure && make dist
./contrib/dist/linux/buildrpm.sh -r "--define 'all_external_3rd_party 0'" -c "--with-lustre" -R ~/ompi/build/  -sbmo ./openmpi-5.0.4a1.tar.gz
...
RPM build errors:
    File listed twice: /opt/openmpi/5.0.4a1/share/doc/openmpi
    File listed twice: /opt/openmpi/5.0.4a1/share/openmpi/modulefiles
    File listed twice: /opt/openmpi/5.0.4a1/share/openmpi/modulefiles/openmpi
    File listed twice: /opt/openmpi/5.0.4a1/share/openmpi/modulefiles/openmpi/5.0.4a1
    File listed twice: /opt/openmpi/5.0.4a1/share/doc/openmpi
    File listed twice: /opt/openmpi/5.0.4a1/share/openmpi/modulefiles
    File listed twice: /opt/openmpi/5.0.4a1/share/openmpi/modulefiles/openmpi
    File listed twice: /opt/openmpi/5.0.4a1/share/openmpi/modulefiles/openmpi/5.0.4a1
    Invalid version (double separator '-'): 2.1.12-stable-ompi: pkgconfig(libevent) = 2.1.12-stable-ompi
    Invalid version (double separator '-'): 2.1.12-stable-ompi: pkgconfig(libevent_core) = 2.1.12-stable-ompi
    Invalid version (double separator '-'): 2.1.12-stable-ompi: pkgconfig(libevent_extra) = 2.1.12-stable-ompi
    Invalid version (double separator '-'): 2.1.12-stable-ompi: pkgconfig(libevent_pthreads) = 2.1.12-stable-ompi
*** FAILURE BUILDING SINGLE RPM!
Aborting

...

```

**Comment by wenduwan** [comment] 2024-04-24 18:13
Likely due to this commit https://github.com/open-mpi/ompi/commit/61e72f9f52a8c7fae23d1565e6b0191fc1da81f5

**Comment by wenduwan** [comment] 2024-04-24 19:43
We will look into this. Shouldn't be a hard fix.

**Comment by wenduwan** [comment] 2024-04-25 18:26
@xin3liang I tried to reproduce this issue on Amazon Linux 2023 following the provided steps but couldn't get the error. I wonder in particular how did you generate `openmpi-5.0.4a1.tar.gz`?

**Comment by xin3liang** [comment] 2024-04-26 01:52
> @xin3liang I tried to reproduce this issue on Amazon Linux 2023 following the provided steps but couldn't get the error. I wonder in particular how did you generate `openmpi-5.0.4a1.tar.gz`?

Hi @wenduwan thanks for spending time on this issue, please remember to download the git submodules `git submodule update --init --recursive`
I generate the tarball via comment the tarball_version, otherwise, you can replace it with openmpi-gitclone.tar.gz.
```
diff --git a/VERSION b/VERSION
index 4388a23ce5..1361d960da 100644
--- a/VERSION
+++ b/VERSION
@@ -58,7 +58,7 @@ repo_rev=
 # tarball_version is not empty, the tarball filename will be of the
 # form openmpi-<tarball_version>.tar.*.

-tarball_version=gitclone
+#tarball_version=gitclone
```

**Comment by wenduwan** [comment] 2024-04-28 01:53
@xin3liang I can finally reproduce the problem. Here is a fix for this particular issue https://github.com/open-mpi/ompi/pull/12501

However, I would recommend installing the external libevent for your distro, instead of using the internal libevent.

**Comment by wenduwan** [comment] 2024-04-30 14:19
@xin3liang What is your system libevent version? Is it possible to pre-install libevent on your hosts and avoid ompi's internal libevent?

**Comment by xin3liang** [comment] 2024-05-06 02:19
> @xin3liang What is your system libevent version? Is it possible to pre-install libevent on your hosts and avoid ompi's internal libevent?

It is libevent-2.1.12-7.  I can compile openMPI with the OS provided libevent.

**Comment by wenduwan** [comment] 2024-05-06 20:27
@xin3liang Thanks for confirming. In this case we strongly recommend using the system libevent instead.

For the record, we have stated this in our documentation https://docs.open-mpi.org/en/v5.0.x/installing-open-mpi/packagers.html#do-not-use-open-mpi-s-internal-dependent-libraries

**Closed** 2024-05-06 20:27 UTC
Labels: Target: v5.0.x
