### ISSUE TITLE
MPI spawn problems with 4.x series again

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#8005] opened 2020-08-14 18:14 UTC
A user has reported problems using Open MPI 4.0.4 when running on two or more hosts. 

https://www.mail-archive.com/users@lists.open-mpi.org//msg34036.html

I've reproduced the problem with the attached test (simplified from the one the user posted to the mailing list).  
The test works correctly with 4.0.1, but not 4.0.2.

Test case:
```
include "mpi.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char ** argv){
    int processesToRun;
    MPI_Comm parentcomm, intercomm;
    MPI_Info info;
    int rank, size, hostName_len;
    char hostName[200];
    MPI_Init( &argc, &argv );
    MPI_Comm_get_parent( &parentcomm );
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
    MPI_Get_processor_name(hostName, &hostName_len);

    if (parentcomm == MPI_COMM_NULL) {
        if(argc < 2 ){
            printf("Processes number needed!");
            return 0;
        }
        processesToRun = atoi(argv[1]);
        MPI_Info_create( &info );
        MPI_Info_set( info, "hostfile", "./hostfile" );
        MPI_Info_set( info, "map_by", "node" );
        MPI_Comm_spawn( argv[0], MPI_ARGV_NULL, processesToRun, MPI_INFO_NULL, 0, MPI_COMM_WORLD, &intercomm, MPI_ERRCODES_IGNORE);
        printf("I'm the parent.\n");
    } else {
        printf("I'm the spawned h: %s  r/s: %i/%i.\n", hostName, rank, size );
    }
    fflush(stdout);
    MPI_Finalize();
    return 0;
}
```
Its not clear yet whether this a problem in OMPI's dpm code or a problem in PMIx.

**Comment by hppritcha** [comment] 2020-08-14 23:08
The user is actually wanting to do something a little different from typical use cases.  He would like to start the ```spawnee``` process as a singleton, and only include in the hostfile (not used in the test above) the node where the spawned process will be launched.

**Comment by rhc54** [comment] 2020-08-14 23:25
Is there a "global" allocation (whether from an RM or via hostfile) that includes all the nodes that will eventually be used? If not, then I don't think this is something we have ever supported - if it worked, it is simply luck. If you use the "hostfile" option to specify where a particular process is to go, then _all_ the nodes that might be used must be passed at the beginning of time. You cannot do that with a singleton - you would have to use mpirun.

If you really do want to do it from a singleton, then you would have to use  the "add_host" (or "add_hostfile") option to indicate that the specified node(s) are to be added to the allocation. Again, that has likely never been tested when starting the whole thing from a singleton and I very much doubt it has ever worked by intent.

We could get it to work, but it would be difficult to backport to the v4.x series as the changes are likely fairly extensive.

**Comment by martinGHub** [comment] 2020-10-08 23:57
Hi @rhc54! I posted this issue in the users mail list of OMPI. I really need to spawn from a singleton because the app which I'm working is interactive and uses _ncurses_. I tried with mpirun but doesn't work. Anyway my problem now is that I don't want spawn over my spawner host (_master_), like _mpirun -nolocal..._ 
So, is it  just not possible now from a singleton?
I don't use a RM. It's possible to do that and then use mi app as a singleton?
Thank you in advance.

**Comment by abouteiller** [comment] 2020-10-23 02:50
Short story, this issue is resolved when using openpmix 3.2.0

https://github.com/openpmix/openpmix/issues/1843

**Comment by martinGHub** [comment] 2020-10-23 22:37
Hi @abouteiller 
I tried OMPI 4.0.4 with PMIx 3.2.0 and it in deed resolves the crash/hang problem. Nevertheless the one of the process allocation with a singleton described above persists. I quote that below. 
Thanks.

"...my problem now is that I don't want spawn over my spawner host (master), like _mpirun -nolocal..._"

**Comment by abouteiller** [comment] 2020-10-26 05:20
To clarify, singleton spawn does work as intended: it can spawn on the same host as the singleton program just fine.

What does not work is spawning from a singleton on another host, which is not supported. 

I just tried with 4.0.1 and it didn't work either then, but that would have been a surprise as I can't see how that would work without the orte dvm launched.

You have multiple options to move forward: 
* have you tried using `mpiexec -n 1 --stdin  0 simple_spawn` ? I have not tried with ncurses but that did work for me to plug-in basic in/out of the master rank with the console. 
* if not, maybe you can rewrite your app using MPI_COMM_CONNECT and MPI_COMM_ACCEPT,, launch your compute workload with `mpiexec --report-uri`  and set the environment variable `MCA_orte_server=$URI ./simple_spawn`

**Comment by martinGHub** [comment] 2020-10-26 19:34
Hi @abouteiller 

I've tried the --stdin 0 with no luck.

About server/client connection: 
The app which I'm working for has to be capable of allowing its users to launch as many jobsthey want; then, they can kill any job at any time; pause/stop a job or some tasks of it, relaunch it, etc. This is done by a collection of built-in commands of this app that can run whether interactively or by user's scripts, handled by an internal interpreter. For this reason the dynamic processes launch here is key. We've already done all this functionality I mentioned with PVM. His spawn function works in the way that permits that. Now, about MPI_COMM_CONNECT / MPI_COMM_ACCEPT functions, I need, before his implementation, a way to do those dynamic process launches. How can I do it in the way I need it? I tried without success things like calls to _system("mpirun -np X")_. Besides, later I read that this is not recommended. 
I hope I was clear in my explanation. 
Regards.

**Comment by rhc54** [comment] 2020-10-26 19:39
What is supposed to happen is that the singleton automatically starts the required DVM support when the application calls comm_spawn. Clearly, that isn't working right now. I won't have time to deal with it for awhile, but we will get it fixed eventually.

**Comment by rhc54** [comment] 2021-03-24 13:42
Sorry for the delayed response. This has been verified as fixed in OMPI master and the OMPI v5 branch, which is soon to be released. In the interim, you are welcome to use a nightly tarball from either of those branches (https://www.open-mpi.org/nightly/)

**Closed by rhc54** 2021-03-24 13:42 UTC
