### ISSUE TITLE
Remote host creates process but not start or finish

### ISSUE THREAD

**Issue by zmonoid** [open-mpi/ompi#5370] opened 2018-07-03 15:22 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)

v3.1.1

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

make from source

### Please describe the system on which you are running

* Operating system/version: centos 7
* Computer hardware: 
* Network type: 

-----------------------------

## Details of the problem

I follow the tutorial given in http://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/

I create a host  file has the following content:
```
# localhost slots=40
10.80.43.53 slots=40
```
So that my command will only run on remote client.

The following command works sucessfully:
```shell
mpirun -v -n 4 --hostfile host /home/bzhou/miniconda3/bin/python --version
```

returns the following information:
```
Python 3.6.5 :: Anaconda, Inc.
Python 3.6.5 :: Anaconda, Inc.
Python 3.6.5 :: Anaconda, Inc.
Python 3.6.5 :: Anaconda, Inc.
```

However, the following command will be hanged:
```shell
mpirun -v -n 4 --hostfile host /home/bzhou/miniconda3/bin/python /home/bzhou/cloud/01-hello-world.py
```
I checked the remote host's processes with htop, and it shows that it already in process list.

It just not started or finished.

May I know the reason?

The python file `01-hello-world.py` are copied from:
https://github.com/jbornschein/mpi4py-examples/blob/master/01-hello-world

**Comment by jsquyres** [comment] 2018-09-14 18:27
@zmonoid I'm sorry for the giant delay on this.  Are you still having this problem?

**Comment by zmonoid** [comment] 2018-09-15 14:12
@jsquyres Yes, still

**Comment by jsquyres** [comment] 2018-09-24 21:54
Can you try running a non-Python program, such as `hostname`?  And if that works, can you also try a simple C MPI program (like https://github.com/open-mpi/ompi/blob/master/examples/hello_c.c)?

I'd like to see if the problem is with Open MPI, or with the Python system you're using.

**Comment by gpaulsen** [comment] 2021-03-26 19:38
@zmonoid, we think this should work if you're fully qualifying the mpi path.  Closing.
Please re-open if it's still an issue in v4.0.5

**Closed by gpaulsen** 2021-03-26 19:38 UTC
Labels: RTE, Target: master, Target: v3.1.x, Target: v4.0.x, bug
