### ISSUE TITLE
ROMIO pthread deadlock @ finalize in 1.8.1

### ISSUE THREAD

**Issue by ompiteam** [open-mpi/ompi#200] opened 2014-10-01 16:30 UTC
From http://www.open-mpi.org/community/lists/users/2014/04/24259.php

------

     Hi 
    
        The following program deadlocks in mpi_finalize with OMPI 1.8.1 but works correctly with OMPI 1.6.5

        Is there a work around?
    
      Thanks
    
     Jamil

```
program mpiio
use mpi
implicit none
integer(kind=4) :: iprov, fh, ierr
call mpi_init_thread(MPI_THREAD_SERIALIZED, iprov, ierr)
if (iprov < MPI_THREAD_SERIALIZED) stop 'mpi_init_thread'
call mpi_file_open(MPI_COMM_WORLD, 'test.dat', &
MPI_MODE_WRONLY + MPI_MODE_CREATE, MPI_INFO_NULL, fh, ierr)
call mpi_file_close(fh, ierr)
call mpi_finalize(ierr)
end program mpiio

(gdb) bt
#0  0x0000003155a0e054 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x0000003155a09388 in _L_lock_854 () from /lib64/libpthread.so.0
#2  0x0000003155a09257 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007ffff7819f3c in ompi_attr_free_keyval () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/libmpi.so.1
#4  0x00007ffff7857be1 in PMPI_Keyval_free () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/libmpi.so.1
#5  0x00007ffff15b21f2 in ADIOI_End_call () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/openmpi/mca_io_romio.so
#6  0x00007ffff781a325 in ompi_attr_delete_impl () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/libmpi.so.1
#7  0x00007ffff781a4ec in ompi_attr_delete_all () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/libmpi.so.1
#8  0x00007ffff7832ad5 in ompi_mpi_finalize () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/libmpi.so.1
#9  0x00007ffff7b12e59 in pmpi_finalize__ () from /gpfs/thirdparty/zenotech/home/jappa/apps6.4/lib/libmpi_mpifh.so.2
#10 0x0000000000400b64 in mpiio () at t.f90:10
#11 0x0000000000400b9a in main ()
#12 0x000000315561ecdd in __libc_start_main () from /lib64/libc.so.6
#13 0x0000000000400a19 in _start ()
```

**Comment by jsquyres** [comment] 2015-06-25 00:17
@ggouaillardet Did this issue get resolved by the ROMIO refresh?

**Comment by hppritcha** [comment] 2015-06-25 01:13
I'm checking to see if I can reproduce using gfortran/4.9.2

**Comment by hppritcha** [comment] 2015-06-25 05:20
I am unable to reproduce this problem with master.
Closing.

**Closed by hppritcha** 2015-06-25 05:20 UTC
Labels: bug, minor
