### ISSUE TITLE
NetBSD: Runtime error using Open MPI 2.1.0rc2

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3117] opened 2017-03-06 23:07 UTC
@PHHargrove reports hitting a runtime error (using ring_c).c) on NetBSD when using the Open MPI 2.1.0rc2 tarball.  Error is in PMIX.

See https://www.mail-archive.com/devel@lists.open-mpi.org//msg19987.html

**Comment by rhc54** [comment] 2017-03-07 03:33
Here is the error report:

```
2.1.0rc2 tarball on NetBSD7/amd64.
Configured with only --prefix=... and --disable-mpi-fortran

To get past the lack of a struct timeval definition required a small source change in a previous email.
Once past that, I can build Open MPI and compile the examples.
However, I cannot run them.

Output below.

-Paul

$ mpirun -mca btl sm,self -np 2 examples/ring_c
[netbsd-amd64.kvm:20873] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 1651
[netbsd-amd64.kvm:20873] PMIX ERROR: OUT-OF-RESOURCE in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 820
[netbsd-amd64.kvm:20873] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 1468
[netbsd-amd64.kvm:20873] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c at line 592
[netbsd-amd64.kvm:16632] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 349
[netbsd-amd64.kvm:16632] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 839
[netbsd-amd64.kvm:16632] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 1021
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
[netbsd-amd64.kvm:19230] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 349
[netbsd-amd64.kvm:19230] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 839
[netbsd-amd64.kvm:19230] PMIX ERROR: ERROR in file /home/phargrov/OMPI/openmpi-2.1.0rc2-netbsd7-amd64/openmpi-2.1.0rc2/opal/mca/pmix/pmix112/pmix/src/dstore/pmix_esh.c at line 1021
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[netbsd-amd64.kvm:19230] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[netbsd-amd64.kvm:16632] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31721,1],0]
  Exit code:    1
--------------------------------------------------------------------------

```
@artpol84 Can you please take a look?

**Comment by artpol84** [comment] 2017-03-07 15:33
The only place that can cause this error is `posix_fallocate`. 
https://github.com/open-mpi/ompi/blob/v2.x/opal/mca/pmix/pmix112/pmix/src/sm/pmix_mmap.c#L69

@PHHargrove can you check `/tmp` directory to have a leftover?
is there any restrictions on that dir? Like it is a ramdisk with some fixed memory size?

**Comment by PHHargrove** [comment] 2017-03-07 15:46
Thanks, Artem.  
Indeed /tmp is a ram disk that is too small.  
Setting TMPDIR resolved the issue.  

I would suggest that in the future a better error message would be helpful, but is not critical.

**Comment by PHHargrove** [comment] 2017-03-07 15:59
> Setting TMPDIR resolved the issue.

I spoke too soon.  
Setting TMPDIR=$HOME (on a filesystem with 24GB of free space) did not help.

**Comment by PHHargrove** [comment] 2017-03-07 16:04
I see a part of the problem: posix_fallocate does **not** set errno on failure.  

Here is a relevant portion of the posix_fallocate manpage on NetBSD:
```
RETURN VALUES
     If successful, the posix_fallocate() function will return zero.
     Otherwise an error number will be returned, without setting errno.
```

And Linux says much the same:
```
RETURN VALUE
       posix_fallocate()  returns  zero on success, or an error number on failure.  Note that errno
       is not set.
```

**Comment by artpol84** [comment] 2017-03-07 16:12
But still it fails for some reason.
Can you try to output what posix_fallocate is returned?

**Comment by PHHargrove** [comment] 2017-03-07 16:33
> But still it fails for some reason.
> Can you try to output what posix_fallocate is returned?

I am working on it, but I am traveling this week (sitting in the middle of a large meeting).

**Comment by PHHargrove** [comment] 2017-03-07 17:06
>>But still it fails for some reason.
Can you try to output what posix_fallocate is returned?  

> I am working on it, but I am traveling this week (sitting in the middle of a large meeting).

The return value is `EOPNOTSUPP`, which POSIX documents as "Operation not supported on *socket*".  This makes no sense to me.
It is possible that `ENOTSUP` (Operation not supported) was intended.  

Perhaps the configure test for `HAVE_POSIX_FALLOCATE` should to verify that the call actually succeeds.  
Alternatively (likely simpler) the PMIX code could ignore `ENOTSUP` and `EOPNOTSUPP` return codes (*not* errno).   This would result in behavior indistinguishable to the case when `HAVE_POSIX_FALLOCATE` is not defined.

**Comment by PHHargrove** [comment] 2017-03-07 17:42
To completely discharge my role as the "portability police", I want to note when `HAVE_POSIX_FALLOCATE` is not defined the code is using `ftruncate()` instead.  
However, this is a non-portable use of that function.  
Here is what the NetBSD manpage says on the subject:  
```
STANDARDS
     Use of truncate() to extend a file is an IEEE Std 1003.1-2004
     (``POSIX.1'') extension, and is thus not portable.  Files can be extended
     in a portable way seeking (using lseek(2)) to the required size and
     writing a single character with write(2).
```
The Mac OS X, FreeBSD and OpenBSD manpages say something similar in their "BUGS" section:
```
Use of truncate() to extend a file is not portable.
```
The Linux manpage provides the most useful information on the subject:
```
       [...] the
       POSIX standard allows two behaviors for ftruncate() when  length  exceeds  the  file  length
       (note  that  truncate() is not specified at all in such an environment): either returning an
       error, or extending the file.
```
So, note that "returning an error" is a POSX-compliant behavior when `ftruncate()` is used to extend a file.

However, in reality this is likely not an issue for 2 reasons.
  1.  I have yet to see any system on which `ftruncate()` failed to extend *except* for FAT/VFAT filesystems on Linux (which is not a suitable `$TMPDIR` anyway).
  2.  The current POSIX.1 (IEEE Std 1003.1-2008, 2016 Edition) no longer lists extension as optional `If the file previously was smaller than this size, ftruncate() shall increase the size of the file.`

**Comment by rhc54** [comment] 2017-03-07 18:06
So it sounds like we need to do one or two things, and perhaps a third:

1. update the check for ```HAVE_POSIX_FALLOCATE``` to test functionality as well as presence
1. check the return code instead of errno when calling it - we should do this regardless, though it may also serve as the only required action
1. perhaps look at using lseek to extend the file instead of ftruncate, though as you say, ftruncate extending the file may no longer be optional anyway. I'd put this at low priority

**Comment by PHHargrove** [comment] 2017-03-07 18:59
@rhc54 I agree on all three points above, including placing low priority on allowing for failure of ftruncate().

I agree that with the proper checks item 2 alone should be sufficient.  There is a 50%+ chance that a tested-and-signed-off patch will appear here in the next two hour that implements item 2.

**Comment by PHHargrove** [comment] 2017-03-07 20:25
Proposed [patch](https://github.com/open-mpi/ompi/files/825566/issue3117-patch.txt) which has been tested (via ring_c) on the NetBSD/amd64 system where the problem was first observed.

**Comment by artpol84** [comment] 2017-03-07 20:48
thanks Paul, can you create a PR against PMIx master or you want me to do that?

**Comment by PHHargrove** [comment] 2017-03-07 20:54
@artpol84 I would really appreciate it if you could handle the PR.
I am at (or over?) the limit of what I can do while still keeping up with the meeting I am sitting in.

**Comment by artpol84** [comment] 2017-03-07 20:56
Thanks, Paul. We will take care.

**Comment by artpol84** [comment] 2017-03-08 06:31
@karasevb please create PR

**Comment by hppritcha** [comment] 2017-03-09 15:02
@jsquyres I vote for moving this to 2.1.1

**Comment by PHHargrove** [comment] 2017-03-09 15:04
I only test on the effect system(s) - I don't *use* them.  
So waiting for 2.1.1 is not a problem for me.

**Comment by jsquyres** [comment] 2017-03-09 15:06
@hppritcha I just moved the milestone, but then I looked closer / remembered what this one was -- wasn't it fixed in https://github.com/open-mpi/ompi/pull/3130 ?

**Comment by rhc54** [comment] 2017-03-09 15:28
yes, it was, so closing this one

**Closed by rhc54** 2017-03-09 15:28 UTC
Labels: bug

**Comment by guziy** [comment] 2020-03-03 15:01
Thanks @artpol84 this saved me a lot of time and frustration. Redefined TMPDIR and it works fine.

Cheers
