### ISSUE TITLE
Examples and all user code no longer compiles with 2.1.0 using mxm

### ISSUE THREAD

**Issue by lancewilson-monash** [open-mpi/ompi#3232] opened 2017-03-24 03:59 UTC
When trying to compile the examples after configuring, compiling and installing 2.1.0 no code will compile and returns errors similar to the following. 

``` 
mpicc -g -I/usr/local/openmpi/2.1.0-gcc4/include -I/usr/local/gcc/4.9.3/include/c++/4.9.3/x86_64-unknown-linux-gnu/ -I/usr/local/gcc/4.9.3/include -L/usr/local/openmpi/2.1.0-gcc4/lib -L/usr/local/gcc/4.9.3/lib64  hello_c.c   -o hello_c
gcc: error: 25517_LDFLAGS: No such file or directory
gcc: error: 25517_LDFLAGS: No such file or directory
make: *** [hello_c] Error 1 
``` 

If I recompile openmpi with the same parameters the error message changes with a  new random number.

```
< #define WRAPPER_EXTRA_LDFLAGS "-L/opt/slurm-16.05.4/lib -L/usr/lib64 25517_LDFLAGS -L/opt/mellanox/mxm/lib 25517_LDFLAGS    -Wl,-rpath -Wl,/opt/slurm-16.05.4/lib -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/opt/mellanox/mxm/lib -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags"
---
> #define WRAPPER_EXTRA_LDFLAGS "-L/opt/slurm-16.05.4/lib -L/usr/lib64 5362_LDFLAGS -L/opt/mellanox/mxm/lib 5362_LDFLAGS    -Wl,-rpath -Wl,/opt/slurm-16.05.4/lib -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/opt/mellanox/mxm/lib -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags"
```

It looks like there is a bug in the configure script that is collecting the number from somewhere and putting it into the LDFLAGS

` mtl_mxm_LDFLAGS="$$_LDFLAGS $ompi_check_mxm_LDFLAGS"`

Changing the configure script to remove the number causes software to fail on run even though it compiles.

` Device name:           mlx5_0 ` with OFED 3.2

**Comment by rhc54** [comment] 2017-03-24 04:03
Why are you adding all those flags to mpicc? You shouldn't add anything to it - all the required options are already there.

**Comment by lancewilson-monash** [comment] 2017-03-24 04:20
That is what the makefile is doing by default. Removing those options results in exactly the same error. 

On our cluster we run multiple version of openmpi and compilers so often these are added by the software when it is compiled.

**Comment by lancewilson-monash** [comment] 2017-03-24 04:25
It is a regression as the examples for 2.0.2 compile and run without the compile fail.

**Comment by jsquyres** [comment] 2017-03-24 10:09
Can you please send all the information listed here: https://www.open-mpi.org/community/help/

**Comment by ggouaillardet** [comment] 2017-03-25 13:53
it looks like open-mpi/ompi@8c2086995d1083361ed515b0246c6550e4b8137c was not backported

**Comment by jsquyres** [comment] 2017-03-25 14:03
@jladd-mlnx Is Mellanox not testing MXM with v2.1.x?  Can you please file PRs to v2.x and/or v2.0.x if necessary.  Thanks.

**Comment by ggouaillardet** [comment] 2017-03-26 05:25
Fwiw, v2.0.x uses an older logic, and v3.x is up-to-date
so PR is only required for v2.x

**Comment by lancewilson-monash** [comment] 2017-03-27 02:45
@jsquyres Please find attached the requested output. Github required a zip file so it has been put into a zip file.
[ompi-output.tar.bz2.zip](https://github.com/open-mpi/ompi/files/871340/ompi-output.tar.bz2.zip)

**Comment by ggouaillardet** [comment] 2017-03-27 02:50
@lancewilson-monash i think the issue is known and was already fixed in master
can you please manually download and apply the patch available at https://github.com/open-mpi/ompi/pull/3240.patch and try again ?
note you need recent autotools, and you will have to run ```./autogen.pl --force```

**Comment by jladd-mlnx** [comment] 2017-03-27 16:31
@jsquyres Very strange. We test MXM with 2.x nightly and have no issues.

**Comment by rhc54** [comment] 2017-03-27 16:32
Ah, but do you build the examples in those tests? I think that is the only issue being raised here

**Comment by jladd-mlnx** [comment] 2017-03-27 16:33
@rhc54 Everynight we do a full build and build IMB, OSU, and the examples dir.

**Comment by rhc54** [comment] 2017-03-27 16:34
Okay, thanks for clarifying. Not sure what is going on then, other than perhaps a difference in environment.

**Comment by jladd-mlnx** [comment] 2017-03-27 16:35
@rhc54 HPC-X is based on 2.x and out in the wild and people are building applications every day.

**Comment by rhc54** [comment] 2017-03-27 16:36
Understood - but the patch shows there is a clear typo in the LDFLAGS. Best guess: folks have their MXM libs in standard locations, and so the typo isn't impacting them. However, in this user's case, they are in a non-standard location, and so the typo breaks things.

**Comment by ggouaillardet** [comment] 2017-03-31 00:46
fixed in #3240

**Closed by ggouaillardet** 2017-03-31 00:46 UTC
Labels: bug, Target: 2.x

**Comment by pliniosilveira** [comment] 2017-05-11 20:28
I got this issue building openmpi from hpcx-v1.8.0-gcc-MLNX_OFED_LINUX-4.0-1.0.1.0-redhat7.3-x86_64 (openmpi-2.0.2).

Can anyone point out which exact parameter is causing this problem to show up?
Would it be --with-mxm or --with-mxm-libs or both?

**Comment by alinask** [comment] 2017-05-14 16:11
A new version of HPC-X, with this fix, will be available on June 29th on the Mellanox website.
