### ISSUE TITLE
io=ompio MPI_File_write, wrong answer (noncontig view)

### ISSUE THREAD

**Issue by markalle** [open-mpi/ompi#6296] opened 2019-01-23 22:55 UTC
I built OMPI on x86_64 using branch v4.0.x and am able to see a wrong answer from the following testcase.  It fails single host with 4 ranks, and using the local /tmp filesystem.

https://gist.github.com/markalle/4ec1a4da04cddb7078a6096106f9d5e7
mpicc -o x readwrite.c
mpirun -mca io ompio -np 4 ./x

The testcase uses randomized displacements and lengths, and cycles through different read/write styles. In one mode it writes each chunk individually, in one mode it sets the view to a non-contiguous datatype and performs one MPI_File_write(), in another mode it does the same and uses MPI_File_write_all().

The failure is specifically in the MPI_File_write() of a non-contiguous view. The other modes pass.

**Comment by markalle** [comment] 2019-01-23 22:58
@edgargabriel
I haven't looked into the cause, but suppose it might be sieving

**Comment by edgargabriel** [comment] 2019-01-23 23:00
@markalle I''ll have a look at it, but the only component in ompiuo that does data sieving is the two-phase fcoll one. This is however not selected by default anymore in v4.,0, the new default component is vulcan, which does not do data sieving. Individual I/O also doesn't do data sieving in ompio.

**Comment by ggouaillardet** [comment] 2019-01-24 08:21
@markalle fwiw, I was only able to reproduce issues with `ROMIO`

**Comment by edgargabriel** [comment] 2019-01-24 15:36
@markalle very nice test!

Similarly to what @ggouaillardet reported, I could however not reproduce the problem. I tried master and v4.0.x, 2 local files systems (xfs and ext4), with and without --enable-debug, and 4 as well as 8 processes with ompio. The test finishes in all cases correctly for me. 

Not entirely sure on how to continue on this issue. Since the test is using a randomized displacement, it might very well be that we are just not hitting that combination that triggers the problem, but I ran the test now numerous times and the problem didn't occur on my system in any of the cases.

**Comment by markalle** [comment] 2019-01-24 18:57
Okay, I think I see what happened. I had been tracking the issue on PPC then switched to x86_64 before submitting the bug, but accidentally switched to romio in the process. So I agree at least that x86_64 + ompio isn't hitting this.

So now I need to go back and see if I can still get a failure from PPC using ompio. So far I'm not getting a failure there either, so.... maybe we just close this and I'll come back if I can get a real failure again

**Comment by edgargabriel** [comment] 2019-01-24 19:10
ok, sounds good.

**Comment by awlauria** [comment] 2021-06-30 14:09
@markalle did you have any luck on this?

I copied your test and am running it in a loop today on a relatively new master, will report back any failures.

**Comment by awlauria** [comment] 2021-07-08 16:54
I was unable to reproduce on x86 or ppc with current ompi master. Closing - if this pops up again we can either re-open or open a new ticket.

**Closed by awlauria** 2021-07-08 16:54 UTC
