### ISSUE TITLE
RSH launcher hangs on more than 65 nodes

### ISSUE THREAD

**Issue by jladd-mlnx** [open-mpi/ompi#4465] opened 2017-11-07 19:56 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
v3.0.x
master

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone 

### Please describe the system on which you are running

* Operating system/version: 
RedHat 7.3
* Computer hardware: 
Intel dual socket Broadwell

* Network type: 
IB
-----------------------------

## Details of the problem

Open MPI 3.0.x and master, the following command hangs when the number of nodes in the hostfile is 66 or more (NOTE: this was originally reported to us by a customer; on their system, the hangs happens on at 65 nodes or more):

```
$mpirun --npernode 1 --hostfile mfile -mca plm rsh --debug-daemons -x LD_LIBRARY_PATH hostname
```
Debug output looks as follows:

```
Daemon [[50860,0],46] checking in as pid 24964 on host clx-hercules-096
[clx-hercules-096:24964] [[50860,0],46] orted: up and running - waiting for commands!
[clx-hercules-096:24964] [[50860,0],46] orted_cmd: received tree_spawn
Daemon [[50860,0],6] checking in as pid 4077 on host clx-hercules-008
[clx-hercules-008:04077] [[50860,0],6] orted: up and running - waiting for commands!
[clx-hercules-008:04077] [[50860,0],6] orted_cmd: received tree_spawn
Daemon [[50860,0],41] checking in as pid 30550 on host clx-hercules-060
[clx-hercules-060:30550] [[50860,0],41] orted: up and running - waiting for commands!
[clx-hercules-060:30550] [[50860,0],41] orted_cmd: received tree_spawn
Daemon [[50860,0],22] checking in as pid 11025 on host clx-hercules-025
[clx-hercules-025:11025] [[50860,0],22] orted: up and running - waiting for commands!
[clx-hercules-025:11025] [[50860,0],22] orted_cmd: received tree_spawn
Daemon [[50860,0],30] checking in as pid 8031 on host clx-hercules-034
[clx-hercules-034:08031] [[50860,0],30] orted: up and running - waiting for commands!
[clx-hercules-034:08031] [[50860,0],30] orted_cmd: received tree_spawn
```

We found that disabling the tree based RSH launch works around the issue, i.e.

```
$mpirun --npernode 1 --hostfile mfile -mca plm rsh -mca plm_rsh_no_tree_spawn true --debug-daemons -x LD_LIBRARY_PATH hostname
```

does NOT hang and produces the expected result. 

This appears to be a regression from the 2.x series. We do NOT observe this issue in any of the 2.x branches.

**Comment by rhc54** [comment] 2017-11-07 20:26
I suspect you are using an out-of-date master - this was reported and resolved recently. Are you sure you are at the head?

**Comment by jladd-mlnx** [comment] 2017-11-07 20:32
@rhc54 was this issue filed and closed? Can you point me to the fix?

**Comment by jladd-mlnx** [comment] 2017-11-07 20:46
The master was built on October 27 at commit 5d208a1

**Comment by rhc54** [comment] 2017-11-07 20:53
It was an offline communication reporting a problem identical to this one. The fix was committed here: https://github.com/open-mpi/ompi/pull/4365, and confirmed by the third party.

**Comment by rhc54** [comment] 2017-11-08 02:05
I'm afraid I won't have any time to look at this (as was stated at the last devel meeting, I am no longer working much on OMPI), so I'll have to defer to someone else. Last I checked, the problem had been resolved.

**Comment by jladd-mlnx** [comment] 2017-11-08 03:21
@rhc54 thanks, @karasevb Please take a look at the issue.

**Comment by rhc54** [comment] 2017-11-25 14:43
just curious - any progress on this?

**Comment by karasevb** [comment] 2017-11-26 03:41
@rhc54 there is still in my tasks list

**Comment by jjhursey** [comment] 2017-12-09 21:26
Did https://github.com/open-mpi/ompi/pull/4591 fix this issue, or is it still present on master?

**Comment by rhc54** [comment] 2017-12-09 23:03
I believe the prior fix reference in that PR fixed master, and the current problem was solely on 3.0.0. As @ggouaillardet noted, I fixed master a while back, but this particular part of the fix never went back to 3.0.

**Comment by ggouaillardet** [comment] 2017-12-10 00:01
i was able to reproduce the issue with `v3.0.x` using 3 nodes and `--mca routed_radix 1`.
if you `--mca plm_base_verbose 10`, you will note `orted` on node 1 has zero children.

i did no observe this behavior on master, so per @rhc54 comment, it is likely already fixed there.

**Comment by jjhursey** [comment] 2017-12-12 16:19
Ok so should we close this ticket?

**Comment by rhc54** [comment] 2017-12-12 16:20
@karasevb reports he still sees it, but I don't know how his setup differs from ours

**Comment by bwbarrett** [comment] 2017-12-12 16:47
@jladd-mlnx said they were going to test to see if there's a difference in behavior between the `tcp` and `ud` `oob` components, since they're likely using `ud` by default and the rest of us are probably using `tcp`.

I've tagged this as both 3.0.x and 3.1.x issue as we don't know whether it's happening on those branches, but Mellanox seemed to indicate that it was.

**Comment by rhc54** [comment] 2017-12-13 19:44
This is a cluster configuration specific issue - the root cause is here: https://github.com/open-mpi/ompi/issues/4621

**Closed by rhc54** 2017-12-13 19:44 UTC
Labels: bug, Target: 3.0.x, Target: master, Target: v3.1.x
