### ISSUE TITLE
Installing OpenMPI on Perlmutter @ NERSC

### ISSUE THREAD

**Issue by jscook2345** [open-mpi/ompi#10901] opened 2022-10-06 22:36 UTC
**Is your feature request related to a problem? Please describe.**
We'd like to introduce openmpi as a package on Perlmutter @ NERSC. We are aware there may some issues porting over to the latest HPE / Cray Slingshot interconnect and would like to help test solutions to improve progress in that direction.

**Describe the solution you'd like**
openmpi source that could be built and tested on perlmutter such that we can offer it as a package for our users. Some optimization of the package would be ideal.

**Describe alternatives you've considered**

**Additional context**
Not sure if this is the best place to start this discussion, but I thought I'd try to get the ball rolling. Thanks!

**Comment by rhc54** [comment] 2022-10-06 22:38
FWIW: OMPI is installed and running on Frontier, which is a Slingshot-based Slurm-run system. So long as you don't require VNI isolation, it should just work if you use OFI for the transport layer.

**Comment by hppritcha** [comment] 2022-10-06 22:45
The problem is we need 5.0.0 for ss11.

**Comment by hppritcha** [comment] 2022-10-06 22:46
And we are patiently waiting for that release to happen

**Comment by hppritcha** [comment] 2022-10-06 22:48
If a pre release would be okay we could go with that.

**Comment by jsquyres** [comment] 2022-10-07 12:32
@jscook2345 Just to be 100% sure: you mean Open MPI, not OpenMP, right?  (your initial post says "openmp")

**Comment by jscook2345** [comment] 2022-10-07 14:17
@jsquyres Yes, sorry. open-mpi. I will fix the typo.

**Comment by hppritcha** [comment] 2022-10-18 18:04
We found an issue with the 5.0.0rc8 and cuda support.  confirmed fix is in 5.0.x at ed81406d and put in a request for a rc9 to install.

**Comment by hppritcha** [comment] 2022-10-24 15:58
module use /global/common/software/m3169/perlmutter/modulefiles
module load openmpi/5.0.0rc9-ofi-cuda-22.5_11.7 

i've only built for gnu PrgEnv at the moment.  smoke tested that gpu rdma direct works.  there are some performance issues for small transfers.

**Comment by hppritcha** [comment] 2022-10-31 18:04
gnu and cray variants are installed.  nvidia compiler segfaults trying to build Open MPI with optimization enabled.
I think the rest of the details of installing a production 5.0.0 on perlmutter should be tracked by a nersc internal ticket as they may well involve exchange of information with the system vendor that may not be appropriate for a github public repo issue.

**Comment by hppritcha** [comment] 2022-11-07 16:20
narrowed down the nvidia problem - see NERSC issue [INC0193833].

Closing this issue.  If nersc staff wants to meet me in Dallas next week to discuss in more details that would be great.

**Closed by hppritcha** 2022-11-07 16:20 UTC
