### ISSUE TITLE
including openib in btl list causes horrible vader or sm performance.

### ISSUE THREAD

**Issue by gpaulsen** [open-mpi/ompi#1252] opened 2015-12-21 22:39 UTC
On master branch <d0b4aa1f9af61c4f7abcadbc2d903f8d4e669f21>

I observe a strange behavior.  I think that openib may be using too large of a hammer for numa membinding, possibly setting the wrong memory binding policy for the vader and sm shared memory segments.  I've only come to this conclusion empirically based on performance numbers.

For example, I have a RHEL 6.5 node with a single Mellanox Technologies MT25204 [InfiniHost III Lx HCA] ConnectX-3 card with a single port active.

Bad Latency run single host:

```sh
$  mpirun -host "mpi03" -np 4 --bind-to core --report-bindings --mca btl openib,vader,self ./ping_pong_ring.x2
[mpi03:12941] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../..][../../../../../../../..]
[mpi03:12941] MCW rank 1 bound to socket 1[core 8[hwt 0-1]]: [../../../../../../../..][BB/../../../../../../..]
[mpi03:12941] MCW rank 2 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../..][../../../../../../../..]
[mpi03:12941] MCW rank 3 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 7.11 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 7.10 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 7.15 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 7.17 usec/msg
```

Similar behavior with sm:

```sh
$ mpirun -host "mpi03" -np 4 --bind-to core --report-bindings --mca btl openib,sm,self ./ping_pong_ring.x2
[mpi03:14928] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../..][../../../../../../../..]
[mpi03:14928] MCW rank 1 bound to socket 1[core 8[hwt 0-1]]: [../../../../../../../..][BB/../../../../../../..]
[mpi03:14928] MCW rank 2 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../..][../../../../../../../..]
[mpi03:14928] MCW rank 3 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 7.45 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 7.38 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 7.35 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 7.38 usec/msg
```

When I remove openib results look much better:

```sh
$ mpirun -host "mpi03" -np 4 --bind-to core --report-bindings --mca btl vader,self ./ping_pong_ring.x2
[mpi03:15819] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../..][../../../../../../../..]
[mpi03:15819] MCW rank 1 bound to socket 1[core 8[hwt 0-1]]: [../../../../../../../..][BB/../../../../../../..]
[mpi03:15819] MCW rank 2 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../..][../../../../../../../..]
[mpi03:15819] MCW rank 3 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 0.50 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 0.50 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 0.49 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 0.51 usec/msg
```

Similar behavior with sm (though it's half as fast as vader):

```sh
$ mpirun -host "mpi03" -np 4 --bind-to core --report-bindings --mca btl sm,self ./ping_pong_ring.x2
[mpi03:16608] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../..][../../../../../../../..]
[mpi03:16608] MCW rank 1 bound to socket 1[core 8[hwt 0-1]]: [../../../../../../../..][BB/../../../../../../..]
[mpi03:16608] MCW rank 2 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../..][../../../../../../../..]
[mpi03:16608] MCW rank 3 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 0.98 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 1.00 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 0.95 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 0.93 usec/msg
```

If I disable binding explicitly with --bind-to none, even when specifying openib I see the expected results (with either vader or sm, but now sm is the same speed as vader... weird):

```sh
$ mpirun -host "mpi03" -np 4 --bind-to none --report-bindings --mca btl openib,vader,self ./ping_pong_ring.x2
[mpi03:20206] MCW rank 1 is not bound (or bound to all available processors)
[mpi03:20205] MCW rank 0 is not bound (or bound to all available processors)
[mpi03:20207] MCW rank 2 is not bound (or bound to all available processors)
[mpi03:20208] MCW rank 3 is not bound (or bound to all available processors)
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 0.50 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 0.50 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 0.50 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 0.49 usec/msg
```

```sh
$ mpirun -host "mpi03" -np 4 --bind-to none --report-bindings --mca btl openib,sm,self ./ping_pong_ring.x2
[mpi03:21058] MCW rank 0 is not bound (or bound to all available processors)
[mpi03:21059] MCW rank 1 is not bound (or bound to all available processors)
[mpi03:21060] MCW rank 2 is not bound (or bound to all available processors)
[mpi03:21061] MCW rank 3 is not bound (or bound to all available processors)
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 0.50 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 0.51 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 0.51 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 0.49 usec/msg
```

Finally just for completeness... the best 0 byte ping pong ring times I could get was with --bind-to core --map-by core:

```sh
$ mpirun -host "mpi03" -np 4 --bind-to core --map-by core --report-bindings --mca btl vader,self ./ping_pong_ring.x2
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
[mpi03:32149] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../..][../../../../../../../..]
[mpi03:32149] MCW rank 1 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../..][../../../../../../../..]
[mpi03:32149] MCW rank 2 bound to socket 0[core 2[hwt 0-1]]: [../../BB/../../../../..][../../../../../../../..]
[mpi03:32149] MCW rank 3 bound to socket 0[core 3[hwt 0-1]]: [../../../BB/../../../..][../../../../../../../..]
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 0.37 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 0.37 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 0.38 usec/msg
[3:mpi03] ping-pong 0 bytes ...
0 bytes: 0.38 usec/msg
```

I've attached my source for ping_pong_ring.c:

[ping_pong_ring.txt](https://github.com/open-mpi/ompi/files/69064/ping_pong_ring.txt)

**Comment by gpaulsen** [comment] 2015-12-21 22:41
@hjelmn - Jeff Squyres said I should tag you on this, that you might have some insight.

**Comment by hjelmn** [comment] 2015-12-21 23:24
Yeah. This happens because we are polling the completion queue. I have been planning to work on this when i get a chance.

**Comment by hppritcha** [comment] 2015-12-22 17:02
@gpaulsen which milestone would you like to give this.  If it involves a lot of changes I'd prefer it to be in 2.1.0 or maybe 2.0.1?  (I'll add the 2.0.1 milestone in a bit)

**Comment by gpaulsen** [comment] 2015-12-22 17:29
I was hoping for 2.0, (I didn't see a 2.0 label), as this makes openib runs pretty useless.
This is NOT a blocker for IBM, but I assumed it was a blocker for Open MPI Community.

**Comment by jsquyres** [comment] 2016-01-04 19:40
Hey @hjelmn, can we talk about this tomorrow on the call?  I'm wondering:

* Should the openib BTL just be smart enough to not register its progress function when its `add_procs()` hasn't found any peers, and/or `del_procs()` has removed all peers?
    * As a side effect: is the openib BTL progress function required to process incoming connections?  Or is this not even an issue if the BTL determines that it can't talk to any peers?  More specifically: is there ever a race condition -- e.g., involving dynamic processes -- where an incoming connection request could arrive in a BTL (such as the openib BTL) before the BTL knew that an incoming connection *could* be coming from that peer?
* I'm *guessing* that other BTL will also have this (set of) issues.  Do you know?
* If so, how much of a change does this represent to openib (and potentially others)?  I.e., do we *need* this for 2.0.0, or can it wait until 2.1.0?  I ask because Open MPI has had this behavior for a long time, so it's not technically a regression.  But it would be a nice performance issue to fix.

**Comment by jsquyres** [comment] 2016-01-05 17:04
Discussion on the call...

This seems to be because of how we now add all endpoints for all BTLs (because of the new `add_procs()` work).  Hence, even though a process may be 100% on a single server, if network BTLs determine that they could run (e.g., openib), the openib BTL modules will be added in the PML.  Therefore we queue up their progress functions and poll them -- even though they will never be used (unless a dynamic process comes along and uses them).

There's a secondary implication: one-sided atomics.  It's unfortunate that CPU atomics != network hardware atomics, so we have to go 100% one way or the other.  The current implementation uses the network stack atomics (for the same reason as above: a dynamic process may come along and therefore *require* the use of network atomics).

@hjelmn is going to look at a slightly different approach: have `opal_progress()` monitor the progress functions that it calls.  Progress functions that don't return any events for a long time will get downgraded in priority and called less frequently.

**Comment by gpaulsen** [comment] 2016-01-05 17:07
We discussed in [today's call](https://github.com/open-mpi/ompi/wiki/WeeklyTelcon_20160105) that this is a complex issue with the new dynamic add procs, and that we must include network endpoints for two reasons.  One is that if we use any network atomics, all atomics must be network atomics.  The other is to support spawning a new job on another node.

Nathan's proposed solution is to add a decay function to the progression loop, so that any components that are not actually progressing anything, won't get called as often.

**Comment by bosilca** [comment] 2016-01-05 17:52
Talking specifically about IB, we should take advantage of the fact that it is a connection-based network and only register the progress callback when there are established connections. More generally, a more reasonable approach will be to delay the progress registration until there is something to progress (this is under the assumption that the connection establishment is handled by a separate thread).

**Comment by jsquyres** [comment] 2016-01-05 18:06
Agreed: that, too.

**Comment by gpaulsen** [comment] 2016-01-11 16:52
I should add that this was build Multi-threaded, for x86 with the GNU compilers.

**Comment by gpaulsen** [comment] 2016-01-20 15:56
I'm ready to retest.  Please comment in this issue  with which PR to try.

**Comment by hppritcha** [comment] 2016-01-21 15:09
@hjelmn do you have an eta for the backoff fix?

**Comment by hjelmn** [comment] 2016-01-21 15:36
Should have it ready to test later today.

**Comment by hjelmn** [comment] 2016-01-22 23:54
hmm, I see why I am not getting the same level of slowdown as you. The problem is less the progress function (which adds ~ 100ns) but the asynchronous thread.

@gpaulsen Could you run the reproducer with a debug build and the -mca btl_base_verbose 100 option and send me the output?

**Comment by jsquyres** [comment] 2016-01-25 18:14
I just pinged @gpaulsen -- he's going to check this out today.

**Comment by hjelmn** [comment] 2016-01-25 18:15
Good. I am sure a btl log will should what is causing the async thread to wake up.

**Comment by gpaulsen** [comment] 2016-01-26 00:08
I emailed output directly to Nathan.
Strangely I was only able to reproduce with a non-debug build.  -g did not show the issue (though I didn't try very hard).

**Comment by jsquyres** [comment] 2016-01-26 02:58
FWIW, for large text outputs, we typically tend to use the gist.github.com service, and then post the link here.

**Comment by jsquyres** [comment] 2016-01-29 13:14
@gpaulsen @hjelmn Where are we on this issue?

**Comment by gpaulsen** [comment] 2016-01-29 15:31
I've been trying to instrument the code to provide additional output, but when I do, I see nothing new in the output.  I'll have some more time after 3pm central to work on this again today.

**Comment by gpaulsen** [comment] 2016-01-29 23:31
Just finished a web-x with Jeff, and we put some more opal_outputs in and around the openib component.  It looks like OpenIB *IS* calling it's progress thread, even on a single host.

Only reproduce the bad performance without --enable-debug.
I have compiled WITH Thread support: posix (MPI_THREAD_MULTIPLE: yes, OPAL support: yes, OMPI progress: no, ORTE progress: yes, Event lib: yes)
Command:
> cat hosts
mpi03 slots=4
> mpirun --hostfile hosts -np 4 --bind-to core --report-bindings --mca btl_openib_verbose 100 --mca btl_base_verbose 100 --mca btl openib,vader,self ./ping_pong_ring.x2

I don't see any calls to btl_openib_async_device, udcm_cq_event_dispatch.

I DO see calls to: btl_openib_component_open, and udcm_module_init (which returns success).

And when I'm running I see many many calls to the progress function: btl_openib_component_progress()

Jeff thinks this might be evidence for your initial thoughts @hjelmn.   Could you please take another look?

**Comment by gpaulsen** [comment] 2016-02-01 15:41
@hjelmn, Any luck?  Do you want to do a shared screen with me?

**Comment by hjelmn** [comment] 2016-02-01 17:22
I still think this is unrelated to the progress function since --bind-to none helps as well. I will look deeper and see what is different between the optimized and debug builds that could be having an impact.

**Comment by hjelmn** [comment] 2016-02-01 17:25
Can you put an opal output in the loop in progress_engine in opal/runtime/opal_progress_threads.c? That should be waking up almost never during the steady-state.

**Comment by gpaulsen** [comment] 2016-02-01 19:38
That is correct.  I've verified that each rank is only calling opal/runtime/progress_engine() once, but we're still getting many many calls in the openib progress function

**Comment by hjelmn** [comment] 2016-02-01 21:07
@gpaulsen Strange. I will have to do some more digging to figure out what might be going on. I measured the affect of the openib btl's progress engine on a shared memory ping-pong and it is at best 50-100 ns. I tested this by just setting btl_progress to NULL in the btl and comparing to the normal latency.

**Comment by jsquyres** [comment] 2016-02-01 22:17
@gpaulsen Can you try removing the openib progress function (i.e., maybe just hack up the code to not register the openib progress function) and see what happens?

I know @hjelmn says it only takes something like 40ns, but there's also caching effects, and vader/sm are sooo sensitive to that kind of stuff.  If it's easy, it's worth trying.

**Comment by gpaulsen** [comment] 2016-02-01 22:17
sure, trying.

**Comment by gpaulsen** [comment] 2016-02-01 22:42
Okay verified that if I set the .btl_init and .btl_progress fields in the .super of: mca_btl_openib_component_t structure in btl_openib_component.c, the performance returns to normal!

**Comment by hjelmn** [comment] 2016-02-01 22:58
do not set init to null. just progress

**Comment by gpaulsen** [comment] 2016-02-02 12:22
Okay, sorry.  Same result when I keep init as it is in master, but just set progress to NULL.  I still see horrible performance on a single node, and in this mode, if I put a print in btl_openib_component_progress I see on the order of 45,000 calls to btl_openib_component_progress() per rank(but I measured perf without this print).

I still see that --bind-to none makes the problem go away.  With --bind-to none, when I print in btl_openib_component_progress() I only see around 17,000 calls.  This (17K < 45K) could be related to the shorter overall runtime.

I was concerned about these prints in the progress function altering the runtime and the counts of calls to the progress function, so I added a counter, and printed it at component close (removing the other prints).  I found:
--bind-to core -> Still bad = 7.00 usec/msg 0 byte ping pong ring 4 procs same node (vader)
  - Interesting in this mode the number of progress calls vary greatly: 475282, 8227, 463568, 8202.
--bind-to none -> Good perf = 0.35 usec/msg 0 byte pingpong ring 4 procs same node (vader)
   - in this mode, the number of pogress calls are more symetric: 19405, 19943, 20595, 20133.

**Comment by hppritcha** [comment] 2016-02-02 15:26
Are the same bad results obtained if the processes are pinned to other cores on the node?

**Comment by gpaulsen** [comment] 2016-02-02 16:00
Great question.  I investigated a few other nodes of the same cluster (some without IB), and can still reproduce the problem.
Then I tried adding --map-by core and the problem disapeared.
When I changed that to --map-by socket the problem reappeared.
Finally I tried --bind-to core --map-by socket and removed openib from the list of btls, and the problem disappeared again.

Does this mean that the presence of the openib btl changes the mapping of the ranks?

**Comment by jsquyres** [comment] 2016-02-02 16:02
Can you provide an lstopo output for your nodes showing the cores and your hca devices?

**Comment by lanl-ompi** [comment] 2016-02-02 17:05
@gpaulsen could you actually try moving the pairs around the node like with

mpirun --bind-to core --cpu-set 5,6 --display-map -np 2 ./the_command

**Comment by lanl-ompi** [comment] 2016-02-02 17:08
also, could you get check /proc/interrupts between runs?

**Comment by lanl-ompi** [comment] 2016-02-02 17:09
sorry I see I"m logged in as the lanl bot.

**Comment by gpaulsen** [comment] 2016-02-02 17:28
Well, I need at least 3 ranks to reproduce the slowdown.  So I tried --bind-to core --display-map -np 3 and got this:
[0:mpi03] ping-pong 0 bytes ...
0 bytes: 6.98 usec/msg
[1:mpi03] ping-pong 0 bytes ...
0 bytes: 6.99 usec/msg
[2:mpi03] ping-pong 0 bytes ...
0 bytes: 0.36 usec/msg
This means that the connection from rank 2 of CommWorld, to rank 0 of comm world is fast, but not the other two.
The prog-cnt sorted by PID: 
[mpi03:12092] GEOFF - prog-cnt == 244446
[mpi03:12093] GEOFF - prog-cnt == 4158
[mpi03:12094] GEOFF - prog-cnt == 246610

Can we assume assending rank IDs map to the assending PIDs?
And the output from --display-map and --report-bindings from same 3 proc run:
 ========================   JOB MAP   ========================

 Data for node: mpi03   Num slots: 16   Max slots: 0    Num procs: 3
        Process OMPI jobid: [14913,1] App: 0 Process rank: 0 Bound: socket 0[core 0[hwt 0-1]]:[BB/../../../../../../..][../../../../../../../..]
        Process OMPI jobid: [14913,1] App: 0 Process rank: 1 Bound: socket 1[core 8[hwt 0-1]]:[../../../../../../../..][BB/../../../../../../..]
        Process OMPI jobid: [14913,1] App: 0 Process rank: 2 Bound: socket 0[core 1[hwt 0-1]]:[../BB/../../../../../..][../../../../../../../..]

 =============================================================
[mpi03:12087] MCW rank 0 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../..][../../../../../../../..]
[mpi03:12087] MCW rank 1 bound to socket 1[core 8[hwt 0-1]]: [../../../../../../../..][BB/../../../../../../..]
[mpi03:12087] MCW rank 2 bound to socket 0[core 1[hwt 0-1]]: [../BB/../../../../../..][../../../../../../../..]

I'll post the /proc/interupts before and after the above run next.

**Comment by gpaulsen** [comment] 2016-02-02 18:01
Cool!  I uploaded the /proc/interupts before and after to gist:
before:  https://gist.github.com/gpaulsen/9b55d2de12a356450a4d
after: https://gist.github.com/gpaulsen/d07c3b39fb4fe9894dc8
No idea how to read those.

**Comment by gpaulsen** [comment] 2016-02-02 18:22
Still see bad latency when I try a weird --cpu-set like 5,7,9,11 (hyperthreading is on here).

[mpi03:24541] MCW rank 0 bound to socket 0[core 5[hwt 0-1]]: [../../../../../BB/../..][../../../../../../../..]
[mpi03:24541] MCW rank 1 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[mpi03:24541] MCW rank 2 bound to socket 0[core 7[hwt 0-1]]: [../../../../../../../BB][../../../../../../../..]
[mpi03:24541] MCW rank 3 bound to socket 1[core 11[hwt 0-1]]: [../../../../../../../..][../../../BB/../../../..]

And still bad latency with --cpu-set 9,11,13,15  (16 physical cores across 2 sockets with hyperthreading enabled)
[mpi03:26551] MCW rank 0 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[mpi03:26551] MCW rank 1 bound to socket 1[core 11[hwt 0-1]]: [../../../../../../../..][../../../BB/../../../..]
[mpi03:26551] MCW rank 2 bound to socket 1[core 13[hwt 0-1]]: [../../../../../../../..][../../../../../BB/../..]
[mpi03:26551] MCW rank 3 bound to socket 1[core 15[hwt 0-1]]: [../../../../../../../..][../../../../../../../BB]

**Comment by gpaulsen** [comment] 2016-02-02 18:22
Any other ideas?  I'm central time, and can web-X if you have time.

**Comment by hppritcha** [comment] 2016-02-02 20:31
I don't see anything unusual with the interrupt info.

**Comment by hjelmn** [comment] 2016-02-02 21:14
I tried again and I can't reproduce on master on an opteron + connectx node. Is there any way you can give access to this machine?

**Comment by gpaulsen** [comment] 2016-02-02 22:01
Yes, we can do a shared webX.  Let me know what time you're available.

**Comment by hjelmn** [comment] 2016-02-02 22:37
I have time now or tomorrow between 9 and 11 MST.

**Comment by gpaulsen** [comment] 2016-02-03 12:43
Lets shoot for 10 MST today for next iteration.

**Comment by hjelmn** [comment] 2016-02-03 16:25
Works for me.

**Comment by gpaulsen** [comment] 2016-02-03 17:59
Nathan was able to isolate the issue to openib/udcm section of code.  He's now re-reading code to come up with next items to try for next iteration this afternoon.

**Comment by gpaulsen** [comment] 2016-02-04 16:22
Let me know when is a good time to iterate again.

**Comment by hjelmn** [comment] 2016-02-04 18:16
Anytime after 1 MST works for me.

**Comment by gpaulsen** [comment] 2016-02-04 18:38
Let's say 1pm Central / 2pm MST.

**Comment by hjelmn** [comment] 2016-02-04 18:57
Works for me.

**Comment by gpaulsen** [comment] 2016-02-04 19:06
Doah!  1pm Central is 12pm MST.  You available nowish?

**Comment by hjelmn** [comment] 2016-02-04 19:08
hah, ok. going on now

**Comment by hjelmn** [comment] 2016-02-04 23:37
Well, can throw out the udcm cause. We did some more digging and it is indeed the openib progress function. Problem is whatever is causing the slowdown for shared memory is also causing a slowdown for internode ping-pong. The slowdown only happens for processes on the second socket of either node. @gpaulsen is going to experiment with different ofed/mofed versions to see if the slowdown is a ofed bug.

**Comment by hjelmn** [comment] 2016-02-04 23:40
As such this may not be a blocker for 2.0.0. We certainly can add the code to reduce the number of calls to the openib progress function when the btl is not in active use or we could to not poll the openib completion queues unless there are connections but this would fix the symptom not the cause.

**Comment by jsquyres** [comment] 2016-02-04 23:45
Sounds like this could use some testing on other people's IB hardware -- do the same thing as @gpaulsen (including an MPI process that is NUMA-far from the HCA) and see if they get the same kind of bad performance.

**Comment by nysal** [comment] 2016-02-05 04:49
Is this sandy bridge? I vaguely recollect adding a stall loop before calling ibv_poll_cq() for processes on the second socket to work around a hardware issue.

**Comment by gpaulsen** [comment] 2016-02-05 12:12
Yes!  This IS a Sandy Bridge.  Intel Xeon E5-2660.

**Comment by gpaulsen** [comment] 2016-02-05 14:48
So, I talked with @nysal.  He remembers finding this problem internally at IBM with another PE-MPI, and putting in a spin delay before ibv_poll_cq() when running on Sandybridge with certain OFED versions.  That's all he remembers.

**Comment by gpaulsen** [comment] 2016-02-05 14:54
@hjelmn, The two "good" changes to openib that we made yesterday, do you want to get those upstream, or would you like me to?  That might be good practice for me getting stuff upstream, unless you wanted to go and look at other stuff too.

Also, I am not as confident that it's only ibv_poll_cq's fault for the horrible performance.  I really thought that I NULLed out the progression pointer as stated above.  I'm going to try to reproduce that today.
Also, Isn't that ibv_poll_cq() call in openib on another thread from the shared memory?  WHY would that slow down the shared memory progression?  or is ALL BTL progression done on that other thread?
Finally, if the new version of MOFED doesn't fix this, does it warrant trying your progression decay function?  Or would you prefer to try to detect the Sandybridge architecture and put a spin loop before the ibv_poll_cq()?  or just ignore it for this hardware?

**Comment by hppritcha** [comment] 2016-02-05 15:09
Okay this brings back memories.  On Cray for processes on the remote socket from the Aries/hcae in craypich we had to add a back off for functions we knew polled cache lines that were also potentially written to by the I/o device.  It was a bug in the sandy bridge  north ridge.  

Craypich only turned on the back off if rank was on remote socket and it was sandybridge.  Problem was fixed in ivy ridge as I recall.

**Comment by hjelmn** [comment] 2016-02-05 15:41
Ok, it sounds like we can fix this a similar way in Open MPI. We can easily detect both sandybridge and a remote socket. I will take a crack at writing this later today.

**Comment by hjelmn** [comment] 2016-02-05 15:50
Looks like we have a Sandy Bridge system with QLogic. Let me see if I can get the same slowdown with this system.

**Comment by hjelmn** [comment] 2016-02-05 19:51
No luck getting a similar slowdown with libibverbs 1.0.8 from RHELL 6.7 with QLogic. Will have to test the workaround on the system @gpaulsen is running on.

**Comment by jsquyres** [comment] 2016-02-09 17:16
Update from discussion on Feb 9 2016 webex: it may not be the well-known Sandy Bridge bug -- it seems like the latency added is too high (the Sandy Bridge bug only aded hundreds of nanoseconds, not multiple milliseconds).  @gpaulsen is going to test with MXM/RC to see if he can duplicate the issue -- if it's a hardware / driver issue, it should show up with MXM, too.

That being said, we still want the progressive backoff progress functionality, but probably not for v2.0.0.  A good target would likely be v2.1.x.

**Comment by hjelmn** [comment] 2016-02-09 17:20
@jsquyres multiple microseconds, not milli.

**Comment by jsquyres** [comment] 2016-02-09 17:22
@hjelmn Thanks -- I edited/fixed the comment.

**Comment by gpaulsen** [comment] 2016-02-09 17:23
I THINK it's showing up with MxM also.  I can reproduce with just MxM across 2 nodes (fast on first socket and slow on 2nd), or MxM on same node.  The thing is, I'm getting nasty messages saying that MxM was unable to be opened, so Now I don't know WHAT is happening.
`[gpaulsen@mpi03 ompibase]$ mpirun --hostfile hosts -np 2 --bind-to core --dispy-map --report-bindings --mca mtl mxm --map-by core --cpu-set 9,11 ./ping_pong_ring.x3 64 | & tee mxm_one_node_both_2nd_socket.out
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
 Data for JOB [2344,1] offset 0

 ========================   JOB MAP   ========================

 Data for node: mpi03   Num slots: 16   Max slots: 0    Num procs: 2
        Process OMPI jobid: [2344,1] App: 0 Process rank: 0 Bound: socket 1[core 9[hwt 0-1]]:[../../../../../../../..][../BB/../../../../../..]
        Process OMPI jobid: [2344,1] App: 0 Process rank: 1 Bound: socket 1[core 11[hwt 0-1]]:[../../../../../../../..][../../../BB/../../../..]

 =============================================================
[mpi03:07262] MCW rank 0 bound to socket 1[core 9[hwt 0-1]]: [../../../../../../../..][../BB/../../../../../..]
[mpi03:07262] MCW rank 1 bound to socket 1[core 11[hwt 0-1]]: [../../../../../../../..][../../../BB/../../../..]
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      mpi03
Framework: mtl
Component: mxm
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
Open MPI stopped checking at the first component that it did not find.

Host:      mpi03
Framework: mtl
Component: mxm
--------------------------------------------------------------------------
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
[0:mpi03] ping-pong 64 bytes ...
64 bytes: 10.64 usec/msg
64 bytes: 6.01 MB/sec
[1:mpi03] ping-pong 64 bytes ...
64 bytes: 10.66 usec/msg
64 bytes: 6.00 MB/sec
`

And then if I run the same command with --cpu_set 1,4 (both on first socket), I see that they're bound correctly each to a different core on the first socket, and I get good latency.  BUT I still see this "Could not find component" error message.

Is my command correct?  Is it using MxM intra-node?  Or is it falling back to TCP or SHMEM or something else?

**Comment by gpaulsen** [comment] 2016-02-09 17:26
ANOTHER thing... 

I do NOT see this behavior with Platform MPI using VERBS RC:

[gpaulsen@mpi03 ompibase]$ /opt/ibm/platform_mpi/bin/mpirun -np 2 -intra=nic -prot -IBV -aff=bandwidth,v ~/bin/ppr.x 64
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
Host 0 -- ip 9.21.55.63 -- ranks 0 - 1

 host | 0
======|======
    0 : IBV

 Prot -  All Intra-node communication is: IBV

Host 0 -- ip 9.21.55.63 -- [0+16 1+17 2+18 3+19 4+20 5+21 6+22 7+23],[8+24 9+25 10+26 11+27 12+28 13+29 14+30 15+31]
- R0: [11 00 00 00 00 00 00 00],--  : 0x10001
- R1: --,[11 00 00 00 00 00 00 00]  : 0x1000100
[0:mpi03] ping-pong 64 bytes ...
64 bytes: 1.67 usec/msg
64 bytes: 38.35 MB/sec
[1:mpi03] ping-pong 64 bytes ...
64 bytes: 1.68 usec/msg
64 bytes: 38.17 MB/sec

**Comment by jladd-mlnx** [comment] 2016-02-09 17:39
Geoff, looks like you haven't built your OMPI with MXM support.

**Comment by jladd-mlnx** [comment] 2016-02-09 17:40
Your experiment 'With MXM' is not valid. It's falling back onto the BTL.

**Comment by gpaulsen** [comment] 2016-02-09 18:00
Ah, yes.  Drat.  Thanks.  ompi_info |grep -i mxm shows nothing...
rebuilding.  Thanks.

**Comment by gpaulsen** [comment] 2016-02-15 13:59
I updated to latest master, and can no longer reproduce.
I'll try to reproduce on 2.0 branch tuesday morning (I'm off today).

**Comment by gpaulsen** [comment] 2016-02-25 15:54
I reran with open MPI 2.0 branch, and the latency hit is about 500ns to RDMA via openib to the far socket on haswell.

**Comment by jladd-mlnx** [comment] 2016-02-25 17:15
Nice. Exactly what I would expect.

**Comment by gpaulsen** [comment] 2016-02-25 17:22
okay great good to know.  I have the additional item to test on 1.10 to see if it was a regression, but we're pretty sure it's not a regression.  Assuming it's not, we'll close this.

**Comment by jladd-mlnx** [comment] 2016-02-25 23:33
Geoff, did you mean Sandy Bridge?

**Comment by gpaulsen** [comment] 2016-02-25 23:41
Oh right sorry.  Sandy Bridge.:  Intel(R) Xeon(R) CPU E5-2660

**Comment by jladd-mlnx** [comment] 2016-02-26 00:00
OK. This is expected on SB.

**Comment by hppritcha** [comment] 2016-03-01 23:35
So what's the outcome here?  I thought we'd decided that this could be closed in discussions last week?

**Comment by gpaulsen** [comment] 2016-03-02 14:09
Yes I think so too.  I committed to test with the 1.10 to prove it's not a regression, but that seems very unlikely, and I'm swamped at the moment.

**Closed** 2016-03-02 14:12 UTC
Labels: blocker, bug
