### ISSUE TITLE
MPI_Gather of indexed typed to raw data

### ISSUE THREAD

**Issue by ctheo** [open-mpi/ompi#634] opened 2015-06-10 14:27 UTC
I have encountered a problem on using MPI_Gather for gathering indexed integers to a vector of integers. When I try to gather the integers without creating a new receive type, I get a MPI_ERR_TRUNCATE error. 
The error appears from two processes.

**\* An error occurred in MPI_Gather
**\* on communicator MPI_COMM_WORLD
**\* MPI_ERR_TRUNCATE: message truncated
**\* MPI_ERRORS_ARE_FATAL: your MPI job will now abort

I noticed that this error does not occur when I use data transfer size less than 6K bytes.

I have verified the error occurs in open-mpi v1.6 (ubuntu) and v1.8 (fedora).

```
#include <stdlib.h>
#include "mpi.h"

int i, comm_rank, comm_size, err;
int *send_data, *recv_data;
int *blocklengths, *displacements;
MPI_Datatype send_type;

int main ( int argc, char *argv[] ){
  MPI_Init ( &argc, &argv );
  MPI_Comm_rank(MPI_COMM_WORLD, &comm_rank);
  MPI_Comm_size(MPI_COMM_WORLD, &comm_size);


  unsigned int block = 1000;
  unsigned int count = 1000;

  send_data = malloc(sizeof(int)*block*count);
  for (i=0; i<block*count; ++i) send_data[i] = i;

  recv_data = 0;
  if(comm_rank==0) recv_data = malloc(sizeof(int)*block*count*comm_size);

  blocklengths = malloc(sizeof(int)*count);
  displacements = malloc(sizeof(int)*count);
  for (i=0; i<count; ++i) {
    blocklengths[i] = block;
    displacements[i] = i*block;
  }
  MPI_Type_indexed(count, blocklengths, displacements, MPI_INT, &send_type);
  MPI_Type_commit(&send_type);

  err = MPI_Gather((void*)send_data, 1, send_type, (void*)recv_data, block*count, MPI_INT, 0, MPI_COMM_WORLD);
  if (err) MPI_Abort(MPI_COMM_WORLD, err);

  free(send_data);
  free(recv_data);
  free(blocklengths);
  free(displacements);


  MPI_Finalize ( );
  return 0;
}
```

**Comment by jsquyres** [comment] 2015-06-10 16:00
@bosilca Can you have a look?  I can confirm that the issue is repeatable on the master and head of v1.8 branch.  To my quick look, the test program looks correct.

The test program is included in the initial issue report (it wasn't included in the initial email, but it's visible on the web interface).

**Comment by bosilca** [comment] 2015-06-10 19:54
This is a known bug. The tuned collective modules fails to work correctly
when processes are using different datatypes, especially when some level of
pipelining is involved.

Until I have some time to look into the details, setting the following 2
MCA parameters might provide a temporary solution.

coll_tuned_gather_algorithm = 2
coll_tuned_gather_algorithm_segmentsize = 0

**Comment by ctheo** [comment] 2015-06-11 06:32
@jsquyres and @bosilca thanks for the support.

The workaround I use is:

    MPI_Type_contiguous(block*count, MPI_INT, &recv_type);
    MPI_Type_commit(&recv_type);
    err = MPI_Gather((void*)send_data, 1, send_type, (void*)recv_data, 1, recv_type, 0, MPI_COMM_WORLD);

How about Open MPI v1.6.5?
As you might know ubuntu 15.04 uses 1.6.5.

**Comment by jsquyres** [comment] 2015-10-15 18:24
This is a long-standing issue.  I'm guessing it won't get fixed in the v1.10.x series.

**Comment by bosilca** [comment] 2015-10-15 20:13
There is no efficient solution. The problem here is that different processes use different datatypes, and as a result the pipelining chose by one process might be incompatible with the choices of other processes. Thus, either we change the calls to PML to include the convertor inside (which will allow us to do consistent pipelining across all processes involved in any collective communication), or we switch to a non pipelined (thus less performant) version of the collective.

**Comment by bosilca** [comment] 2019-05-08 03:28
There is no point of keeping this open. For performance reasons we do want to keep the pipelining, but as there is no way to know if all processes participate with the same datatype and count we cannot guarantee that the pipelining will work. The solution right now is to disable pipelining, either globally or per communicator (using MPI_T right before creating the communicator that will be used for this operation).

**Closed by bosilca** 2019-05-08 03:28 UTC
Labels: bug
