### ISSUE TITLE
mpi_abort_delay doesn't  work

### ISSUE THREAD

**Issue by tingweiwu** [open-mpi/ompi#6639] opened 2019-05-06 06:57 UTC
Thank you for taking the time to submit an issue!

### What version of Open MPI are you using? (e.g., v1.10.3, v2.1.0, git branch name and hash, etc.)
mpirun.real (OpenRTE) 3.1.2

### Describe how Open MPI was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
```
mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget https://www.open-mpi.org/software/ompi/v3.1/downloads/openmpi-3.1.2.tar.gz && \
    tar zxf openmpi-3.1.2.tar.gz && \
    cd openmpi-3.1.2 && \
    ./configure --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi
```

### Please describe the system on which you are running

* Operating system/version: 
ubuntu16.04
* Computer hardware: 
V100GPU+InfiniBand
* Network type: 
docker cni networker

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:

I met `ORTE has lost communication with a remote daemon.` error  described in  #6618 

and I want to debug what happened at that time.

so I add mpi_abort_delay at the start command  
`mpirun  -x NCCL_DEBUG=INFO -mca mpi_abort_delay -1 -mca mpi_abort_print_stack 1 python train_ds.py`
as the mpi_abort_delay described in the https://www.open-mpi.org/faq/?category=debugging
```
mpi_abort_delay: If nonzero, print out an identifying message when MPI_ABORT is invoked showing the hostname and PID of the process that invoked MPI_ABORT, and then delay that many seconds before exiting. A negative value means to delay indefinitely. This allows a user to manually come in and attach a debugger when an error occurs. Remember that the default MPI error handler — MPI_ERRORS_ABORT — invokes MPI_ABORT, so this parameter can be useful to discover problems identified by mpi_param_check.
mpi_abort_print_stack: If nonzero, print out a stack trace (on supported systems) when MPI_ABORT is invoked.
```
but the process still exit when meet `ORTE has lost communication with a remote daemon.`

how could I configure  openmpi to not terminate the job if ORTE has lost communication with a remote daemon ?

is there any other debug method to debug `ORTE has lost communication with a remote daemon.` ?

**Comment by kawashima-fj** [comment] 2019-05-07 05:55
You cannot debug it using `mpi_abort_delay`.

When the `orterun` command is executed, it launches daemon processes (`orted`) in remote nodes. Subsequently the `orterun` and `orted` launch an MPI program. The message `ORTE has lost communication with a remote daemon.` means that `orterun` has lost connection with `orted` for some reason. On the other hand, `mpi_abort_delay` affects the behavior of the `MPI_ABORT` routine called by an MPI program. Unless the connection loss is caused by the `MPI_ABORT` (I think probably not), `mpi_abort_delay` has no effect on your error. I'm not familiar with `orterun`/`orted` and cannot give a good advice about #6618, sorry.

So I close this issue. If you have more questions, feel free to reopen it.

**Closed by kawashima-fj** 2019-05-07 05:55 UTC
Labels: question
