### ISSUE TITLE
Fix unsafe use of gethostname() across code base

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#6801] opened 2019-07-09 13:00 UTC
Per discussion on https://github.com/open-mpi/ompi/pull/6797#discussion_r301564512, it looks like there's a small-but-persistent issue throughout the Open MPI code base: the use of the `gethostname()` call.  It's not a huge issue, but it would be good to clean this up, and is an excellent first PR for the code base.

In `opal_config_bottom.h`, we define `OPAL_MAXHOSTNAMELEN` to be one more than the system max:

https://github.com/open-mpi/ompi/blob/b738fa295dbc78a625f0a262119757c3d5c59cd0/opal/include/opal_config_bottom.h#L295-L302

And in most place in the code base, we call `gethostname()` like this:

```c
char hostname[OPAL_MAXHOSTNAMELEN];
gethostname(hostname, sizeof(hostname));
```

After all, `gethostname()` is a pretty safe function -- it's almost certainly *not* going to fail due to some kind of system error.  The only reason it would likely fail is if the buffer is too short.  And the definition of `OPAL_MAXHOSTNAMELEN` *should* be 1 larger than the max hostname size.  So calling `gethostname()` shouldn't fail.  Probably.

That being said, it's not entirely clear that `OPAL_MAXHOSTNAMELEN` is *guaranteed* to be 1 more than the system's max hostname length *in all cases*.  For example, MacOS 10.14 `gethostname(3)` will return at most `sysconf(_SC_HOST_NAME_MAX)` characters.

While hostnames >= `OPAL_MAXHOSTNAMELEN` are likely quite rare, it *is* possible (especially in large automated systems where hostnames are auto-generated).  This is an excellent issue for a newbie to the Open MPI code base to handle: bolster up our usage of `gethostname()`.

Indeed, the simplest solution may well be to:

1. write `opal_gethostname()` that does appropriate error checking and *guarantees* to null-terminate the output buffer, even if the hostname itself gets truncated.
1. update the rest of the codebase to use `opal_gethostname()` instead of `hostname`.  Or even `#define gethostname(a, b) opal_gethostname((a), (b))` in `opal_config_bottom.h` to transparently transmogrify all calls to use `opal_gethostname()`.

**Comment by hppritcha** [comment] 2019-07-13 03:39
assigning to myself as proxy for new hire starting in August

**Comment by cpshereda** [comment] 2019-10-07 21:46
Looking at this now. @jsquyres - any suggestions on where to put opal_gethostname(), assuming it's a C function? It would need to be somewhere where the call to gethostname() inside of it will not get clobbered by the preprocessor macro redefining gethostname, assuming we (I) do it that way.

Also, is there a macro for a debug level in this code, or something like it? I'd like to add some output when debugging is turned on for the case when gethostname returns ENAMETOOLONG or EINVAL, assuming that's the way you do things in this code.

**Comment by jsquyres** [comment] 2019-10-07 23:05
> Looking at this now. @jsquyres - any suggestions on where to put opal_gethostname(), assuming it's a C function? 

Probably in `opal/util` somewhere would be fine.  There's a bunch of other utility-like functions in there.

> It would need to be somewhere where the call to gethostname() inside of it will not get clobbered by the preprocessor macro redefining gethostname, assuming we (I) do it that way.

You can locally `#undef gethostname` in the `.c` file where you define `opal_gethostname()`.
 
> Also, is there a macro for a debug level in this code, or something like it? I'd like to add some output when debugging is turned on for the case when gethostname returns errno of ENAMETOOLONG or EINVAL, assuming that's the way you do things in this code.

You can use `opal_output_verbose()` for these kinds of things.  Check out the docs for that in `output.h`.  There may well already be an OPAL-level base stream you can use (vs. opening your own output stream) that keys off `opal_base_verbose`, or somesuch MCA param. I'm afraid I don't remember offhand -- you might want to poke through `ompi_info --all --parsable | grep opal | grep verbose` and see if you can find a suitable existing OPAL base verbose MCA param, and if so, find what stream it is hooked to.

**Comment by cpshereda** [comment] 2019-10-07 23:11
> You can locally #undef gethostname in the .c file where you define opal_gethostname(). 

Yes, of course. Sorry.

And thanks for the pointers.

**Comment by jsquyres** [comment] 2019-10-07 23:17
> > You can locally #undef gethostname in the .c file where you define opal_gethostname().
> 
> Yes, of course. Sorry.

Are you apologizing for not knowing every trick in the book / not knowing everything about the Open MPI code base within a week or two?  Stop that!  :stuck_out_tongue:

Questions are good.

> And thanks for the pointers.

👍

**Comment by cpshereda** [comment] 2019-10-10 17:29
I did some research and it appears this issue is more complicated than just putting a null terminator in the final position of the hostname. Yes, a result can be truncated and then possibly not terminated, but also:

- A truncated result can return either failure or success, depending on the implementation;
- In some implementations if the buffer is too small, nothing is written to it. And my understanding is that again, this could return either failure or success.

Ideally opal_gethostname would return a string of arbitrary length (perhaps limited to some very large size, ~32k or whatever), with the hostname allocated inside the function and freed outside of it. 

Barring that, and perhaps for now, I think we should return a truncated, terminated result as opposed to any null result, and return an error if the result is truncated (as well as preserve errno as set by gethostname, and any failure of gethostname not related to truncation). This means dynamically calling gethostname inside opal_gethostname.

I'm opposed to using a preprocessor macro to redefine gethostname, primarily because it is obfuscatory. I have been in the position before of having to maintain code that does similar things and it can be extremely frustrating. And if we were to check the return code from opal_gethostname/gethostname, almost all of those gethostname calls would have to be modified anyway. Howard and I discussed it and he agreed that it would be better to just change the code to call opal_gethostname instead. So that makes two of us.

I have a version of opal_gethostname written that I've hand-tested. I still have to replace the calls to gethostname with opal_gethostname depending on what is decided: 

- We can just do a simple replace of gethostname with opal_gethostname, without checking the return of opal_gethostname; 
- We can check the return code, recognize any truncation/failure, and perhaps do something with that (what?);
- Instead of the above, we can dynamically allocate space for hostname inside opal_gethostname with a starting size of OPAL_MAXHOSTNAMELEN and an upper limit of 32k, making a truncated hostname extremely unlikely. This would require that hostname be freed later.

Focusing just on ompi/opal, Howard explained to me that code in certain paths should be left alone: 
mca/event
mca/loc
mca/pmix
and anything with romio in the path.

So my plan will be to modify every gethostname call under ompi/opal other than the ones above. That also means I won't touch ompi/ompi, ompi/orte, or ompi/cshmem paths unless it's decided otherwise.

**Comment by jsquyres** [comment] 2019-10-11 16:12
Generally everything you said sounds good:
* Let's not `#define gethostname opal_gethostname`
* Need to decide what to do on error

I don't think we want to have `opal_gethostname()` alloc memory, though -- that would mean that all the code currently calling `gethostname()` would need more than a trivial update (i.e., free the memory, which may require being delayed, if the hostname is being used asynchronously).

Here's another option: have an `opal_hostname` global variable that is filled during `opal_init()` and freed during `opal_finalize`.  That way, you *can* alloc memory and guarantee to have a value that is long enough, ...etc.  And it gets freed properly at the end of time.

Would that work?

**Comment by bwbarrett** [comment] 2019-10-11 16:17
An `opal_get_host_name()` call which returns a const pointer makes sense to me.  I think that fits most of our usecases.  Obviously, we can't #define gethostname in tha case, but that might be ok.

**Comment by cpshereda** [comment] 2019-10-17 16:53
@bwbarrett, what problem would be solved by having `opal_gethostname()` return a const pointer? I don't understand why that would be useful/necessary in this code. Or do you mean a pointer to a const, as in `const char *opal_gethostname()`? Or do you mean something else?

@jsquyres - good suggestion and I can do that once I understand the const pointer request better and what we might do with that. If you can point me to where in the code (ie, which main() are we talking about) I should be calling opal_init and opal_finalize, I'd appreciate it.

Sorry for the slow response and any inconvenience - it's an occasional thing with me due to the way I partition my time.

**Comment by jsquyres** [comment] 2019-10-17 17:14
Actually, @bwbarrett's and my suggestions are fairly similar.  His is a bit more safe.

```c
// opal_gethostname.c
static char local_hostname[4096] = "Failed to obtain hostname";
static bool first = true;

const char *opal_gethostname(void)
{
    if (first) {
        first = false;
        // Do all the work to properly fill in local_hostname
    }

    return local_hostname;
}
```

There's no need to free memory at finalization because there's a giant stack buffer that is guaranteed to be big enough to handle any practical hostname size (I made up 4096 -- pick something relevant).

The first time through, it does the work to actually obtain the hostname.  If it fails, it leaves in the default value of "Failed to obtain hostname".  Then the rest of the code base doesn't have to handle failures -- the rest of the code base will just emit "Failed to obtain hostname", and that will be a Good Enough signal to the user that something went wrong.

**Comment by cpshereda** [comment] 2019-10-17 17:30
Right, a pointer to a const rather than a const pointer. And ok, that makes sense, I can do that.

**Comment by cpshereda** [comment] 2019-11-15 18:01
@jsquyres - Before I open a PR for these changes, any suggestions for what can help me test all of them as thoroughly as possible? @hppritcha suggested the IBM component of MTT (Actually LAM?) for testing mpi, but I'm not really clear on how to test everything else.

Per Howard's suggestion and recent developments, I changed more than just opal/, such as some codefiles in orte/ and some in ompi/. How would I test what's been changed in orte/, for example?

Also, if I have changes to ompi/examples, how can we incorporate that since it's excluded via .gitignore?

Finally, I have a standalone version of this to put somewhere, as a tester. It's not using MPI. Where would I put it? Or do we not put that in the master branch?

**Comment by hppritcha** [comment] 2019-12-19 03:49
marking this as a good first BR was ridiculous

**Comment by rhc54** [comment] 2019-12-19 04:03
Agreed - I think the problem is that those of us who had previously been dealing with the hostname issue didn't pay attention to this issue (too busy with other things, sadly) or we would have seen where things were going off-track sooner. My apologies.

**Comment by awlauria** [comment] 2020-03-03 13:54
Good to close this issue?

**Closed** 2020-03-03 13:55 UTC
Labels: Target: master, bug
