### ISSUE TITLE
Version 5.0.0rc7 generates broken runtime

### ISSUE THREAD

**Issue by carlosrosales** [open-mpi/ompi#10437] opened 2022-05-31 18:04 UTC
Hi,

I built from source 5.0.0rc7 on an AWS EC2 hpc48.xlarge instance ( AMD Milan class processor, Amazon Linux 2 with kernel 4.14.262, EFA enabled ) and found no errors in the configuration or build process. I used gcc 11.2.0 for the build. However the runtime does not seem to work at all . mpirun simply returns and not even "mpirun --help" works. There are no errors, just a silent failure.

Before testing I set my PATH and LD_LIBRARY_PATH to the correct location for the build, and verified it with "which mpirun"

My configuration seemed to be correctly setup to enable both TCP and EFA. My specific configuration line was this:

```
configure --prefix=/shared/apps/mpi/openmpi/5.0.0rc7/gcc-11.2.0 \
--enable-shared --with-libfabric=/opt/amazon/efa \
--enable-prte-prefix-by-default=/shared/apps/mpi/openmpi/5.0.0rc7/gcc-11.2.0 \
CC=gcc CXX=g++ FC=gfortran LDFLAGS="-Wl,--build-id -Wl,--enable-new-dtags"
```

I attach the config.log output as well as the terminal recorded output for the configure and make/make install steps.

Please let me know if there is any other information I can provide to help isolate the issue.

[openmpi_5.0.0rc7_config.log](https://github.com/open-mpi/ompi/files/8807989/openmpi_5.0.0rc7_config.log)
[openmpi_5.0.0rc7_configuration.log](https://github.com/open-mpi/ompi/files/8807991/openmpi_5.0.0rc7_configuration.log)
[openmpi_5.0.0rc7_install.log](https://github.com/open-mpi/ompi/files/8807992/openmpi_5.0.0rc7_install.log)

**Comment by jsquyres** [comment] 2022-05-31 18:07
FYI @open-mpi/efa 

I doubt that this is an EFA-specific problem, but the reporter specifically mentions AWS/EFA.

**Comment by wzamazon** [comment] 2022-05-31 18:25
I can reproduce this issue, and I am positive it is not EFA specific. As carlos mentioned, `mpirun --help` does not produce any output.

**Comment by wzamazon** [comment] 2022-05-31 18:38
`prterun --help` does not print anything either.

**Comment by awlauria** [comment] 2022-06-01 12:24
The submodule pointer in prrte is pretty up-to-date, pointing to this commit: https://github.com/openpmix/prrte/commit/f75647a0518b5a476011f543200fca1cf8600cb8

I don't see anything obvious that came after this that would fix the issue, but I don't recall seeing it myself.

**Comment by rhc54** [comment] 2022-06-01 12:59
Yeah, that is pretty out-of-date now, and indeed does not include the fix for this problem.

**Comment by awlauria** [comment] 2022-06-01 13:03
Can you point to what commit fixes this problem? I don't see any obvious fix for this in the 8 commits that came after this update.

It's moot, since we'll update the submodule pointer anyway for the next rc, but for documentation purposes it would be nice to know.

**Comment by awlauria** [comment] 2022-06-01 17:15
@carlosrosales or @wzamazon would you be able to verify that the latest v2.1 prrte branch fixes this issue?

**Comment by wzamazon** [comment] 2022-06-01 19:49
@awlauria 

I tried update prrte in v5.0.x to v2.1 but encountered several issues:

First, prrte v2.1 configure failed and says it requires pmix >= 4.1.3, while openpmix in Open MPI v5.0.x is v4.1.3.

This was solved when I update `openpmix` in v5.0.x branch to latest of `v4.1` branch.

However, with openpmix  v4.1. branch, prrte cannot be compiled. error message was
```
undefined reference to `PMIX_INFO_LIST_INSERT'
```

This compilation error can be solved by use the latest `master` branch of openpmix.

However, after the compilation issue is fixed.

The command `mpirun`  will hang.

**Comment by rhc54** [comment] 2022-06-04 12:50
Why OMPI is targeting the PMIx v4.1 branch is a mystery to me - it was targeting v4.2 before. Regardless, I have updated the v4.1 branch so PRRTE builds against it.

I'm not seeing any hangs, nor is the PRRTE CI. You'll need to provide more info to ensure you aren't hanging in the MPI layer.

**Comment by awlauria** [comment] 2022-06-08 14:12
@AboorvaDevarajan created https://github.com/open-mpi/ompi/pull/10457 to bring the v5.0.0 submodule pointers up-to-date.

**Comment by awlauria** [comment] 2022-06-09 16:10
The update to prrte/pmix modules has been brought into the v5.0.x branch. can you verify whether it fixes your issue?

**Comment by awlauria** [comment] 2022-06-15 14:59
@wzamazon we discussed this a bit yesterday, and came to the conclusion that the internal pmix submodule pointer was pointing to the v4.2 branch, however the VERSION file in openpmix was not updated to reflect that (my bad - this should have been checked a long time ago). This seems to be corrected now in the openpmix branch repo - thanks @rhc54 .

For clarity:
- The internal openpmix should always be pointing near the top of the v4.2 branch.
- The internal prrte submodule should always be pointing near the top of the v2.1 branch.

If you can verify that the current 5.0.x branch fixes your issue when you get a chance we'd appreciate it. Thanks!

**Comment by wzamazon** [comment] 2022-06-15 16:54
Thank you! I can confirm the current 5.0.x branch does not have this issue any more.

**Comment by awlauria** [comment] 2022-06-16 19:45
Thanks ! I think we can close this issue. @carlosrosales the fix will be in rc8. in the meantime you can clone and build the current v5.0.x branch for a fix.

**Closed by awlauria** 2022-06-16 19:45 UTC
Labels: Severity: blocker, question, Target: v5.0.x
