### ISSUE TITLE
MPI-4: Routines that can be called before MPI_Init

### ISSUE THREAD

**Issue by dalcinl** [open-mpi/ompi#10794] opened 2022-09-13 08:25 UTC
See Table 11.1 in Sec 11.4.1 pp 513 of the MPI-4.0 std document. This table lists routines that can be called BEFORE `MPI_Init_[thread]`.

However, with current Open MPI main branch, some of these routines cannot be called before `MPI_Init_[thread]`.
The list of routines with issues follows:

 *  `MPI_INFO_GET_STRING` (I have not checked `MPI_INFO_GET_VALUELEN`)
 *  `MPI_INFO_GET_NTHKEY`
 *  `MPI_INFO_FREE`
 *  `MPI_INFO_F2C`
 *  `MPI_ERROR_STRING` (segfault)
 *  `MPI_ERROR_CLASS` (segfault)

The `MPI_INFO` routines in the list above need relaxing error checking to allow invocation before MPI initialization. 

The last two routines in the list above may be more involved, I'm not sure about their implementation details. 
Also note that `MPI_ERROR_{CLASS|STRING}` fail only if called before `MPI_INFO_CREATE`.

PS: I have a python script that can be used as a reproducer, and also to confirm all these issues are fixed once the work is done.

**Comment by hppritcha** [comment] 2022-09-29 17:11
Okay I'm looking at this some.  Although the standard does have a list of functions that can be called prior to initializing MPI or a Session, that does not mean that these can be randomly tested with random wrong values prior to initialization of MPI and expect some useful behavior.   For example, for MPI_Info_f2c, if one's expecting to just call this alone in a test and put in some random value for an argument, that things are going to work.  To properly use MPI_Info_f2c, for example, one had to a have first invoked MPI_Info_create except fo MPI_INFO_ENV and MPI_INFO_NULL.  The same thing goes for the other info calls in the above list.  

I'm going to fix some of these to be a little smarter, and fix the segfaults, but just want to set expectations.

**Comment by dalcinl** [comment] 2022-09-29 17:57
What makes you think I would have tested these routines with random input? I was working on properly written tests that would properly test an MPI implementation’s ability to function without MPI_Init. And then I faced all the issues I’m reporting here.

**Comment by hppritcha** [comment] 2022-09-29 18:56
i'm wondering because if the test calls MPI_Info_create first, then the first four routines in the list should work - assuming of course there isn't a bug(s).  Anyway I'll see if I can reproduce, but will go on the assumption that MPI_Info_create is invoked first to get an info handle to use as an argument.

**Comment by dalcinl** [comment] 2022-09-30 09:21
> i'm wondering because if the test calls MPI_Info_create first, then the first four routines in the list should work - 

Of course ...

> assuming of course there isn't a bug(s).

but there is a trivial "bug" indeed in each of these routines. The routines explicitly check for MPI initialization and they should not, see yourself:

* https://github.com/open-mpi/ompi/blob/main/ompi/mpi/c/info_get_string.c#L77
* https://github.com/open-mpi/ompi/blob/main/ompi/mpi/c/info_get_nthkey.c#L64
* https://github.com/open-mpi/ompi/blob/main/ompi/mpi/c/info_free.c#L60
* https://github.com/open-mpi/ompi/blob/main/ompi/mpi/c/info_f2c.c#L69

And of course the fix is trivial, just remove the lines I listed above.

About the last two routines I reported (`MPI_ERROR_{STRING|CLASS}`), I have not looked into it, but I guess the fix should be easy, most likely ensuring some internal stuff gets initialized.

**Comment by hppritcha** [comment] 2022-10-07 16:07
closed via #10898 and #10885

**Closed by hppritcha** 2022-10-07 16:07 UTC
Labels: bug, Target: main, Target: v5.0.x
